### ISSUE TITLE
🐛  Website broken

### ISSUE THREAD

**Issue by mehulmpt** [biomejs/biome#1004]
### Environment information

```block
N/A
```

### What happened?

Hi
The website currently is broken. It seems like some configuration issue from your end?

<img width="1281" alt="Screenshot 2023-12-02 at 03 24 10@2x" src="https://github.com/biomejs/biome/assets/10388889/8b2e2b07-a182-4305-bde5-e8640fa6750e">

### Expected result

The website should open fine

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
We migrate from Vercel to Netify. This pulled the website down. It should now be up :)
