### ISSUE TITLE
Cleanup of unused imports mangles them

### ISSUE THREAD

**Issue by roderik** [biomejs/biome#1015]
### Environment information

```block
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.11.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

The following file has a bunch of unused imports: https://share.cleanshot.com/BGMXFDqb
Saving it ends up like this: https://share.cleanshot.com/KM1tSmWZ

But it does work for just one like this https://share.cleanshot.com/WcB9RLBR
Or like this: https://share.cleanshot.com/KTx3wrC3

And it fails for the combination of the two working ones above https://share.cleanshot.com/wLZry1GL

In the [CBS template](https://codesandbox.io/p/sandbox/biome-starter-cbs-rky6zq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpnzvi1e00073b6rfjwvhwij%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpnzvi1e00033b6rkxszgsez%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpnzvi1e00053b6rdamiq5ev%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpnzvi1e00063b6rkn24cw6u%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpnzvi1e00033b6rkxszgsez%2522%253A%257B%2522id%2522%253A%2522clpnzvi1e00033b6rkxszgsez%2522%252C%2522activeTabId%2522%253A%2522clpnzy3ud00sj3b6r0auird0m%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpnzvi1e00023b6r0m7d2ocx%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252FDockerfile%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fenvironment.ts%2522%252C%2522id%2522%253A%2522clpnzwedv004z3b6ru0kpmtq6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fpubsub%252Fpubsub.module.ts%2522%252C%2522id%2522%253A%2522clpnzx4tm00de3b6rk7wd6nfg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fpubsub%252Fconfig.ts%2522%252C%2522id%2522%253A%2522clpnzxaww00gg3b6ram5qbr5z%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fbiome.json%2522%252C%2522id%2522%253A%2522clpnzxwn800li3b6rhv7dp42r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.ts%2522%252C%2522id%2522%253A%2522clpnzy3ud00sj3b6r0auird0m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522id%2522%253A%2522clpnzza2400yn3b6r6yqvzawr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Findex.ts%2522%252C%2522id%2522%253A%2522clpo02dpe021f3b6r7a0ysyfr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522clpnzvi1e00063b6rkn24cw6u%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clpnzvi1e00063b6rkn24cw6u%2522%257D%252C%2522clpnzvi1e00053b6rdamiq5ev%2522%253A%257B%2522id%2522%253A%2522clpnzvi1e00053b6rdamiq5ev%2522%252C%2522activeTabId%2522%253A%2522clpo01oh301wv3b6rzd1yxzt1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpnzvi1e00043b6rfiyy0njv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522lint%2522%257D%252C%257B%2522id%2522%253A%2522clpo01oh301wv3b6rzd1yxzt1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clpo01oih001ceeiph6gz00k8%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), using the commandline, it does not break 
In my own project using the commandline it also works

With the vscode extension, it breaks.

- vscode config https://gist.github.com/roderik/6154f22a0f75bae75176a3472118fe3f
- Biome extension v2.0.0
- biome 1.4.1 listed at the right bottom of the screen

### Expected result

Do not break

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by roderik** [comment]
Workaround

```
  "editor.codeActionsOnSave": {
    "source.fixAll": "explicit",
    "quickfix.biome": true,
    "source.organizeImports.biome": true
  },
```

this makes vscode clean up the imports first it seems

**Comment by cw-1988** [comment]
happening again for ts/react imports in vscode extension, release and prerelease version (3.3.0)
terminal biome (2.3.7) works fine

the recommended fix does not work for me,

quickfix.biome even by its own mangles the imports:

	"editor.codeActionsOnSave": {
		// "source.fixAll.biome": "explicit",
		// "source.organizeImports.biome": "explicit",
		"quickfix.biome": "always" // or explicit, doesnt matter
	}

**Comment by siketyan** [comment]
@cw-1988 Using quickfix.biome as a format-on-save action is **NOT** recommended. See https://biomejs.dev/linter/rules/no-quickfix-biome/ and use **only** `source.fixAll.biome` (and `source.organizeImports.biome`) instead.

**Comment by cw-1988** [comment]
Thanks for the tip ;-)
