### ISSUE TITLE
The CLI told me to report this

### ISSUE THREAD

**Issue by BjoernRave** [biomejs/biome#1019]
### Environment information

```block
Source Location: /Users/runner/work/biome/biome/crates/biome_rowan/src/ast/mod.rs:614:45
Thread Name: biome::worker_10
Message: Malformed separated list, separator expected but found node JS_PROPERTY_OBJECT_MEMBER@26247..26519 instead. You must add missing markers for missing separators.
```

### What happened?

it crashed when trying to run: `pnpm dlx @biomejs/biome check --apply-unsafe .`

### Expected result

apply linting suggestions

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Are you able to share a repository or a snippet that causes this issue? We will also need to know your configuration

**Comment by ematipico** [comment]
Closing because we aren't able to replicate the issue
