### ISSUE TITLE
🐛 Spurious "Illegal duplicate default export declarations" with exported value and type

### ISSUE THREAD

**Issue by stwlam** [biomejs/biome#1037]
### Environment information

```block
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

https://biomejs.dev/playground/?code=ZQB4AHAAbwByAHQAIABkAGUAZgBhAHUAbAB0ACAAYwBsAGEAcwBzACAARgBvAG8AIAB7AH0ACgAKAGUAeABwAG8AcgB0ACAAZABlAGYAYQB1AGwAdAAgAGkAbgB0AGUAcgBmAGEAYwBlACAARgBvAG8AIAB7AH0ACgA%3D

### Expected result

No error (or maybe just a light scolding)

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by strager** [comment]
Declaration merging occurs here just like with non-exported classes/interfaces.
```typescript
class A {}
interface I {}  // merged

export default class B {}
export default interface B {}  // merged
```

**Comment by Conaclos** [comment]
I previously created a helper to check if two declarations are mergeables. The helper is in [`biome_js_syntax::binding_ext.rs`](https://github.com/biomejs/biome/blob/main/crates/biome_js_syntax/src/binding_ext.rs#L49).
