### ISSUE TITLE
📝 Nested arrow functions are split on multiple lines

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#1039]
### Environment information

```bash
main
```

### Playground link

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&code=YwBvAG4AcwB0ACAAbQBlAHMAcwBhAGcAZQBzACAAPQAgAHMAdABkAG8AdQB0AAoACQAJAC4AcwBwAGwAaQB0ACgAJwBcAG4AJwApAAoACQAJAC4AZgBpAGwAdABlAHIAKAAoAGwAbgApACAAPQA%2BACAAIQAhAGwAbgAuAHQAcgBpAG0AKAApACkACgAJAAkALgBtAGEAcAAoACgAbABuACkAIAA9AD4ACgAJAAkACQBsAG4ACgAJAAkACQAJAC4AcgBlAHAAbABhAGMAZQAoAC8AWwA92IDeAyVdAC8AZwAsACAAJwAnACkACgAJAAkACQAJAC4AcgBlAHAAbABhAGMAZQAoAC8AXABzACsALwBnACwAIAAnACAAJwApAAoACQAJAAkACQAuAHQAcgBpAG0AKAApAAoACQAJACkAOwA%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
FYI the issue comes from here: https://github.com/withastro/adapters/pull/79/files#diff-1d2a2b56ad20e7e5b13936929d10bebf30d56ffa7cdc64f686dff4ae6cfafb60

**Comment by kalleep** [comment]
I can take a look at this one. This does not seem to have anything to do with nested arrow function but rather something with call chains.

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&code=YQAuAHMAKAAvAD3YgN492IDeLwApAC4AcwAoACkALgBzACgAKQA%3D
