### ISSUE TITLE
🐛 --no-errors-on-unmatched not respected

### ISSUE THREAD

**Issue by pm-dev** [biomejs/biome#1058]
### Environment information

```block
CLI:
  Version:                      1.4.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.3"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

I can't seem to get the `--no-errors-on-unmatched` option to work in my environment (zsh command line). Some options work, i.e. `--help` will print the help output. It may be true that other options are also not working.. `--verbose` doesn't seem to change the output. 
I'm wondering if this could be a regression?

### Expected result

```zsh
git:(main) ✗ npx @biomejs/biome lint --no-errors-on-unmatched **/file-does-not-exist.ts 
zsh: no matches found: **/file-does-not-exist.ts

git:(main) ✗ npx @biomejs/biome format --no-errors-on-unmatched **/file-does-not-exist.ts
zsh: no matches found: **/file-does-not-exist.ts

git:(main) ✗ npx @biomejs/biome format --no-errors-on-unmatched file-does-not-exist.ts 
file-does-not-exist.ts internalError/io  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ No such file or directory (os error 2)
  
  ⚠ This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
  

Compared 0 file(s) in 73µs
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
All the attempts seem to be correct:
- the CLI doesn't support globs as inputs, so the result is expected
- --verbose is for diagnostics that contain more info, although we don't know any of them, that's why the output is the same
- the option --no-errors-on-matched works for files that exist but aren't recognised by Biome (meaning it doesn't know how to handle them)

**Comment by pm-dev** [comment]
> the CLI doesn't support globs as inputs
That's odd because using **/*.ts does work. What is the correct way to run lint/format/check on all ts files under the current directory and don't error if there are none.?

**Comment by pm-dev** [comment]
That's right @Conaclos. I thought the "no matches found:" output was from biome, but it was from zsh. FWIW this can be turned off via `unsetopt nomatch` ([discussion](https://github.com/ohmyzsh/ohmyzsh/issues/31#issuecomment-359728582))

For anyone coming across this in the future, since globs don't work, use a path to the directory (i.e. `./` for current directory) then [files.include](https://biomejs.dev/reference/configuration/#filesinclude) to match only specific files.
