### ISSUE TITLE
🐛 Linter error output not showing when `--diagnostics-level=error` and [number of non-error diagnostics] > `N` in `--max-diagnostics=N`

### ISSUE THREAD

**Issue by eirikove** [biomejs/biome#1083]
### Environment information

```block
$ biome rage
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v16.14.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/1.22.19"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           true
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 false

Workspace:
  Open Documents:               0

Done in 0.08s.
```
### What happened?

I've installed `biomejs` alongside ESLint/prettier in a big and old React project at my workplace. We have almost 2000 biome-parsable files and around 600 ish (biome) lint errors out of the box. I've disabled the formatting and import sorting for now, focusing only on linting.

So what I did was run `biome lint ./src --diagnostic-level=error` a few times and then went into `biome.json` and set all the lint rules producing errors to `"warn"`, thinking I'd gradually work my way through and turn them into errors one by one.

At some point, re-running the linter would tell me I have `X` diagnostics and `Y` errors, and the process would exit with error code 1 saying "Some errors were emitted while running checks.", but it wouldn't output those errors to the console so I could figure out which files to scan, or even which rules produced said errors.

However, if I completely turn `"off"` the rules that were set to `"warn"` in `biome.json`, the remaining lint errors are output perfectly fine. 

So it seems to me that passing the `--diagnostic-level=error` won't actually output your lint errors if the `--max-diagnostics=N` heap/stack/whatever is filled to the brim with lint warnings.

### Expected result

I expect when passing the flag `--diagnostics-level=error` that the linter is only to find up to `--max-diagnostics=N` number of error-type diagnostics and then print those. I expect  ~~lint-warnings~~ diagnostics of other severities **to not affect** the output.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by eirikove** [comment]
On a little personal note: 

I submitted this as a bug because I was thinking "wait is this intentional?" and I guess in hindsight, it very well might be. But as I was working on this, I was really struggling to find documentation to help explain to me why the linter would say I had lint errors without actually outputting them regardless of which flag options I was passing to the `lint` command. 

So I'm not saying this is definitely a bug, but if this is intended behaviour, please update the documentation to reflect this better.

**Comment by eirikove** [comment]
> I bet that we increase the printed diagnostic counter regardless of their severity, and as a result the counter is filled with warnings and no errors are printed.

@ematipico Sounds like a perfectly reasonable explanation for the problem I'm experiencing, and probably not the worst of things to fix. Fingers crossed it's that simple! 👍

**Comment by ematipico** [comment]
@yossydev 

This is where you want to look

https://github.com/biomejs/biome/blob/f6bff7d0aed53f7206fc9800938fabc1f3ed3e0e/crates/biome_cli/src/execute/traverse.rs#L290

Check where we increase the printed diagnostics counter. We should do it only if the `diagnostic.severity()` is higher of the severity passed from the user.

**Comment by ematipico** [comment]
Hi @yossydev do you plan to submit a PR soon?

**Comment by yossydev** [comment]
@ematipico 
Sorry for the delay in responding:pray: My schedule has been packed these days.
I can proceed with this response tomorrow or the day after, but should I hurry up and implement it?

**Comment by ematipico** [comment]
That's okay, I wanted to understand if you were still interested.

**Comment by ematipico** [comment]
Fixed by https://github.com/biomejs/biome/pull/1299

Try the latest nightly and let us know
