### ISSUE TITLE
📎 `lint/noUselessTernary` - `eslint/no-uneeded-ternary`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#1089]
### Description

Implement [no-unneeded-ternary](https://eslint.org/docs/latest/rules/no-unneeded-ternary/) without rule options.

Want to contribute? Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z).

Suggested names: `noUselessTernary`, `noUselessCondititionalExpression`

**Comment by vasucp1207** [comment]
I want to work on this.
