### ISSUE TITLE
🐛 VSCode extension format disagrees with `biome format`

### ISSUE THREAD

**Issue by MCFX2** [biomejs/biome#1100]
### Environment information

```block
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v19.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/3.6.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0

VSCode Extension version is 2.0.0 (latest at time of writing), but tested this with several other versions and got identical behavior.
```

### What happened?

Three minimal reproduceable examples:

```ts
export function initErrorHandling(): void {
	process.on("unhandledRejection", (error: Error, promise) => {
		log.error(`Unhandled promise rejection from ${typeof (promise)}, reason: ${error}`);
	});
}
```

VSCode biome extension formats the code as shown. However, the command produces this error:

```ts
  ℹ Formatter would have printed the following content:

    32    │ - → → log.error(`Unhandled·promise·rejection·from·${typeof·(promise)},·reason:·${error}`);
       32 │ + → → log.error(
       33 │ + → → → `Unhandled·promise·rejection·from·${typeof·promise},·reason:·${error}`,
       34 │ + → → );
```

This can be worked around by rewriting the message to be shorter (we have our line lengths configured at 80 characters) or by manually formatting it ourselves. Then it produces a new error (which the VSCode format also does not seem to care about):

```ts
  ℹ Formatter would have printed the following content:

    33 │ → → → `Unhandled·promise·rejection·from·${typeof·(promise)},·reason:·${error}`,
       │                                                  -       -

```
This can also be fixed by hand however.

Another, more unfortunate example is with the following code:

```ts
	public override async initialize() { }
```

Once again, the extension formats this as shown. But the command fails for this reason:

```ts
  ℹ Formatter would have printed the following content:

    244 │ → public·override·async·initialize()·{·}
        │                                       -
```
It believes there should be no space between the braces. If I delete this space, the VSCode extension will format it back in, so there seems to be no way of resolving this short of adding dummy code in this empty function.

### Expected result

Formatting a file with the VSCode extension should result in a clean output from the format command.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by MCFX2** [comment]
I found another example:

```ts
				const myVariable = someFunction(someObject,
					"abc",
					"def",
					"xyz"
				);
```

VSCode seems quite happy with this, but whenever I have a line formatted like this, `biome format` prompts me to either add a trailing comma to the last line or combine these lines into one line depending on the length.

I'm starting to get the impression that the extension just doesn't have any concept of line length, that would explain at least some of the behavior I'm getting.

**Comment by ematipico** [comment]
How does your configuration file look like? 

It seems to me that the VSCode extension isn't loading your `biome.json` file and it's using its defaults when formatting the code.

**Comment by MCFX2** [comment]
> How does your configuration file look like?
> 
> It seems to me that the VSCode extension isn't loading your `biome.json` file and it's using its defaults when formatting the code.

The config for the formatter is set up as follows:

```json
	"formatter": {
		"enabled": true,
		"formatWithErrors": true,
		"indentStyle": "tab",
		"indentWidth": 2,
		"lineWidth": 80,
		"ignore": []
	}
```

Which is, as I understand it, basically the default format anyway. There is one thing that could be causing confusion, which is that there are a couple nested projects in this workspace with their own biome.json, however each of these is pretty much identical at the moment.

**Comment by ematipico** [comment]
In the VScode extension, you should see the version that Biome is using, in the bottom right corner of the window. Is it 1.4.1?

**Comment by ematipico** [comment]
<img width="323" alt="Screenshot 2023-12-07 at 15 39 06" src="https://github.com/biomejs/biome/assets/602478/8267673c-5df8-4030-8cb2-44ae414ba1c8">

You should see something similar. If you don't, not sure what the issue could be 🤔 

I wonder if the issue is because you're using a Workspace, which we don't have good support for (we have an issue tracking the works).

**Comment by MCFX2** [comment]
> > Sorry, I used poor terminology. I mean workspace in the VSCode sense, i.e. the folder I've got open in VSCode.
> 
> Yes that's exactly what I was referring to! :D
> 
> We have an issue in fact: [biomejs/biome-vscode#18](https://github.com/biomejs/biome-vscode/issues/18)
> 
> I really think that's the issue

I see then. That does track with my experience- Thinking back, it seems like this only started happening once we had a second project in the repo. It was working fine before then.

I noticed it complaining about the lack of a Biome binary, which I previously just ignored since it seemed to be working fine regardless, but I tried having it download Biome like it wanted to instead to see what would happen. I now have the status indicator in the corner like you've shown, but the same issues remain.

I guess that just leaves the question of, if Biome isn't working, what's formatting my code? 🤔 I don't have any other formatting extensions.

**Comment by ematipico** [comment]
> I guess that just leaves the question of, if Biome isn't working, what's formatting my code? 🤔 I don't have any other formatting extensions.

Is it possible that you have a `biome` process still running? I would check that

**Comment by MCFX2** [comment]
> > I guess that just leaves the question of, if Biome isn't working, what's formatting my code? 🤔 I don't have any other formatting extensions.
> 
> Is it possible that you have a `biome` process still running? I would check that

Well, I think it is running, it's just not formatting things correctly. Mostly this is a minor annoyance but in some cases (like the `function x() { }` vs `function x() {}` example) the formatter disagrees with the other formatter.

If workspaces aren't supported, then what exactly is the expected way we use the VSCode extension? I'm getting this same behavior even when I just directly connect to a remote folder.

**Comment by MCFX2** [comment]
Update: I think I figured it out. It was a PEBKAC error, there in fact _was_ another formatter- the VSCode TS plugin provides one, and it had somehow become the default. All the odd discrepancies were fixed when I switched back to Biome.

Thanks for the rapid response! You saved me a ton of time.

**Comment by Adharsraj** [comment]
Remove prettier extension >reload developer window > set biome as default formater then format >boom
