### ISSUE TITLE
📎 Enable PyCharm support for IntelliJ plugin

### ISSUE THREAD

**Issue by anonrig** [biomejs/biome#1103]
### Description

We use PyCharm at Sentry. Since Prettier is also supported in PyCharm, I think it's possible for Biome to add PyCharm support. Since PyCharm uses IntelliJ underneath, I think it would be really easy to add a support for PyCharm as well.

**Comment by ematipico** [comment]
I think should be fairly easy. cc @victor-teles can you leave instructions on how to do so?

**Comment by victor-teles** [comment]
The plugin is already supported in PyCharm, Maybe the problem is related to #1091.
@anonrig Could you confirm your PyCharm version?

**Comment by anonrig** [comment]
@victor-teles Nice catch. `PyCharm 2023.3 (Professional Edition)`

**Comment by victor-teles** [comment]
@anonrig Can you check if the problem has been solved in the latest version?

**Comment by anonrig** [comment]
I can now install it. Thanks!

<img width="1094" alt="Screenshot 2023-12-11 at 9 13 54 AM" src="https://github.com/biomejs/biome/assets/1935246/3e4bbaab-7839-404a-9a31-b341eb34a4e2">
