### ISSUE TITLE
📎 Adding pre-commit support for Biome

### ISSUE THREAD

**Issue by anonrig** [biomejs/biome#1105]
### Description

We use `pre-commit` in Sentry. Similar to https://github.com/pre-commit/mirrors-prettier, it would be good to have a Biome plugin for pre-commit.

**Comment by Conaclos** [comment]
The plugin could provide four hooks that maps to the corresponding command
- `ci`: `biome ci --files-ignore-unknown=true --no-errors-on-unmatched`
  Check if the committed files are correctly formatted and linted (readonly mode)
- `check`: `biome check --apply-safe --files-ignore-unknown=true --no-errors-on-unmatched`
  To format, lint, and apply safe fixes to the committed files
- `format`: `biome format --write --files-ignore-unknown=true --no-errors-on-unmatched`
  To format the committed files
- `lint`: `biome lint --apply-safe --files-ignore-unknown=true --no-errors-on-unmatched`
  To lint and apply safe fixes to the committed files

What do you think?

**Comment by Conaclos** [comment]
I have created a [dedicated repository](https://github.com/biomejs/pre-commit) for Biome's pre-commit hooks. Please let me know if this suits your needs :)

Once stabilized, I plan to tag a first version.

**Comment by anonrig** [comment]
It seems the repository works perfectly. I added it to Sentry PR. Ref: https://github.com/getsentry/sentry/pull/61397/commits/4583249ac8fa1df5f0277cbb030b3f723b80e361. Can you release a tag/version on the repository? @Conaclos

**Comment by Conaclos** [comment]
I tagged [v0.1.0](https://github.com/biomejs/pre-commit/releases/tag/v0.1.0).
