### ISSUE TITLE
📎 Update Intellij plugin to support 2023.3

### ISSUE THREAD

**Issue by henrikbossart** [biomejs/biome#1111]
### Description

The plugin works nicely with 2023.2.5, but needs updating for 2023.3 :+1:

**Comment by ematipico** [comment]
Wasn't this fixed with the latest version?

**Comment by henrikbossart** [comment]
Oh, right, I didn't notice that latest release, but I see it in my inbox yet! I guess it just hasn't made it to the JetBrains Marketplace yet then.

**Comment by victor-teles** [comment]
There a small delay when we release new versions of the plugin because JetBrains have a review/approval process

@ematipico is it approved by them?

**Comment by ematipico** [comment]
Still under approval, in the meantime here is the direct link https://plugins.jetbrains.com/plugin/22761-biome/versions/stable/451195

**Comment by henrikbossart** [comment]
Awesome, thanks 🎉 Love the tool, btw 😎
