### ISSUE TITLE
📎 useExhaustiveDependencies - Implement Configurable Stable Hooks in biome.json

### ISSUE THREAD

**Issue by TakaoNarikawa** [biomejs/biome#1128]
### Description

I'm proposing an enhancement for the Biome linter, inspired by ESLint's handling of similar issues ([Issue #16873](https://github.com/facebook/react/issues/16873)). The key idea is to enable the specification of stable custom hooks in `biome.json`, akin to how React's `useState` is treated in dependency arrays. This feature aims to improve consistency and developer experience when working with various state management libraries like Recoil. For further background and discussion, you can refer to [this discussion](https://github.com/biomejs/biome/discussions/1034).

## Background
The current `use_exhaustive_dependencies` rule in Biome does not differentiate between hooks that require their setter functions to be included in dependency arrays and those that do not. For example, with React's useState, we don't need to include the setter function in dependency arrays:

```ts
const [foo, setFoo] = useState(123);
const fn1 = useCallback(() => setFoo(234), []);
```

However, with similar hooks from other libraries, like useRecoilState from Recoil, the setter must be included:

```ts
const [bar, setBar] = useRecoilState(barAtom);
const fn2 = useCallback(() => setBar(234), [setBar]); // setBar needs to be included
```

This inconsistency can lead to confusion and potential issues in dependency management.

## Proposed Feature
The idea is to introduce a new configuration option in biome.json to designate specific hooks as stable. For example:

```json
"useExhaustiveDependencies": {
  "level": "error",
  "options": {
    "hooks": [],
    "stableHooks": {
      "useRecoilState": true,
      "useResetRecoilState": [true, false]
    }
  }
}
```

In this configuration, `useRecoilState` would be treated as entirely stable, while `useResetRecoilState` would have its first index marked as stable and the second as not.

## Technical Challenges and Request for Contribution
While I have made a preliminary attempt at this ([Commit f0433f18](https://github.com/GeCS-Inc/biome/commit/f0433f18c6d796731defb56037507bc40e41feef)), I must confess that my experience with Rust is quite limited. As a result, I am not in a position to commit these changes to the project myself. Therefore, I am seeking assistance from more experienced Rust developers in our community to help implement this feature.

**Comment by ematipico** [comment]
Let's see if we can find someone that can help you. 

However, I think you; should still send a PR with the deserialization of the new option, and we will take over from there. Doing so, you'll get an attribution for your work!

**Comment by arendjr** [comment]
I’m interested in seeing this to completion, but it’ll be at least a few weeks until I can pick this up, I expect, so don’t assign me just yet 😅

**Comment by arendjr** [comment]
I'm going to work on this.

**Comment by ematipico** [comment]
Closed by https://github.com/biomejs/biome/pull/1979
