### ISSUE TITLE
📝 Does not format `tsconfig.<name>.json` files like `tsconfig.json`

### ISSUE THREAD

**Issue by Ethan-Arrowood** [biomejs/biome#1151]
### Environment information

```bash
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.1.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
    "$schema": "https://biomejs.dev/schemas/1.4.0/schema.json",
    "organizeImports": {
        "enabled": true
    },
    "formatter": {
        "enabled": true
    },
    "linter": {
        "enabled": true,
        "rules": {
            "recommended": true
        }
    }
}
```

### Playground link

https://codesandbox.io/p/devbox/biome-starter-cbs-rky6zq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clq1qf82j00073d5ximtybseu%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clq1qf82j00023d5xvrfsenbl%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clq1qf82j00053d5xtncpa140%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clq1qf82j00063d5xsjoy5g5s%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B100%252C0%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clq1qf82j00023d5xvrfsenbl%2522%253A%257B%2522id%2522%253A%2522clq1qf82j00023d5xvrfsenbl%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clq1qf82j00063d5xsjoy5g5s%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clq1qf82j00063d5xsjoy5g5s%2522%257D%252C%2522clq1qf82j00053d5xtncpa140%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clq1qf82j00033d5xysmfscvp%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522check%2522%257D%252C%257B%2522id%2522%253A%2522clq1qf82j00043d5x0be3whvw%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522lint%2522%257D%255D%252C%2522id%2522%253A%2522clq1qf82j00053d5xtncpa140%2522%252C%2522activeTabId%2522%253A%2522clq1qf82j00033d5xysmfscvp%2522%257D%257D%252C%2522showDevtools%2522%253Afalse%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Hey @Ethan-Arrowood , it seems that your codesandbox link doesn't contain any tsconfig file.

By default, Biome **doesn't** format the `tsconfig.json` file because tsc applies special formatting to it.

**Comment by Ethan-Arrowood** [comment]
Weird. Definitely added them. I'll re-add, but I think the issue is simple enough. If biome ignores the path `tsconfig.json`, I think it should also automatically ignore `tsconfig.*.json`. This is a common pattern today where the root tsconfig is extended for different purposes (like build, lint, test, etc.). And even more common in monorepos. 

I currently have to add `ignore: [ 'tsconfig.*.json' ]` to all my biome.json configs

**Comment by ematipico** [comment]
Unfortunately, we can't make assumptions like these as library authors, because those files aren't directly under the domain of tool. `tsconfig.json` is under the `tsc` domain, but `tsconfig.somethig.json` isn't. Also, another user might decide to call it `something.tsconfig.json` and Biome won't be able to detect it.

We add an exception for this case, we might end up adding other exceptions, creating a pretext. 

I think you did the right thing here, manually ignore the files.

**Comment by Ethan-Arrowood** [comment]
Gotcha. Good enough reasoning for me. Thank you 😄 excited for the work y'all are doing here 🚀
