### ISSUE TITLE
🐛 No matches found when formatting and linting group routes on nextjs

### ISSUE THREAD

**Issue by glendell03** [biomejs/biome#1159]
### Environment information

```block
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-kitty"
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "bun/1.0.15"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### This is my setup
1. Setup NextJs, lint-staged and husky
```ts
const path = require('path')

const biomeCheck = filenames =>
	`bun biome check --apply --organize-imports-enabled=true ${filenames.map(f => path.relative(process.cwd(), f)).join(' ')}`

module.exports = {
	'*.{ts,tsx,js,jsx}': [biomeCheck],

	'**/*.{css,scss,md,html,json}': [biomeCheck]
}
```

2. create a route group
reference: https://nextjs.org/docs/app/building-your-application/routing/route-groups

3. on pushing the code to github i will run a lint and format it does work on normal path but on route groups it returns a error
```bash
/bin/bash: -c: line 0: syntax error near unexpected token `('
/bin/bash: -c: line 0: `biome check --apply --organize-imports-enabled=true app/(authenticated)/(seller)/layout.tsx
```
<img width="928" alt="image" src="https://github.com/biomejs/biome/assets/58845052/d8b89033-fdda-4407-aadc-aee4aee71f72">

### This can also be test even without lint-staged and husky
1. create a route group
2. run biome format and linter `bun biome check --apply --organize-imports-enabled=true  app/(authenticated)/(seller)/layout.tsx`

<img width="813" alt="image" src="https://github.com/biomejs/biome/assets/58845052/cbfcdf60-48e2-4649-b5d7-8edb2445b45b">

### Expected result

this is the expected output it should lint and format the file
its working on normal path

<img width="583" alt="image" src="https://github.com/biomejs/biome/assets/58845052/76cf0450-f3a9-4d1b-9be6-d6d8681e1a0f">

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
If you notice, the error is thrown by your bash, not biome. Your bash is trying to do something, probably exploding the paths because they resemble globs.

Try to prepend `noglob` before the Biome command

**Comment by glendell03** [comment]
<img width="791" alt="image" src="https://github.com/biomejs/biome/assets/58845052/9d76f5c1-3c85-45c0-a56e-fa158d00839e">

`noglob` and putting quote on the file paths is working thanks!! 

will close this issue now :)
