### ISSUE TITLE
📝 Biome's import sorting is being cancelled out by vscode's import sorting

### ISSUE THREAD

**Issue by ChiefORZ** [biomejs/biome#1165]
### Environment information

```bash
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.8.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.6.10"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
  "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
  "vcs": {
    "enabled": true,
    "clientKind": "git",
    "useIgnoreFile": true
  },
  "organizeImports": {
    "enabled": false
  },
  "linter": {
    "enabled": false
  },
  "files": {
    "ignoreUnknown": true
  },
  "formatter": {
    "enabled": true,
    "formatWithErrors": true,
    "indentStyle": "space",
    "indentWidth": 2,
    "lineWidth": 100,
    "ignore": ["**/.next", "**/.wireit", "**/dist", "**/node_modules"]
  },
  "javascript": {
    "formatter": {
      "enabled": true,
      "quoteStyle": "double",
      "arrowParentheses": "always",
      "trailingComma": "all",
      "lineEnding": "lf"
    }
  },
  "json": {
    "formatter": {
      "enabled": true
    }
  }
}
```

### Playground link

https://biomejs.dev/playground/?code=aQBtAHAAbwByAHQAIAB7ACAAagB3AHQARABlAGMAbwBkAGUAIAB9ACAAZgByAG8AbQAgACIAagB3AHQALQBkAGUAYwBvAGQAZQAiADsACgBpAG0AcABvAHIAdAAgAGMAcgBlAGEAdABlAE0AaQBkAGQAbABlAHcAYQByAGUAIABmAHIAbwBtACAAIgBuAGUAeAB0AC0AaQBuAHQAbAAvAG0AaQBkAGQAbABlAHcAYQByAGUAIgA7AAoAaQBtAHAAbwByAHQAIAB7ACAATgBlAHgAdABSAGUAcwBwAG8AbgBzAGUALAAgAHQAeQBwAGUAIABOAGUAeAB0AFIAZQBxAHUAZQBzAHQAIAB9ACAAZgByAG8AbQAgACIAbgBlAHgAdAAvAHMAZQByAHYAZQByACIAOwA%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ChiefORZ** [comment]
For a better understanding what i mean with the title:

For me to get biome's import sorting to work i needed to enable the vscode's default import sorting aswell, so my vscode's settings.json looks like this:

```json
// settings.json 
{
    "editor.codeActionsOnSave": {
      "quickfix.biome": "explicit",
      "source.fixAll": "explicit",
      "source.organizeImports": "explicit",
      "source.organizeImports.biome": "explicit",
      "source.sortPackageJson": "explicit"
    }
}
```
If i remove the option `source.organizeImports` - no imports will be sorted at all, vscode will not do anything. 

In the playground provided the sorting will always be 
```js
import { type NextRequest, NextResponse } from "next/server";
```
so this is the correct way biome is sorting things.

But when Cmd+S and the codeActions run, the result will be 
```js
import { NextResponse, type NextRequest } from "next/server";
```
which i guess is vscode's default formatting/sorting.


I tried to remove all other codeActions, as well as re-ordering both "source.organizeImports" rules so that maybe the "source.organizeImports.biome" rule wins, but this did nothing -.-

**Comment by jpenna** [comment]
Same here

**Comment by ematipico** [comment]
> "source.organizeImports": "explicit",

This is action code that triggers the built-in import sorting of VSCode, it should not be used if you want to use only Biome: [source.organizeImports.biome](https://biomejs.dev/analyzer/import-sorting/#import-sorting-via-vscode-extension).

If the import sorting is applied, I suspect there's something wrong how the project is setup. Any chance you can create a reproduction to look at? Without that, we can't help you

**Comment by jpenna** [comment]
I'm using it like this in my Workspace settings:

```json
  "[javascript]": {
    "editor.defaultFormatter": "biomejs.biome",
    "editor.codeActionsOnSave": {
      "quickfix.biome": "explicit",
      "source.organizeImports.biome": "explicit",
      "source.organizeImports": "never",
      "source.fixAll": "explicit"
    }
  },
... and the same for typescript, typescriptreact, etc.
```

Because `source.organizeImports` is "never", it isn't organizing any imports now... If I set it to "explicit", it overrides Biome's.

**Comment by Conaclos** [comment]
Is the problem still there?
