### ISSUE TITLE
📝 Removed escapes are taken into account to determine if the enclosing group must be expanded

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#1169]
### Environment information

```
Playground
```

### Configuration

```
Default configuration
```

### Description

Biome remove unnecessary escape. However, it doesn't take the reduced length into account to evaluate if it has to expand the enclosing group. This leads to [non-idempotent formatting]( [corresponding divergence](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report.md#jsstringsescapedjs)).

 [Playground link](https://biomejs.dev/playground/?enabledLinting=false&code=ZQB4AHAAbwByAHQAIABjAG8AbgBzAHQAIABNAFMARwBfAEcARQBOAEUAUgBJAEMAXwBPAFAARQBSAEEAVABJAE8ATgBfAEYAQQBJAEwAVQBSAEUAXwBCAE8ARABZAF8AMgAgAD0ACgAgACAAZwBvAG8AZwAuAGcAZQB0AE0AcwBnACgAIgBUAGgAYQB0AFwAJwBzACAAYQBsAGwAIAB3AGUAIABrAG4AbwB3ACIAKQA7AAoACgBlAHgAcABvAHIAdAAgAGMAbwBuAHMAdAAgAE0AUwBHAF8ARwBFAE4ARQBSAEkAQwBfAE8AUABFAFIAQQBUAEkATwBOAF8ARgBBAEkATABVAFIARQBfAEIATwBEAFkAXwAyACAAPQAgAGcAbwBvAGcALgBnAGUAdABNAHMAZwAoAAoACQAiAFQAaABhAHQAJwBzACAAYQBsAGwAIAB3AGUAIABrAG4AbwB3ACIALAAKACkAOwA%3D)

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by kalleep** [comment]
I can take a look at this one!

**Comment by Conaclos** [comment]
@kalleep That was fast ❤️‍🔥
