### ISSUE TITLE
📝 A commuted empty statement inside an arrow function leads to non-idempotent formatting

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#1171]
### Environment information

```
Playground
```

### Configuration

```
Default configuration
```

### Description

[Playground link](https://biomejs.dev/playground/?enabledLinting=false&code=dQBzAGUAcgBzAC4AbQBhAHAAKAAoAHUAcwBlAHIAOgAgAFUAcwBlAHIAKQA6ACAAVQBzAGUAcgAgAD0APgAgAHsACgAgACAAOwAgAC8ALwAgAGMAbwBtAG0AZQBuAHQACgB9ACkACgAKAHUAcwBlAHIAcwAuAG0AYQBwACgACgAJACgAdQBzAGUAcgA6ACAAVQBzAGUAcgApADoAIABVAHMAZQByACAAPQA%2BACAAewAKAAkACQAvAC8AIABjAG8AbQBtAGUAbgB0AAoACQB9ACwACgApADsA)

This leads to [non-idempotent formatting](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report.md#typescripttypeparamsprint-width-120issue-7542tsx).

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by kalleep** [comment]
I can take a look into this one
