### ISSUE TITLE
📝 Comments between function parens and body should be consistently placed

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#1172]
### Environment information

```
Playground
```

### Configuration

```
Default configuration
```

### DEscription

[Playground link](https://biomejs.dev/playground/?enabledLinting=false&code=KABmAHUAbgBjAHQAaQBvAG4AIABuAGEAbQBlAGQAKAApAAoALwAvACAAdABoAGkAcwAgAGkAcwAgAGEAIABmAHUAbgBjAHQAaQBvAG4ACgB7AAoAIAAgAHIAZQB0AHUAcgBuACAANAAyAAoAfQApACgAKQA7AAoACgAoAGYAdQBuAGMAdABpAG8AbgAgAG4AYQBtAGUAZAAoACkAIAAvAC8AIAB0AGgAaQBzACAAaQBzACAAYQAgAGYAdQBuAGMAdABpAG8AbgAKAHsACgAJAHIAZQB0AHUAcgBuACAANAAyADsACgB9ACkAKAApADsA)

This leads to [non-idempotent formatting](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report.md#typescripttypeparamsprint-width-120issue-7542tsx).

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by kalleep** [comment]
I can tackle this one
