### ISSUE TITLE
📝 Commented single instruction in a control flow body should be consistently formatted

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#1173]
### Environment information

```Playground
```

### Configuration

```
Default configuration
```

### Description

[Playground link](https://biomejs.dev/playground/?enabledLinting=false&code=bABhAGIAZQBsADEAOgAgAGYAbwByACAAKAA7ADsAKQAgAGMAbwBuAHQAaQBuAHUAZQAgAGwAYQBiAGUAbAAxAAoALwAqACAAYwBvAG0AbQBlAG4AdAAgACoALwAKADsACgAKAGwAYQBiAGUAbAAxADoAIABmAG8AcgAgACgAOwA7ACkACgAJAGMAbwBuAHQAaQBuAHUAZQAgAGwAYQBiAGUAbAAxADsACgAJAC8AKgAgAGMAbwBtAG0AZQBuAHQAIAAqAC8ACgAKAGwAYQBiAGUAbAAxADoAIABmAG8AcgAgACgAOwA7ACkAIABjAG8AbgB0AGkAbgB1AGUAIABsAGEAYgBlAGwAMQAgAC8ALwAgAGMAbwBtAG0AZQBuAHQACgA7AAoACgBsAGEAYgBlAGwAMQA6ACAAZgBvAHIAIAAoADsAOwApAAoAIAAgAGMAbwBuAHQAaQBuAHUAZQAgAGwAYQBiAGUAbAAxADsAIAAvAC8AIABjAG8AbQBtAGUAbgB0AA%3D%3D)

this leads to [non-idempotent formatting](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report.md#typescripttypeparamsprint-width-120issue-7542tsx)

I suggest the following formatting (and thus to slightly diverge from Prettier for the first one):

```js
label1: for (;;) continue label1; /* comment */

label1: for (;;) continue label1; // comment
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by mdm317** [comment]
May I try to solve this issue?

**Comment by Conaclos** [comment]
Of course :) All yours!
