### ISSUE TITLE
💅 Calling biome lint errors with internal error: use_exhaustive_dependencies.rs when referencing an enum renamed with the import statement

### ISSUE THREAD

**Issue by jschaf** [biomejs/biome#1194]
### Environment information

```bash
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.3.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Rule name

n/a

### Playground link

https://biomejs.dev/playground/?code=aQBtAHAAbwByAHQAIAB7ACAAdQBzAGUATQBlAG0AbwAgAH0AIABmAHIAbwBtACAAJwByAGUAYQBjAHQAJwA7AAoACgBlAG4AdQBtACAARgBvAG8AIAB7AAoAIAAgAEEAIAA9ACAAMQAsAAoAfQAKAAoAaQBtAHAAbwByAHQAIABGAG8AbwAyACAAPQAgAEYAbwBvADsACgAKAGMAbwBuAHMAdAAgAHUAcwBlAEIAYQBkACAAPQAgACgAKQAgAD0APgAgAHsACgAgACAAdQBzAGUATQBlAG0AbwAoACgAKQAgAD0APgAgAHsACgAgACAAIAAgADIAIAA9AD0APQAgAEYAbwBvADIALgBBADsACgAgACAAfQAsACAAWwBdACkAOwAKAH0AOwAKAA%3D%3D&jsx=false

### Expected result

It should apply fixes successfully.

Instead, it errored with the following

```
2023-12-14T22:22:01.589456Z ERROR  biome::worker_7 Processes linting: crates/biome_cli/src/panic.rs: Biome encountered an unexpected error

This is a bug in Biome, not an error in your code, and we would appreciate it if you could report it to https://github.com/biomejs/biome/issues/ along with the following information to help us fixing the issue:

Source Location: crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs:493:13
Thread Name: biome::worker_7
Message: internal error: entered unreachable code
```

### Debugging notes

I think it's related to using the import statement to alias another type. Bisecting a file showed that the problem is this pattern:

**bad.ts**
```ts
import { useMemo } from 'react';

enum Foo {
  A = 1,
}

import Foo2 = Foo;

const useBad = () => {
  useMemo(() => {
    2 === Foo2.A;
  }, []);
};

```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
The bug is currently triggered here:

https://github.com/biomejs/biome/blob/6d86024e02c4049ae24302964fe0ca4f8229a470/crates/biome_js_analyze/src/semantic_analyzers/correctness/use_exhaustive_dependencies.rs#L505-L513
