### ISSUE TITLE
📎 Create a new `git hooks` recipe 

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#1198]
### Description

Essentially, on this page we want to add some recipes for how to add Biome to commit hooks:
- lint-staged
- lefthook
- etc.

@nhedger:  I know you set up a commit hook in `biome-vscode`, this knowledge could live in that page
@Conaclos : I know you created a repository around this, but honestly, I don't know what that is about. We can have some knowledge in that page

The name of the page isn't set on stone, feel free to come up with a better name

**Comment by danielsarsi** [comment]
Hey! I'm using a simplified pre-commit hook only for formatting. Putting here in case it's useful for this task:
```sh
#!/usr/bin/env sh

EXTENSION="js|jsx|ts|tsx|json|mjs|cjs"
STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E "(${EXTENSION})$" | tr '\n' ' ')

if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

yarn biome format --write --colors=off $STAGED_FILES
git add $STAGED_FILES

if git diff --cached --quiet; then
  echo "No changes left to commit. Aborting."
  exit 1
fi
```

**Comment by depsimon** [comment]
> Hey! I'm using a simplified pre-commit hook only for formatting.

Any downsides to running `check` instead of `format` have you been bit by something?

**Comment by nhedger** [comment]
> > Hey! I'm using a simplified pre-commit hook only for formatting.
> 
> Any downsides to running `check` instead of `format` have you been bit by something?

`check` will also run the linter, so I guess it depends on what you're trying to achieve.
