### ISSUE TITLE
📎 Create a new issue template for documentation

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#1199]
### Description

Some people asked, and maybe we should create a template for that.

Different requirements: 
- URL of the page
- describe the error
- expected result 
- a dropdown of the language (default is English)
- CoC checkbox

Help wanted! :)

**Comment by nhedger** [comment]
Documentation URLs already have the language in the path. Do we need the dropdown? We'd have to maintain the list whenever a new language is added. It's not a big deal, but I can see us forgetting about it.

**Comment by ematipico** [comment]
It's completely possible we will forget about it, but having a drop-down would allow us to assign a label (which we don't have yet) with the language

**Comment by nhedger** [comment]
Alrighty 👌
