### ISSUE TITLE
🐛 Playground console has no scroll

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#120]
### Environment information

```block
Tested on Firefox 117 and Chromium 116.
```

### What happened?

It is no longer possible to scroll in the console of the [playground](https://biomejs.dev/playground/?lintRules=all&code=IABpAGYAIAAoAAoAIAAgACAAIQBpAHMAQgBlAHQAdwBlAGUAbgAoAEsASQBOAEQAXwBOAE8ATgBfAEMASgBLACwAIABLAEkATgBEAF8AQwBKAEsAXwBQAFUATgBDAFQAVQBBAFQASQBPAE4AKQAgACYAJgAKACAAIAAgACAALwAvACAAcwBvAG0AZQAgAGMAbwBtAG0AZQBuAHQACgAgACAAIAAgACEAWwBsAGEAcwB0AE4AbwBkAGUALgB2AGEAbAB1AGUALAAgAG4AbwBkAGUALgB2AGEAbAB1AGUAXQAuAHMAbwBtAGUAKAAoAHYAYQBsAHUAZQApACAAPQA%2BACAALwBcAHUAMwAwADAAMAAvAC4AdABlAHMAdAAoAHYAYQBsAHUAZQApACkACgAgACAAKQAgAHsAfQA%3D).
The bug is not present on the [rome playground](https://docs.rome.tools/playground/?lintRules=all&code=IABpAGYAIAAoAAoAIAAgACAAIQBpAHMAQgBlAHQAdwBlAGUAbgAoAEsASQBOAEQAXwBOAE8ATgBfAEMASgBLACwAIABLAEkATgBEAF8AQwBKAEsAXwBQAFUATgBDAFQAVQBBAFQASQBPAE4AKQAgACYAJgAKACAAIAAgACAALwAvACAAcwBvAG0AZQAgAGMAbwBtAG0AZQBuAHQACgAgACAAIAAgACEAWwBsAGEAcwB0AE4AbwBkAGUALgB2AGEAbAB1AGUALAAgAG4AbwBkAGUALgB2AGEAbAB1AGUAXQAuAHMAbwBtAGUAKAAoAHYAYQBsAHUAZQApACAAPQA%2BACAALwBcAHUAMwAwADAAMAAvAC4AdABlAHMAdAAoAHYAYQBsAHUAZQApACkACgAgACAAKQAgAHsAfQA%3D&typescript=false&jsx=false).

### Expected result

Scrolling should be possible.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Levieber** [comment]
I checked here and it looks like by adding an overflow as auto in the pre tag, the scrolling comes back.

**Comment by Conaclos** [comment]
Oh thank to investigate the issue! Feel free to open a PR :)
