### ISSUE TITLE
📎 Add `source` and `source_kind` to a rule metadata 

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#1200]
### Description

We want to two new metadata fields to our rules:
- `source`: the URL of the rule we inspired from. Many rules aren't "new", but they were inspired or ported from other existing linters: `eslint`, `typescript-eslint`, `clippy`, eslint plugins, etc.
- `source_kind`: the kind of "inspiration", meaning if the rule applies the same logic as the source or if we decided to deviate from the source. 

The two new metadata will have to look like this:

```rs
enum Source {
	Eslint(&'static, &'static str),
	TsEslint(&'static, &'static str),
	Clippy(&'static, &'static str),
	/// All other sources
	Other(&'static, &'static str),
}


enum SourceKind {
	SameLogic,
	Inspired
}
```

When creating a rule, the macro will look like this:

```rs
declare_rule! {
	/// Documentation
    pub(crate) UseAwait {
        version: "1.4.0",
        name: "useAwait",
        recommended: true,
		source: Source::Eslint("require-wait", "https://eslint.org/docs/latest/rules/require-await#rule-details"),
		source_kinud: SourceKind::SameLogic,
    }
}
```

Then, we can use these metadata to enhance the documentation of our pages by adding a new paragraph:
```markdown
Source: <a href="https://eslint.org/docs/latest/rules/require-await#rule-details" target="_blank"><code>require-await</code></a>
```
This new paragraph should be appended to the description of the rule **before** transforming it to HTML. 

Like this, the source is opened to a new tab and we don't disrupt the navigation.

In the future, we can use these metadata to also create a table that maps our rules to eslint.

Here's an example of PR that added new metadata: https://github.com/biomejs/biome/pull/426/files

Please **don't** do everything at once, but:
1. Add the metadata to `RuleMeta`
2. Update the `lintdoc` script
3. Gradually update the lint rules

**Comment by Conaclos** [comment]
Thanks to bring this again, it is something I had in mind since a long time (we discussed it on Discord).
Some remarks:

- I think we can omit the URL for the known sources, because this can be inferred.
- I think we could add more sources ("important" eslint plugins)

**Comment by ematipico** [comment]
@Conaclos feel free to add some pseudo code, so first-time contributors have a clear idea of what they should do. I trust your judgment and ideas.

**Comment by Levieber** [comment]
I want to try this one

**Comment by ematipico** [comment]
Hey @Levieber, that's yours. As suggested, first let's add the metadata. Then update the lintdoc script, and finally we can start adding this data to the rules. It's fine making multiple PRs

**Comment by Levieber** [comment]
What to do with Biome's own rules?

**Comment by ematipico** [comment]
Nothing :)

**Comment by Conaclos** [comment]
Question: if `source` is set, then `source_kind` should be set?

If yes, then we should certainly merge the two fields into a single one?

Using a tuple:

```rs
declare_rule! {
    /// Documentation
    pub(crate) UseAwait {
        name: "useAwait",
        source: (Source::Eslint("require-wait"), SourceKind::SameLogic),
    }
}
```

or:

```rs
declare_rule! {
    /// Documentation
    pub(crate) UseAwait {
        name: "useAwait",
        source: (Source::Eslint("require-wait", SourceKind::SameLogic),
    }
}
```

**Comment by ematipico** [comment]
If the source kind isn't set, we can fairly assume that we haven't deviated. Or we can throw a panic when we launch the lintdoc script and force the user to set one. Or your suggestion. We have options. I prefer defaults, less friction towards contributors.

**Comment by ematipico** [comment]
We merged the PR from @Levieber, we can now start gradually adding these metadata to the rules
