### ISSUE TITLE
📝 Biome differs from prettier for Array.reduce when second arg is long

### ISSUE THREAD

**Issue by jschaf** [biomejs/biome#1208]
### Environment information

```bash
CLI:
  Version:                      1.4.1-nightly.e087146
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.3.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
  "$schema": "https://biomejs.dev/schemas/1.4.1/schema.json",
  "javascript": {
    "formatter": {
      "lineWidth": 100
    }
  }
}
```

### Playground link

https://biomejs.dev/playground/?lineWidth=100&indentStyle=space&bracketSameLine=true&code=dAB5AHAAZQAgAEQAZQBsAGkAdgBlAHIAeQBXAGkAbgBkAG8AdwAgAD0AIABzAHQAcgBpAG4AZwA7AAoACgAvAC8AIABCAGkAbwBtAGUAIABmAG8AcgBtAGEAdABzACAAcgBlAGQAdQBjAGUAIAAiAGMAdQBkAGQAbABlAGQAIgA7ACAAcwB0AGEAcgB0AGkAbgBnACAAbwBuACAAdABoAGUAIABzAGEAbQBlACAAbABpAG4AZQAuAAoAZQB4AHAAbwByAHQAIABjAG8AbgBzAHQAIABmAG8AbwBRAHUAeAAgAD0AIAAoAGQAZQBsAGkAdgBlAHIAeQBXAGkAbgBkAG8AdwBzADoAIABEAGUAbABpAHYAZQByAHkAVwBpAG4AZABvAHcAWwBdACkAOgAgAEQAZQBsAGkAdgBlAHIAeQBXAGkAbgBkAG8AdwBbAF0AIAA9AD4ACgAgACAAWwAuAC4ALgBkAGUAbABpAHYAZQByAHkAVwBpAG4AZABvAHcAcwBdAC4AcgBlAGQAdQBjAGUAKAAoAGEAYwBjACwAIABjAHUAcgByACkAIAA9AD4AIAB7AAoAIAAgACAAIABpAGYAIAAoAGMAdQByAHIAIAA9AD0APQAgACcAJwApACAAewAKACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAYQBjAGMAOwAKACAAIAAgACAAfQAKACAAIAAgACAAcgBlAHQAdQByAG4AIABbAC4ALgAuAGEAYwBjACwAIABjAHUAcgByAF0AOwAKACAAIAB9ACwAIABbAF0AIABhAHMAIABzAHQAcgBpAG4AZwBbAF0AKQA7AAoACgAvAC8AIABCAGkAbwBtAGUAIABmAG8AcgBtAGEAdABzACAAcgBlAGQAdQBjAGUAIABiAHkAIABvAHAAZQBuAGkAbgBnACAAYQAgAG4AZQB3ACAAbABpAG4AZQAuACAACgAvAC8AIABUAGgAZQAgAG8AbgBsAHkAIABjAGgAYQBuAGcAZQAgAGkAcwAgAHUAcwBpAG4AZwAgACIAYQBzACAARABlAGwAaQB2AGUAcgB5AFcAaQBuAGQAbwB3AFsAXQAiACAAaQBuAHMAdABlAGEAZAAgAG8AZgAgACIAYQBzACAAcwB0AHIAaQBuAGcAWwBdACIALgAKAGUAeABwAG8AcgB0ACAAYwBvAG4AcwB0ACAAZgBvAG8AUQB1AHgAMgAgAD0AIAAoAGQAZQBsAGkAdgBlAHIAeQBXAGkAbgBkAG8AdwBzADoAIABEAGUAbABpAHYAZQByAHkAVwBpAG4AZABvAHcAWwBdACkAOgAgAEQAZQBsAGkAdgBlAHIAeQBXAGkAbgBkAG8AdwBbAF0AIAA9AD4ACgAgACAAWwAuAC4ALgBkAGUAbABpAHYAZQByAHkAVwBpAG4AZABvAHcAcwBdAC4AcgBlAGQAdQBjAGUAKAAKACAAIAAgACAAKABhAGMAYwAsACAAYwB1AHIAcgApACAAPQA%2BACAAewAKACAAIAAgACAAIAAgAGkAZgAgACgAYwB1AHIAcgAgAD0APQA9ACAAJwAnACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAYQBjAGMAOwAKACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAByAGUAdAB1AHIAbgAgAFsALgAuAC4AYQBjAGMALAAgAGMAdQByAHIAXQA7AAoAIAAgACAAIAB9ACwACgAgACAAIAAgAFsAXQAgAGEAcwAgAEQAZQBsAGkAdgBlAHIAeQBXAGkAbgBkAG8AdwBbAF0ALAAgAAoAIAAgACkAOwAKAA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by faultyserver** [comment]
I _believe_ this is fixed by https://github.com/biomejs/biome/pull/1057. I can test it out on `main` later today, but that fix will be in the next release.

**Comment by jschaf** [comment]
I'm running 1.4.1-nightly.e087146 which is 
 https://github.com/biomejs/biome/commit/2928f95f6194b800b69382cac85cd0c36463618d.

Looks like #1152 was merged before that, so it wouldn't fix this issue.

**Comment by faultyserver** [comment]
ahh. I see the issue now. It's not necessarily the length of the type, but the fact that it's not a primitive type. even just the letter `n` as the type (i.e., `[] as n[]` causes it to break.

So what we need is a check for short reference identifiers in the type as well.

**Comment by jschaf** [comment]
One day turnaround! Nice work and much appreciated.
