### ISSUE TITLE
☂️ Translate the website into Arabic (ar)

### ISSUE THREAD

**Issue by ImBIOS** [biomejs/biome#1223]
### Description

If you would like to contribute to a specific page, please leave a comment indicating the page you would like to translate and create a PR.
If there is any error, please notify us here in the comments.

- [x] Translate sidebar @ImBIOS
- [x] Translate README.md @ImBIOS
- [ ] Translate the files inside src/content/docs
  - [x] index.md @ImBIOS 
  - [ ] 404.md
  - [ ] analyzer/index.mdx
  - [ ] formatter/index.mdx
  - [ ] formatter/option-philosophy.md
  - [ ] formatter/differences-with-prettier.md
  - [ ] linter/index.mdx
  - [ ] guides/big-projects.mdx
  - [ ] guides/getting-started.mdx
  - [ ] guides/how-biome-works.mdx
  - [ ] guides/integrate-in-editor.mdx
  - [ ] guides/manual-installation.mdx
  - [ ] internals/architecture.mdx
  - [ ] internals/credits.mdx
  - [ ] internals/language-support.mdx
  - [ ] internals/philosophy.mdx
  - [ ] internals/versioning.mdx
  - [ ] recipes/continuous-integration.mdx
  - [ ] reference/vscode.mdx

The following files don't need to be translated, since they are auto-generated

- internals/changelog.mdx
- linter/rules/*.mdx
- reference/configuration.mdx (will be auto-generated in <https://github.com/biomejs/biome/issues/825> )
- reference/cli.mdx
- blog/*.mdx (low priority)

**Comment by ematipico** [comment]
Thank you @ImBIOS , but we are going to wait for translating pages to this language until we have more contributors/maintainers that speak this language.
