### ISSUE TITLE
📎 Implement `lint/useNumberNamespace` - `eslint-unicorn/prefer-number-properties`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#1228]
### Description

Implement [prefer-number-properties](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-number-properties.md)

Biome already provides [noGlovalIsFinite](https://biomejs.dev/linter/rules/no-global-is-finite/) and [noGlobalIsNan](https://biomejs.dev/linter/rules/no-global-is-nan/) because the global and Number-namespaced functions have not the same semantic. Thus, the new rule should ignore these two functions.

The new rule could provide a safe fix.

Want to contribute? Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z).

Suggested names: `useNumberNamespace`, `useNumberProperties`

## Implementation notes

Take a look at the implementations of [noGlovalIsFinite](https://biomejs.dev/linter/rules/no-global-is-finite/) and [noGlobalIsNan](https://biomejs.dev/linter/rules/no-global-is-nan/).

**Comment by seitarof** [comment]
Hi! I'd like to try on this.

**Comment by ematipico** [comment]
I wonder why this should fail

```js
const {parseInt} = Number;
const foo = parseInt('10', 2);
```

**Comment by Conaclos** [comment]
> I wonder why this should fail
> 
> ```js
> const {parseInt} = Number;
> const foo = parseInt('10', 2);
> ```

Same here. I think we should only take global references into account. This example should pass.
