### ISSUE TITLE
📎 Add code fix for `lint/useNodeImportProtocol`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#1261]
### Description

`useNodeImportProtocol` was recently added without code fix. We could add a code fix that suggests adding the `node:` protocol to the import. The fix should be unsafe because we cannot be sure that the module is a NodeJs module.

Want to contribute? Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z).

**Comment by vasucp1207** [comment]
I want to work on this
