### ISSUE TITLE
💅 `noUnusedImports` does not work with using TS `declare const`

### ISSUE THREAD

**Issue by AbhiPrasad** [biomejs/biome#1269]
### Environment information

```bash
$ /Users/abhijeetprasad/workspace/sentry-javascript/node_modules/.bin/biome rage
CLI:
  Version:                      1.4.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/1.22.19"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### Rule name

lint/nursery/noUnusedImports

### Playground link

https://biomejs.dev/playground/?lintRules=all&code=aQBtAHAAbwByAHQAIAAqACAAYQBzACAAcgBvAHUAdABlAE0AbwBkAHUAbABlACAAZgByAG8AbQAgACcAXwBfAFMARQBOAFQAUgBZAF8AVwBSAEEAUABQAEkATgBHAF8AVABBAFIARwBFAFQAXwBGAEkATABFAF8AXwAnADsACgAKAGQAZQBjAGwAYQByAGUAIABjAG8AbgBzAHQAIAByAG8AdQB0AGUATQBvAGQAdQBsAGUAOgAgAHsACgAgACAARwBFAFQAPwA6ACAAKAAuAC4ALgBhAHIAZwBzADoAIAB1AG4AawBuAG8AdwBuAFsAXQApACAAPQA%2BACAAdQBuAGsAbgBvAHcAbgA7AAoAIAAgAFAATwBTAFQAPwA6ACAAKAAuAC4ALgBhAHIAZwBzADoAIAB1AG4AawBuAG8AdwBuAFsAXQApACAAPQA%2BACAAdQBuAGsAbgBvAHcAbgA7AAoAIAAgAFAAVQBUAD8AOgAgACgALgAuAC4AYQByAGcAcwA6ACAAdQBuAGsAbgBvAHcAbgBbAF0AKQAgAD0APgAgAHUAbgBrAG4AbwB3AG4AOwAKACAAIABQAEEAVABDAEgAPwA6ACAAKAAuAC4ALgBhAHIAZwBzADoAIAB1AG4AawBuAG8AdwBuAFsAXQApACAAPQA%2BACAAdQBuAGsAbgBvAHcAbgA7AAoAIAAgAEQARQBMAEUAVABFAD8AOgAgACgALgAuAC4AYQByAGcAcwA6ACAAdQBuAGsAbgBvAHcAbgBbAF0AKQAgAD0APgAgAHUAbgBrAG4AbwB3AG4AOwAKACAAIABIAEUAQQBEAD8AOgAgACgALgAuAC4AYQByAGcAcwA6ACAAdQBuAGsAbgBvAHcAbgBbAF0AKQAgAD0APgAgAHUAbgBrAG4AbwB3AG4AOwAKACAAIABPAFAAVABJAE8ATgBTAD8AOgAgACgALgAuAC4AYQByAGcAcwA6ACAAdQBuAGsAbgBvAHcAbgBbAF0AKQAgAD0APgAgAHUAbgBrAG4AbwB3AG4AOwAKAH0AOwAKAAoAZQB4AHAAbwByAHQAIABjAG8AbgBzAHQAIABHAEUAVAAgAD0AIABbAHIAbwB1AHQAZQBNAG8AZAB1AGwAZQAuAEcARQBUACwAIAAnAEcARQBUACcAXQA7AA%3D%3D

### Expected result

When importing a function and using `declare const` to declare a type of that function, `noUnusedImports` always assumes the import is unused. 

See https://github.com/getsentry/sentry-javascript/pull/9895/files#r1430423634 for example PR.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
I was not aware of this kind of [declaration merging](https://www.typescriptlang.org/docs/handbook/declaration-merging.html). Do you have any _TypeScript_ resources that document this? This looks wrong to me 🤔

I could suggest using module augmentation instead:

```ts
import * as routeModule from "__SENTRY_WRAPPING_TARGET_FILE__";

declare module "__SENTRY_WRAPPING_TARGET_FILE__" {
  export function GET(...args: unknown[]): unknown;
  /* ... */
}

export const GET = [routeModule.GET, 'GET'];
```

**Comment by AbhiPrasad** [comment]
I can't find any TS docs about it, but it is valid - see some examples from the TS codebase itself https://github.com/search?q=repo%3Amicrosoft%2FTypeScript+declare+const&type=code

I agree your change feels more idomatic, but I think biome should still account for this edge case.

**Comment by ematipico** [comment]
> I agree your change feels more idomatic, but I think biome should still account for this edge case.

While I feel the sentiment, I find it very hard to explain something that we can't document. When we create a rule, we always strive to write something that we can properly document, with references too. 

If we can't document this edge case, how can we prove that what we are doing is the right way?

**Comment by Conaclos** [comment]
> I can't find any TS docs about it, but it is valid - see some examples from the TS codebase itself https://github.com/search?q=repo%3Amicrosoft%2FTypeScript+declare+const&type=code

`declare const` is indeed valid and documented. What I am talking about is making cohabit an import and a `declare const` with the same name.

I took some time to test locally, and if the imported file exists, I get an error:

```ts
// @filename a.jts
export {}


// @filename b.js
import * as ns from "./a.js";
//          ^^
//          Import declaration conflicts with local declaration of 'ns'. ts(2440)

declare const ns: {
  f: () => unknown
};
```

However, if the imported file doesn't exist (your case?), _TypeScript_ doesn't report the error – this is likely a bug from TSC.
Thus, I think it is an error of using an identical name for an import and a `declare const`.

**Comment by AbhiPrasad** [comment]
Got it, thanks for helping investigate, I'll also open a bug with TS about the compiler issue.
