### ISSUE TITLE
CSS Parser: parse font feature values 

### ISSUE THREAD

**Issue by denbezrukov** [biomejs/biome#1282]
https://developer.mozilla.org/en-US/docs/Web/CSS/@font-feature-values

**Comment by suxin2017** [comment]
please assign this to me

**Comment by unvalley** [comment]
@suxin2017 Could you work on another issue? I'll send a PR within a few days.

**Comment by suxin2017** [comment]
> @suxin2017 Could you work on another issue? I'll send a PR within a few days.

👌
