### ISSUE TITLE
📎 Implement `json.parser.allowTrailingCommas`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#129]
### Description

As reported in #83, some config files support trailing comma.
`json.parser.allowTrailingCommas: true` enables trailing commas in `json` and `jsonc` files, making the following example valid:

```jsonc
{
  "prop1": [
    1,
    2,
  ],
  "prop2": 0,
}
```

Similar to `json.parser.allowComments`, `json.parser.allowTrailingCommas: true` should be enabled by default when parsing files such as `tsconfig.json`, [VSCode config files](https://code.visualstudio.com/docs/languages/json#_json-with-comments), and others?

**Comment by nissy-dev** [comment]
I'm working
