### ISSUE TITLE
🐛 Prefer biome.json over rome.json

### ISSUE THREAD

**Issue by yphoenix** [biomejs/biome#132]
### Environment information

```block
You have both a rome.json and biome.json file while you migrate your build system.
```

### What happened?

If you have both a rome.json file (for reasons) and a biome.json file, biome reads the rome.json file and ignores the biome.json file.

### Expected result

It should prefer the biome config file and fall back to the rome one if not found.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
Closing because it is already planned. See #54.
