### ISSUE TITLE
📝 Comments are displaced when formatting JSON with comments

### ISSUE THREAD

**Issue by espenja** [biomejs/biome#1322]
### Environment information

```bash
λ pnpm biome rage
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.11.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
	"$schema": "https://biomejs.dev/schemas/1.4.1/schema.json",
	"organizeImports": {
		"enabled": true
	},
	"linter": {
		"enabled": true,
		"rules": {
			"recommended": true,
			"suspicious": {
				"noExplicitAny": "off"
			},
			"complexity": {
				"noStaticOnlyClass": "off"
			}
		}
	},
	"formatter": {
		"enabled": true,
		"indentStyle": "tab",
		"indentWidth": 4,
		"lineEnding": "lf",
		"lineWidth": 130,
		"formatWithErrors": false
	},
	"javascript": {
		"formatter": {
			"enabled": true,
			"semicolons": "asNeeded",
			"trailingComma": "none"
		},
		"parser": {
			"unsafeParameterDecoratorsEnabled": true
		}
	},
	"json": {
		"formatter": {
			"enabled": true,
			"indentStyle": "tab",
			"indentWidth": 2
		},
		"parser": {
			"allowComments": true,
			"allowTrailingCommas": false
		}
	},
	"files": {
		"include": ["**/*.[jt]s", "**/*.[jt]sx", "**/*.json", "**/*.md"],
		"ignore": ["**/node_modules/**", "**/__azurite*", "**/dist/**", "**/*tsconfig*", "**/swagger/swagger*.*"]
	}
}
```

### Playground link

https://biomejs.dev/playground/?indentWidth=4&files.settings.json=ewAgAAoACQAvAC8AIABJAGYAIABhACAASgBTAE8ATgAgAGYAaQBsAGUAIAB3AGkAdABoACAAYwBvAG0AbQBlAG4AdABzACAAYwBvAG4AdABhAGkAbgBzACAAYQBuACAAbwBiAGoAZQBjAHQAIAB3AGgAaQBjAGgAIABpAHMAIAAiAGUAbQBwAHQAeQAiACwAIABvAG4AbAB5ACAAYwBvAG4AdABhAGkAbgBpAG4AZwAgAGMAbwBtAG0AZQBuAHQAZQBkACAAbwB1AHQAIABwAHIAbwBwAGUAcgB0AGkAZQBzACAAYQBuAGQAIAB2AGEAbAB1AGUAcwAsACAAdABoAGUAIAByAGUAcwB1AGwAdABpAG4AZwAgAGYAbwByAG0AYQB0AHQAaQBuAGcAIAB3AGkAdABoACAAQgBpAG8AbQBlACAAZABpAHMAcABsAGEAYwBlAHMAIAB0AGgAZQAgAGMAbwBtAG0AZQBuAHQAcwAsACAAYQBuAGQAIABwAHUAdABzACAAdABoAGUAIABjAGwAbwBzAGkAbgBnACAAYgByAGEAYwBrAGUAdAAgAEIARQBGAE8AUgBFACAAYQBsAGwAIABjAG8AbQBtAGUAbgB0AHMALgAgAFQAaABpAHMAIABkAG8AZQBzACAAbgBvAHQAIABoAGEAcABwAGUAbgAgAGkAZgAgAHQAaABlACAAbwBiAGoAZQBjAHQAIABjAG8AbgB0AGEAaQBuAHMAIABhAHQAIABsAGUAYQBzAHQAIABvAG4AZQAgAGwAaQBuAGUAIAB0AGgAYQB0ACAAaQBzACAAbgBvAHQAIABjAG8AbQBtAGUAbgB0AGUAZAAuACAASQBmACAAdABoAGUAIABmAGkAbABlACAAaQBzACAAZgBvAHIAbQBhAHQAdABlAGQAIABhACAAcwBlAGMAbwBuAGQAIAB0AGkAbQBlACwAIAB0AGgAZQAgAGMAbwBtAG0AZQBuAHQAcwAgAHcAaQBsAGwAIABoAGEAdgBlACAAdABoAGUAaQByACAAaQBuAGQAZQBuAHQAYQB0AGkAbwBuACAAcgBlAG0AbwB2AGUAZAAuACAAVQBuAGMAbwBtAG0AZQBuAHQAaQBuAGcAIAB0AGgAZQBzAGUAIABsAGkAbgBlAHMAIABhAGYAdABlAHIAIAB0AGgAaQBzACAAZgBvAHIAbQBhAHQAdABpAG4AZwAgAHQAaABlAG4AIABwAHIAbwBkAHUAYwBlAHMAIABpAG4AdgBhAGwAaQBkACAASgBTAE8ATgAsACAAZgBvAHIAIABlAHgAYQBtAHAAbABlACAAaQBuACAALgB2AHMAYwBvAGQAZQAvAHMAZQB0AHQAaQBuAGcAcwAuAGoAcwBvAG4ACgAJACIAZgBpAGwAZQBzAC4AZQB4AGMAbAB1AGQAZQAiADoAIAB7AAoACQAJAC8ALwAgACIAKgAqAC8AXwBfACoAcwB0AG8AcgBhAGcAZQAqAF8AXwAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwBfAF8AKgBhAHoAdQByAGkAdABlACoAXwBfAC4AagBzAG8AbgAiADoAIAB0AHIAdQBlAAoACQAJAC8ALwAgACIAKgAqAC8ALgBnAGkAdAAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwAuAGcAaQB0AGEAdAB0AHIAaQBiAHUAdABlAHMAIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8ALgBnAGkAdABpAGcAbgBvAHIAZQAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwAuAGgAdQBzAGsAeQAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwAuAGwAaQBuAHQAcwB0AGEAZwBlAGQAcgBjAC4AagBzAG8AbgAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwAuAG4AcABtAHIAYwAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwAuAHAAcgBlAHQAdABpAGUAcgBpAGcAbgBvAHIAZQAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwAuAHAAcgBlAHQAdABpAGUAcgByAGMAIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8ALgBzAHcAYwByAGMAIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8ALgB0AHMAYgB1AGkAbABkAGkAbgBmAG8AIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8ALgB0AHUAcgBiAG8AIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8AYgBpAGMAZQBwAGMAbwBuAGYAaQBnAC4AagBzAG8AbgAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwBqAGUAcwB0AC4AYwBvAG4AZgBpAGcAKgAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwBuAG8AZABlAF8AbQBvAGQAdQBsAGUAcwAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwBuAG8AZABlAG0AbwBuAC4AagBzAG8AbgAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwBwAG4AcABtAC0AdwBvAHIAawBzAHAAYQBjAGUALgB5AGEAbQBsACIAOgAgAHQAcgB1AGUALAAKAAkACQAvAC8AIAAiACoAKgAvAHQAcwBjAG8AbgBmAGkAZwAqAC4AagBzAG8AbgAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwB0AHMAdQBwACoALgBqAHMAbwBuACIAOgAgAHQAcgB1AGUALAAKAAkACQAvAC8AIAAiACoAKgAvAHQAcwB1AHAALgBjAG8AbgBmAGkAZwAuAHQAcwAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwB0AHUAcgBiAG8ALgBqAHMAbwBuACIAOgAgAHQAcgB1AGUALAAKAAkACQAvAC8AIAAiACoAKgAvAHYAaQB0AGUALgBjAG8AbgBmAGkAZwAuAHQAcwAiADoAIAB0AHIAdQBlAAoACQB9AAoAfQA%3D&files.settings2.json=ewAgAAoACQAvAC8AIABJAGYAIABhACAASgBTAE8ATgAgAGYAaQBsAGUAIAB3AGkAdABoACAAYwBvAG0AbQBlAG4AdABzACAAYwBvAG4AdABhAGkAbgBzACAAYQBuACAAbwBiAGoAZQBjAHQAIAB3AGgAaQBjAGgAIABpAHMAIAAiAGUAbQBwAHQAeQAiACwAIABvAG4AbAB5ACAAYwBvAG4AdABhAGkAbgBpAG4AZwAgAGMAbwBtAG0AZQBuAHQAZQBkACAAbwB1AHQAIABwAHIAbwBwAGUAcgB0AGkAZQBzACAAYQBuAGQAIAB2AGEAbAB1AGUAcwAsACAAdABoAGUAIAByAGUAcwB1AGwAdABpAG4AZwAgAGYAbwByAG0AYQB0AHQAaQBuAGcAIAB3AGkAdABoACAAQgBpAG8AbQBlACAAZABpAHMAcABsAGEAYwBlAHMAIAB0AGgAZQAgAGMAbwBtAG0AZQBuAHQAcwAsACAAYQBuAGQAIABwAHUAdABzACAAdABoAGUAIABjAGwAbwBzAGkAbgBnACAAYgByAGEAYwBrAGUAdAAgAEIARQBGAE8AUgBFACAAYQBsAGwAIABjAG8AbQBtAGUAbgB0AHMALgAgAFQAaABpAHMAIABkAG8AZQBzACAAbgBvAHQAIABoAGEAcABwAGUAbgAgAGkAZgAgAHQAaABlACAAbwBiAGoAZQBjAHQAIABjAG8AbgB0AGEAaQBuAHMAIABhAHQAIABsAGUAYQBzAHQAIABvAG4AZQAgAGwAaQBuAGUAIAB0AGgAYQB0ACAAaQBzACAAbgBvAHQAIABjAG8AbQBtAGUAbgB0AGUAZAAuACAASQBmACAAdABoAGUAIABmAGkAbABlACAAaQBzACAAZgBvAHIAbQBhAHQAdABlAGQAIABhACAAcwBlAGMAbwBuAGQAIAB0AGkAbQBlACwAIAB0AGgAZQAgAGMAbwBtAG0AZQBuAHQAcwAgAHcAaQBsAGwAIABoAGEAdgBlACAAdABoAGUAaQByACAAaQBuAGQAZQBuAHQAYQB0AGkAbwBuACAAcgBlAG0AbwB2AGUAZAAuACAAVQBuAGMAbwBtAG0AZQBuAHQAaQBuAGcAIAB0AGgAZQBzAGUAIABsAGkAbgBlAHMAIABhAGYAdABlAHIAIAB0AGgAaQBzACAAZgBvAHIAbQBhAHQAdABpAG4AZwAgAHQAaABlAG4AIABwAHIAbwBkAHUAYwBlAHMAIABpAG4AdgBhAGwAaQBkACAASgBTAE8ATgAsACAAZgBvAHIAIABlAHgAYQBtAHAAbABlACAAaQBuACAALgB2AHMAYwBvAGQAZQAvAHMAZQB0AHQAaQBuAGcAcwAuAGoAcwBvAG4ACgAJACIAZgBpAGwAZQBzAC4AZQB4AGMAbAB1AGQAZQAiADoAIAB7AAoACQAJACIAKgAqAC8AXwBfACoAcwB0AG8AcgBhAGcAZQAqAF8AXwAiADoAIAB0AHIAdQBlAAoACQAJAC8ALwAgACIAKgAqAC8AXwBfACoAYQB6AHUAcgBpAHQAZQAqAF8AXwAuAGoAcwBvAG4AIgA6ACAAdAByAHUAZQAKAAkACQAvAC8AIAAiACoAKgAvAC4AZwBpAHQAIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8ALgBnAGkAdABhAHQAdAByAGkAYgB1AHQAZQBzACIAOgAgAHQAcgB1AGUALAAKAAkACQAvAC8AIAAiACoAKgAvAC4AZwBpAHQAaQBnAG4AbwByAGUAIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8ALgBoAHUAcwBrAHkAIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8ALgBsAGkAbgB0AHMAdABhAGcAZQBkAHIAYwAuAGoAcwBvAG4AIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8ALgBuAHAAbQByAGMAIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8ALgBwAHIAZQB0AHQAaQBlAHIAaQBnAG4AbwByAGUAIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8ALgBwAHIAZQB0AHQAaQBlAHIAcgBjACIAOgAgAHQAcgB1AGUALAAKAAkACQAvAC8AIAAiACoAKgAvAC4AcwB3AGMAcgBjACIAOgAgAHQAcgB1AGUALAAKAAkACQAvAC8AIAAiACoAKgAvAC4AdABzAGIAdQBpAGwAZABpAG4AZgBvACIAOgAgAHQAcgB1AGUALAAKAAkACQAvAC8AIAAiACoAKgAvAC4AdAB1AHIAYgBvACIAOgAgAHQAcgB1AGUALAAKAAkACQAvAC8AIAAiACoAKgAvAGIAaQBjAGUAcABjAG8AbgBmAGkAZwAuAGoAcwBvAG4AIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8AagBlAHMAdAAuAGMAbwBuAGYAaQBnACoAIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8AbgBvAGQAZQBfAG0AbwBkAHUAbABlAHMAIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8AbgBvAGQAZQBtAG8AbgAuAGoAcwBvAG4AIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8AcABuAHAAbQAtAHcAbwByAGsAcwBwAGEAYwBlAC4AeQBhAG0AbAAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwB0AHMAYwBvAG4AZgBpAGcAKgAuAGoAcwBvAG4AIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8AdABzAHUAcAAqAC4AagBzAG8AbgAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwB0AHMAdQBwAC4AYwBvAG4AZgBpAGcALgB0AHMAIgA6ACAAdAByAHUAZQAsAAoACQAJAC8ALwAgACIAKgAqAC8AdAB1AHIAYgBvAC4AagBzAG8AbgAiADoAIAB0AHIAdQBlACwACgAJAAkALwAvACAAIgAqACoALwB2AGkAdABlAC4AYwBvAG4AZgBpAGcALgB0AHMAIgA6ACAAdAByAHUAZQAKAAkAfQAKAH0A

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by espenja** [comment]
I was unsure where to add expected and actual behavior, as there were no fields for it in the template, but I included a description in a comment in both files in the playground link.

**Comment by faultyserver** [comment]
I think the playground is probably the best place to talk about actual/expected behavior, since we can always see the input and output right next to each other and compare directly to Prettier there.

And thanks for the detailed information about what's happening in there! Makes it very easy to diagnose.
