### ISSUE TITLE
Cannot run on StackBlitz: `< must be followed by a word`

### ISSUE THREAD

**Issue by tony19** [biomejs/biome#1341]
### Environment information

The requested command fails on StackBlitz:

```block
❯ npx @biomejs/biome rage
/home/projects/github-ogy9eg/node_modules/@biomejs/cli-linux-x64/biome: line 1: < must be followed by a word
```

### What happened?

1. Open [StackBlitz repro](https://stackblitz.com/edit/github-ogy9eg?file=.stackblitzrc).
2. Observe the error in the terminal:

    ```
    /home/projects/github-ogy9eg/node_modules/@biomejs/cli-linux-x64/biome: line 1: < must be followed by a word
    ```

### Expected result

`biome` runs without that error

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
I suggest opening an issue in stackblitz repository. Biome works in codesandbox, even though they use different technologies.

That's why we don't use stackblitz to reproduce issues.
