### ISSUE TITLE
☂️ Translate the website into Spanish

### ISSUE THREAD

**Issue by bjohansebas** [biomejs/biome#1380]
### Description

If you would like to contribute to a specific page, please leave a comment indicating the page you would like to translate and create a PR.
If there is any error, please notify here in the comments

## Pages

- [ ] Translate sidebar @bjohansebas
- [ ] Translate README.md 
- [ ] Translate the files inside src/content/docs
    - [ ] index.mdx @bjohansebas
    - [ ] analyzer/index.mdx @bjohansebas
    - [ ] formatter/index.mdx @bjohansebas
    - [ ] formatter/option-philosophy.md @bjohansebas 
    - [ ] formatter/differences-with-prettier.md @bjohansebas 
    - [ ] linter/index.mdx
    - [ ] guides/big-projects.mdx
    - [ ] guides/getting-started.mdx
    - [ ] guides/how-biome-works.mdx
    - [ ] guides/integrate-in-editor.mdx
    - [ ] guides/manual-installation.mdx
    - [ ] internals/architecture.mdx
    - [ ] internals/credits.mdx
    - [ ] internals/language-support.mdx
    - [ ] internals/philosophy.mdx
    - [ ] internals/versioning.mdx
    - [ ] recipes/continuous-integration.mdx
    - [ ] reference/vscode.mdx

The following files don't need to be translated, since they are auto-generate

- internals/changelog.mdx
- linter/rules/*.mdx
- reference/configuration.mdx (will be auto-generated in #825)
- reference/cli.mdx

**Comment by ematipico** [comment]
@bjohansebas are there other people who will help you?

**Comment by pataruco** [comment]
@ematipico @bjohansebas I can help, and I can commit if docs change in the future, too.

@ematipico, Are two people enough for your team to push this feature forward?

**Comment by ematipico** [comment]
I'm not a Spanish speaker. For now it's you and @bjohansebas :)

**Comment by bjohansebas** [comment]
@pataruco thank you for supporting this initiative.

**Comment by eyubkh** [comment]
@bjohansebas @pataruco Hi guys, I can help with this also. 

@ematipico How many people is need it to do the translation?

**Comment by ematipico** [comment]
At least two
