### ISSUE TITLE
Show advice messages to help to fix lint error with error message

### ISSUE THREAD

**Issue by mehm8128** [biomejs/biome#1391]
I have discussed in https://github.com/biomejs/biome/discussions/1390
`react-hooks/exhaustive-deps` shows advice message including concrete missing variable names with error message such as `React Hook useEffect has a missing dependency: 'missingVariableName'. Either include it or remove the dependency array.`, but biome VSCode extension shows only error message such as `This hook specifies more dependencies than necessary.` when we use `useExhaustiveDependencies` rule.
With concrete missing variable names, we can quickly fix lint error. So I want you to consider about it.

**Comment by ematipico** [comment]
@mehm8128 I moved it here because the diagnostics is something that part of the core repository, not the VSCode extension

**Comment by mehm8128** [comment]
Sorry, Thank you🙏

**Comment by SuperKruse** [comment]
esLint have a quick fix for it, that either adds or removes the necessary dependencies.
Would it be possible to add that functionality?

**Comment by ematipico** [comment]
> esLint have a quick fix for it, that either adds or removes the necessary dependencies.
> Would it be possible to add that functionality?

I think it's best to create a new issue for that. Creating a code action isn't as simple as changing a phrase in the diagnostic.

**Comment by mehm8128** [comment]
For this issue, is it ok that we only show missing or excessive variable names with error message such as `This hook specifies more dependencies than necessary: 'excessiveVariable'`?
