### ISSUE TITLE
Biome errors out on decorator params

### ISSUE THREAD

**Issue by ThallesP** [biomejs/biome#1403]
### Environment information

```block
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.16.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.5.1"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

[Code Sandbox Reproduction](https://codesandbox.io/p/devbox/biome-starter-cbs-rky6zq?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqwez2ho0005356kbpk3zclc%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqwez2hn0002356kxw8gibnh%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqwez2hn0003356kll5s656j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqwez2hn0004356kfkzat12a%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqwez2hn0002356kxw8gibnh%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqwez2hn0001356kkjjo5scb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%257D%255D%252C%2522id%2522%253A%2522clqwez2hn0002356kxw8gibnh%2522%252C%2522activeTabId%2522%253A%2522clqwez2hn0001356kkjjo5scb%2522%257D%252C%2522clqwez2hn0004356kfkzat12a%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqwez2hn0004356kfkzat12a%2522%257D%252C%2522clqwez2hn0003356kll5s656j%2522%253A%257B%2522id%2522%253A%2522clqwez2hn0003356kll5s656j%2522%252C%2522activeTabId%2522%253A%2522clqwf0yb9008q356kyqeb2mzf%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqwf0yb9008q356kyqeb2mzf%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clqwf0yna000jedip7d4f6cih%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Expected result

It should work

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ThallesP** [comment]
fixing issue with reproduction link, give me a minute

**Comment by ematipico** [comment]
You must enable this property https://biomejs.dev/reference/configuration/#javascriptparserunsafeparameterdecoratorsenabled

**Comment by ThallesP** [comment]
> You must enable this property https://biomejs.dev/reference/configuration/#javascriptparserunsafeparameterdecoratorsenabled

Hey @ematipico thanks it's working now, could I ask why it's unsafe? 
Would be possible to warn the user about this flag on the cli output somehow until this is fixed?

**Comment by ematipico** [comment]
There's nothing to fix, we decided to name the option like this because parameter decorators aren't part of the official spec of JavaScript, so you're effectively using invalid syntax.

**Comment by jpike88** [comment]
I know im being cheeky... @ematipico just as an fyi, biomejs has a 'differences with prettier' page. On that page, you should add that prettier would format the css and html in this code, while biomejs will not:

```
@Component({
  template: `
    <div>
      Hello World
    </div>
  `,
  styles: `
    div { background: pink; }
  `
})
export class AppComponent {}
```
