### ISSUE TITLE
📝 Formatter propose change that brokes parse with comment and async function

### ISSUE THREAD

**Issue by witem** [biomejs/biome#1406]
### Environment information

```bash
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "screen-256color"
  JS_RUNTIME_VERSION:           "v18.16.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/3.2.3"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
  "$schema": "https://biomejs.dev/schemas/1.4.1/schema.json",
  "organizeImports": {
    "enabled": true
  },
  "files": {
    "ignore": ["*.md", "__*.ts", "node_modules/**/*", "dist/**/*"]
  },
  "formatter": {
    "indentStyle": "space",
    "indentWidth": 2,
    "lineWidth": 100,
    "ignore": []
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
      "style": {
        "noParameterAssign": "warn"
      },
      "suspicious": {
        "noExplicitAny": "warn",
        "noConfusingVoidType": "warn",
        "noAssignInExpressions": "warn",
        "noMisrefactoredShorthandAssign": "error"
      },
      "complexity": {
        "noForEach": "off",
        "noStaticOnlyClass": "warn",
        "noExcessiveCognitiveComplexity": {
          "level": "error",
          "options": {
            "maxAllowedComplexity": 20
          }
        }
      },
      "correctness": {
        "noVoidTypeReturn": "warn"
      }
    }
  },
  "javascript": {
    "parser": {
      "unsafeParameterDecoratorsEnabled": true
    },
    "formatter": {
      "quoteStyle": "single",
      "quoteProperties": "asNeeded",
      "trailingComma": "all",
      "semicolons": "always"
    }
  }
}
```

### Playground link

https://biomejs.dev/playground/?code=QABJAG4AagBlAGMAdABhAGIAbABlACgAKQAKAGUAeABwAG8AcgB0ACAAYwBsAGEAcwBzACAATABCAG8AbwBrACAAZQB4AHQAZQBuAGQAcwAgAEkAbgBkAGUAeABlAHIAQQBiAHMAdAByAGEAYwB0ACAAewAKACAAIABAAHMAbwBtAGUARABlAGMAbwByAGEAdABvAHIAKAB7AAoAIAAgACAAIABiAGEAdABjAGgAOgAgAHQAcgB1AGUALAAKACAAIAB9ACkACgAgACAALwAvACAAYgBpAG8AbQBlAC0AaQBnAG4AbwByAGUAIABsAGkAbgB0AC8AYwBvAG0AcABsAGUAeABpAHQAeQAvAG4AbwBFAHgAYwBlAHMAcwBpAHYAZQBDAG8AZwBuAGkAdABpAHYAZQBDAG8AbQBwAGwAZQB4AGkAdAB5ADoAIABuAGUAZQBkACAAdABvACAAcgBlAGYAYQBjAHQAbwByAAoAIAAgAGEAcwB5AG4AYwAgAGgAYQBuAGQAbABlAEwAQgBvAG8AawAoAGUAdgBlAG4AdABzADoAIAB1AG4AawBuAG8AdwBuAFsAXQApACAAewAKACAAIAAgACAAYwBvAG4AcwBvAGwAZQAuAGwAbwBnACgAZQB2AGUAbgB0AHMAKQA7AAoAIAAgAH0ACgB9AA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by witem** [comment]
It brake code, putting a comment between `async` and the function name.
![image](https://github.com/biomejs/biome/assets/1782530/f98234eb-f599-4d59-8fca-a99505062a2c)
![image](https://github.com/biomejs/biome/assets/1782530/43900f81-0596-49ba-87b0-18e182d3d4b3)

**Comment by faultyserver** [comment]
The error here is that `async` cannot have a newline after it before the name of the function it applies to, otherwise the name gets interpreted as a plain identifier and not a keyword (even in strict mode, weirdly).

The fix for this issue is to match the output that Prettier has and preserve the comment above the `async` token, rather than moving it to between the token and the name.
