### ISSUE TITLE
📝 VSCode and CLI result differs

### ISSUE THREAD

**Issue by dalisoft** [biomejs/biome#1416]
### Screen Sharing

https://github.com/biomejs/biome/assets/3511344/0c9c9a5a-5dd0-4b56-ac50-5e5f3ebab3c8

**Result: VSCode extension does not respect config on project/workspace root**

### Environment information

```bash
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.5.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
	"$schema": "https://biomejs.dev/schemas/1.4.1/schema.json",
	"formatter": {
		"enabled": true,
		"formatWithErrors": false,
		"lineWidth": 80,
		"indentStyle": "space",
		"indentWidth": 2,
		"lineEnding": "lf"
	},
	"linter": {
		"enabled": false
	},
	"javascript": {
		"formatter": {
			"enabled": true,
			"quoteStyle": "single",
			"trailingComma": "none",
			"arrowParentheses": "always",
			"bracketSpacing": true,
			"bracketSameLine": true
		}
	},
	"json": {
		"parser": {
			"allowComments": true,
			"allowTrailingCommas": false
		},
		"formatter": {
			"enabled": true
		}
	}
}
```

### Playground link

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&jsxQuoteStyle=single&trailingComma=none&bracketSameLine=true&enabledLinting=false&code=ZQB4AHAAbwByAHQAIABkAGUAZgBhAHUAbAB0ACAAewAKAAkAIgAkAHMAYwBoAGUAbQBhACIAOgAgACIAaAB0AHQAcABzADoALwAvAGIAaQBvAG0AZQBqAHMALgBkAGUAdgAvAHMAYwBoAGUAbQBhAHMALwAxAC4ANAAuADEALwBzAGMAaABlAG0AYQAuAGoAcwBvAG4AIgAsAAoACQAiAGYAbwByAG0AYQB0AHQAZQByACIAOgAgAHsACgAJAAkAIgBlAG4AYQBiAGwAZQBkACIAOgAgAHQAcgB1AGUALAAKAAkACQAiAGYAbwByAG0AYQB0AFcAaQB0AGgARQByAHIAbwByAHMAIgA6ACAAZgBhAGwAcwBlACwACgAJAAkAIgBsAGkAbgBlAFcAaQBkAHQAaAAiADoAIAA4ADAALAAKAAkACQAiAGkAbgBkAGUAbgB0AFMAdAB5AGwAZQAiADoAIAAiAHMAcABhAGMAZQAiACwACgAJAAkAIgBpAG4AZABlAG4AdABXAGkAZAB0AGgAIgA6ACAAMgAsAAoACQAJACIAbABpAG4AZQBFAG4AZABpAG4AZwAiADoAIAAiAGwAZgAiAAoACQB9ACwACgAJACIAbABpAG4AdABlAHIAIgA6ACAAewAKAAkACQAiAGUAbgBhAGIAbABlAGQAIgA6ACAAZgBhAGwAcwBlAAoACQB9ACwACgAJACIAagBhAHYAYQBzAGMAcgBpAHAAdAAiADoAIAB7AAoACQAJACIAZgBvAHIAbQBhAHQAdABlAHIAIgA6ACAAewAKAAkACQAJACIAZQBuAGEAYgBsAGUAZAAiADoAIAB0AHIAdQBlACwACgAJAAkACQAiAHEAdQBvAHQAZQBTAHQAeQBsAGUAIgA6ACAAIgBzAGkAbgBnAGwAZQAiACwACgAJAAkACQAiAHQAcgBhAGkAbABpAG4AZwBDAG8AbQBtAGEAIgA6ACAAIgBuAG8AbgBlACIALAAKAAkACQAJACIAYQByAHIAbwB3AFAAYQByAGUAbgB0AGgAZQBzAGUAcwAiADoAIAAiAGEAbAB3AGEAeQBzACIALAAKAAkACQAJACIAYgByAGEAYwBrAGUAdABTAHAAYQBjAGkAbgBnACIAOgAgAHQAcgB1AGUALAAKAAkACQAJACIAYgByAGEAYwBrAGUAdABTAGEAbQBlAEwAaQBuAGUAIgA6ACAAdAByAHUAZQAKAAkACQB9AAoACQB9ACwACgAJACIAagBzAG8AbgAiADoAIAB7AAoACQAJACIAcABhAHIAcwBlAHIAIgA6ACAAewAKAAkACQAJACIAYQBsAGwAbwB3AEMAbwBtAG0AZQBuAHQAcwAiADoAIAB0AHIAdQBlACwACgAJAAkACQAiAGEAbABsAG8AdwBUAHIAYQBpAGwAaQBuAGcAQwBvAG0AbQBhAHMAIgA6ACAAZgBhAGwAcwBlAAoACQAJAH0ALAAKAAkACQAiAGYAbwByAG0AYQB0AHQAZQByACIAOgAgAHsACgAJAAkACQAiAGUAbgBhAGIAbABlAGQAIgA6ACAAdAByAHUAZQAKAAkACQB9AAoACQB9AAoAfQAKAA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
The VSCode extension/LSP expects you to have the biome.json in the root of the project, so it can correctly resolve it.

In your situation, the LSP is applying Biome's defaults, and the CLI is probably picking up the configuration correctly.

**Comment by dalisoft** [comment]
@ematipico Thank you for response
I already have added `biome.json` in root of project/folder. CLI works correctly but VSCode extension is not

**Comment by ematipico** [comment]
Can you share the repository with us, or create a minimal repository?

**Comment by mrtsven** [comment]
I'm not entirely sure, but I see that you're using pnpm. Depending on your settings it could be that you're using symbolic links with pnpm.

according to the [documentation:](https://biomejs.dev/reference/configuration/#extends) 

> must be reachable by Biome, e.g. symbolic links might not be resolved by Biome;

**Comment by dalisoft** [comment]
Here is my config: https://github.com/dalisoft/airlight/blob/master/packages/biome-config/biome.json and repo is lives at https://github.com/dalisoft/airlight

**Comment by ematipico** [comment]
> Here is my config: [dalisoft/airlight@`master`/packages/biome-config/biome.json](https://github.com/dalisoft/airlight/blob/master/packages/biome-config/biome.json?rgh-link-date=2024-01-04T08%3A50%3A05Z) and repo is lives at [dalisoft/airlight](https://github.com/dalisoft/airlight)

@dalisoft as @mrtsven [suggested](https://github.com/biomejs/biome/issues/1416#issuecomment-1876595201), you're using pnpm, which creates symbolic links and Biome doesn't support them.

**Comment by dalisoft** [comment]
@ematipico I am using [shamefully-hoist](https://github.com/dalisoft/airlight/blob/master/.npmrc#L5) option and CLI works fine. So problem is only `pnpm`?

**Comment by ematipico** [comment]
When `pnpm` installs dependencies, it creates **symbolic links** inside the `node_modules` folder. Biome, for now, doesn't follow symbolic links when resolving files inside `extends`. We **say it** in the documentation.

My advice is to **not** go through `node_modules` folder if you are inside a monorepo, and to go through the file system, e.g. `./packages/biome-config-airlight/biome.json`

**Comment by dalisoft** [comment]
@ematipico I updated file and still same behavior

**Comment by ematipico** [comment]
@dalisoft Could you try one of our latest nightly? I tested it with the version `1.4.1` and I could replicate the issue, then I tested it with the compiled version we have in `main` and I can't see the issue anymore. Try to use `npm i @biomejs/biome@1.4.1-nightly.d869a33`

**Comment by dalisoft** [comment]
@ematipico Yes, thank you. It works now fine and as excepted

**Comment by dalisoft** [comment]
@ematipico The issue is back. Can you please try it again on your machine?

**Comment by dalisoft** [comment]
Very strange results. Sometimes it works sometimes not, sorry for pinging

**Comment by ematipico** [comment]
We have an issue where ignored files are formatted in VSCode.
 That could be the issue

**Comment by ashishsurya** [comment]
https://github.com/biomejs/biome/assets/72222785/cda5e374-8fd7-4908-baa7-d723acd0644a

Still getting this error, 

```txt
CLI:
  Version:                      1.7.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.19.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

**Comment by anatooly** [comment]
Hi. How this fix?

in last biome version 1.8.3 & vscode extension different format result `npx biome format --write`

"bracketSpacing": true,

**Comment by ematipico** [comment]
@anatooly please open a new issue or join the Discord server
