### ISSUE TITLE
📝 Formatter insists on bugging my `@ts-ignore` comment

### ISSUE THREAD

**Issue by hyoretsu** [biomejs/biome#1420]
### Environment information

```bash
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.12.1"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
	"$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
	"files": {
		"ignoreUnknown": true
	},
	"formatter": {
		"lineWidth": 110
	},
	"javascript": {
		"formatter": {
			"arrowParentheses": "asNeeded"
		},
		"parser": {
			"unsafeParameterDecoratorsEnabled": true
		}
	},
	"linter": {
		"enabled": true,
		"rules": {
			"recommended": true,
			"a11y": {
				"useKeyWithClickEvents": "off"
			},
			"style": {
				"noNonNullAssertion": "off",
				"noParameterAssign": "warn",
				"useSingleVarDeclarator": "off"
			},
			"suspicious": {
				"noExplicitAny": "off"
			}
		}
	}
}
```

### Playground link

https://biomejs.dev/playground/?code=CgAoAAoAIAAgAC8ALwAgAEAAdABzAC0AaQBnAG4AbwByAGUACgAgACAAKAAoACgAYgBvAHMAcwBlAHMAWwBiAG8AcwBzAF0AWwBjAGwAZQBhAHIAZQBkAEQAaQBmAGYAaQBjAHUAbAB0AHkAXQAuAHAAcgBpAGMAZQAgACoAIAByAGUAYgBvAG8AdABNAHUAbAB0ACkAIAAvAAoAIAAgACAAIAAgACAAYwB1AHIAcgBlAG4AdABDAGgAYQByAGEAYwB0AGUAcgAuAGIAbwBzAHMAaQBuAGcAUgBvAHUAdABpAG4AZQBbAGAAJAB7AGMAbABlAGEAcgBlAGQARABpAGYAZgBpAGMAdQBsAHQAeQB9ACAAJAB7AGIAbwBzAHMAfQBgAF0AIQAuAHQAaQBtAGUAVABhAGsAZQBuACkAIAAqAAoAIAAgACAAIAAgACAANwAyADAAMAApACAALwAKACAAIAAxADIAMAAwADAAMAAwADAAMAAwAAoAKQAuAHQAbwBGAGkAeABlAGQAKAAyACkA

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
I advise you to open an issue in the Prettier repository too, they have the same issue: https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAdKAKdACbB6PbAARgGcBaASwHMoIAnOHbDVgIwlNLlIG0OuAXV5gANnACGjACYARSgDMFlMAFdRMAJ6CAdAAd6KuNgBU2RhwgwAsupgBKfM1y419RrADCACykSw8PQ6AqSUUNQAShCqMGFwvAAGACTAYpIy8koqdpoAvtgpIbkJggCEOrEAtnAAKhIA1giOJs4uAOwATAAMXY54zACM3T0jPej2FRAAYpQAHnDSGB32IAA0IBB6sdCkyKBS9BAA7gAKUgi7KBKiRxKau+ts9P6NMADKEtUAMnHICtfcR7PMCvN56fxhajIGD0VRwdbcSqUaGw+EgOCzPRwQzVWDXGrYqBSSg8P4AtGhcLiACKqiscDJokBIAAVqRZm9ITS6fBGcyAI48uAnQ56S4gCQUKBwBYLNYgGESSiiSGeCCVSoSZAS0SieWU6jiACCMBhlDYMWF2J+0r5aO8MEqogA6t5KPBSOCwHA3hd3ZQAG7uzTasBceUBuEASSg0gQ7zAhi2Rtjby04jt6wMnDgzueem1Bh42IDDPWYW49BgIok1E1mZA4Pole1WixpETlC28oMYRgzso0hg3mQAA4uutGILKIwa3WtUh-ky0TAJGwB0OR0gOutVNw6mxLkvmXBKmwFnHpF8JOFVLW4FMGJrTZDtRIYhAQLlckA

**Comment by ematipico** [comment]
Closing as this is an upstream issue
