### ISSUE TITLE
📎 Translate Git Hooks page

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#1421]
### Description

We added a new recipe to our website, which we should translate:

https://biomejs.dev/recipes/git-hooks/

**Comment by eryue0220** [comment]
Can I have a tried to translate into Chinese?

**Comment by ematipico** [comment]
Thank you @eryue0220, that would be much appreciated! 🙏

**Comment by OldBigBuddha** [comment]
Can I try this in Japanese?

**Comment by ematipico** [comment]
Sure @OldBigBuddha , thank you

**Comment by nhedger** [comment]
Sure thing @CookieDasora, thanks !

**Comment by nhedger** [comment]
Thanks, everyone, for your help translating the page.
