### ISSUE TITLE
🐛 Found Unknown Key(s) in Config

### ISSUE THREAD

**Issue by amlcodes** [biomejs/biome#1430]
### Environment information

```block
CLI:
  Version:                      1.4.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.7.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.14.0"

Biome Configuration:
  Error:                        Found an unknown key `noInvalidUseBeforeDeclaration`.
  Error:                        Found an unknown key `noMisleadingCharacterClass`.
  Error:                        Found an unknown key `noNodejsModules`.
  Error:                        Found an unknown key `noUselessTernary`.
  Error:                        Found an unknown key `useExportType`.
  Error:                        Found an unknown key `useFilenamingConvention`.
  Error:                        Found an unknown key `useForOf`.
  Error:                        Found an unknown key `useNodejsImportProtocol`.
  Status:                       Loaded with errors
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

Am I doing something wrong? the schema does not include these keys and it's in nursery so it makes sense, but just making sure.

<img width="557" alt="image" src="https://github.com/biomejs/biome/assets/15385357/40e9d5b6-2b2d-4fd2-a4ff-10d57a4751a9">

### Expected result

keys to be recognized or marked deprecated

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Those errors that you see are coming **from Biome**. Notice you have those errors inside the rage command too.

For example, `noNodejsModules` is a rule that **hasn't been** released yet.

**Comment by amlcodes** [comment]
@ematipico thanks for the reply! Totally understand they are coming from biome and see them inside the rage command. I expected the Nursery commands to be actively worked on, but would be noted as unreleased or deprecated if not being active in the latest release. Must be reading the docs wrong, appreciate the help!

**Comment by nhedger** [comment]
@amlcodes The docs now make it clearer if a rule has not yet been released.

See https://github.com/biomejs/biome/pull/1431
