### ISSUE TITLE
🐛 vscode extension fills hard drive with biome server logs

### ISSUE THREAD

**Issue by timfish** [biomejs/biome#1450]
### Environment information

```block
macOS Sonoma - Apple M1
```

### What happened?

macOS warned me that my hard drive was full which was a surprise!

I found a directory at:
`/private/var/folders/_g/h7yb6x5n6dl0qrhxvkffsm8h0000gn/biome-logs/`
It had 15 x 15GB server logs files totalling ~270GB

### Expected result

Does not fill hard drive

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Wow that's concerning. Let's see what we can do

**Comment by ematipico** [comment]
How many files are there inside the folder?

**Comment by timfish** [comment]
The first files 8-10 files I could see were 15GB each and named something like `server-logs-something` but the directory totalled ~270GB so I guess there were 15 ish files in there. Unfortunately I deleted the entire directory so I can't be sure now.
