### ISSUE TITLE
🐛 .gitignore files are part of biome output as protected files?

### ISSUE THREAD

**Issue by carlsverre** [biomejs/biome#1477]
### Environment information

```block
CLI:
  Version:                      1.5.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.14.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

1. run `biome check .`
2. see output:
```
./.gitignore project ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ℹ The file ./.gitignore is protected because is handled by another tool. Biome won't process it.
```

### Expected result

AFAIK biome doesn't support formatting/linting .gitignore files? So the only way to silence this alarm is to tell biome to silence all protected files... which I don't want to do since it might silence something I want to see.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by carlsverre** [comment]
I have reproed this issue here: https://github.com/carlsverre/biome-issues

**Comment by carlsverre** [comment]
Ok this seems to be "expected behavior" per the docs: https://biomejs.dev/guides/how-biome-works/#protected-files

You can silence this warning using `--diagnostic-level=warn` when running the biome cli.

I'm not sure what the value of emitting these messages by default is. Especially for files like `.gitignore` which wouldn't be touched by biome anyways.

**Comment by Conaclos** [comment]
I think we could emit these diagnostic under `--verbose` and hide them in non-verbose mode.

**Comment by ari-becker** [comment]
Additionally, I tried to "fix" this on my setup by adding `**/.gitignore` to my `files.ignore` in `biome.json`. I would expect that to silence these messages, but it didn't.

**Comment by ematipico** [comment]
This should be fixed
