### ISSUE TITLE
Do not raise an error if the language of the file extension cannot be determined

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#1482]
### Discussed in https://github.com/biomejs/biome/discussions/1479

<div type='discussions-op-text'>

<sup>Originally posted by **smorimoto** January  8, 2024</sup>
As the title says, it currently raises an error if the language of the file extension cannot be determined, but it should be either warning or info.</div>

**Comment by ematipico** [comment]
I would like to have a reproduction. Would it be possible?

**Comment by Conaclos** [comment]
This should be fixed by the latest release (1.5.2).
