### ISSUE TITLE
🐛 Include doesn't work for formatter

### ISSUE THREAD

**Issue by anthonyhayesres** [biomejs/biome#1495]
### Environment information

I just want a way to run biome formatter on the files in the include array of `biome.json`

Reproduction here: https://github.com/anthonyhayesres/biome-format-bug

### What happened?

One possible fix is to use `biome format ./**/*` but that gives `spawn E2BIG` on a large codebase, making it unusable for my use case. Perhaps we could exclude the path and biome would read only from the include array?

The use case is I want to slowly migrate a monorepo to use biome, so have the biome.json in the root of the project, but only format certain directories, having everything configured in the biome.json file (so, for example, biome IDE plugins would also work out-of-the-box)

### Expected result

It should format the files in "includes", and only those files, in a way that gets around the spawn E2BIG issue

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
This should be fixed in the last patch release (v1.5.1). Could anyone confirm that they no longer get errors?

**Comment by anthonyhayesres** [comment]
:tada: thank you! I'll test it out today and let you know!

**Comment by Conaclos** [comment]
This is now fixed by the lastest reelases (1.5.2). Thanks for your help!
