### ISSUE TITLE
🐛 Deleted files are not ignored when VCS integration is enabled

### ISSUE THREAD

**Issue by RShirohara** [biomejs/biome#1508]
### Environment information

```block
CLI:
  Version:                      1.5.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.5.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.14.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

If a file is deleted at commit time, `biome check` and `biome ci` using the `--changed` option will recognize the deleted file as a check target, resulting in a read error for a file that does not actually exist.

### Step to reproduce

1. Delete the file and commit on a branch different from the `vcs.defaultBranch` setting.
2. Run `biome check --changed .`  
   Output:

   ```
   eslint.config.js internalError/io  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

     ✖ No such file or directory (os error 2)
     
     ⚠ This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
   ```

### Additional info

This problem was discovered during the creation of a CI process using Biome.
(RShirohara/unified-webnovel#227)

### Expected result

If the `--changed` option is used, deleted files are expected to simply be ignored.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
@simonxabris are you interested in this issue?
