### ISSUE TITLE
📚 Outdated `$schema` url in docs

### ISSUE THREAD

**Issue by malobre** [biomejs/biome#1534]
### Documentation URL

https://biomejs.dev/reference/configuration/#schema

### Description

`$schema` url is not up to date.

[Multiple pages](https://github.com/search?q=repo%3Abiomejs%2Fbiome+https%3A%2F%2Fbiomejs.dev%2Fschemas%2F1+path%3A%2F%5Ewebsite%5C%2Fsrc%5C%2Fcontent%5C%2Fdocs%5C%2F%2F&type=code) are affected.

### Expectations

```json
{
  "$schema": "https://biomejs.dev/schemas/1.5.1/schema.json"
}
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by nhedger** [comment]
Thanks for bringing it to attention. Would you like to contribute a fix?

**Comment by malobre** [comment]
@nhedger I'll make a quick PR to update the urls to `1.5.1` but this should probably be automatically checked / updated upon new release.

**Comment by nhedger** [comment]
Thanks @malobre, I agree.

**Comment by malobre** [comment]
Should we leave this issue open until the urls are automatically updated ?

**Comment by nhedger** [comment]
Let's open a new one specifically for this task.

If you'd like to take care of it, go ahead. Otherwise, I'll do that sometime later today.
