### ISSUE TITLE
📝 Comment's above the `from 'blah'` in a multi-line-export do not have whitespace preserved, moved to same line as `from`

### ISSUE THREAD

**Issue by SpanishPear** [biomejs/biome#1589]
### Environment information

```bash
N/A - Playground
```

### Playground link

https://biomejs.dev/playground/?code=ZQB4AHAAbwByAHQAIAB7AAoAIAAgACAAIABUAEUAUwBUACwACgAgACAAIAAgAFMATwBNAEUALAAKACAAIAAgACAARQBYAFAATwBSAFQAUwAsAAoAIAAgACAAIAAvAC8AIABlAHMAbABpAG4AdAAtAGQAaQBzAGEAYgBsAGUALQBuAGUAeAB0AC0AbABpAG4AZQAgAHMAbwBtAGUALwBjAHUAcwB0AG8AbQAvAHIAdQBsAGUACgB9ACAAZgByAG8AbQAgACcAcwBvAG0AZQAtAHAAYQBjAGsAYQBnAGUAJwA7AA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by SpanishPear** [comment]
```diff
export {
      SOME,
      EXPORTS,
- ····//·eslint-disable-next-line·some/custom/rule
- }·from·'some-package';
+ }·from·//·eslint-disable-next-line·some/custom/rule
+ 'some-package';
```
Sorry if the title is misleading, hope the playground/diff makes it clear :)

**Comment by SpanishPear** [comment]
How easy would something like this be? With some guidance I could take a look :D

**Comment by ematipico** [comment]
@SpanishPear 

You might want to start looking at how/where we place the comments: https://github.com/biomejs/biome/blob/main/crates%2Fbiome_js_formatter%2Fsrc%2Fcomments.rs#L121

**Comment by SpanishPear** [comment]
Thanks for your guidance @ematipico !!
