### ISSUE TITLE
Misconfigured config leads to using all the default settings

### ISSUE THREAD

**Issue by nstepien** [biomejs/biome#1623]
In Biome 1.5.1, `useConsistentArrayType` was moved back to the `nursery` group, which made the Biome cli complain about it, and is how I discovered this issue.
While the cli doesn't do anything beside throwing an error, it seems like the vscode extension instead reverts to use all the defaults for the formatter.
So formatting on save will change all space indentation to tabs for example.

Ideally a misconfiguration in the linter should not affect the formatter's configuration. Or the linter's config itself for that matter.

**Comment by nstepien** [comment]
Checked again today, if I make a typo in the config, and reload VSCode, Biome will not be available as a formatter:
![image](https://github.com/biomejs/biome/assets/567105/33ef0fa3-05c1-4733-aac6-04aa4f2f306d)
![image](https://github.com/biomejs/biome/assets/567105/ecfbb99a-173e-448b-8698-4d1e123a6302)

It's a step in the right direction, now Biome won't format files incorrectly, but I still wish it'd be able to format if the config error is not related to the formatting settings.

**Comment by ematipico** [comment]
Closing. The CLI now errors. In v1.8 the LSP will not do anything.
