### ISSUE TITLE
💅 wrong edge case detection in useExhaustiveDependencies since 1.5.2

### ISSUE THREAD

**Issue by ViliamKopecky** [biomejs/biome#1636]
### Environment information

```bash
1.5.2
```

### Rule name

useExhaustiveDependencies

### Playground link

https://biomejs.dev/playground/?lintRules=all&code=aQBtAHAAbwByAHQAIAB7ACAAdQBzAGUAQwBhAGwAbABiAGEAYwBrACwAIAB1AHMAZQBTAHQAYQB0AGUAIAB9ACAAZgByAG8AbQAgACIAcgBlAGEAYwB0ACIACgAKAGUAeABwAG8AcgB0ACAAZgB1AG4AYwB0AGkAbwBuACAAdQBzAGUASABvAG8AawAoACkAIAB7AAoAIAAgACAAIABjAG8AbgBzAHQAIABbAHMAZQBjAHQAaQBvAG4AcwBdACAAPQAgAHUAcwBlAFMAdABhAHQAZQAoACIAIgApAAoAIAAgAAoAIAAgAAkAdQBzAGUAQwBhAGwAbABiAGEAYwBrACgACgAJAAkAKABzAGUAYwB0AGkAbwBuAEsAZQB5ADoAIABzAHQAcgBpAG4AZwAsACAAaQB0AGUAbQA6ACAAcwB0AHIAaQBuAGcAKQAgAD0APgAgAHsACgAJAAkACQByAGUAdAB1AHIAbgAgAHMAZQBjAHQAaQBvAG4AcwBbAHMAZQBjAHQAaQBvAG4ASwBlAHkAXQA%2FAC4AaQBuAGMAbAB1AGQAZQBzACgAaQB0AGUAbQApACAAPwA%2FACAAZgBhAGwAcwBlAAoACQAJAH0ALAAKAAkACQBbAHMAZQBjAHQAaQBvAG4AcwBdACwACgAJACkACgB9AA%3D%3D

### Expected result

```tsx
import { useCallback, useState } from "react"

export function useHook() {
    const [sections] = useState("")
  
  	useCallback(
		(sectionKey: string, item: string) => {
			return sections[sectionKey]?.includes(item) ?? false
		},
		[sections],
	)
}
```

This ends up these errors:

- This hook does not specify all of its dependencies: sections[sectionKey]?.includes
- This hook specifies more dependencies than necessary: sections

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by XiNiHa** [comment]
I guess I broke dynamically computed property handling in #1327, will fix soon (since it looks pretty straightforward)
