### ISSUE TITLE
💅 Enum Initializer putting initialization inside inline comment

### ISSUE THREAD

**Issue by Reed-Anderson** [biomejs/biome#1640]
### Environment information

```bash
CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.1.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Rule name

lint/style/useEnumInitializers

### Playground link

https://biomejs.dev/playground/?code=ZQBuAHUAbQAgAFMAZQB2AGUAcgBpAHQAeQAgAHsACgAgACAAIAAgAEkAbgBmAG8AIAA9ACAAMQAsACAALwAvACAATgBvAHQAIABhACAAcAByAG8AYgBsAGUAbQAsACAAcwBvAG0AZQB0AGkAbQBlAHMAIABhACAAbQBpAHMAdABhAGsAZQAKACAAIAAgACAAQQBkAHYAaQBzAG8AcgB5ACwAIAAvAC8AIABOAG8AdAAgAGEAIABwAHIAbwBiAGwAZQBtACwAIABvAGYAdABlAG4AIABhACAAbQBpAHMAdABhAGsAZQAKACAAIAAgACAAQwBhAHUAdABpAG8AbgAsACAALwAvACAATQBpAG4AbwByACAAZQByAHIAbwByACwAIABuAG8AbgAtAHAAcgBlAHYAZQBuAHQAaQBuAGcACgAgACAAIAAgAFcAYQByAG4AaQBuAGcALAAgAC8ALwAgAFMAZQByAGkAbwB1AHMAIABlAHIAcgBvAHIALAAgAHAAcgBlAHYAZQBuAHQAcwAgAHAAcgBvAGQAdQBjAHQAaQBvAG4ACgAgACAAIAAgAEUAcgByAG8AcgAgAC8ALwAgAEMAcgBpAHQAaQBjAGEAbAAgAGUAcgByAG8AcgAsACAAcAByAGUAdgBlAG4AdABzACAAZABlAHYAIABhAG4AZAAgAHAAcgBvAGQAdQBjAHQAaQBvAG4ACgB9AA%3D%3D

### Expected result

```
enum Severity {
	Info = 1, // Not a problem, sometimes a mistake
	Advisory = 2, // Not a problem, often a mistake
	Caution = 3, // Minor error, non-preventing
	Warning = 4, // Serious error, prevents production
	Error = 5 // Critical error, prevents dev and production
}
```

**Actual Result**
```
enum Severity {
	Info = 1, // Not a problem, sometimes a mistake
	Advisory = 2, // Not a problem, often a mistake
	Caution = 3, // Minor error, non-preventing
	Warning = 4, // Serious error, prevents production
	Error // Critical error, prevents dev and production = 5
}
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by kalleep** [comment]
Seems like this only happens when the last element is missing a comma. I can look into this one :)

**Comment by kalleep** [comment]
Forgot to link to the issue in the pr but this one can be closed because https://github.com/biomejs/biome/pull/1650 was merged
