### ISSUE TITLE
💅 lint/suspicious/noFallthroughSwitchClause doesn't respect never

### ISSUE THREAD

**Issue by nxht** [biomejs/biome#1644]
### Environment information

```bash
CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.14.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Rule name

lint/suspicious/noFallthroughSwitchClause

### Playground link

https://biomejs.dev/playground/?code=ZgB1AG4AYwB0AGkAbwBuACAAdABoAHIAbwB3AFQAZQBzAHQAKAApADoAIABuAGUAdgBlAHIAIAB7AAoAIAAgAHQAaAByAG8AdwAgAG4AZQB3ACAARQByAHIAbwByACgAJwB0AGgAcgBvAHcAIABpAG4AIABmAHUAbgBjAHQAaQBvAG4AJwApADsACgB9AAoACgBjAG8AbgBzAHQAIABhADoAIABuAHUAbQBiAGUAcgAgAD0AIAAxADsACgAKAHMAdwBpAHQAYwBoACAAKABhACkAIAB7AAoAIAAgAGMAYQBzAGUAIAAwADoAIAB7AAoAIAAgACAAIAB0AGgAcgBvAHcAIABuAGUAdwAgAEUAcgByAG8AcgAoACcAcwBpAG0AcABsAGUAIAB0AGgAcgBvAHcAJwApADsACgAgACAAfQAKACAAIABjAGEAcwBlACAAMQA6ACAAewAKACAAIAAgACAAdABoAHIAbwB3AFQAZQBzAHQAKAApADsACgAgACAAfQAKACAAIABjAGEAcwBlACAAMgA6ACAAewAKACAAIAAgACAAYwBvAG4AcwBvAGwAZQAuAGwAbwBnACgAJwBoAGkAJwApADsACgAgACAAfQAKAH0ACgA%3D

### Expected result

I think it should respect `never` thus not throwing error, or at least there should be option to allow the case. 
And when `break;` is added, Typescript complaints `Unreachable code detected.ts(7027)`.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Biome doesn't have type inference capabilities, so this case is impossible to detect.
