### ISSUE TITLE
📎 Create a CodeSandBox for Biome

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#165]
### Description

CBS (https://codesandbox.io) is an excellent tool for prototyping and sharing projects/MVPs with other people.

We could create a CBS with biome installed and some basic commands prepared. Users who can't share a reproduction, could fork the sand box and share it with us.

The reason why I chose CBS, is because biome doesn't work with stackblitz.

**Comment by akash1412** [comment]
Hi, I'm interested in working on this issue. could you please assign it to me?

**Comment by ematipico** [comment]
Done! Let us know if you have any questions.

Ideally, we want to have the link to CBS somewhere in our contribution guide - with some instructions if needed, and in our issue template.

**Comment by ematipico** [comment]
@akash1412 do you have any news? If you're swamped, we can give the task to someone else

**Comment by akash1412** [comment]
Submitted the pull request at https://github.com/biomejs/biome/pull/285.
