### ISSUE TITLE
💅 lint/style/noVar triggered in a declare statement

### ISSUE THREAD

**Issue by amoreaulemay** [biomejs/biome#1651]
### Environment information

```bash
CLI:
  Version:                      1.3.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.11.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### Rule name

lint/style/noVar

### Playground link

https://biomejs.dev/playground/?code=aQBuAHQAZQByAGYAYQBjAGUAIABDAHUAcwB0AG8AbQBXAGkAbgBkAG8AdwAgAGUAeAB0AGUAbgBkAHMAIABXAGkAbgBkAG8AdwAgAHsACgAgACAAIAAgAFQAeAB0ADoAIAB7AAoAIAAgACAAIAAgACAAIAAgAGwAYQB1AG4AYwBoAEMAbwBtAHAAbwBuAGUAbgB0AD8AOgAgACgAZQB4AHAAZQByAGkAZQBuAGMAZQBJAGQAOgAgAHMAdAByAGkAbgBnACwAIABvAHAAdABpAG8AbgBzAD8AOgAgAHsAIABmAG8AcgBjAGUAPwA6ACAAYgBvAG8AbABlAGEAbgAgAH0AKQAgAD0APgAgAHYAbwBpAGQACgAgACAAIAAgAH0ACgB9AAoACgBkAGUAYwBsAGEAcgBlACAAZwBsAG8AYgBhAGwAIAB7AAoAIAAgACAAIABpAG4AdABlAHIAZgBhAGMAZQAgAFcAaQBuAGQAbwB3ACAAewAKACAAIAAgACAAIAAgACAAIABUAHgAdAA6ACAAQwB1AHMAdABvAG0AVwBpAG4AZABvAHcAWwAnAFQAeAB0ACcAXQA7AAoAIAAgACAAIAB9AAoAIAAgACAAIAB2AGEAcgAgAFQAeAB0ADoAIABDAHUAcwB0AG8AbQBXAGkAbgBkAG8AdwBbACcAVAB4AHQAJwBdADsACgB9AA%3D%3D

### Expected result

In a `declare global` it can be expected to use `var` to declare globally available objects.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
You could replace `var` with `let`?

**Comment by amoreaulemay** [comment]
@Conaclos Not for global declaration.

In TypeScript, when you're augmenting the global scope with new variables using a `declare global` block, you need to use `var` instead of `let` or `const`. This is primarily because of the way TypeScript handles different scopes and declarations:

1. **Global Declaration**: When you declare a variable globally, it should be accessible from any other scope. The `var` keyword in TypeScript (and JavaScript) is function-scoped or globally-scoped if not inside a function. This means a `var` declaration inside a `declare global` block effectively extends to the global scope.

2. **Hoisting and Re-declarations**: `var` allows for hoisting and can be re-declared. This is more in line with how global variables behave in a broader environment, where different scripts might declare the same variable without knowing about each other.

3. **Legacy and Compatibility**: The behavior of `var` is more aligned with traditional JavaScript, where global variables were always declared with `var`. TypeScript maintains this pattern for consistency and compatibility.

In contrast, `let` and `const` are block-scoped (limited to the block where they are defined), and `const` also prevents reassignment. These characteristics make them unsuitable for declarations meant to have a global scope in the TypeScript ecosystem. Using `let` or `const` in a `declare global` block would conflict with their inherent design of being confined to a specific block or scope.

**Comment by Conaclos** [comment]
Thanks for this detailed explanation.

**Comment by ash0080** [comment]
https://biomejs.dev/playground/?lineWidth=120&indentStyle=space&quoteStyle=single&semicolons=as-needed&attributePosition=multiline&bracketSameLine=true&lintRules=all&files.data.tsx=ZQB4AHAAbwByAHQAIABkAGUAZgBhAHUAbAB0ACAAewAKACAAIABmAGwAbwB3AFAAcgBvAHAAcwA6ACAAJwBhACcACgB9ACAAcwBhAHQAaQBzAGYAaQBlAHMAIABGAGwAbwB3AEMAbwBuAGYAaQBnAA%3D%3D&files.main.tsx=ZABlAGMAbABhAHIAZQAgAGcAbABvAGIAYQBsACAAewAKACAAIAAgACAAaQBuAHQAZQByAGYAYQBjAGUAIABGAGwAbwB3AEMAbwBuAGYAaQBnACAAewAKACAAIAAgACAAIAAgACAAIABmAGwAbwB3AFAAcgBvAHAAcwA6ACAAcwB0AHIAaQBuAGcACgAgACAAIAAgAH0ACgB9AA%3D%3D

Regarding similar situations, should the same requirement of "no undeclared variables" also be satisfied?
