### ISSUE TITLE
🐛 `files.ignore` working via CLI but not via VSCode Formatter

### ISSUE THREAD

**Issue by 7SindDev** [biomejs/biome#1654]
### Environment information

```block
CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v18.18.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/4.0.2"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:
```

### What happened?

The reproduction of the problem is included in [this repository](https://github.com/7SindDev/biome_ignore_files_vscode_bug_reproduction). The details are included in the README of this repository!

### Expected result

VSCode with `Format On Save` & all `.tsx` files ignored: not format (more details in [this repository](https://github.com/7SindDev/biome_ignore_files_vscode_bug_reproduction))

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by JP250552** [comment]
I am seeing the same behavior with `formatter.ignore` as well

**Comment by nhedger** [comment]
I was able to reproduce this issue on `1.5.2` and `1.5.3`, but I wasn't able to reproduce on `1.5.1`. A regression may have been introduced in `1.5.2`.

**Comment by ematipico** [comment]
cc @Conaclos

**Comment by Conaclos** [comment]
I think the issue is coming from [this change](https://github.com/biomejs/biome/pull/1531/files#diff-44597116d9e04058d25bbf598592581aba739f46eb7c703bec79c8d8e4147d3dL159-L173). I will send a fix.
