### ISSUE TITLE
📎 Improve message of diagnostic

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#1698]
### Description

The following diagnostic isn't very useful when prompted to the user:

https://github.com/biomejs/biome/blob/13ec78dc3bc4bded1bca8072f9a55a6756f32cf8/crates/biome_service/src/diagnostics.rs#L391-L393

We throw this diagnostic when a user tries to format code that has parsing diagnostics. 

It would be great to add something more, for example, "If you wish to format invalid code, enable `formatter.formatWithError`"

**Comment by shoaibkh4n** [comment]
Hi @ematipico,
I've submitted a pull request addressing the clarity issue discussed here. You can find it at [#1732](https://github.com/biomejs/biome/pull/1732#issue-2114239321). I've rephrased the message to enhance its clarity for users.

**Comment by ematipico** [comment]
Closed by #1732
