### ISSUE TITLE
📝 The flag log-kind doesn't change the output format in 1.5.3

### ISSUE THREAD

**Issue by jschaf** [biomejs/biome#1701]
### Environment information

```bash
CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.5.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
  "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
  "files": {
    "ignore": ["*.pb.ts", "erp/app/dist", ".gitignore", "baseline.sarif.json"],
    "ignoreUnknown": true
  },
  "vcs": {
    "clientKind": "git",
    "enabled": true,
    "useIgnoreFile": true,
    "defaultBranch": "main"
  },
  "formatter": {
    "ignore": ["*.pb.ts", "pos/domain/*.json", "erp/app/dist", "google/**"],
    "indentWidth": 2,
    "indentStyle": "space"
  },
  "javascript": {
    "formatter": {
      "quoteStyle": "single",
      "lineWidth": 100,
      "bracketSameLine": true
    }
  },
  "linter": {
    "enabled": true,
    "ignore": ["*.pb.ts"],
    "rules": {
      "complexity": {
        "noStaticOnlyClass": "off",
        "noForEach": "off"
      },
      "correctness": {
        "noUnusedVariables": "error"
      },
      "style": {
        "noUnusedTemplateLiteral": "off",
        "noParameterAssign": "off"
      },
      "suspicious": {
        "noConfusingVoidType": "off"
      }
    }
  },
  "organizeImports": {
    "enabled": false
  }
}
```

### Playground link

https://biomejs.dev/playground/?lineWidth=120&code=YwBvAG4AcwB0ACAAZgBvAG8AIAA9ACAAIgAxADIAMwA0ACIAIAA7AA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

### Repro

These invocations all show the same output `pretty`:

```sh
npx biome format --log-kind=compact .
npx biome format --log-kind=pretty .
npx biome format --log-kind=json .
```

**Comment by ematipico** [comment]
That's not a formatting issue, that option is available to all commands.

Could you at least share some screenshots, please? Or video. We don't need a playground

**Comment by jschaf** [comment]
> That's not a formatting issue, that option is available to all commands.

I wasn't sure how to categorize global options.

> Could you at least share some screenshots, please? Or video. We don't need a playground

Sure:

<img width="880" alt="Screenshot 2024-01-30 at 12 49 17 PM" src="https://github.com/biomejs/biome/assets/22385/3d9c4af1-09b1-49ee-af4a-878230f385b1">

**Comment by ematipico** [comment]
You have to enable logging. 

What you see on screen are **diagnostics**. Logs are different. Use `--log-kind=info`

**Comment by Hookyns** [comment]
So, are there any options to change the diagnostics format?

When used in git hooks, IDEs show output usually in small pop-up windows. I'd like to see something like: "There are 20 errors in 6 files." or list of files with errors; something compact.

**Comment by ematipico** [comment]
> So, are there any options to change the diagnostics format?
> 

No, not yet. I've done some preliminary work though

> When used in git hooks, IDEs show output usually in small pop-up windows. I'd like to see something like: "There are 20 errors in 6 files." or list of files with errors; something compact.
> 
> 

I'm not sure what you are referring to. But if you have some idea, I suggest creating a GitHub discussion

**Comment by ematipico** [comment]
I'm going to close the issue. OP hasn't replied in a while, and it seems he misunderstood the issue
