### ISSUE TITLE
📚 Insight needed: Why is `forEach` allowed if you expose the index?

### ISSUE THREAD

**Issue by eirikove** [biomejs/biome#1702]
### Documentation URL

https://biomejs.dev/linter/rules/no-for-each/

### Description

I want to understand the reasoning behind why `forEach` is allowed when you expose the index. I get why it can be disallowed when you don't.

![image](https://github.com/biomejs/biome/assets/21888865/e0d613bf-168c-494e-be22-4f0439c44b11)

![image](https://github.com/biomejs/biome/assets/21888865/84e13102-3dd2-4be9-b2dd-0f737602ebe6)

I do find `arr.forEach((element, index) => {` to be more intuitive to use and easier to write than
`for(const [index, element] of arr.entries()) {`, so I guess that could be _a reason_, but that still doesn't cover all the bullet points in the documentation (chaining with `filter` or `map`, complex callback function), although it does expose the iteration process more.

Is that it, or is there something more convoluted going on behind the curtains?

### Expectations

Expected it to be disallowed at all times when I specify `noForEach: "error"`

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
This is a result of a [previous discussion](https://github.com/biomejs/biome/issues/547#issuecomment-1806023034)

**Comment by eirikove** [comment]
@Conaclos Ah, thanks for pointing me there! 👍🏻 That makes good sense (and javascript, as usual, doesn't) 

Thanks! 

Should perhaps the documentation add a note explaining why multiple arguments in `forEach` is valid, or do you consider that more of a "go read the javascript documentation and you'll get it eventually" kind of thing? 😄

**Comment by ematipico** [comment]
@eirikove, feel free to provide more explanation about it with a PR. If you have this doubt, I am sure there are other people that wonder the same.

**Comment by chansuke** [comment]
I'd like to add some explanation about that if possible
