### ISSUE TITLE
💅 noParameterReassign not working

### ISSUE THREAD

**Issue by HermanBergsholm** [biomejs/biome#1703]
### Environment information

```bash
CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.3"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Rule name

noParameterReassign

### Playground link

https://biomejs.dev/playground/?lineWidth=120&indentStyle=space&trailingComma=es5&semicolons=as-needed&code=CgAvAC8AIABBAHMAIAB5AG8AdQAgAGMAYQBuACAAcwBlAGUAIABiAGUAbABvAHcALAAgAGkAdAAgAGYAYQBpAGwAZQBzACAAdABvACAAcABhAHIAcwBlACAAdABoAGUAIABiAGkAbwBtAGUALQBpAGcAbgBvAHIAZQAgAGYAbwByACAAbgBvAFAAYQByAGEAbQBlAHQAZQByAFIAZQBhAHMAcwBpAGcAbgAKAAoAZgB1AG4AYwB0AGkAbwBuACAAcgBlAHAAcgBvAGQAdQBjAGUAKABtAGEAbgBhAGcAZQBtAGUAbgB0ACkAewAKACAAIAAvAC8AIABiAGkAbwBtAGUALQBpAGcAbgBvAHIAZQAgAGwAaQBuAHQALwBzAHQAeQBsAGUALwBuAG8AUABhAHIAYQBtAGUAdABlAHIAUgBlAGEAcwBzAGkAZwBuADoAIAA8AGYAYQBpAGwAZQBzACAAdABvACAAcABhAHIAcwBlAD8APwA%2BAAoAIAAgAGkAZgAgACgAIQBtAGEAbgBhAGcAZQBtAGUAbgB0ACkAIAB7AAoAIAAgACAAIAAgACAAbQBhAG4AYQBnAGUAbQBlAG4AdAAgAD0AIAAiAG0AYQBuAGEAZwBlAGQAIgAKACAAIAAgACAAfQAKAH0ACgAKAAoALwAvACAAQQBsAHMAbwAsACAAaQBmACAAZABpAHMAYQBiAGwAaQBuAGcAIABuAG8AUABhAHIAYQBtAGUAdABlAHIAUgBlAGEAcwBzAGkAZwBuACAAbwBuACAAYgBpAG8AbQBlAC4AagBzACwAIABhAGwAbAAgAGwAaQBuAHQAaQBuAGcAIABhAG4AZAAgAGYAbwByAG0AYQB0AHQAaQBuAGcAIABzAGUAaQB6AGUAIAB0AG8AIAB3AG8AcgBrADoAIAAKAC8ALwAgACIAbABpAG4AdABlAHIAIgA6ACAAewAKAC8ALwAgACAAIAAgACAAIAAgACAAIAAiAGUAbgBhAGIAbABlAGQAIgA6ACAAdAByAHUAZQAsAAoALwAvACAAIAAgACAAIAAgACAAIAAgACIAcgB1AGwAZQBzACIAOgAgAHsACgAvAC8AIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAiAHMAdAB5AGwAZQAiADoAIAB7ACIAbgBvAFAAYQByAGEAbQBlAHQAZQByAFIAZQBhAHMAcwBpAGcAbgAiADoAIAAiAG8AZgBmACIAfQAKAC8ALwAgACAAIAAgACAAIAAgACAAIAB9ACAACgAvAC8AIAAgACAAIAAgAH0ALAA%3D

### Expected result

I expect the two followings things to happen: 

1. When using biome-ignore for the specified rule, it should be ignored. 
2. When I set biome.js to ignore the rule, I expect the formatting and linting to not stop working across the entire project, and also that the rule is ignored across the project. 

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
It's called [noParameterAssign](https://biomejs.dev/linter/rules/no-parameter-assign) :)

**Comment by HermanBergsholm** [comment]
Oh, my bad! Thanks, closing issue. (not sure how I missed that lol)
