### ISSUE TITLE
💅 Bug when linting on save, when Biome is changing RegEx to literal

### ISSUE THREAD

**Issue by HermanBergsholm** [biomejs/biome#1704]
### Environment information

```bash
CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.3"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Rule name

useRegexLiterals

### Playground link

https://biomejs.dev/playground/?lineWidth=120&indentStyle=space&trailingComma=es5&semicolons=as-needed&code=IAAgAGMAbwBuAHMAdAAgAHIAZQBnAGUAeAAgAD0AIABuAGUAdwAgAFIAZQBnAEUAeABwACgAIgA6AC8ALwBbAF4AOgAvAF0AKgAiACkACgAKAC8ALwAgAF4AIABiAGUAYwBvAG0AZQBzACAACgAKAGMAbwBuAHMAdAAgAHIAZQBnAGUAeAAgAD0AIAAvADoALwAvAFsAXgA6AC8AXQAqAC8ACgAKAC8ALwAgAF4AIAB1AHAAbwBuACAAcwBhAHYAaQBuAGcALAAgAHcAaABpAGMAaAAgAHcAaQBsAGwAIABjAGEAdQBzAGUAIABhAHAAcABsAGkAYwBhAHQAaQBvAG4AIAB0AG8AIABjAHIAYQBzAGgALgAgAAoACgAvAC8AIABUAGUAbQBwAG8AcgBhAHIAaQBsAHkAIABzAG8AbAB2AGUAZAAgAHUAcwBpAG4AZwA6ACAACgAKAC8ALwAgAGIAaQBvAG0AZQAtAGkAZwBuAG8AcgBlACAAbABpAG4AdAAvAGMAbwBtAHAAbABlAHgAaQB0AHkALwB1AHMAZQBSAGUAZwBlAHgATABpAHQAZQByAGEAbABzADoAIABiAGkAbwBtAGUAIABiAHUAZwBzACAAbwB1AHQAIABvAG4AIAByAGUAZwBlAHgAIABsAGkAdABlAHIAYQBsAHMA

### Expected result

As the string does not contain any concatenation, I find it weird that Biome tries to lint it differently when saving. 

As can be seen in the playground link, this: 
`const regex = new RegExp("://[^:/]*")`
turns into this: 
` const regex = /://[^:/]*/`
when saving/running linter. This is a syntax error and will crash the node application. 

Expected outcome is, I guess, that Biome does not do anything with this variable's value, as there is no string concatenation present. 

Using `// biome-ignore lint/complexity/useRegexLiterals` temporarily to avoid this, but that should not be necessary. 

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by togami2864** [comment]
I'll take a look :)
