### ISSUE TITLE
📎 Implement format option `singleAttributePerLine`

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#1706]
### Description

From the discussion https://github.com/biomejs/biome/discussions/698

It would be great if someone wanted to implement this option.

Here's the prettier reference: https://prettier.io/docs/en/options#single-attribute-per-line

I'm happy to reply to any questions you might have.

**Comment by octoshikari** [comment]
Hi @ematipico ! I've start working on this issue and have 1 question about running specific jsx tests with newly added configuration option `singleAttributePerLine`. For now add this in crates/biome_js_formatter/tests/prettier_tests.rs  for options variable, but it apply for all tests and i have a lot of snapshot changes. Can you help with how i should do it correctly for testing purpose

**Comment by ematipico** [comment]
That's expected because we track the value of the options in the snapshot tests. Just make sure that the snapshots show the new option. Then, commit all these new snapshot changes, and start creating new test cases.

**Comment by octoshikari** [comment]
I mean , how i can apply new options for specific tests cases not for all existed. It my first contribution to biome and i not a familiar with all processes

**Comment by ematipico** [comment]
Hi @octoshikari , sorry for the lack of context, I didn't have much time yesterday.

Creating new tests with new options in the formatter is a bit hectic and outdated, and I hope to renovate it soon, maybe with some help. 

So, usually, you can find an `options.json` file, like this one:

https://github.com/biomejs/biome/blob/7f821521d7b4c81b5bda9b9a8d54e35434ec1d07/crates/biome_js_formatter/tests/specs/ts/enum/options.json#L1-L10

Since we are **adding a new option**, we have to tell the testing infrastructure to understand and read the new option. You'll have to add a new option here: 

https://github.com/biomejs/biome/blob/7f821521d7b4c81b5bda9b9a8d54e35434ec1d07/crates/biome_js_formatter/tests/language.rs#L198-L233

And then you have to apply this option here, by adding a new function called `with_*`

https://github.com/biomejs/biome/blob/7f821521d7b4c81b5bda9b9a8d54e35434ec1d07/crates/biome_js_formatter/tests/language.rs#L279-L282

This should be enough to prepare the testing infrastructure.

Then, I suggest creating a new folder here: https://github.com/biomejs/biome/tree/main/crates/biome_js_formatter/tests/specs/jsx

As you can see, there are already two folder that test a particular option. Follow the same pattern. Create a new JSX file with what you want to test. Then create `options.json` file and add the new option you created before. You must use underscores.

**Comment by octoshikari** [comment]
@ematipico Hi! Thank you for good clarification. I'm already created PR for this issue and added new test case with `options.json` usage. Will be glad for any feedback when you will have time for that

**Comment by hugo-kamae** [comment]
Hello, I'm sorry to bring this ticket up again, but I've just come across this discussion. I'm interested in the 'singleAttributePerLine' property, but I can't find it in the BiomeJS documentation. If I include it in biome.json in “formatter” I get an error (version 1.9.4). Is there any particular action I need to take to access it?

Hugo

**Comment by ematipico** [comment]
@hugo-kamae 

There's always a change that we change the and of the options.

Use the command `biome migrate prettier` to have a seamless migration, or refer to this page for all the options: https://biomejs.dev/formatter/#options

**Comment by hugo-kamae** [comment]
@ematipico 
Super, thank you very much! Indeed I found my answer by following your link!

Have good day to you and good coding sessions
