### ISSUE TITLE
🐛 Biome client: couldn't create connection to server - with Windows + Volta + Biome global install

### ISSUE THREAD

**Issue by nickwelsh1** [biomejs/biome#1713]
### Environment information

```block
CLI:
  Version:                      1.5.2
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v18.17.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### What happened?

For terminal commands I'm using Powershell.
1. Install Volta https://docs.volta.sh/guide/getting-started#windows-installation
2. Install Node 
```
volta install node
```
3. Install Biome globally 
```
volta install @biomejs/biome
```
4. create a biome.json in a project folder with the following
```
{
  "formatter": {
    "enabled": true,
    "indentStyle": "space",
    "lineWidth": 180,
    "formatWithErrors": false,
    "indentWidth": 2,
    "lineEnding": "lf",
    "ignore": []
  },
  "linter": {
    "enabled": false
  }
}
```
5. Run VScode
6. Install Biome extension (v2.1.2)
7. Restart VScode
*Error: "Biome executable could not be found"
8. Set windows environment variables Path: to contain
```
%userprofile%\AppData\Local\Volta\bin
%userprofile%\AppData\Local\Volta\tools\shared
%userprofile%\AppData\Local\Volta\tools\image\packages
C:\Program Files\Volta\
C:\Program Files\Microsoft VS Code\bin
```
9. In VScode settings.json set 
```
biome.lspBin": "C:\\Users\\<user name>\\AppData\\Local\\Volta\\bin
```
10. Restart VScode
*Error: "Biome client: couldn't create connection to server"
Additional details:
Windows 10
Powershell 7.4.1
winget v1.6.3482
node v20.10.0
vscode 1.85.2

### Expected result

It should not throw an error.
![image](https://github.com/biomejs/biome/assets/15595566/aa50a19f-40d0-4627-b430-c5407761a462)

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
> biome.lspBin": "C:\\Users\\<user name>\\AppData\\Local\\Volta\\bin

I believe `bin` is a folder, and probably in that `bin` folder there's the `biome` binary. If so, then you have to add `biome` after bin

**Comment by jcalvezar** [comment]
Any news? I don't have volta, I got that message when installing the extension in VSCode

**Comment by nhedger** [comment]
> Any news? I don't have volta, I got that message when installing the extension in VSCode

Please open a new issue with details specific to your problem. Many factors could trigger this issue, and we need more information to troubleshoot.

**Comment by nickwelsh1** [comment]
The VScode Biome extension updated to version 2.2.2 so I tried this again, following @ematipico suggestions.

I changed settings.json file for each of the following tests:

1. `"biome.lspBin": "C:\\Users\\(username here)\\AppData\\Local\\Volta\\bin\\biome",`
**succeded**

2. `"biome.lspBin": "/Users/(my username here)/AppData/Local/Volta/bin/biome",`
**succeded**

3. I have `%userprofile%\AppData\Local\Volta\bin` added to the User **PATH** environment variable.

4. `"biome.lspBin": "${env:userprofile}/Users/(my username here)/AppData/Local/Volta/bin/biome",`
failed to interpret the variable
falls back to searching the PATH environment variable
**succeded**

5. `"biome.lspBin": "${env:userprofile}\\Users\\(my username here)\\AppData\\Local\\Volta\\bin\\biome",`
failed to interpret the variable
falls back to searching the PATH environment variable
**succeded**

6. If I don't set "biome.lspBin" it falls back to searching the **PATH** environment variable.
**succeded**

I recommend Volta users do method 2 and perhaps 3 as a fallback.

thank you @ematipico my issue is resolved.

**Comment by ckken** [comment]
```json
{
  "biome.lspBin": "node_modules/@biomejs/biome/bin/biome",
  "typescript.tsdk": "node_modules/typescript/lib",
}
```
ts work on window and mac,but biome work on mac only!

**Comment by PaulRBerg** [comment]
If you got this error when you opened a project in which you didn't want to use Biome, you can add this setting:

```json
"biome.requireConfigFile": true
```

Note that this is only available on the pre-release version of the VSCode extension (v2 and above).

**Comment by Mingx94** [comment]
> {
>   "biome.lspBin": "node_modules/@biomejs/biome/bin/biome",
>   "typescript.tsdk": "node_modules/typescript/lib",
> }
> ts work on window and mac,but biome work on mac only!

windows lspBin should be `node_modules/@biomejs/cli-win32-x64/biome.exe`

**Comment by yairEO** [comment]
constantly happening to me on latest Biome version and on latest Cursor IDE (i'm on windows 11)
