### ISSUE TITLE
📎 Move Biome configuration in its own crate

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#1738]
### Description

This is an internal refactor, so we should not break anything and the existing tests should all pass.

The objective of this task is to move everything that we have in this folder 

https://github.com/biomejs/biome/tree/main/crates/biome_service/src/configuration

Inside in its own crate called `biome_configuration`. Once this is done, it's a matter of updating the rest of the crates to use `biome_configuration` crate.

Remember to add `biome_configuration` in the  [top level Cargo.toml](https://github.com/biomejs/biome/blob/49ea64830787eda7c6a0cb33547581d6046f4055/Cargo.toml#L113-L122)

**Comment by shoaibkh4n** [comment]
Hey @ematipico , I tried to do this, creating a PR , could you please review this [https://github.com/biomejs/biome/pull/1742#issue-2116434102](https://github.com/biomejs/biome/pull/1742#issue-2116434102) and suggest me the changes if any.
