### ISSUE TITLE
🐛 LSP: diagnostics do not respect severity

### ISSUE THREAD

**Issue by ivanjermakov** [biomejs/biome#1744]
### Environment information

```block
// biome rage
CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```
```
// nvim -v
NVIM v0.9.5
Build type: Release
LuaJIT 2.1.1702233742
```
```
// :LspInfo
Client: biome (id: 2, bufnr: [1])
                         filetypes:       javascript, javascriptreact, json, jsonc, typescript, typescript.tsx, typescriptreact
                         autostart:       true
                         root directory:  <project>
                         cmd:             $HOME/.local/share/nvim/mason/bin/biome lsp-proxy
```

### What happened?

All LSP diagnostics provided by `biome lsp-proxy` have severity `ERROR` (`1` in nvim LSP API)

![image](https://github.com/biomejs/biome/assets/26609879/5111da6a-8775-4d6b-a8a8-5692cc9a50ca)

```
:=vim.diagnostic.get(0)
{ {
    bufnr = 1,
    code = "lint/complexity/useFlatMap",
    col = 8,
    end_col = 29,
    end_lnum = 0,
    lnum = 0,
    message = "The call chain .map().flat() can be replaced with a single .flatMap() call.",
    namespace = 40,
    severity = 1,
    source = "biome",
    user_data = {
      lsp = {
        code = "lint/complexity/useFlatMap",
        codeDescription = {
          href = "https://biomejs.dev/linter/rules/use-flat-map"
        }
      }
    }
  }, {
    bufnr = 1,
    code = "lint/style/useConst",
    col = 0,
    end_col = 3,
    end_lnum = 0,
    lnum = 0,
    message = "This let declares a variable which is never re-assigned.",
    namespace = 40,
    severity = 1,
    source = "biome",
    user_data = {
      lsp = {
        code = "lint/style/useConst",
        codeDescription = {
          href = "https://biomejs.dev/linter/rules/use-const"
        },
        relatedInformation = { {
            location = {
              range = {
                ["end"] = {
                  character = 5,
                  line = 0
                },
                start = {
                  character = 4,
                  line = 0
                }
              },
              uri = "file://<redacted>/index.ts"
            },
            message = ""
          } }
      }
    }
  } }
```

### Expected result

I expect Biome diagnostics to only use WARNING, INFO, and HINT LSP severity.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
I don't use vim very often, so you'll have to give us more information to understand why you expect a different severity.

Is it something you can set at LSP setting level?

**Comment by ivanjermakov** [comment]
> I don't use vim very often, so you'll have to give us more information to understand why you expect a different severity.

[TypeScript LSP](https://github.com/typescript-language-server/typescript-language-server) publishes ERROR diagnostics only when code will not be compiled by `tsc`. It also uses HINT severity for unused symbols and unreachable code.

I expect Biome to follow the same conventions, producing at most WARNING diagnostics. Otherwise it's unclear if the code compiles when both Biome LSP and TypeScript LSP are running for buffer.

Consider the following line:
```js
let b = 5 + {}
```
There are 3 diagnostics:
- `tsserver` (ERROR): Operator '+' cannot be applied to types 'number' and '{}'. [2365]
- `tsserver` (HINT): 'b' is declared but its value is never read. [6133]
- `biome lsp-proxy` (ERROR): This let declares a variable which is never re-assigned. [lint/style/useConst]

And highlight shows why it's confusing:
![image](https://github.com/biomejs/biome/assets/26609879/129aa7d5-b2e2-40f6-99ac-45939fbb80dc)

If Biome published diagnostics with WARNING/INFO severity this confusion would be resolved, since then won't be inferred as compilation error.

> Is it something you can set at LSP setting level?

I think it's possible to use [NeoVim LSP API](https://neovim.io/doc/user/lsp.html) to intercept Biome diagnostics and change their severity, but I think it's rather a hack than a solution. 

> Is it documented somewhere?

If you mean Biome behavior, skimming through the Biome code I found that it's setting `severity` to `Severity::Error` by default, perhaps without a way to configure it on a diagnostic level:
https://github.com/biomejs/biome/blob/3773dd73e679b5e320010c5e4aa4453531d0ab4c/crates/biome_diagnostics/src/diagnostic.rs#L43-L45

**Comment by ematipico** [comment]
Ok, this message explains better what you meant at the beginning, it was very difficult without context.

Biome is meant to run out of the box, and it's meant to offer a set of functionalities with good defaults. Among these defaults, there are formatting, linting and importing sorting.

Linting comes with a set of recommended rules that should error when running the `lint` command. This gives a equal experience for both CLI and LSP. That's what this tool is also about.

Comparing Biome to the TypeScript language server isn't a fair assessment because they have two different means, also Biome LSP isn't **yet** a replacement for a full fledged language server. However, you can still use a configuration file to reduce the severity of the lint rules.

**Comment by ivanjermakov** [comment]
I agree that Biome is by no means a replacement for tsserver, and the problem is that it's not convenient to use it as a companion LSP for helpful suggestions because of severity. I acknowledge that it might complicate things by separating severity logic across CLI and LSP.

I will try to configure nvim to force Biome LSP to publish warnings and share my results.

Thanks for your effors.

**Comment by ivanjermakov** [comment]
I had no success intercepting diagnostics in nvim so I made a change to convert Biome ERROR diagnostic to LSP WARNING.

Not sure if this is a correct approach, but it works for my use case.

See [1744-lsp-severity](https://ivanjermakov/biome/tree/1744-lsp-severity).

**Comment by Conaclos** [comment]
We plan to allow configuring the severity level for every group of lint rules. This will allow you to set `warning` instead of `error` for rules of a group.
