### ISSUE TITLE
📎 Create lint rules for barrel files

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#1750]
### Description

We would want to implement the rules that belong to: https://github.com/thepassle/eslint-plugin-barrel-files

- [x] `noBarrelFile` -> [barrel-files/avoid-barrel-files](https://github.com/thepassle/eslint-plugin-barrel-files/blob/main/docs/rules/avoid-barrel-files.md)
- [x] `noNamespaceImport` [barrel-files/avoid-namespace-imports](https://github.com/thepassle/eslint-plugin-barrel-files/blob/main/docs/rules/avoid-namespace-import.md) @unvalley 
- [x] `noReExportAll` [barrel-files/avoid-re-export-all](https://github.com/thepassle/eslint-plugin-barrel-files/blob/main/docs/rules/avoid-re-export-all.md) @mdm317 

Comment here which rule you would like to implement.

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by mdm317** [comment]
Can I work on "noReExportAll"??

**Comment by ematipico** [comment]
Sure go ahead!

**Comment by unvalley** [comment]
I made a pr for `noNamespaceImport`.

**Comment by togami2864** [comment]
I'll try `noBarrelFile`:)
