### ISSUE TITLE
📎 Add command `biome migrate eslint`

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#1752]
## Description

We want to create a new command, `biome migrate eslint`, which will attempt to determine the rules configured in eslint and update the `biome.json` with rules that have a source in Biome.

Plus, it will attempt to read `.eslintignore` file and map the glob patterns in `biome.json#linter.ignore`

### Limitations and expectations 

Computing the rules that applied by eslint by reading the configuration file isn't an easy task, mainly because the majority of the projects out there use JavaScript to write their configuration file.

**Comment by Conaclos** [comment]
> Computing the rules that applied by eslint by reading the configuration file isn't an easy task, mainly because the majority of the projects out there use JavaScript to write their configuration file.

We could invoke eslint with the [`--print-config` CLI flag](https://eslint.org/docs/latest/use/command-line-interface#--print-config) to obtain the final config.

**Comment by Conaclos** [comment]
I am starting the work to support the migration from the legacy eslint config.

**Comment by movahhedi** [comment]
Supporting flat configs (eslint.config.js) would also be much appreciated.

**Comment by dmythro** [comment]
I think a feature like this will help a lot with getting more projects migrated to Biome.
Plus, I'd highly appreciate showing a list of rules which are not (yet) supported so you always know what you are missing. Moving to Formatter is one thing, but moving to another Linter which may not check important stuff for you is bad when you know about it the hard way.

**Comment by ffMathy** [comment]
@Conaclos how is this going? Is there a draft PR open where we can follow the progress? 😅❤️

**Comment by Conaclos** [comment]
The implementation is now in a good shape. Any comments/reviews are welcome. #2103

**Comment by Conaclos** [comment]
We have released a [Nightly](https://github.com/biomejs/biome/releases/tag/cli%2Fv1.6.4-nightly.a995ada) that includes `biome migrate eslint`. Please let us know if you find any issue. We look forward to hearing about your experiences with this new feature!

**Comment by umstek** [comment]
This works great, although a simple eslint config generated a lot of biome rules with `recommended` set to `false`. I wonder whether there's an overlap between the generated and the recommended rules set and also whether the recommended rules could be better than the original eslint rules? Unfortunately, I couldn't find a recommended (default) rules file to compare this against, only the [docs](https://biomejs.dev/linter/rules/).

**Comment by Conaclos** [comment]
@umstek Yeah most of the rules are in the recommended set. It was simpler to disable recommended and migrate individually every rule. You can find the list of recommended rule here: https://biomejs.dev/linter/rules/#recommended-rules. There is an open discussion to provide a way of removing redundant configs: https://github.com/biomejs/biome/issues/2465

**Comment by umstek** [comment]
@Conaclos Thanks. So I did this, with that list of recommended rules extracted as `recommended.txt`. 

```typescript
import biome from './biome.json';

const recommended = (await Bun.file('./recommended.txt').text())
  .split('\n')
  .map((x: string) => x.trim())
  .filter(Boolean);

biome.linter.rules.recommended = true;

const groups = Object.keys(biome.linter.rules).filter(
  (x) => typeof biome.linter.rules[x] === 'object',
);

for (const rule of recommended) {
  for (const group of groups) {
    if (biome.linter.rules[group][rule]) {
      delete biome.linter.rules[group][rule];
    }
  }
}

Bun.write('biome.deduped.json', JSON.stringify(biome, null, 2));
```

Looks good enough.

**Comment by umstek** [comment]
@Conaclos Thanks. I [wrote a script](https://gist.github.com/umstek/da056e505f819ad924c04ab820b2382e) to do what I wanted.
