### ISSUE TITLE
📎 Add `--formatter` to the command `biome rage`

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#1754]
### Description

We want to add a new option called `--formatter` to the command `biome rage`.

The command is meant to print helpful information for us maintainers. With the `--foramtter` option, we want to print a list of the options currently applied by the current configuration.

This is where the implementation should be: 

https://github.com/biomejs/biome/blob/1646ddb29b3227d81413324f6aa2cf99d0ffdd4d/crates/biome_cli/src/commands/rage.rs#L17-L59

**Comment by seitarof** [comment]
@ematipico 
I'd like to work on this issue.
This issue is similar to #1753 .

**Comment by nhedger** [comment]
I've assigned it to you @seitarof, thanks for the interest!
