### ISSUE TITLE
🐛 @biomejs/js-api ERESOLVE overriding peer dependency

### ISSUE THREAD

**Issue by NikolaRHristov** [biomejs/biome#1773]
### Environment information

```block
CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.4.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

When using `@biomejs/js-api` `0.3.0-nightly.cfef948` `peerDependencies` are not found.

```
11:10:31.337	Detected the following tools from environment: nodejs@18.17.1, npm@9.6.7
11:10:31.338	Installing project dependencies: npm install --progress=false
11:10:40.164	npm WARN ERESOLVE overriding peer dependency
11:10:40.165	npm WARN While resolving: @biomejs/js-api@0.3.0-nightly.cfef948
11:10:40.166	npm WARN Found: peerOptional @biomejs/wasm-nodejs@"^10.0.0" from the root project
11:10:40.166	npm WARN 
11:10:40.166	npm WARN Could not resolve dependency:
11:10:40.166	npm WARN peerOptional @biomejs/wasm-nodejs@"^10.0.0" from the root project
11:10:50.432	npm ERR! code ETARGET
11:10:50.433	npm ERR! notarget No matching version found for @biomejs/wasm-nodejs@^10.0.0.
11:10:50.434	npm ERR! notarget In most cases you or one of your dependencies are requesting
11:10:50.434	npm ERR! notarget a package version that doesn't exist.
```

### Expected result

Normal install.

Managed to get it working by placing an `.npmrc` file in the root of the repository:

```sh
legacy-peer-deps=true
shamefully-hoist=true
strict-peer-dependencies=false
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
We don't officially maintain these packages yet. Would you like to help @NikolaRHristov ?

**Comment by NikolaRHristov** [comment]
Yes, definitely, I use it in https://github.com/NikolaRHristov/AstroBiome

**Comment by futured-it** [comment]
Someone was already [fixed](https://github.com/biomejs/biome/commit/cb5a0ece54a8dc0d2b2d1bbe95f31dad902f4daf) it, but it isn't deployed yet (I mean, updated on npm registry), so we can't really fix this issue until owner of npm package will update it.

**Comment by ematipico** [comment]
I just released a new nightly: https://www.npmjs.com/package/@biomejs/js-api/v/0.3.0-nightly.384b31d

**Comment by futured-it** [comment]
> I just released a new nightly: https://www.npmjs.com/package/@biomejs/js-api/v/0.3.0-nightly.384b31d

I would recommend to release as `latest`, because if someone will install with `npm install <pkg_name>` (without specifying the version) it'll install previous version which can lead to new issues like this. Or note in README about it.

**Comment by ematipico** [comment]
We will do it once we release v1.6.0
