### ISSUE TITLE
📚 [docs] "Since version 1.6.0" potential typo?

### ISSUE THREAD

**Issue by devdumpling** [biomejs/biome#1777]
### Documentation URL

https://biomejs.dev/guides/how-biome-works/#configuration

### Description

In the configuration section, it specifies that jsonc is available since 1.6.0. As far as I can tell, 1.6.0 isn't released yet. 

I'm confused whether this is a typo or if jsonc is meant to be released in the upcoming minor release. Happy to correct if the docs are open source, or if I'm missing something feel free to close. Thanks!

### Expectations

`jsonc` support should point to correct version (?) support was added, or if it will be added in a future version, clarify that.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by unvalley** [comment]
@devdumpling yes, 1.6.0 isn't released yet.

The JSONC support is made by @ematipico , is the describing 1.6.0 is intended?

**Comment by ematipico** [comment]
Not a bug, I intentionally wrote it this way. We usually merge the PR with feature and code, to avoid too much fragmentation.
