### ISSUE TITLE
🐛 Doesn't work at all, empty output (Windows)

### ISSUE THREAD

**Issue by BorisZubchenko** [biomejs/biome#1798]
### Environment information

```block
I can't get the output of `biome rage`. Please clarify what info do you need.

node v20.11.0
npm 10.4.0
```

### What happened?

Calling `npx @biomejs/biome` with any argument just returns an empty output. I use Windows 11 and can't test it on other OSs.

1. `mkdir biome-bug && cd biome-bug`
2. `npm init`
3. `npm install --save-dev --save-exact @biomejs/biome`
4. `npx @biomejs/biome any arg here it doesn't matter at all`
5. Receive an empty output.

### Expected result

It should work.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
You have to provide a folder or file to the command:

```
biome format file.js
```

**Comment by BorisZubchenko** [comment]
The thing is that it doesn't matter what I type, the output is empty.

![image](https://github.com/biomejs/biome/assets/31354262/eca18fe0-644f-4e92-8a13-174a739bb5bf)

**Comment by Levieber** [comment]
I'm on Windows and it's works

![Biome output](https://github.com/biomejs/biome/assets/104157600/3d4f4b53-94f4-4c12-b3f2-11ef770d792f)

![Biome format output](https://github.com/biomejs/biome/assets/104157600/ef12583a-052e-4814-b79d-f4790183ffa1)

**Comment by Levieber** [comment]
I'm using PowerShell 7.4.1 and Windows Terminal

**Comment by ematipico** [comment]
You're using the incorrect package. It's also highlighted in the homepage

![Screenshot_2024-02-12-21-19-59-51_3aea4af51f236e4932235fdada7d1643.jpg](https://github.com/biomejs/biome/assets/602478/6742ada2-e863-41fd-933b-50172cd8caf0)

Closing.

**Comment by BorisZubchenko** [comment]
@spdiswal doesn't work either

**Comment by BorisZubchenko** [comment]
@Levieber It doesn't

![image](https://github.com/biomejs/biome/assets/31354262/fcf0edfb-b835-4f0b-8ea5-964bc347c47e)

**Comment by Levieber** [comment]
@BorisZubchenko What is it like in Powershell?

**Comment by BorisZubchenko** [comment]
Same

![image](https://github.com/biomejs/biome/assets/31354262/9a77930a-91a9-4a06-92b6-ff95a8cc5ae2)

**Comment by spdiswal** [comment]
What happens if you run Biome from a script in `package.json` instead of `npx`?

For example:
```json
  "scripts": {
    "format": "biome format index.js",
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

```shell
npm run format
```

**Comment by BorisZubchenko** [comment]
No luck 😞 

![image](https://github.com/biomejs/biome/assets/31354262/bbd40dd9-9da0-4e83-aec2-c72a1651c800)

**Comment by BorisZubchenko** [comment]
No, it basically doesn't respect any passed argument.

![image](https://github.com/biomejs/biome/assets/31354262/ad59718e-0990-4e10-b26b-19222130ac7e)

**Comment by ematipico** [comment]
Does this happen with other package managers like pnpm or yarn?

**Comment by BorisZubchenko** [comment]
Please consider [this comment](https://github.com/biomejs/biome/issues/1798#issuecomment-1939643398). It's like "stuck", so I can't type and unable to kill the process.

**Comment by BorisZubchenko** [comment]
Now everything works, even with the old version when the bug occurred: `npx @biomejs/biome@1.5.3` 

Unfortunately, I still don't know the reason. Maybe some Windows-related bug. I'm closing this issue since it's not popular.

**Comment by Levieber** [comment]
Downloading Visual C++ Redistributable for Visual Studio 2015 seems to have solved it

**Comment by BorisZubchenko** [comment]
It may be, because back then I had a fresh Windows installation, without redists. Since then, I downloaded Steam or something and it installed these packages.

**Comment by hdkhang6803** [comment]
It works when I clear all the packages of my ReactJS project using `git clean -f -x -d` and reinstall them all again. Also, my teammates accidentally downloaded a `biome` package (not sure where it came from but a high risk of conflict) so I removed it before reinstalling the dependencies.
