### ISSUE TITLE
📝 Inconsistency compared to prettier

### ISSUE THREAD

**Issue by xXNickznXx** [biomejs/biome#1805]
### Environment information

```bash
CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.1.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
  "$schema": "https://biomejs.dev/schemas/1.5.3/schema.json",
  "javascript": {
    "formatter": {
      "quoteStyle": "single",
      "trailingComma": "none"
    }
  },
  "formatter": {
    "indentStyle": "space",
    "lineEnding": "crlf",
    "lineWidth": 140
  }
}
```

### Playground link

https://biomejs.dev/playground/?lineWidth=140&indentStyle=space&quoteStyle=single&trailingComma=none&typescript=false&code=ZgB1AG4AYwB0AGkAbwBuACAAYQAoACkAIAB7AAoAIAAgAGkAZgAgACgAdAByAHUAZQApACAAewAKACAAIAAgACAAYwBvAG4AcwB0ACAAdwBhAGwAawBlAHIAQwBoAGkAbABkAHIAZQBuAFcAaQB0AGgAUQB1AG8AdABhAHQAaQBvAG4ATQBhAHIAawAgAD0AIABkAG8AYwB1AG0AZQBuAHQALgBjAHIAZQBhAHQAZQBUAHIAZQBlAFcAYQBsAGsAZQByACgACgAgACAAIAAgACAAIAB0AGgAaQBzAC4AdABlAHgAdABDAG8AbgB0AGUAbgB0AEUAbABlAG0AZQBuAHQALgBuAGEAdABpAHYAZQBFAGwAZQBtAGUAbgB0ACwACgAgACAAIAAgACAAIABOAG8AZABlAEYAaQBsAHQAZQByAC4AUwBIAE8AVwBfAFQARQBYAFQALAAKACAAIAAgACAAIAAgACgAbgBvAGQAZQApACAAPQA%2BACAAKABEAEkAUwBBAEwATABPAFcARQBEAF8AUQBVAE8AVABFAFMALgBzAG8AbQBlACgAKABzACkAIAA9AD4AIABuAG8AZABlAC4AdABlAHgAdABDAG8AbgB0AGUAbgB0AC4AaQBuAGMAbAB1AGQAZQBzACgAcwApACkAIAA%2FACAATgBvAGQAZQBGAGkAbAB0AGUAcgAuAEYASQBMAFQARQBSAF8AQQBDAEMARQBQAFQAIAA6ACAATgBvAGQAZQBGAGkAbAB0AGUAcgAuAEYASQBMAFQARQBSAF8AUwBLAEkAUAApAAoAIAAgACAAIAApADsACgAgACAAfQAKAH0ACgA%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by mdm317** [comment]
Can i try this issue?

**Comment by mdm317** [comment]
@togami2864 
Thank you! It seems like it will be a great help.
