### ISSUE TITLE
💅 useExhaustiveDependencies gives different results in different environments

### ISSUE THREAD

**Issue by RJWadley** [biomejs/biome#1834]
### Environment information

```bash
On MACOS:

CLI:
  Version:                      1.5.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.3"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0


On Linux:

CLI:
  Version:                      1.5.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.11.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Rule name

useExhaustiveDependencies

### Playground link

[https://biomejs.dev/playground/?code=import%20%7B%20useCallback%2C%20useEffect%2C%20useState%20%7D%20from%20%22react%22%0A%0Aexport%20default%20function%20ImageSequence%28%29%20%7B%0A%09const%20%5BsequenceData%5D%20%3D%20useState%28%7B%0A%09%09frame%3A%200%2C%0A%09%09images%3A%20%5B%5D%20as%20HTMLImageElement%5B%5D%2C%0A%09%7D%29%0A%0A%09const%20createImage%20%3D%20useCallback%28%0A%09%09%28src%3A%20string%2C%20index%3A%20number%29%20%3D%3E%20%7B%0A%09%09%09if%20%28sequenceData.images%5Bindex%5D%29%20return%0A%09%09%09const%20img%20%3D%20new%20Image%28%29%0A%09%09%09img.src%20%3D%20src%0A%09%09%09sequenceData.images%5Bindex%5D%20%3D%20img%0A%09%09%7D%2C%0A%09%09%5BsequenceData.images%5D%2C%0A%09%29%0A%0A%09useEffect%28%28%29%20%3D%3E%20%7B%0A%09%09for%20%28let%20i%20%3D%200%3B%20i%20%3C%20length%3B%20i%20%2B%3D%201%29%20%7B%0A%09%09%09const%20maxLen%20%3D%20length.toString%28%29.length%0A%09%09%09const%20imageNumber%20%3D%20i.toString%28%29.padStart%28maxLen%2C%20%220%22%29%0A%0A%09%09%09import%28%60..%2Fimages%2Fsequence%2F%24%7BimageNumber%7D.webp%60%29%0A%09%09%09%09.then%28%28image%3A%20%7B%20default%3A%20string%20%7D%29%20%3D%3E%20%7B%0A%09%09%09%09%09return%20createImage%28image.default%2C%20i%29%0A%09%09%09%09%7D%29%0A%09%09%09%09.catch%28console.error%29%0A%09%09%7D%0A%09%7D%2C%20%5BcreateImage%5D%29%0A%0A%09return%20%3Ccanvas%20%2F%3E%0A%7D](https://biomejs.dev/playground/?code=import%20%7B%20useCallback%2C%20useEffect%2C%20useState%20%7D%20from%20%22react%22%0A%0Aexport%20default%20function%20ImageSequence%28%29%20%7B%0A%09const%20%5BsequenceData%5D%20%3D%20useState%28%7B%0A%09%09frame%3A%200%2C%0A%09%09images%3A%20%5B%5D%20as%20HTMLImageElement%5B%5D%2C%0A%09%7D%29%0A%0A%09const%20createImage%20%3D%20useCallback%28%0A%09%09%28src%3A%20string%2C%20index%3A%20number%29%20%3D%3E%20%7B%0A%09%09%09if%20%28sequenceData.images%5Bindex%5D%29%20return%0A%09%09%09const%20img%20%3D%20new%20Image%28%29%0A%09%09%09img.src%20%3D%20src%0A%09%09%09sequenceData.images%5Bindex%5D%20%3D%20img%0A%09%09%7D%2C%0A%09%09%5BsequenceData.images%5D%2C%0A%09%29%0A%0A%09useEffect%28%28%29%20%3D%3E%20%7B%0A%09%09for%20%28let%20i%20%3D%200%3B%20i%20%3C%20length%3B%20i%20%2B%3D%201%29%20%7B%0A%09%09%09const%20maxLen%20%3D%20length.toString%28%29.length%0A%09%09%09const%20imageNumber%20%3D%20i.toString%28%29.padStart%28maxLen%2C%20%220%22%29%0A%0A%09%09%09import%28%60..%2Fimages%2Fsequence%2F%24%7BimageNumber%7D.webp%60%29%0A%09%09%09%09.then%28%28image%3A%20%7B%20default%3A%20string%20%7D%29%20%3D%3E%20%7B%0A%09%09%09%09%09return%20createImage%28image.default%2C%20i%29%0A%09%09%09%09%7D%29%0A%09%09%09%09.catch%28console.error%29%0A%09%09%7D%0A%09%7D%2C%20%5BcreateImage%5D%29%0A%0A%09return%20%3Ccanvas%20%2F%3E%0A%7D)

### Expected result

I'm expecting no linting errors (this is what occurs on macos and on the playground)

In linux environments like github actions, I get two linting errors that I cannot fix:

```
  ✖ This hook specifies a dependency more specific that its captures: sequenceData.images
  
    5 │ 		images: [] as HTMLImageElement[],
    6 │ 	});
  > 7 │ 	const createImage = useCallback(
      │ 	                    ^^^^^^^^^^^
    8 │ 		(src: string, index: number) => {
    9 │ 			if (sequenceData.images[index]) return;
  
  ℹ This capture is more generic than...
  
     7 │ 	const createImage = useCallback(
     8 │ 		(src: string, index: number) => {
   > 9 │ 			if (sequenceData.images[index]) return;
       │ 			    ^^^^^^^^^^^^^^^^^^^^^^^^^^
    10 │ 			const img = new Image();
    11 │ 			img.src = src;
  
  ℹ ...this dependency.
  
    12 │ 			sequenceData.images[index] = img;
    13 │ 		},
  > 14 │ 		[sequenceData.images],
       │ 		 ^^^^^^^^^^^^^^^^^^^
    15 │ 	);
    16 │ 	useEffect(() => {
  

./test.tsx:7:22 lint/correctness/useExhaustiveDependencies ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ This hook does not specify all of its dependencies: sequenceData.images[index]
  
    5 │ 		images: [] as HTMLImageElement[],
    6 │ 	});
  > 7 │ 	const createImage = useCallback(
      │ 	                    ^^^^^^^^^^^
    8 │ 		(src: string, index: number) => {
    9 │ 			if (sequenceData.images[index]) return;
  
  ℹ This dependency is not specified in the hook dependency list.
  
     7 │ 	const createImage = useCallback(
     8 │ 		(src: string, index: number) => {
   > 9 │ 			if (sequenceData.images[index]) return;
       │ 			    ^^^^^^^^^^^^^^^^^^^^^^^^^^
    10 │ 			const img = new Image();
    11 │ 			img.src = src;
  

./test.tsx lint ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ The file contains diagnostics that needs to be addressed.
  
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by cybrwlf525** [comment]
Seeing this behavior in linux environment too using WSL Ubuntu

**Comment by ematipico** [comment]
@RJWadley 

Can you try one of the latest nightlies? I believe we fixed this

**Comment by RJWadley** [comment]
@ematipico [1.5.3-nightly.69f9031](https://www.npmjs.com/package/@biomejs/biome/v/1.5.3-nightly.69f9031) is working great for me on ubuntu!
