### ISSUE TITLE
☂️ Lint rules for testing frameworks

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#1848]
### Description

We want to implement some lint rules to help people with their tests. I baked this list from the `eslint-plugin-jest` and evaluated only those rules that **aren't** pedantic and can be enabled for multiple test runners: `mocha`, `jest`, `node:test`, etc.

Feel free to comment here on which rule you would like to implement. We have some utilities that should help you to develop the rule: 
- https://github.com/biomejs/biome/blob/c5a98a72def0a1db072fc3face35cb30241608dd/crates/biome_js_syntax/src/expr_ext.rs#L1569
- https://github.com/biomejs/biome/blob/c5a98a72def0a1db072fc3face35cb30241608dd/crates/biome_js_syntax/src/expr_ext.rs#L1665
- https://github.com/biomejs/biome/blob/c5a98a72def0a1db072fc3face35cb30241608dd/crates/biome_js_syntax/src/expr_ext.rs#L1686

There are more functions in that files, feel free to explore.

This is an example of usage:

https://github.com/biomejs/biome/blob/c5a98a72def0a1db072fc3face35cb30241608dd/crates/biome_js_analyze/src/analyzers/nursery/no_focused_tests.rs#L43-L52

The names aren't set in stone, and feel free to suggest alternatives.

- [x] `noExportsInTest` [source](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-export.md) @ah-yu 
- [x] `noNestedTestSuites` [source](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/max-nested-describe.md) @vasucp1207 
- [x] `noDoneCallback` [source](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-done-callback.md) @vasucp1207
- [x] `noDuplicateTestHooks` [source](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-duplicate-hooks.md) @vasucp1207 
- [ ] `noMisplacedAssertion` [source](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-standalone-expect.md) @ematipico

**Comment by vasucp1207** [comment]
I am picking `noDuplicateTestHooks`.

**Comment by ah-yu** [comment]
Can I work on `noExportsInTest`?

**Comment by vasucp1207** [comment]
I am working on `noNestedTestSuites`.

**Comment by ematipico** [comment]
I will work on `noMisplacedAssertion`

**Comment by vasucp1207** [comment]
I am working on `noDoneCallback`.
