### ISSUE TITLE
🐛 extends npm package no work

### ISSUE THREAD

**Issue by ckken** [biomejs/biome#1862]
### Environment information

```block
{
	"extends": [
		"packages/biome-emp-config/biome.json" //work
                "biome-emp-config/biome.json"//install package to project no work
	]
}
```

### What happened?

no work

### Expected result

work for extends npm package

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
This feature hasn't been released yet, it will be available from version 1.6

**Comment by ckken** [comment]
thanks!

**Comment by nevir** [comment]
Ran into this (and looking forward to it)

I wonder if y'all should tweak the CI workflows to hold back website updates until a new version is released?
