### ISSUE TITLE
💅 <JSDoc type @type {const} doesn't work>

### ISSUE THREAD

**Issue by nickcomua** [biomejs/biome#1872]
### Environment information

```bash
CLI:
  Version:                      1.5.3    
  Color support:                true     
                                         
Platform:                                
  CPU Architecture:             x86_64   
  OS:                           windows  
                                         
Environment:                             
  BIOME_LOG_DIR:                unset    
  NO_COLOR:                     unset    
  TERM:                         unset    
  JS_RUNTIME_VERSION:           "v21.6.1"
  JS_RUNTIME_NAME:              "node"   
  NODE_PACKAGE_MANAGER:         unset    
                                         
Biome Configuration:                     
  Status:                       unset
                                     
Workspace:                           
  Open Documents:               0
```

### Rule name

https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#casts

### Playground link

https://biomejs.dev/playground/?code=YwBvAG4AcwB0ACAAYwBvAG0AbQBhAG4AZABUAHkAcABlAE0AYQBwACAAPQAgAC8AKgAqACAAQAB0AHkAcABlACAAewBjAG8AbgBzAHQAfQAgACoALwAgACgAewAKAAkACQBJAEYAOgAgAHsAIAB0AHkAcABlADoAIAAiAHMAYwByAGkAcAB0AGkAZgBjAG8AbgBkAGkAdABpAG8AbgAiACAAfQAsAAoACQAJAEUATABJAEYAOgAgAHsAIAB0AHkAcABlADoAIAAiAHMAYwByAGkAcAB0AGUAbABpAGYAYwBvAG4AZABpAHQAaQBvAG4AIgAgAH0ALAAKAAkACQBFAEwAUwBFADoAIAB7ACAAdAB5AHAAZQA6ACAAIgBzAGMAcgBpAHAAdABlAGwAcwBlAGMAbwBuAGQAaQB0AGkAbwBuACIAIAB9ACwACgAJAAkATQBEAFIAOgAgAHsAIAB0AHkAcABlADoAIAAiAHMAYwByAGkAcAB0AG0AZAByACIAIAB9ACwACgAJAAkAUgBNAFAAVAA6ACAAewAgAHQAeQBwAGUAOgAgACIAcwBjAHIAaQBwAHQAcgBtAHAAdAAiACAAfQAsAAoACQAJAFcAQQBJAFQAOgAgAHsAIAB0AHkAcABlADoAIAAiAHMAYwByAGkAcAB0AHcAYQBpAHQAIgAgAH0ALAAKAAkACQBTAEUAVAA6ACAAewAgAHQAeQBwAGUAOgAgACIAcwBjAHIAaQBwAHQAYQBjAHQAaQBvAG4AIgAgAH0ALAAKAAkACQBDAE8ATQBNAEUATgBUADoAIAB7ACAAdAB5AHAAZQA6ACAAIgBzAGMAcgBpAHAAdABjAG8AbQBtAGUAbgB0ACIAIAB9ACwACgAJAAkARQBOAEQAXwBJAEYAOgAgAHsACgAJAAkACQB0AHkAcABlADoAIAAiAGQAZQBjAGkAcwBpAG8AbgAiACwACgAJAAkACQB0AGUAeAB0ADoAIAAiAEUATgBEACAASQBGACIALAAKAAkACQAJAHYAYQBsAHUAZQA6ACAAIgBFAE4ARABfAEkARgA7ACIALAAKAAkACQAJAGYAaQBsAGwAOgAgACIAIwBFAEUARgAxAEYANgAiACwACgAJAAkACQBzAHQAcgBvAGsAZQA6ACAAIgAjAEIAOABDADYARAA2ACIALAAKAAkACQAJAGUAeAB0AHIAYQBMAGkAbgBlAHMAUwB0AHIAbwBrAGUAOgAgACIAIwBCADgAQwA2AEQANgAiACwACgAJAAkAfQAsAAoACQAJAE4ARQBYAFQAOgAgAHsAIAB0AHkAcABlADoAIAAiAHMAYwByAGkAcAB0AGUAbgBkACIAIAB9ACwACgAJAH0AKQA7AAoACgAvAC8AIABjAG8AbQBtAGEAbgBkAFQAeQBwAGUATQBhAHAALgA%3D&typescript=false&jsx=false

### Expected result

"as const" analog for jsdoc
https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#casts
it dosent work for biome.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
Biome doesn't support TSdoc typing. It is not planned for now.

**Comment by Conaclos** [comment]
Biome doesn't support TSdoc typing. It is not planned for now.
