### ISSUE TITLE
💅 Evolving any is considered implicit any by `noImplicitAnyLet`

### ISSUE THREAD

**Issue by bgenia** [biomejs/biome#1883]
### Environment information

```bash
CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.5.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.4.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           true
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Rule name

lint/suspicious/noImplicitAnyLet

### Playground link

https://biomejs.dev/playground/?code=LwAvACAARQB2AG8AbAB2AGkAbgBnACAAYQBuAHkAIABpAHMAIABjAG8AbgBzAGkAZABlAHIAZQBkACAAaQBtAHAAbABpAGMAaQB0ACAAYQBuAHkACgBsAGUAdAAgAGIACgBiACAAPQAgADEACgAKAC8ALwAgAEUAdgBvAGwAdgBpAG4AZwAgAGEAcgByAGEAeQAgAGkAcwAgAGkAZwBuAG8AcgBlAGQACgBjAG8AbgBzAHQAIABhAHIAcgAgAD0AIABbAF0ACgBhAHIAcgAuAHAAdQBzAGgAKAAxACkACgBhAHIAcgAuAHAAdQBzAGgAKAAiAGgAZQBsAGwAbwAiACkACgA%3D

## Evolving any

```ts
let b
b = 1
```

This case should be only marked as "implicit any" if `noImplicitAny` tsconfig option is set to `false`. If the purpose of this rule is specifically to forbid using evolving any I suggest at least changing the rationale in the docs because currently it does not make sense.

[The docs say](https://biomejs.dev/linter/rules/no-implicit-any-let) that this is a "dangerous escape hatch" and typescript's `noImplicitAny` doesn't report this case, this is because it's not actually an `any`. This is a separate feature which allows inferring variable type from assignments. This is type safe. 

[Example 1](https://www.typescriptlang.org/play?noImplicitAny=false#code/PTAEAEDsHsEkFsAOAbAlgY1QFwIKQJ4BcoAZgIbIDOApgLABQAJtesmQE7WkCuk6WqaJFDohlbvGoA5CQCNq7ABQA3Ct2rFIchQEpiy6KkYMGyallDUAHmSRmGIUKAB6AfhP1rtlFwC8oACIAC2pkZGhQAHdodmRGAIBuSxs7OnpHJ0ys7JynNw9RSHFJGXh5JS9UnQYgA)
[Example 2](https://www.typescriptlang.org/play?#code/PTAEAEDsHsEkFsAOAbAlgY1QFwIKQJ4BcoWATgK4CmAsAFAAml6yAhqZaAGbmTparRIodIIDO5eJQByEgEaVSACgBuLZFWKQ5CgJTFl0VPTp1klLKEoAPFkjN0QoUAD0A-CdrXbKDgF5QAEQAFpTIyNCgAO7QpMj0AQDcljZ2NLSOTplZ2TlObh4ikOKSMvDySl6pOnRAA)

See microsoft/TypeScript#11263 microsoft/TypeScript#45369 microsoft/TypeScript#54414

## Evolving arrays

This behavior also exists in a form of evolving arrays, for which biome does not check.

```ts
const arr = []
arr.push(1)
arr.push("hello")
```

[Example 1](https://www.typescriptlang.org/play?noImplicitAny=false#code/PTAEAEDsHsEkFsAOAbAlgY1QFwIKQJ4BcoAZgIbIDOApgLABQ60klWoARqALygDaAuqBCgAIqkooy+agBNQZSvIICGDdgDpEAV0oALABQBGAJQBuDg2GhrN6wD0A-Kvobte-QCJd1ZMmgezC3orW1DbR2dXHQMsACctakD2SzAw0Ij6IA)
[Example 2](https://www.typescriptlang.org/play?#code/PTAEAEDsHsEkFsAOAbAlgY1QFwIKQJ4BcoWATgK4CmAsAFDrSQDOWoARqALygDaAuqBCgAIqiYoAhvkoATUBKbyC-OnTYA6ROSYALABQBGAJQBudnSGgr1qwD0A-KtoatuvQCIdlZMmjvT5rSWNiE2Dk4u2vpkVAFsFmChIeG0QA)

If this rule is meant to ban evolving types, I suggest banning this too.

See microsoft/TypeScript#11432 microsoft/TypeScript#43752

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
Good point. We should certainly rename the rule and add more cases.

**Comment by bgenia** [comment]
Another case of control flow inference for which biome does not check:

```ts
class Example {
       b
    // ^? inferred as number

    constructor() {
        this.b = 2
    }
}
```

[Playground](https://biomejs.dev/playground/?code=YwBsAGEAcwBzACAARQB4AGEAbQBwAGwAZQAgAHsACgAgACAAIAAgACAAIAAgAGIACgAgACAAIAAgAC8ALwAgAF4APwAgAGkAbgBmAGUAcgByAGUAZAAgAGEAcwAgAG4AdQBtAGIAZQByAAoACgAgACAAIAAgAGMAbwBuAHMAdAByAHUAYwB0AG8AcgAoACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAHQAaABpAHMALgBiACAAPQAgADIACgAgACAAIAAgAH0ACgB9AAoA)
[Example 1](https://www.typescriptlang.org/play?noImplicitAny=false#code/PTAEAEDsHsEkFsAOAbAlgY1QFwIKQJ4BcoAZgIbIDOApgLABQD6yZlloAogB5lLLWgA3g1CixoAEYixIUAD0A-A2mj00SJSwAnAK7os0LQAoAlEJXjQWABapKAOgmgAvKABMFgL4Nv9IA)
[Example 2](https://www.typescriptlang.org/play?#code/PTAEAEDsHsEkFsAOAbAlgY1QFwIKQJ4BcoWATgK4CmAsAFB3rICGAzi6AKIAeTSyloAN51QosaABGIsSFAA9APx1po9NEgsy5dFmikAFAEohK8SQAWqFgDoJoALygATKYC+dd7SA)

This is practically the same case as `implicitAnyLet`

**Comment by Conaclos** [comment]
@fujiyamaorange
Which changes would you like to introduce? It is not clear to me for now...

**Comment by fujiyamaorange** [comment]
I plan to redefine these case as **valid** because it seems a kind of evolving any type according to @bgenia .

```
let someVar1;
someVar1 = '123';
```

**Comment by Conaclos** [comment]
> I plan to redefine this case as valid because it seems a kind of evolving any type

This could make the rule useless?

Instead, I could create a new rule `noEvolvingAny` and I could deprecate `noImplicitAny` (once `noEvolvingAny` is stabilized).
The new rule could report these cases:

```ts
let a; // the current `noImplicitAny`
const b = [];
let c = null;
```

**Comment by fujiyamaorange** [comment]
Oh, fantastic!
Thank you for explaining me about the problem. I understand.

Let me try this!

**Comment by unvalley** [comment]
We have noEvolvingAny lint rule now, so I close this issue.
