### ISSUE TITLE
🐛 using Biome in VSCode then save completely removes lines from the file being saved 

### ISSUE THREAD

**Issue by ghiscoding** [biomejs/biome#1890]
### Extension version

2.1.2

### Biome version

1.5.3

### Operating system

- [X] Windows
- [ ] macOS
- [ ] Linux

### Description

I started using Biome VSCode extension and it works great except in 1 file of my project, I think it might be because of the file length (1800 lines). In some cases when I try to add a comment line before an `if` condition and I save the file, it completely removes the `if` line which totally breaks my code. The alternative I found was to move the comment **after** the `if` instead of **before** but that is not what I wanted and that is totally not expected either. You can replicate this problem by clone 

### Steps to reproduce

You can replicate this problem by cloning my open source repo
1. `git clone https://github.com/ghiscoding/multiple-select-vanilla`
2. `pnpm install` the project
3. set your VSCode `formatOnSaveMode` to `modifications` only
4. open the file `packages/multiple-select-vanilla/src/MultipleSelectInstance.ts#L922-L926`  (ref [line 922](https://github.com/ghiscoding/multiple-select-vanilla/blob/main/packages/multiple-select-vanilla/src/MultipleSelectInstance.ts#L922-L926))
5. swap lines 922 with line 923 and see the problem occurs
  - this issue replicates every single time on my end 

I use this project VSCode settings (see [here](https://github.com/ghiscoding/multiple-select-vanilla/blob/main/.vscode/settings.json))

```json
{
  "editor.defaultFormatter": "biomejs.biome",
  "editor.formatOnSave": true,
  "editor.formatOnPaste": false,
  "typescript.tsdk": "node_modules\\typescript\\lib"
}
```

![Code_NwHhkGAQIN](https://github.com/biomejs/biome-vscode/assets/643976/9d68f4b3-4400-437e-b8c8-af24e40f6af6)

### Expected behavior

it should not remove any lines

### Does this issue occur when using the CLI directly?

No

**Comment by ghiscoding** [comment]
@ematipico I did provide the repro, my project is open source and public, the repro is shown above in the "Steps to Reproduce"

**Comment by ematipico** [comment]
I am sorry, but we require a minimal reproduction, not a repository where things keep moving and changing. A new repository would be great.

**Comment by ghiscoding** [comment]
Well the bug is caused by the VSCode `editor.formatOnSaveMode` set to `modifications` only and is also mentioned in this other opened issue #2260 if that other issue gets resolved then I'm pretty sure it will fix my issue as well. You can keep just the other issue opened if it's more relevant (even though it was opened after mine, the issue is probably the same cause)

**Comment by ghiscoding** [comment]
closing since I don't have time to create a new repro (I still think the provided repo was enough) and the issue #2260 has the same root cause, so let's track issue #2260 instead.
