### ISSUE TITLE
📎 Implement `lint/useJsxKeyInIterable` - `eslint-react/jsx-key`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#1899]
### Description

Implement [jsx-key](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-key.md).

Want to contribute? Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z).

Suggested name: `useJsxKeyInIterable`.

I think we don't need to provide the rule options:
- `checkFragmentShorthand` was added to avoid a breaking change.
  Thus, we don't need this option. We should report  shorthand fragment without the `key` property.
- `warnOnDuplicates`: no sure about that one.

**Comment by vohoanglong0107** [comment]
Thanks for creating the issue @Conaclos. Can I take a stab at this?
