### ISSUE TITLE
📎 Improve `useNamingConvention` options

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#1900]
### Discussed in https://github.com/biomejs/biome/discussions/1725

<div type='discussions-op-text'>

<sup>Originally posted by **anonrig** January 31, 2024</sup>
### Description

Add support for more options in `useNamimgConvention`.

**Comment by ddanielsantos** [comment]
hello! Do you think this is a good issue for someone with little experience in the codebase? I would like to help with it if possible

**Comment by Conaclos** [comment]
> hello! Do you think this is a good issue for someone with little experience in the codebase? I would like to help with it if possible

I have already started toying with an implementation.
However, you can help to shape the options by posting proposals in the related discussion #1725

**Comment by Conaclos** [comment]
I've just published #2770 that adds options to `useNamingConvention`.
