### ISSUE TITLE
📎 `derive(biome_deserialize::Deserializable)`: add support for ignoring unknown fields

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#1901]
### Description

This could help to address #1898.

Currently, `biome_deserialize::Deserializable` doesn't allow unknowns fields.
By default serde allows unknown fields. A user have to add the [`serde(deny_unknown_fields)`](https://serde.rs/container-attrs.html#deny_unknown_fields) to forbid unknown fields.

There are two possible approaches:

1. Keeping our current default and add the struct (container) attribute `deserializable(allow_unknown_fields)` to allow unknown fields.

2. Adopting serde's defaults and support both `serde(deny_unknown_fields)` and `deserializable(deny_unknown_fields)`.

**Comment by Conaclos** [comment]
A third option is to introduce `unknown_fields` attribute that takes a value among `deny`, `warn` and `allow`. `serde(deny_unknown_fields)` could be equivalent to `unknown_fields = deny`. We could default to `unknown_fields = warn`.

@arendjr @ematipico any opinion?

**Comment by ematipico** [comment]
I like your last proposal.

As for the default behaviour, I don't have strong preferences. I would favour the one that makes less changes to our code base.
