### ISSUE TITLE
💅 Incorrect fix for `noUselessFragments`

### ISSUE THREAD

**Issue by BatuhanW** [biomejs/biome#1926]
### Environment information

```bash
> refinejs-repo@0.0.0 biome
> biome rage

CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.19.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.5"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 false
```

### Rule name

noUselessFragments

### Playground link

https://biomejs.dev/playground/?code=LwAvACAARQB4AGEAbQBwAGwAZQAgAGMAbwBkAGUACgAKAGMAbwBuAHMAdAAgAHAAcgBvAHYAaQBkAGUAcgBPAHAAdABpAG8AbgAxACAAPQAgAHsACgAgACAAbgBhAG0AZQA6ACAAJwBHAGkAdABIAHUAYgAnAAoAfQAKAAoAYwBvAG4AcwB0ACAAcAByAG8AdgBpAGQAZQByAE8AcAB0AGkAbwBuADIAIAA9ACAAewAKACAAIABuAGEAbQBlADoAIAAnAEcAbwBvAGcAbABlACcALAAKACAAIABpAGMAbwBuADoAIAA8AEcAbwBvAGcAbABlAEkAYwBvAG4AIAAvAD4ACgB9AAoACgAvAC8AIABIAGUAcgBlACAAdwBlACAAZwBlAHQAIAB1AG4AbgBlAGMAZQBzAHMAYQByAHkAIABmAHIAYQBnAG0AZQBuAHQAIABlAHIAcgBvAHIALgAKAGMAbwBuAHMAdAAgAEIAZQBmAG8AcgBlAEYAaQB4ACAAPQAgACgAKQAgAD0APgAgAHsACgAgACAAcgBlAHQAdQByAG4AIAA8AEIAdQB0AHQAbwBuACAAbABlAGYAdABJAGMAbwBuAD0AewA8AD4AewBwAHIAbwB2AGkAZABlAHIAPwAuAGkAYwBvAG4AfQA8AC8APgB9ACAALwA%2BAAoAfQAKAAoALwAvACAAVABoAGUAbgAgAHIAdQBuAG4AaQBuAGcAIABgAGIAaQBvAG0AZQAgAGwAaQBuAHQAIAAtAC0AYQBwAHAAbAB5AC0AdQBuAHMAYQBmAGUAYAAgAHUAcABkAGEAdABlAHMAIAB0AGgAZQAgAGMAbwBtAHAAbwBuAGUAbgB0ACAAYQBzACAAZgBvAGwAbABvAHcAcwA6AAoAYwBvAG4AcwB0ACAAQQBmAHQAZQByAEYAaQB4ACAAPQAgACgAKQAgAD0APgAgAHsACgAgACAAcgBlAHQAdQByAG4AIAA8AEIAdQB0AHQAbwBuACAAbABlAGYAdABJAGMAbwBuAD0AcAByAG8AdgBpAGQAZQByAD8ALgBpAGMAbwBuACAALwA%2BAAoAfQAKAAoALwAvACAAUwBpAG4AYwBlACAAdABoAGUAIABmAGkAeAAgAHIAZQBtAG8AdgBlAHMAIABiAHIAYQBjAGsAZQB0AHMAIABhAHIAbwB1AG4AZAAgAGkAdAAsACAAYQBuAGQAIABpAHQAJwBzACAAbgBvAHQAIABhAG4AIABlAHgAcAByAGUAcwBzAGkAbwBuACAAYQBuAHkAbQBvAHIAZQAsACAAaQB0ACAAcABhAG4AaQBjAHMAIQAKAC8ALwAgAEIAaQBvAG0AZQAgAGUAbgBjAG8AdQBuAHQAZQByAGUAZAAgAGEAbgAgAHUAbgBlAHgAcABlAGMAdABlAGQAIABlAHIAcgBvAHIACgAKAC8ALwAgAFQAaABpAHMAIABpAHMAIABhACAAYgB1AGcAIABpAG4AIABCAGkAbwBtAGUALAAgAG4AbwB0ACAAYQBuACAAZQByAHIAbwByACAAaQBuACAAeQBvAHUAcgAgAGMAbwBkAGUALAAgAGEAbgBkACAAdwBlACAAdwBvAHUAbABkACAAYQBwAHAAcgBlAGMAaQBhAHQAZQAgAGkAdAAgAGkAZgAgAHkAbwB1ACAAYwBvAHUAbABkACAAcgBlAHAAbwByAHQAIABpAHQAIAB0AG8AIABoAHQAdABwAHMAOgAvAC8AZwBpAHQAaAB1AGIALgBjAG8AbQAvAGIAaQBvAG0AZQBqAHMALwBiAGkAbwBtAGUALwBpAHMAcwB1AGUAcwAvACAAYQBsAG8AbgBnACAAdwBpAHQAaAAgAHQAaABlACAAZgBvAGwAbABvAHcAaQBuAGcAIABpAG4AZgBvAHIAbQBhAHQAaQBvAG4AIAB0AG8AIABoAGUAbABwACAAdQBzACAAZgBpAHgAaQBuAGcAIAB0AGgAZQAgAGkAcwBzAHUAZQA6AAoACgAvAC8AIABTAG8AdQByAGMAZQAgAEwAbwBjAGEAdABpAG8AbgA6ACAALwBVAHMAZQByAHMALwByAHUAbgBuAGUAcgAvAHcAbwByAGsALwBiAGkAbwBtAGUALwBiAGkAbwBtAGUALwBjAHIAYQB0AGUAcwAvAGIAaQBvAG0AZQBfAHIAbwB3AGEAbgAvAHMAcgBjAC8AYQBzAHQALwBtAG8AZAAuAHIAcwA6ADIAMwA4ADoAMQAzAAoALwAvACAAVABoAHIAZQBhAGQAIABOAGEAbQBlADoAIABiAGkAbwBtAGUAOgA6AHcAbwByAGsAZQByAF8AOAAKAC8ALwAgAE0AZQBzAHMAYQBnAGUAOgAgAFQAcgBpAGUAZAAgAHQAbwAgAGMAYQBzAHQAIABuAG8AZABlACAAdwBpAHQAaAAgAGsAaQBuAGQAIABKAFMAXwBFAFgAUABSAEUAUwBTAEkATwBOAF8AUwBUAEEAVABFAE0ARQBOAFQAIABhAHMAIABgACIAYgBpAG8AbQBlAF8AagBzAF8AcwB5AG4AdABhAHgAOgA6AGcAZQBuAGUAcgBhAHQAZQBkADoAOgBuAG8AZABlAHMAOgA6AEEAbgB5AEoAcwBDAGEAbABsAEEAcgBnAHUAbQBlAG4AdAAiAGAAIABiAHUAdAAgAHcAYQBzACAAdQBuAGEAYgBsAGUAIAB0AG8AIABjAGEAcwB0AA%3D%3D

### Expected result

Using fragments here should be considered correct and linter should not warn about it.

```
return <Button leftIcon={<>provider?.icon</>} />
```
### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Hey @BatuhanW , thank you for the report.

The expected result block is meant for **you** to tell **us** what you would expect from the rule. What kind of fix would you expect?

**Comment by BatuhanW** [comment]
> Hey @BatuhanW , thank you for the report.
> 
> The expected result block is meant for **you** to tell **us** what you would expect from the rule. What kind of fix would you expect? No need to show the error twice (the playground is enough), but to show how the correct fix should be.

Hey @ematipico, updated the description ✅

**Comment by ematipico** [comment]
Why would you need to pass a fragment as a prop? Isn't just `provider?.icon` enough?
