### ISSUE TITLE
🐛 `const` declaration w/o init in a TS declaration file trigger a parse error

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#1981]
### Environment information

```block
Playground
```

### What happened?

`const` declaration without initialization in a TypeScript declaration file (`.d.ts`) are no longer allowed: they trigger a parsing error `Const declarations must have an initialized value.`.

[Playground](https://biomejs.dev/playground/?files.decl.d.ts=ZQB4AHAAbwByAHQAIABjAG8AbgBzAHQAIABYADoAIABuAHUAbQBiAGUAcgA%3D)

### Expected result

`const` declaration without initialization should be allowed in TypeScript declaration files

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ah-yu** [comment]
It seems that the parser is functioning properly, this appears to be an issue related to the playground.
