### ISSUE TITLE
🐛 --changed in monorepos throws No such file or directory (os error 2)

### ISSUE THREAD

**Issue by valkum** [biomejs/biome#1996]
### Environment information

```block
CLI:
  Version:                      1.5.3-nightly.4fa841c
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.6.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/4.1.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

If you have a monorepo with a folder named `/typescript` and you run the biome command inside the /typescript folder it will try to access the changed files that are outside of the `/typescript` directory (even with vcsRoot set).
This emits Internal errors
```
yarn run biome check --since origin/main --changed --vcs-root .. --vcs-enabled true --no-errors-on-unmatched .",

PWD: /Users/valkum/git/projects/x/typescript
typescript/scripts/ci-check.sh internalError/io  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ No such file or directory (os error 2)

  ⚠ This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.


Checked 0 files in 710µs. No fixes needed.
```
### Expected result

The paths of the changed files should be compared against the current working directory and updated and filtered before accessed.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by castarco** [comment]
From what I see, this bug also applies as well to the `--staged` feature I proposed ( #2300  ) (I already verified it, it fails because of the same reason).

Is anyone working on this one? I can prepare a fix for this one, as I already familiarised myself with that part of the code base.
