### ISSUE TITLE
`useImportType` breaks class based dependency injection in Nest.JS

### ISSUE THREAD

**Issue by ssilve1989** [biomejs/biome#2003]
### Environment information

```bash
CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.6.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.15.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### Rule name

lint/style/useImportType

### Playground link

https://codesandbox.io/p/devbox/peaceful-bird-glx5h2

### Expected result

It should not apply `import type` to class types where they are used for dependency injection. The generated TS when using import type on the class import results in 
```javascript
exports.AppController = AppController = __decorate([
    (0, common_1.Controller)(),
    __metadata("design:paramtypes", [Function])
], AppController);
```

which is lacking the necessary metadata information, whereas without `import type` it generates 
```javascript
exports.AppController = AppController = __decorate([
    (0, common_1.Controller)(),
    __metadata("design:paramtypes", [app_service_1.AppService])
], AppController);
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
This could be the same issue as #2038. I am waiting more details to decide if they are instances of the sane issue.

**Comment by joshmeads** [comment]
+1 on this. Was going mad trying to find out why my app suddenly broke. I **LOVE** this rule, it's something I've been wanting it for years but I was suddenly thrown into a NestJS project and it took me by surprise.

Would it be possible to have an option to allow classes?

As there is no option in Biome (that I can see) to disable autofix for a single rule it makes it rather difficult to work with.

**Comment by mallowigi** [comment]
Just started giving a shot to Biome and immediately noticed this. This makes it a no-go for Biome as far as I'm standing here.

**Comment by Conaclos** [comment]
`useImportType` is largely inspired from TypeScript Eslint's [consistent-type-imports](https://typescript-eslint.io/rules/consistent-type-imports/). Until their last release, TS ESlint tried to handle this specific case. However, they changed their mind, and the last version of [TS ESlint now rejects this](https://typescript-eslint.io/blog/changes-to-consistent-type-imports-with-decorators/) like Biome's `useImportType`. The main reason are:

- conflicts with TypeScript's `isolatedModules`,
- TS decorators are based on a legacy and retired proposal and are on the verge of deprecation.

The only exception they have introduced is to completely disable the rule in a file containing at least one decorator if the `experimentalDecorators` and `emitDecoratorMetadata` options are enabled.

Based on this new knowledge, I think it would be a mistake to waste time on this. I recommend that users simply disable the rule in projects that use frameworks that rely on an outdated and never-standardised syntax.

**Comment by a-c-m** [comment]
Ran into this as well, assuming we can just override this rule?
