### ISSUE TITLE
💅 `useImportType` fixes `import React from 'react'` into `import type React from 'react'`

### ISSUE THREAD

**Issue by ipanasenko** [biomejs/biome#2004]
### Environment information

```bash
CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.19.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  Recommended:                  true
  All:                          false
  Rules:                        a11y/noSvgWithoutTitle = "off"
                                a11y/useKeyWithClickEvents = "off"
                                a11y/useKeyWithMouseEvents = "off"
                                a11y/useValidAnchor = "off"
                                complexity/noUselessLoneBlockStatements = "error"
                                correctness/noInvalidUseBeforeDeclaration = "off"
                                correctness/noNewSymbol = "error"
                                correctness/noUnusedPrivateClassMembers = "error"
                                correctness/noUnusedVariables = "error"
                                correctness/useExhaustiveDependencies = "off"
                                correctness/useHookAtTopLevel = "error"
                                nursery/noExportsInTest = "error"
                                nursery/noSemicolonInJsx = "error"
                                nursery/noUselessTernary = "error"
                                performance/noDelete = "off"
                                style/noNegationElse = "error"
                                style/noNonNullAssertion = "off"
                                style/noRestrictedGlobals = "error"
                                style/noShoutyConstants = "error"
                                style/noUnusedTemplateLiteral = "off"
                                style/useBlockStatements = "error"
                                style/useCollapsedElseIf = "error"
                                style/useForOf = "error"
                                style/useNodejsImportProtocol = "error"
                                style/useNumberNamespace = "error"
                                style/useShorthandAssign = "error"
                                style/useShorthandFunctionType = "error"
                                style/useSingleCaseStatement = "error"
                                suspicious/noConsoleLog = "error"
                                suspicious/noRedeclare = "off"

Workspace:
  Open Documents:               0
```

### Rule name

lint/style/useImportType

### Playground link

not possible to reproduce in playground

### Expected result

Don't touch this import

<img width="484" alt="image" src="https://github.com/biomejs/biome/assets/576152/d3800d5e-0c16-4021-88ad-12a6e198186b">

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ipanasenko** [comment]
It's not used explicitly, there's a component in that file, JSX is returned.
I will try to come up with minimum reproduction example

**Comment by Conaclos** [comment]
New versions of React no longer require/recommend to import React explicitly. We decided to follow that and to report non-explicit use of React.

**Comment by ipanasenko** [comment]
I can't update react version, I'm stuck with react16 for some time.

**Comment by ematipico** [comment]
> I can't update react version, I'm stuck with react16 for some time.

I think you just need to update the Babel compiler, but I might be wrong

**Comment by ematipico** [comment]
> New versions of React no longer require/recommend to import React explicitly. We decided to follow that and to report non-explicit use of React.

Now that we're able to retrieve dependencies, we might be able to make the rule smarter.

Or just allow list React for the time being.

**Comment by ipanasenko** [comment]
Don't know about Babel, I have a TS error

<img width="719" alt="image" src="https://github.com/biomejs/biome/assets/576152/3be97266-a6f1-4199-b66a-ba91a00050bf">

**Comment by ematipico** [comment]
Ah shoot, TypeScript is very old fashioned and doesn't allow that. And doesn't even provide an option for that... Welcome to the tooling world! 🌎

**Comment by Sec-ant** [comment]
> Ah shoot, TypeScript is very old fashioned and doesn't allow that. And doesn't even provide an option for that... Welcome to the tooling world! 🌎

emmm, I believe TypeScript supports this. There's an option in `tsconfig.json` that indicates how JSX is treated during transpiling: https://www.typescriptlang.org/tsconfig#jsx

If the value is set to `react-jsx` or `react-jsxdev`, the `React` can be omitted in `.tsx` files and shouldn't report any type errors.

So if I understand right, we need to parse the babel config for `.jsx` files and the `tsconfig.json` for `.tsx` files to decide whether to remove the explicit `React` import accordingly.

**Comment by ipanasenko** [comment]
`react-jsx` is only for React 17+, if I understood it right, we have React 16.

Also, keep in mind that tsconfig can extend  another tsconfig, which can extend another tsconfig (we have it 😁)

**Comment by Sec-ant** [comment]
But I don't think we can ever make this rule smart enough.

For one thing, parsing `tsconfig`s or babel configs and matching files correctly would be a lot of work. Because we can have multiple configs in different formats and extending each other just like what @ipanasenko said.

And for another, there'll be always new tools which may use other forms of configs or inexplicitly enforce different strategies. And apart from `react`, many other libraries support JSX too.

My advice is providing an option for users to let biome ignore certain imports. I'm not sure though if this should be added under `useImportType` or in a higher level.

**Comment by Conaclos** [comment]
@ipanasenk
How many diagnostics of this kind do you have?

**Comment by Netail** [comment]
> Don't know about Babel, I have a TS error
> 
> <img alt="image" width="719" src="https://private-user-images.githubusercontent.com/576152/311427783-3be97266-a6f1-4199-b66a-ba91a00050bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NTM5MDAsIm5iZiI6MTcxMjY1MzYwMCwicGF0aCI6Ii81NzYxNTIvMzExNDI3NzgzLTNiZTk3MjY2LWE2ZjEtNDE5OS1iNjZhLWJhOTFhMDAwNTBiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQwOTA2NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNDhmYzNlZjg2ZTFhOTExNjU3ZWY2ZTYwNjY2NjkxYTNjMjdlMDc5M2Q0ZmY1Y2VkYWNhMGY0OWMwYTBjMmE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0AwlrUcMa22n6zrLaFaDyfArP92dlOguOyUSYslesfo">

We are currently facing the same issue

**Comment by ematipico** [comment]
This should be easy to fix, and we should allowlist React for the time being

**Comment by ipanasenko** [comment]
Yeah, `ignoreReact` option would be cool, similar to this: https://github.com/biomejs/biome/pull/2306

**Comment by Conaclos** [comment]
Could someone provide a code sample?

**Comment by ipanasenko** [comment]
Basically, any React code :)
```tsx
import React from 'react';

const MyComponent = () => {
  return <div />;
};
```

This should stay intact. Currently it's transformed to `import type React from 'react';`

**Comment by Conaclos** [comment]
> Basically, any React code :)
> 
> ```tsx
> import React from 'react';
> 
> const MyComponent = () => {
>   return <div />;
> };
> ```
> 
> This should stay intact. Currently it's transformed to `import type React from 'react';`

It is not. `useImportType` ignores unused imports.

**Comment by ematipico** [comment]
@arendjr 

Seems like a good place [for this proposal](https://github.com/biomejs/biome/discussions/689), `project` section

**Comment by arendjr** [comment]
@ematipico Yeah, that's where I also suggested we may want to have shared configuration options between linter rules. This is an example where that would be useful, I think. Though we could fit it into today's configuration by just adding underneight the `javascript` options, I suppose. It'd be less clean, but would get the job done until we revamp things properly.

**Comment by Netail** [comment]
> I'm thinking instead of rule-specific `ignoreReact` options, we should have a global config option for the React runtime in use. It would basically correspond to `react` vs. `react-jsx` in TypeScript's [`jsx` configuration](https://www.typescriptlang.org/tsconfig#jsx).
> 
> I'm thinking something like:
> 
> ```rust
> enum ReactRuntime {
>     /// Indicates a modern or native React environment, where the `React` import is not required.
>     ///
>     /// Corresponds to `react-jsx`, `react-jsxdev`, `preserve`, `react-native` values for the `jsx` option
>     /// in TypeScript's `tsconfig.json`.
>     Modern,
> 
>     /// Indicates a legacy React environment that requires the `React` import.
>     ///
>     /// Corresponds to `react` value for the `jsx` option in TypeScript's `tsconfig.json`.
>     Legacy,
> }
> ```
> 
> When we support more project-level analysis, such an option could even have a default `Auto` value that would allow us to auto-detect the value for projects where we can find a `tsconfig.json`.

I feel like Modern & Legacy are not the correct terms.

`react-jsx` & `react-jsxdev` are the ones from React 17, while `react`, `preserve` and `react-native` are the more modern ones

**Comment by arendjr** [comment]
> react-jsx & react-jsxdev are the ones from React 17, while react, preserve and react-native are the more modern ones

Thanks! I might’ve mixed these up.

Afterwards I thought maybe it’s better to call this `JsxRuntime`, instead of `ReactRuntime`, since other frameworks use it too. Then we can call the variant that requires `React` globals to be `ReactLegacy` instead.

**Comment by Netail** [comment]
> > react-jsx & react-jsxdev are the ones from React 17, while react, preserve and react-native are the more modern ones
> 
> Thanks! ~I might’ve mixed these up.~ On a second look, it does look like `react-jsx` and `react-jsxdev` are indeed the modern ones: https://www.typescriptlang.org/tsconfig#jsx
> 
> Afterwards I thought maybe it’s better to call this `JsxRuntime`, instead of `ReactRuntime`, since other frameworks use it too. Then we can call the variant that requires `React` globals to be `ReactLegacy` instead.

Oh mhmm.

Calling it `React` & `ReactLegacy` still doesn't feel right or something. It's still a support options and no plans to phase this out, it just produces a different output syntax

**Comment by arendjr** [comment]
> Calling it React & ReactLegacy still doesn't feel right or something.

I haven't yet decided what to call the main variant. It could still be `Modern`, but I'm slightly leaning towards `Transparent` now. So it would be:

```rs
enum JsxRuntime {
    /// Indicates a modern or native JSX environment, that doesn't require special handling by Biome.
    Transparent,

    /// Indicates a legacy React environment that requires the `React` import.
    ///
    /// Corresponds to the `react` value for the `jsx` option in TypeScript's `tsconfig.json`.
    ReactLegacy,
}
```

The advantage of this enum is also that Biome intends to work towards implementing transformations as well, including a JSX compiler: https://biomejs.dev/blog/roadmap-2024/#transformations

So when we get there, we can also add more variants that allow people to choose which kind of transformation to use exactly, while `Transparent` will continue to mean that Biome shouldn't do any transformation.

> It's still a support options and no plans to phase this out, it just produces a different output syntax

I'm not sure I fully understand this concern. Just because we call it `ReactLegacy`, doesn't mean people cannot use it. It's still supported as you say, but I think even the React devs consider the transformation using `React.createElement()` to be their legacy approach.

**Comment by ematipico** [comment]
What about `ReactClassic`? The word classic messages something old, but on the other hand it doesn't have the same baggage of the world "legacy".

**Comment by Netail** [comment]
> What about `ReactClassic`? The word classic messages something old, but on the other hand it doesn't have the same baggage of the world "legacy".

Sounds better indeed, the word "Legacy" might give people the wrong impression (kind of deprecated or something)

**Comment by arendjr** [comment]
Good suggestion :+1: I see Babel even uses the term classic as well: https://babeljs.io/docs/babel-plugin-transform-react-jsx#react-classic-runtime

**Comment by arendjr** [comment]
I have an initial PR to move the setting: https://github.com/biomejs/biome/pull/2397

When that's merged, I can follow up with a PR for this rule.

**Comment by Netail** [comment]
Might wanna add to this that people could use multiple in the same repo with monorepositories. E.g. use frontends with "preserve" and packages with "react". Not sure if this will be an issue?

**Comment by arendjr** [comment]
> Might wanna add to this that people could use multiple in the same repo with monorepositories. E.g. use frontends with "preserve" and packages with "react". Not sure if this will be an issue?

You can use the `overrides` settings for that, similar to how other settings can be overridden in specific folders or files.
