### ISSUE TITLE
💅 noUndeclaredDependencies in monorepo

### ISSUE THREAD

**Issue by AkisArou** [biomejs/biome#2010]
### Environment information

```bash
CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.3"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Linter:
  Recommended:                  true
  All:                          false
  Rules:                        complexity/noForEach = "off"
                                suspicious/noAssignInExpressions = "off"

Workspace:
  Open Documents:               0
```

### Rule name

noUndeclaredDependencies

### Playground link

https://codesandbox.io/p/devbox/jovial-farrell-7xjyss?workspaceId=78ddf2e1-5da3-4ea2-9688-d44c7d4afd84&embed=1&file=%2Fpackage.json

### Expected result

It should respect the closest package.json in a nested workspace. (I provide the playground link, but linting does not work)

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Can you provide more information inside the expected results?

Given your example, what would you expect?

**Comment by EvHaus** [comment]
The expectation is that the rule would not throw errors if you're using a monorepo package. For example, I have a monorepo like this:

```
biome.json
packages/
  a/
    package.json
    index.ts
  b/
    package.json
```

The file in `packages/a/package.json` has a dependency on `b` like this: `"b": "workspace:../b"`. Then in `packages/a/index.ts` I import `import something from 'b'` and biome complains that this is an `noUndeclaredDependencies`.

The expectation is that Biome would detect `workspace:` dependencies and not throw an error in this case.

**Comment by ematipico** [comment]
I suppose we just to tell users to not use this rule in monorepos for the time being.

We're far from supporting monorepos

**Comment by lxsmnsyc** [comment]
Here's an example of this false warning

<img width="773" alt="Screenshot 2024-03-10 at 3 23 57 PM" src="https://github.com/biomejs/biome/assets/4783372/68d06f8e-a345-4e35-9a55-a242448113cb">

<img width="240" alt="Screenshot 2024-03-10 at 3 25 04 PM" src="https://github.com/biomejs/biome/assets/4783372/adb7c6ee-05b0-4b82-b1c6-dfda13ffd806">

Honestly I thought the rule is just scanning for the `package.json` but it seems like it's also trying to resolve it.

**Comment by Sec-ant** [comment]
> Honestly I thought the rule is just scanning for the `package.json` but it seems like it's also trying to resolve it.

No it doesn't resolve those packages. It just check the keys of `dependencies` and `devDependencies` as of now. The subpath lint error is a bug which should be fixed in #2035.

**Comment by AkisArou** [comment]
Yes, it just checks the keys of dependencies and devDependencies in workspace's package.json and root package.json!

**Comment by ematipico** [comment]
I am going to close this for now. Monorepos are tricky and I don't think the rule, for now, has the capabilities for that.
