### ISSUE TITLE
💅 `useJsxKeyInIterable`: Not working when component starts on the next line

### ISSUE THREAD

**Issue by kevinwolfcr** [biomejs/biome#2011]
### Environment information

```bash
CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "bun/1.0.30"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Linter:
  Recommended:                  false
  All:                          true
  Rules:                        nursery/all = true
                                nursery/useSortedClasses = {"level":"error","options":{"attributes":["class","className","className","classList"],"functions":["clsx","cva","tw","cn"]}}
                                style/all = true
                                style/noImplicitBoolean = "off"
                                style/useBlockStatements = "off"
                                style/useNamingConvention = "off"

Workspace:
  Open Documents:               0
```

### Rule name

useJsxKeyInIterable

### Playground link

https://biomejs.dev/playground/?lintRules=all&code=YwBvAG4AcwB0ACAAZgByAHUAaQB0AHMAIAA9ACAAWwAiAEEAcABwAGwAZQAiACwAIAAiAEIAYQBuAGEAbgBhACIALAAgACIATwByAGEAbgBnAGUAIgBdADsACgAKAGUAeABwAG8AcgB0ACAAZgB1AG4AYwB0AGkAbwBuACAARgBvAG8AZAAoACkAIAB7AAoAIAAgAHIAZQB0AHUAcgBuACAAKAAKACAAIAAgACAAPABkAGkAdgA%2BAAoAIAAgACAAIAAgACAAPABoADEAPgBGAG8AbwBkADwALwBoADEAPgAKACAAIAAgACAAIAAgADwAdQBsAD4ACgAgACAAIAAgACAAIAAgACAAewBmAHIAdQBpAHQAcwAuAG0AYQBwACgAKABmAHIAdQBpAHQAKQAgAD0APgAgACgACgAgACAAIAAgACAAIAAgACAAIAAgADwAbABpACAAawBlAHkAPQB7AGYAcgB1AGkAdAB9AD4AewBmAHIAdQBpAHQAfQA8AC8AbABpAD4ACgAgACAAIAAgACAAIAAgACAAKQApAH0ACgAgACAAIAAgACAAIAA8AC8AdQBsAD4ACgAgACAAIAAgADwALwBkAGkAdgA%2BAAoAIAAgACkAOwAKAH0ACgA%3D

### Expected result

On the attached playground, the following reports `Cannot determine whether this child has the required key prop.`. However, if I place the JSX on the same line as the map, it doesn't report.

This reports:

```tsx
const fruits = ["Apple", "Banana", "Orange"];

export function Food() {
  return (
    <div>
      <h1>Food</h1>
      <ul>
        {fruits.map((fruit) => (
          <li key={fruit}>{fruit}</li>
        ))}
      </ul>
    </div>
  );
}
```

This doesn't:

```tsx
const fruits = ["Apple", "Banana", "Orange"];

export function Food() {
  return (
    <div>
      <h1>Food</h1>
      <ul>
        {fruits.map((fruit) => <li key={fruit}>{fruit}</li>)}
      </ul>
    </div>
  );
}
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by hilja** [comment]
Can confirm. v1.6.0.

**Comment by Sec-ant** [comment]
I have been learning Rust recently and want to get my feet wet. Can I give this a try? @ematipico

**Comment by Conaclos** [comment]
@Sec-ant All yours :)

**Comment by Sec-ant** [comment]
> @Sec-ant This seems to be still happening. Is it meant to work when a component spans multiple lines? All the examples are one-liners.

Would you mind providing the problematic code snippet?

**Comment by hilja** [comment]
@Sec-ant Managed to narrow it down. It breaks if you have a return inside the map:

```tsx
const testArr = [
  { id: 1, name: 'test' },
  { id: 2, name: 'test2' },
  { id: 3, name: 'test3' },
  { id: 4, name: 'test4' },
]

export function TestFoo() {
  return (
    <div>
      <h1>Hello from Foo</h1>
      <ul>
        {testArr.map(item => {
          const { id, name } = item

          // Breaks useJsxKeyInIterable
          return (
            <li key={id}>
              <p>{name}</p>
            </li>
          )
        })}
      </ul>
    </div>
  )
}
```

**Comment by Sec-ant** [comment]
@hilja It should be fixed in #2076.

**Comment by sahithyandev** [comment]
I am on biome v1.6.3, and here is a failing example.

```tsx
const List = ({ items }: { items: Array<string> }) => {
  return (
    <div>
      {items.map((item, i) => {
        // Errors
        return (
          <span key={item}>
            {i} {item}
          </span>
        );
      })}
    </div>
  );
};

// No errors
const List2 = ({ items }: { items: Array<string> }) => {
  return (
    <div>
      {items.map((item, i) => (
        <span key={item}>
          {i} {item}
        </span>
      ))}
    </div>
  );
};
```

**Comment by Sec-ant** [comment]
@sahithyandev I cannot reproduce this in v1.6.3, nor [in the playground](https://biomejs.dev/playground/?lintRules=all&code=YwBvAG4AcwB0ACAATABpAHMAdAAgAD0AIAAoAHsAIABpAHQAZQBtAHMAIAB9ADoAIAB7ACAAaQB0AGUAbQBzADoAIABBAHIAcgBhAHkAPABzAHQAcgBpAG4AZwA%2BACAAfQApACAAPQA%2BACAAewAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAZABpAHYAPgAKACAAIAAgACAAIAAgAHsAaQB0AGUAbQBzAC4AbQBhAHAAKAAoAGkAdABlAG0ALAAgAGkAKQAgAD0APgAgAHsACgAgACAAIAAgACAAIAAgACAALwAvACAARQByAHIAbwByAHMACgAgACAAIAAgACAAIAAgACAAcgBlAHQAdQByAG4AIAAoAAoAIAAgACAAIAAgACAAIAAgACAAIAA8AHMAcABhAG4AIABrAGUAeQA9AHsAaQB0AGUAbQB9AD4ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB7AGkAfQAgAHsAaQB0AGUAbQB9AAoAIAAgACAAIAAgACAAIAAgACAAIAA8AC8AcwBwAGEAbgA%2BAAoAIAAgACAAIAAgACAAIAAgACkAOwAKACAAIAAgACAAIAAgAH0AKQB9AAoAIAAgACAAIAA8AC8AZABpAHYAPgAKACAAIAApADsACgB9ADsACgAKAC8ALwAgAE4AbwAgAGUAcgByAG8AcgBzAAoAYwBvAG4AcwB0ACAATABpAHMAdAAyACAAPQAgACgAewAgAGkAdABlAG0AcwAgAH0AOgAgAHsAIABpAHQAZQBtAHMAOgAgAEEAcgByAGEAeQA8AHMAdAByAGkAbgBnAD4AIAB9ACkAIAA9AD4AIAB7AAoAIAAgAHIAZQB0AHUAcgBuACAAKAAKACAAIAAgACAAPABkAGkAdgA%2BAAoAIAAgACAAIAAgACAAewBpAHQAZQBtAHMALgBtAGEAcAAoACgAaQB0AGUAbQAsACAAaQApACAAPQA%2BACAAKAAKACAAIAAgACAAIAAgACAAIAA8AHMAcABhAG4AIABrAGUAeQA9AHsAaQB0AGUAbQB9AD4ACgAgACAAIAAgACAAIAAgACAAIAAgAHsAaQB9ACAAewBpAHQAZQBtAH0ACgAgACAAIAAgACAAIAAgACAAPAAvAHMAcABhAG4APgAKACAAIAAgACAAIAAgACkAKQB9AAoAIAAgACAAIAA8AC8AZABpAHYAPgAKACAAIAApADsACgB9ADsA). Are you sure you're using the latest version?

![image](https://github.com/biomejs/biome/assets/10386119/233b02f6-4295-4aa6-ae6d-2005bb0d1e83)

**Comment by sahithyandev** [comment]
My bad. Must have been caused because biome's old version was running.

**Comment by scallaway** [comment]
Apologies for opening a closed ticket, but I feel this is still relevant as I've uncovered another case where Biome is unable to see that a `key` prop is present.

Please take a look at [this playground](https://biomejs.dev/playground/?lintRules=all&code=YwBvAG4AcwB0ACAATABpAHMAdAAgAD0AIAAoAHsAIABpAHQAZQBtAHMAIAB9ADoAIAB7ACAAaQB0AGUAbQBzADoAIABBAHIAcgBhAHkAPABzAHQAcgBpAG4AZwAgAHwAIABuAHUAbABsAD4AIAB9ACkAIAA9AD4AIAB7AAoAIAAgAHIAZQB0AHUAcgBuACAAKAAKACAAIAAgACAAPABkAGkAdgA%2BAAoAIAAgACAAIAAgACAAewBpAHQAZQBtAHMALgBtAGEAcAAoACgAaQB0AGUAbQAsACAAaQApACAAPQA%2BACAACgAgACAAIAAgACAAIAAgACAAaQB0AGUAbQAgACEAPQA9ACAAbgB1AGwAbAAgACYAJgAgACgACgAgACAAIAAgACAAIAAgACAAIAAgADwAcwBwAGEAbgAgAGsAZQB5AD0AewBpAHQAZQBtAH0APgAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHsAaQB9ACAAewBpAHQAZQBtAH0ACgAgACAAIAAgACAAIAAgACAAIAAgADwALwBzAHAAYQBuAD4ACgAgACAAIAAgACAAIAAgACAAKQAKACAAIAAgACAAIAAgACkAfQAKACAAIAAgACAAPAAvAGQAaQB2AD4ACgAgACAAKQA7AAoAfQA7AAoACgBjAG8AbgBzAHQAIABMAGkAcwB0ADIAIAA9ACAAKAB7ACAAaQB0AGUAbQBzACAAfQA6ACAAewAgAGkAdABlAG0AcwA6ACAAQQByAHIAYQB5ADwAcwB0AHIAaQBuAGcAIAB8ACAAbgB1AGwAbAA%2BACAAfQApACAAPQA%2BACAAewAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAZABpAHYAPgAKACAAIAAgACAAIAAgAHsAaQB0AGUAbQBzAC4AbQBhAHAAKAAoAGkAdABlAG0ALAAgAGkAKQAgAD0APgAgAAoAIAAgACAAIAAgACAAIAAgAGkAdABlAG0AIAAhAD0APQAgAG4AdQBsAGwAIAA%2FACAAKAAKACAAIAAgACAAIAAgACAAIAAgACAAPABzAHAAYQBuACAAawBlAHkAPQB7AGkAdABlAG0AfQA%2BAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAewBpAH0AIAB7AGkAdABlAG0AfQAKACAAIAAgACAAIAAgACAAIAAgACAAPAAvAHMAcABhAG4APgAKACAAIAAgACAAIAAgACAAIAApACAAOgAgAG4AdQBsAGwACgAgACAAIAAgACAAIAApAH0ACgAgACAAIAAgADwALwBkAGkAdgA%2BAAoAIAAgACkAOwAKAH0AOwA%3D)

The basic idea behind it is that if you have a ternary statement within a `.map()` call where one branch outputs JSX, even if you supply a `key` prop Biome can't see that.

**Comment by Sec-ant** [comment]
@scallaway I don't think they're the same bug. Please check issues #2468 and #2590, and the PR #2667.

**Comment by scallaway** [comment]
Ah yep sorry!
