### ISSUE TITLE
🐛 biome.json - linters.globals - Property globals is not allowed.

### ISSUE THREAD

**Issue by morriq** [biomejs/biome#2031]
### Environment information

```block
CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.11.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

Documentation says to use linter.globals: Astro for astro projects - https://biomejs.dev/internals/language-support/#html-super-languages-support

<img width="725" alt="Screenshot 2024-03-10 at 11 31 48" src="https://github.com/biomejs/biome/assets/2962338/54c2e3e2-4c60-4747-8c01-92fefaebef68">

When I did it I have:
<img width="577" alt="Screenshot 2024-03-10 at 11 31 59" src="https://github.com/biomejs/biome/assets/2962338/92a9ea26-44a7-4081-89cd-2c04efd957d4">

And can't use biome 

<img width="759" alt="Screenshot 2024-03-10 at 11 32 44" src="https://github.com/biomejs/biome/assets/2962338/7ae6bb48-e2c0-4b6c-b509-bfcc16eca28e">

### Expected result

linter.globals work or documentation says truth

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
My bad, I will update fix the documentation. You should use this configuration instead https://biomejs.dev/reference/configuration/#javascriptglobals
