### ISSUE TITLE
📝 Inconsistent print behavior of nested `align`s with Prettier

### ISSUE THREAD

**Issue by Sec-ant** [biomejs/biome#2037]
### Environment information

```bash
CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.6.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Formatter:
  Format with errors:           false
  Indent style:                 Space
  Indent size:                  0
  Indent width:                 8
  Line ending:                  Lf
  Line width:                   80
  Attribute position:           Auto
  Ignore:                       []
  Include:                      []

JavaScript Formatter:
  Enabled:                      true
  JSX quote style:              Double
  Quote properties:             AsNeeded
  Trailing comma:               All
  Semicolons:                   Always
  Arrow parentheses:            Always
  Bracket spacing:              true
  Bracket same line:            false
  Quote style:                  Double
  Indent style:                 unset
  Indent size:                  unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           Auto

JSON Formatter:
  Enabled:                      true
  Indent style:                 unset
  Indent width:                 unset
  Indent size:                  unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
  "formatter": {
    "enabled": true,
    "indentStyle": "space",
    "indentWidth": 8
  }
}
```

### Playground link

https://biomejs.dev/playground/?indentStyle=space&indentWidth=8&code=YQAKACAAIAAgACAAPwAgAC8ALwAgAHMAbwBtAGUAdABoAGkAbgBnACAAbwB1AHQAZQByAAoAIAAgACAAIAAgACAAeAAKACAAIAAgACAAOgAgAC8ALwAgAGUAbABzAGUAIABvAHUAdABlAHIACgAgACAAIAAgACAAIABiAAoAIAAgACAAIAAgACAAPwAgAC8ALwAgAHMAbwBtAGUAdABoAGkAbgBnACAAaQBuAG4AZQByAAoAIAAgACAAIAAgACAAIAAgAHkACgAgACAAIAAgACAAIAA6ACAALwAvACAAZQBsAHMAZQAgAGkAbgBuAGUAcgAKACAAIAAgACAAIAAgACAAIAB6ADsACgA%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
That's weird, the IR seems to be the same

**Comment by Sec-ant** [comment]
> That's weird, the IR seems to be the same

Yes, that's why I think the problem lies in the print behavior. I think we may handle `indent`, `align` and `dedent` in a different way, compared with Prettier. And this piece of comment seems to show that this is an awared issue?

https://github.com/biomejs/biome/blob/5bc24f141449f75f405acc072e463348bbc3b4df/crates/biome_js_formatter/src/utils/conditional.rs#L129-L133

**Comment by Sec-ant** [comment]
I also noticed there're some code snippets that can make Prettier print *uglier* result. So I don't know if we still want to keep this kind of consistency with Prettier.

For example, you can check code like this [in the playground](https://biomejs.dev/playground/?indentStyle=space&indentWidth=8&code=YQAgAC8ALwAgAHQAZQBzAHQACgAgACAAIAAgAD8AIAAvAC8AIABuAGUAcwB0AGUAZAAgAHQAZQBzAHQAIABpAG4AIABjAG8AbgBzAGUAcQB1AGUAbgBjAGUACgAgACAAIAAgACAAIABiAAoAIAAgACAAIAAgACAAIAAgAD8AIAAvAC8AIABuAGUAcwB0AGUAZAAgAGMAbwBuAHMAZQBxAHUAZQBuAGMAZQAgAGkAbgAgAGMAbwBuAHMAZQBxAHUAZQBuAGMAZQAKACAAIAAgACAAIAAgACAAIAAgACAAYwAKACAAIAAgACAAIAAgACAAIAA6ACAALwAvACAAbgBlAHMAdABlAGQAIABhAGwAdABlAHIAbgBhAHQAZQAgAGkAbgAgAGMAbwBuAHMAZQBxAHUAZQBuAGMAZQAKACAAIAAgACAAIAAgACAAIAAgACAAZAAKACAAIAAgACAAOgAgAC8ALwAgAG4AZQBzAHQAZQBkACAAdABlAHMAdAAgAGkAbgAgAGEAbAB0AGUAcgBuAGEAdABlAAoAIAAgACAAIAAgACAAZQAKACAAIAAgACAAIAAgACAAIAA%2FACAALwAvACAAbgBlAHMAdABlAGQAIABjAG8AbgBzAGUAcQB1AGUAbgBjAGUAIABpAG4AIABhAGwAdABlAHIAbgBhAHQAZQAKACAAIAAgACAAIAAgACAAIAAgACAAZgAKACAAIAAgACAAIAAgACAAIAA6ACAALwAvACAAbgBlAHMAdABlAGQAIABhAGwAdABlAHIAbgBhAHQAZQAgAGkAbgAgAGEAbAB0AGUAcgBuAGEAdABlAAoAIAAgACAAIAAgACAAIAAgACAAIABnADsA):

```ts
a // test
    ? // nested test in consequence
      b
        ? // nested consequence in consequence
          c
        : // nested alternate in consequence
          d
    : // nested test in alternate
      e
        ? // nested consequence in alternate
          f
        : // nested alternate in alternate
          g;
```

This kind of issues usually happen when we set the `indent-style` to `spaces`.

**Comment by mdm317** [comment]
I think this problem occur when align has align as its parent.
> https://github.com/biomejs/biome/blob/bdc090be36a3daef194fb885e23baf7710af9bbd/crates/biome_formatter/src/printer/mod.rs#L843-L847

I think we shoud add the count value to align instead of incrementing level when another align already calculated

> https://github.com/biomejs/biome/blob/bdc090be36a3daef194fb885e23baf7710af9bbd/crates/biome_formatter/src/printer/mod.rs#L826-L831

When encountering a 'dedent' whose closest parent is 'align' we reduce the indention in that case I think we should subtract 2 from the align value instead of setting the align value to 0.

Can I give it a try if no one else has started working on it yet?

**Comment by Sec-ant** [comment]
> I think we should subtract 2 from the align value

I don't know about this but why 2 instead of another value? Adding the count value to align seems to lose some information.

**Comment by ematipico** [comment]
@mdm317 I assigned the task to you

> I don't know about this but why 2 instead of another value?

Most notably because we always pass `2` when we use the `align` function. But yeah, we should dedent based on the previous value

**Comment by mdm317** [comment]
I thought of two methods.
1. Store the alignment values in a vector to detect previous value
2. Assume that the dedent following align is always 2.

I would appreciate it if you could let me know your thoughts.

**Comment by ematipico** [comment]
I like it too!
