### ISSUE TITLE
🐛 useExhaustiveDependencies rule should handle preact

### ISSUE THREAD

**Issue by ssssota** [biomejs/biome#2043]
### Environment information

```block
❯ pnpm exec biome rage
CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v18.17.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.15.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

No diagnostics report like importing from `react`.

https://github.com/biomejs/biome/discussions/3#discussioncomment-8734988

```js
import {useEffect} from 'preact/hooks';
// import {useEffect} from 'react';
function Component() {
  let a = 0;
  useEffect(() => {
    console.log(a);
  }, []);
  return null;
}
```

[Playground](https://biomejs.dev/playground/?code=aQBtAHAAbwByAHQAIAB7AHUAcwBlAEUAZgBmAGUAYwB0AH0AIABmAHIAbwBtACAAJwBwAHIAZQBhAGMAdAAvAGgAbwBvAGsAcwAnADsACgAvAC8AIABpAG0AcABvAHIAdAAgAHsAdQBzAGUARQBmAGYAZQBjAHQAfQAgAGYAcgBvAG0AIAAnAHIAZQBhAGMAdAAnADsACgBmAHUAbgBjAHQAaQBvAG4AIABDAG8AbQBwAG8AbgBlAG4AdAAoACkAIAB7AAoAIAAgAGwAZQB0ACAAYQAgAD0AIAAwADsACgAgACAAdQBzAGUARQBmAGYAZQBjAHQAKAAoACkAIAA9AD4AIAB7AAoAIAAgACAAIABjAG8AbgBzAG8AbABlAC4AbABvAGcAKABhACkAOwAKACAAIAB9ACwAIABbAF0AKQA7AAoAIAAgAHIAZQB0AHUAcgBuACAAbgB1AGwAbAA7AAoAfQA%3D)

### Expected result

Diagnostics report from useExhaustiveDependencies.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by arendjr** [comment]
Thanks for reporting! As a workaround, you should be able to configure the hooks in the rule's configuration in the meantime.

**Comment by ematipico** [comment]
I am going to change the labels on this one. 

I deem this as an enhancement. We have built those rules with React in mind, and I'm not sure of preact hooks work the same.

Even so, our logic didn't take preact in mind.

**Comment by arendjr** [comment]
Implemented here: https://github.com/biomejs/biome/pull/2105

I think this covers the places where React/Preact compatibility is relevant for us, but please let me know if I missed something.
