### ISSUE TITLE
🐛 Copy+paste on a Vue file causes massive issues

### ISSUE THREAD

**Issue by milesj** [biomejs/biome#2054]
### Environment information

```block
CLI:
  Version:                      1.6.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.10.5"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

I'm trying to use the new Biome Vue support, which works fine when writing and saving code, but completely breaks when copying and pasting code into the document. It's hard to explain, so I recorded a video.

https://github.com/biomejs/biome/assets/143744/2cc2abad-7c95-4f34-aab2-acaca26b4b9b

When I paste, it seems like the text selection/ranges are off, and it completely breaks the code. After I paste, I hit cmd+z to undo the brokenness, and it gets me to the output of what I expected. It kind of seems like it's running the formatter twice?

I originally though eslint/prettier/etc were also running, and they were all conflicting, but I totally disabled all of those and was able to pinpoint that Biome was the problem.

### Expected result

Pastes as normal.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by arendjr** [comment]
This appears related to https://github.com/biomejs/biome/issues/1570

Could you see if you see multiple formatters in the list as described in that issue?

**Comment by milesj** [comment]
I don't see any duplicates. I also disabled all other formatters and it does still happen.

**Comment by ragrag** [comment]
we noticed similar issues when using noUnusedImports 

@ematipico any rough timeline on when full support is planned 👀

thank you for the amazing work

**Comment by ematipico** [comment]
I believe the latest release should have fixed it
