### ISSUE TITLE
📎 Implement `nursery/useAdjacentOverloadSignatures` - `typescript-eslint/adjacent-overload-signatures`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#2090]
### Description

[adjacent-overload-signatures](https://typescript-eslint.io/rules/adjacent-overload-signatures)

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by chansuke** [comment]
I'd like to work on this issue
