### ISSUE TITLE
🐛 super gets removed in derived anonymous class (parse/noSuperWithoutExtends)

### ISSUE THREAD

**Issue by FCQCarryOut** [biomejs/biome#2108]
### Environment information

```block
should not be required for this issue.
Issue is reproducible in playground.
```

### What happened?

super() gets removed / marked as invalid

Error: `Super() is only valid in derived class constructors`

https://biomejs.dev/playground/?code=YwBsAGEAcwBzACAATwB0AGgAZQByACAAewAKACAAIAAgACAAYwBvAG4AcwB0AHIAdQBjAHQAbwByACgAKQAgAHsACgAgACAAIAAgACAAIAAgACAAYwBvAG4AcwBvAGwAZQAuAGwAbwBnACgAIgAiACkACgAgACAAIAAgAH0ACgB9AAoACgBjAGwAYQBzAHMAIABFAHgAYQBtAHAAbABlACAAewAKACAAIAAgACAAdABlAHMAdAAoACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAbgBlAHcAIABjAGwAYQBzAHMAIABlAHgAdABlAG4AZABzACAATwB0AGgAZQByACAAewAKAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAcAByAGkAdgBhAHQAZQAgAG8AdABoAGUAcgA6ACAAbgB1AG0AYgBlAHIAOwAKAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAYwBvAG4AcwB0AHIAdQBjAHQAbwByACgAKQAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHMAdQBwAGUAcgAoACkAOwAKAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAB0AGgAaQBzAC4AbwB0AGgAZQByACAAPQAgADEAMAA7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAfQAKACAAIAAgACAAIAAgACAAIAB9ACgAKQA7AAoAIAAgACAAIAB9AAoAfQAKAA%3D%3D

### Expected result

super should be allowed in derived anonymous class.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment]
I'd like to work on this.
