### ISSUE TITLE
📎 Remove unused dependencies 

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#2136]
### Description

Boshen created `cargo-shear` to remove unused dependencies, and he used in our repository as a test.

Does anyone want to use it and commit the changes?

https://twitter.com/boshen_c/status/1770106165923586395

**Comment by Kenzo-Wada** [comment]
can I work on this?

**Comment by ematipico** [comment]
@Kenzo-Wada all yours!

**Comment by Kenzo-Wada** [comment]
@ematipico 

Thank You!!
