### ISSUE TITLE
🐛 biome migrate prettier does not recognize endOfLine auto

### ISSUE THREAD

**Issue by eMerzh** [biomejs/biome#2138]
### Environment information

```block
CLI:
  Version:                      1.6.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.6.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

1. npx @biomejs/biome  migrate prettier
2. biome errors :
```
.prettierrc:10:15 deserialize ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Found an unknown value `auto`.

     8 │ 	"bracketSameLine": false,
     9 │ 	"arrowParens": "avoid",
  > 10 │ 	"endOfLine": "auto"
       │ 	             ^^^^^^
    11 │ }
    12 │

  ℹ Accepted values:

  - lf
  - crlf
  - cr

```

### Expected result

Biome proceed :) and probably skip the endofline config?

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
We don't support that option https://biomejs.dev/reference/configuration/#formatterlineending, and it's voluntary.

**Comment by ematipico** [comment]
Sorry, I didn't understand what you're suggesting 😅

**Comment by eMerzh** [comment]
Oupsi .. 
i'll try again
currently, the migrate command fails because of this option.

I totally get that you don't want to support "auto" in biome.
But i "suggest", to either ignore the "auto" value, or convert it forcibly to the preferred option.
(i would say we shouldn't leave the ending as default)

That way, the migration can proceed instead of erroring

clearer?
