### ISSUE TITLE
🐛 files.ignoreUnknown doesn't work as expect

### ISSUE THREAD

**Issue by techzealot** [biomejs/biome#2140]
### Environment information

```block
CLI:
  Version:                      1.6.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.4.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.15.5"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

the playground is here:[codesandbox example](https://codesandbox.io/p/devbox/wonderful-kilby-jrd9j7?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltzoxq4t00053b6pk4ol59xi%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltzoxq4s00023b6pim963ikb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltzoxq4s00033b6pq11fwbqz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltzoxq4s00043b6pyf6wgo6d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltzoxq4s00023b6pim963ikb%2522%253A%257B%2522id%2522%253A%2522cltzoxq4s00023b6pim963ikb%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522cltzoxq4s00043b6pyf6wgo6d%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltzoxq4s00043b6pyf6wgo6d%2522%257D%252C%2522cltzoxq4s00033b6pq11fwbqz%2522%253A%257B%2522id%2522%253A%2522cltzoxq4s00033b6pq11fwbqz%2522%252C%2522activeTabId%2522%253A%2522cltzpemki003z3b6n7a4vtcig%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltzpemki003z3b6n7a4vtcig%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cltzpen770050djip6vk295mk%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

1. change the biome version to 1.6.1 and reinstall the dependecies

2.we add two unsupported empty yml file called: ci.yml config.yml

3.set files.ignoreUnknown=true in biome.json

4.when we execute `npx biome check ci.yml config.yml package.json`,it works well as expect

5.when we execute `npx biome check ci.yml config.yml` or `npx biome check ci.yml`,it went wrong with `No files were processed in the specified paths`

I don't know if it is the right behavior.

but it is not good when we only change the unsupported file and commit it using the lint-staged as follows in package.json

```
"lint-staged": {
    "*": ["biome check --apply"]
}
```

### Expected result

When we set files.ignoreUnknown=true and use only unsupported file as input,it will not throw an error.

Maybe it is a problem we need further discussing.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment]
Hello, this is an expected behavior. You will want to use the [flag `--no-errors-on-unmatched`](https://biomejs.dev/reference/cli). It is also documented in the [Git Hooks](https://biomejs.dev/recipes/git-hooks/) section in the doc.

**Comment by techzealot** [comment]
> Hello, this is an expected behavior. You will want to use the [flag `--no-errors-on-unmatched`](https://biomejs.dev/reference/cli). It is also documented in the [Git Hooks](https://biomejs.dev/recipes/git-hooks/) section in the doc.

thank you for your solution.
