### ISSUE TITLE
💅 `useExhaustiveDependencies` does not follow `react-hooks/exhaustive-deps` behavior for useEffect dependencies

### ISSUE THREAD

**Issue by paprikman** [biomejs/biome#2149]
### Environment information

```bash
CLI:
  Version:                      1.6.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.11.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### Rule name

useExhaustiveDependencies

### Playground link

https://biomejs.dev/playground/?code=aQBtAHAAbwByAHQAIAB7ACAAdQBzAGUARQBmAGYAZQBjAHQAIAB9ACAAZgByAG8AbQAgACIAcgBlAGEAYwB0ACIAOwAKAAoAaQBuAHQAZQByAGYAYQBjAGUAIABJAEEAcABwAFAAcgBvAHAAcwAgAHsACgAgACAAbABhAGIAZQBsAD8AOgAgAHMAdAByAGkAbgBnADsACgB9AAoACgBjAG8AbgBzAHQAIABBAHAAcAA6ACAAUgBlAGEAYwB0AC4ARgBDADwASQBBAHAAcABQAHIAbwBwAHMAPgAgAD0AIAAoAHsAIABsAGEAYgBlAGwAIAB9ACkAIAA9AD4AIAB7AAoAIAAgAGMAbwBuAHMAdAAgAFsAYwBvAHUAbgB0AGUAcgAsACAAcwBlAHQAQwBvAHUAbgB0AGUAcgBdACAAPQAgAHUAcwBlAFMAdABhAHQAZQA8AG4AdQBtAGIAZQByAD4AKAAwACkAOwAKAAoAIAAgAHUAcwBlAEUAZgBmAGUAYwB0ACgAKAApACAAPQA%2BACAAewAKACAAIAAgACAAcwBlAHQAQwBvAHUAbgB0AGUAcgAoACgAcAByAGUAdgApACAAPQA%2BACAAcAByAGUAdgAgACsAIAAxACkAOwAKACAAIAB9ACwAIABbAGwAYQBiAGUAbAAsACAAcwBlAHQAQwBvAHUAbgB0AGUAcgBdACkAOwAKACAAIAAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAZABpAHYAPgAKACAAIAAgACAAIAAgADwAZABpAHYAPgB7AGMAbwB1AG4AdABlAHIAfQA8AC8AZABpAHYAPgAKACAAIAAgACAAIAAgADwAZABpAHYAPgB7AGwAYQBiAGUAbAB9ADwALwBkAGkAdgA%2BAAoAIAAgACAAIAA8AC8AZABpAHYAPgAKACAAIAApAAoAfQA%3D

### Expected result

`react-hooks/exhaustive-deps` allows adding unused (inside the hook) variables in useEffect dependency array. Which, in its turn, helps us to execute some code on local (state) or external (component props) variable change, even if that code does not depend on this variable value.

`useExhaustiveDependencies` does not follow that behavior and throws an error if useEffect has 'unnecessary' dependencies.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by arendjr** [comment]
You’re right, there’s a suggestion for this to split the rule in two: https://github.com/biomejs/biome/issues/630
