### ISSUE TITLE
💅 recommended: false disables all nested rules

### ISSUE THREAD

**Issue by gabberr** [biomejs/biome#2191]
### Environment information

```bash
CLI:
  Version:                      1.6.2
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.11.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### Rule name

recommended

### Playground link

https://codesandbox.io/p/devbox/affectionate-tdd-88kfd8?workspaceId=bd54a27b-9638-44e1-9045-0c9eff5a023a&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltzoxq4t00053b6pk4ol59xi%2522%252C%2522sizes%2522%253A%255B57.07729468599034%252C42.92270531400966%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltzoxq4s00023b6pim963ikb%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltzoxq4s00033b6pq11fwbqz%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltzoxq4s00043b6pyf6wgo6d%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltzoxq4s00023b6pim963ikb%2522%253A%257B%2522id%2522%253A%2522cltzoxq4s00023b6pim963ikb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu6vlav100992e67x9r7aehl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A9%252C%2522startColumn%2522%253A2%252C%2522endLineNumber%2522%253A9%252C%2522endColumn%2522%253A2%257D%255D%252C%2522filepath%2522%253A%2522%252Fbiome.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clu6vlav100992e67x9r7aehl%2522%257D%252C%2522cltzoxq4s00043b6pyf6wgo6d%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltzoxq4s00043b6pyf6wgo6d%2522%257D%252C%2522cltzoxq4s00033b6pq11fwbqz%2522%253A%257B%2522id%2522%253A%2522cltzoxq4s00033b6pq11fwbqz%2522%252C%2522activeTabId%2522%253A%2522clu6vns1f008x2e674tg6jrgl%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clu6vns1f008x2e674tg6jrgl%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clu6vns46007mdjip79by97el%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Expected result

I disabled recommended rules and enabled one specific rule. The rule is not checked!
```
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": false,
      "a11y": {
        "recommended": false,
        "useButtonType": "error"  <- i expect this rule to be enabled
      }
    }
  },
```
We are doing a migration, so we want to turn on rules one-by-one.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment]
Sorry, I think this is a regression introduced in #2072, I'll fix it ASAP.
