### ISSUE TITLE
Setting BIOME_CONFIG_PATH breaks VSCode extension

### ISSUE THREAD

**Issue by david-04** [biomejs/biome#2234]
### Environment information

```block
CLI:
  Version:                      1.6.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "cygwin"
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### What happened?

1. Set environment variable [BIOME_CONFIG_PATH](https://biomejs.dev/reference/cli/#biome-lsp-proxy) to a custom default configuration file (e.g. `C:\MyFiles\biome.default.json`).
2. Start VSCode (with the Biome VSCode extension installed and Biome configured as the default formatter for TypeScript).
3. Open a TypeScript project (with or without a local `biome.json`) and try to format a TypeScript file.
4. Formatting fails and an error message pops up, stating that `Extension 'Biome' is configured as formatter but it cannot format 'TypeScript'-files`

### Expected result

Biome should format the code. If the project has a `biome.json`, it should use the configuration from there. If the project does not have a Biome configuration, it should use the file specified in the `BIOME_CONFIG_PATH`.

The environment variable was a good way to define a default configuration that's applied when a VSCode project does not have a local Biome configuration. It has stopped working some time ago. Setting `BIOME_CONFIG_PATH`  now prevents the VSCode extension from working at all (even if the project has a local `biome.json`).

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by benhammondmusic** [comment]
This or something similar is happening on my Mac setup as well

**Comment by nhedger** [comment]
Hi,

Thanks for opening this issue.

The `BIOME_CONFIG_PATH` environment variable expects a path to a **directory**, not a file.

It could be why Biome fails to start, resulting in the VS Code extension behaving like this.

**Comment by david-04** [comment]
Thanks for the clarification, Nicolas. It does work as expected when `BIOME_CONFIG_PATH` points to the directory rather than the file. I'm closing this issue.
