### ISSUE TITLE
🐛 The error message in terminal is not highlight for lint-staged.

### ISSUE THREAD

**Issue by Mayandev** [biomejs/biome#2241]
### Environment information

```block
CLI:
  Version:                      1.6.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v16.20.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/8.19.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Linter:
  Recommended:                  true
  All:                          false
  Rules:                        a11y/all = false
                                complexity/useRegexLiterals = "off"
                                correctness/useExhaustiveDependencies = "off"
                                style/useImportType = "off"

Workspace:
  Open Documents:               0
```

## Screen shot
| Normal Using | Lint Staged |
| ------ | ------ |
| ![image](https://github.com/biomejs/biome/assets/28648715/30f62898-6808-48f5-afa7-bc0e684c3a69) |![image](https://github.com/biomejs/biome/assets/28648715/05cd3d30-b5a1-452f-885d-b005d9dd0f3f)|

### Expected result

The lint-staged error should highlight.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Have you tried to use the `--colors=force` option?

If yes, I would seek support with the lint-staged community. As you noticed Biome prints colours in your terminal as expected. This means that lint-staged isn't probably piping stdout/stderr to your terminal

**Comment by Mayandev** [comment]
Adding `--colors=force` option is OK, thx!
