### ISSUE TITLE
📎 Accept files for `--config-path` and `BIOME_CONFIG_PATH`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#2265]
### Description

See some context in #2240.

For now, the value of the CLI option `-config-path` and the env variable `BIOME_CONFIG_PATH` must be a directory that contains a Biome configuration file. This is confusing for users that expect to diretcly point to a configuration file.

To improve user experience, we should also accept a Biome configuration file as value. This change is backward compatible because a user can still specify a directory.

**Comment by ematipico** [comment]
Since this isn't clear enough, unless someone reads the original discussion, files must be `biome.json` or `biome.jsonc`. Other file names won't be accepted (even the old `rome.json`)

**Comment by Conaclos** [comment]
> Since this isn't clear enough, unless someone reads the original discussion, files must be biome.json or biome.jsonc. Other file names won't be accepted (even the old rome.json)

Thanks for the clarification.
This makes me think a second time about that: Because we accept any filename in the `extends` field in a Biome configuration, this could make sense of accepting any filename as value of this option?

**Comment by ematipico** [comment]
Yeah I can see your point

**Comment by fb55** [comment]
To add to this, the error message for a bad `--config-path` still references a `rome.json`:

```
% pnpm biome check --apply-unsafe --config-path=asdf/biome.json src/generated 
asdf/biome.json/rome.json internalError/fs ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Biome couldn't read the file
  
  ✖ Biome couldn't read the following file, maybe for permissions reasons or it doesn't exists: asdf/biome.json/rome.json
```

**Comment by Sec-ant** [comment]
Unfortunately the `rome.json` is a fallback file Biome will search for if it cannot find `biome.json` or `biome.jsonc` in the provided directory. But I think I can improve the error message as well.
