### ISSUE TITLE
📎 `--write` everywhere

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#2267]
### Description

See #2240 for more context.

- [ ] Add `--write` and `--unsafe` option to lint/check CLI commands
      - `--write` indicates if (safe) code fixes should be applied
      - `--unsafe` indicates that safe and unsafe code fixes should be applied if `--write` is passed
- [ ] Make `biome <lint|check> --apply` an alias of `biome <lint|check> --write`
- [ ] Make `biome <lint|check> --apply-unsafe` an alias of `biome <lint|check> --write --unsafe`

**Comment by ematipico** [comment]
Since this isn't clear unless someone reads the original discussion, `--apply` and `--apply-unsafe` have to be deprecated.

**Comment by Conaclos** [comment]
On second thought, I think we should use `--fix` instead of `--write` because it is a more common option name among linters. This will generate more deprecations, but I think it is time or never?

**Comment by Conaclos** [comment]
> But Biome isn't just a linter 🙄

Yes. However, `biome format --fix` make sense?

**Comment by unvalley** [comment]
I feel almost everything (write, fix, apply) is natural, but I don't know how people think `lint --write`.
+1 for unifying `--fix`.

By the way, do we need to split `--fix`(or `--write`) and `--unsafe`?
I feel it brings us a bit complex.

**Comment by Conaclos** [comment]
I don't understand what you mean, it seems to me that the following two paragraphs are contradictory.

> I'm in favor of unifying --fix but considering --fix-unsafe, users might think the option only fixes unsafe code even though it does fix to the code with applying unsafe fix.

> By the way, do we need to separate --fix (or others) and --unsafe?
> I feel it makes things a bit more complex.

I agree that `--apply-unsafe` is confusing: users could think that it only applies unsafe fixes, while it applies both safe and unsafe fixes.
It is why I proposed `--unsafe`.
Combined with `--fix` it applies safe and unsafe fixes.
This is what Ruff is doing, although the option is named `--unsafe--fixes`.

**Comment by unvalley** [comment]
Ah right, the second paragraph, 'complex' was for handling command line arguments. But I got what this task means.

**Comment by Conaclos** [comment]
Alternatively, we could accept both `--write` and `--fix` because we have users migrating from Prettier (that uses `--write`) and ESLint (that uses `--fix`).

**Comment by ematipico** [comment]
> Alternatively, we could accept both `--write` and `--fix` because we have users migrating from Prettier (that uses `--write`) and ESLint (that uses `--fix`).

So one would be the alias of the other? I like the idea!

**Comment by unvalley** [comment]
I also like it, some package managers do that for `install` and `add`.

**Comment by Conaclos** [comment]
> So one would be the alias of the other?

Yes.
I am not fond of aliases, however, in our case, this looks like a good UX.

**Comment by unvalley** [comment]
What should we do when `biome <lint|check> --unsafe` is given?

It looks like a command to show lint errors subject to unsafe fixes. But here we should show an error incompatible arguments?
