### ISSUE TITLE
🐛 Cannot extends a jsonc configuration file

### ISSUE THREAD

**Issue by KittyGiraudel** [biomejs/biome#2279]
### Environment information

```block
$ /Users/kitty/Sites/biome-jsonc-repro/packages/some-dir/node_modules/.bin/biome rage
CLI:
  Version:                      1.6.4
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.16.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/1.22.21"

Biome Configuration:
  Error:                        Expected a property but instead found '// Test comment'.
  Error:                        End of file expected
  Error:                        End of file expected
  Error:                        End of file expected
  Error:                        End of file expected
  Error:                        Incorrect type, expected an object, but received an array.
  Status:                       Loaded with errors
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

1. Define a `biome.jsonc` configuration file.
2. Define a second configuration file extending from the first.
3. Witness an error when loading that second file.

### Expected result

If jsonc is supported to define configuration files, it should be possible to extend jsonc-defined configuration files, otherwise it’s a bit weird.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Thank you, @KittyGiraudel. Can you share a snippet of the configuration you're using?

**Comment by KittyGiraudel** [comment]
I updated my original comment to reflect the output from `biome rage` ran on this reproducible test case I just created: https://github.com/KittyGiraudel/biome-2279

I noticed that the problem only occurs when the JSONC configuration file contains comments. So it‘s not the format per se that is the problem, but the presence of comments that make the `extends` choke.

I hope this helps. :)
