### ISSUE TITLE
📎 Implement `lint/noConstantMinMax` - `clippy/min_max`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#2304]
### Description

Implement [clippy/min_max](https://rust-lang.github.io/rust-clippy/master/#/min_max)

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

The rule should apply to `Math.min`/`Math,max`.
We should check that `Math` is a global unresolved reference.
See the rules such as [noGlobalIsFinite](https://biomejs.dev/linter/rules/no-global-is-finite/) to check this.

Suggest names: `noConstantMinMax`, `noConstantMathMinMax`

**Comment by mgomulak** [comment]
I'd like to give it a try
