### ISSUE TITLE
🐛 VSCode extension crashes after updating schema to `1.6.4` and fixing warning `Missing property "options"` with `"options": null` 

### ISSUE THREAD

**Issue by FedericoBiccheddu** [biomejs/biome#2313]
### Environment information

```block
CLI:
  Version:                      1.6.4
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm"
  JS_RUNTIME_VERSION:           "v20.11.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.15.6"

Biome Configuration:
  Error:                        options has an incorrect type, expected no value, but received null.
  Status:                       Loaded with errors
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0

VSCode:
  Extension:                    v2.2.2
```

### What happened?

1. Updating the `$schema` property in `biome.json` to `"https://biomejs.dev/schemas/1.6.4/schema.json"` warnings starts to appear.
	- `Missing property "options".`
2. Fix adding `"options": null` in rules as warning suggests
3. Biome extension fails because: `[Error - 11:23:28 PM] options has an incorrect type, expected no value, but received null.`

### Expected result

Warning disappears or extension works correctly.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by FedericoBiccheddu** [comment]
Every rule that has no `option` defined. In my case `nursery/useImportRestrictions`, `style/noDefaultExport`, `style/useShorthandArrayType` and `suspicious/noShadowRestrictedNames`.
 
```json
{
	"$schema": "https://biomejs.dev/schemas/1.6.4/schema.json",
	"files": {
		"ignoreUnknown": true,
		"include": [
			"biome.json",
			"tsconfig.json",
			"app/**/*.css",
			"app/**/*.ts",
			"app/**/*.tsx"
		]
	},
	"organizeImports": {
		"enabled": false
	},
	"linter": {
		"enabled": true,
		"rules": {
			"all": true,
			"nursery": {
				"useImportRestrictions": {
					"level": "off"
				}
			},
			"style": {
				"noDefaultExport": {
					"level": "off"
				},
				"useNamingConvention": {
					"level": "off",
					"options": {
						"strictCase": false
					}
				},
				"useConsistentArrayType": {
					"level": "error",
					"options": {
						"syntax": "generic"
					}
				},
				"useShorthandArrayType": {
					"level": "off"
				}
			},
			"suspicious": {
				"noShadowRestrictedNames": {
					"level": "off"
				}
			}
		}
	}
}
```

**Comment by ematipico** [comment]
I can replicate the issue

**Comment by FedericoBiccheddu** [comment]
In the meantime, the problem goes away setting the rule to `"off"` instead of using `"level"`:
```jsonc
{
	// snip
	"nursery": {
		"useImportRestrictions": "off"
	},
	"style": {
		"noDefaultExport": "off",
		"useNamingConvention": {
			"level": "off",
			"options": {
				"strictCase": false
			}
		},
		"useShorthandArrayType": "off"
	},
	"suspicious": {
		"noShadowRestrictedNames": "off"
	}
	// snip
}
```

**Comment by ematipico** [comment]
@Conaclos could you check this out please? 

@Sec-ant do you think this is a regression of your recent change?

**Comment by Sec-ant** [comment]
> do you think this is a regression of your recent change?

🤔 Sorry, but I have no idea. If @Conaclos need some someone else before he can tend to this issue, I can help.

**Comment by Conaclos** [comment]
I think it is an "expected" regression of #1876.
I didn't manage to make `options` optional. Then, I [decided to accept this regression by assuming that users didn't use an object when the rule has no options](https://github.com/biomejs/biome/pull/1876#discussion_r1496513717).
