### ISSUE TITLE
📎 Update ESLint benchmark to v9

### ISSUE THREAD

**Issue by SuperchupuDev** [biomejs/biome#2326]
### Description

ESLint v9 was released yesterday, and it enables flat config by default, deprecating the old config format. We should update the benchmark infra to update ESLint and its config

**Comment by chansuke** [comment]
I'd like to handle this issue

**Comment by chansuke** [comment]
@Conaclos 
Thank you for your guidance!
I've updated `conaclos/update-bench` in my local environment and did `git push -f upstream conaclos/update-bench` but it seems I couldn't update the branch.

So I created the new branch and sbumitted https://github.com/biomejs/biome/pull/2407
Is this correct approach?

**Comment by SuperchupuDev** [comment]
i *think* conaclos' branch is out of date, you could submit a pr with just your changes instead
