### ISSUE TITLE
📝 Formatter removes semicolons on save in VS code from .tsx files, but not .ts files

### ISSUE THREAD

**Issue by geoguide** [biomejs/biome#2343]
### Environment information

```bash
CLI:
  Version:                      1.6.4
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.11.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.5.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Formatter:
  Format with errors:           false
  Indent style:                 Tab
  Indent size:                  2
  Indent width:                 2
  Line ending:                  Lf
  Line width:                   80
  Attribute position:           Auto
  Ignore:                       []
  Include:                      []

JavaScript Formatter:
  Enabled:                      false
  JSX quote style:              Single
  Quote properties:             AsNeeded
  Trailing comma:               All
  Semicolons:                   AsNeeded
  Arrow parentheses:            Always
  Bracket spacing:              false
  Bracket same line:            false
  Quote style:                  Single
  Indent style:                 unset
  Indent size:                  unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           Auto

JSON Formatter:
  Enabled:                      true
  Indent style:                 unset
  Indent width:                 unset
  Indent size:                  unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
  "$schema": "https://biomejs.dev/schemas/1.6.4/schema.json",
  "organizeImports": {
    "enabled": true
  },
  "javascript": {
    "formatter": {
      "semicolons": "asNeeded",
      "quoteStyle": "single",
      "jsxQuoteStyle": "single",
      "trailingComma": "all"
    }
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
      "suspicious": {
        "noExplicitAny": "off"
      },
      "complexity": {
        "noBannedTypes": "off"
      },
      "a11y": {
        "useKeyWithClickEvents": "off"
      }
    }
  }
}
```

### Playground link

https://biomejs.dev/playground/?semicolons=as-needed&code=ZQB4AHAAbwByAHQAIABjAG8AbgBzAHQAIABmAGUAdABjAGgAQwByAGUAdwBzACAAPQAgAGEAcwB5AG4AYwAgACgAKQAgAD0APgAgAHsACgAgACAAYwBvAG4AcwB0ACAAZgBlAHQAYwBoAEMAcgBlAHcAcwAyACAAPQAgAGEAcwB5AG4AYwAgACgAKQAgAD0APgAgAHsACgAgACAAIAAgAGMAbwBuAHMAdAAgAHsAIABkAGEAdABhACwAIABlAHIAcgBvAHIAIAB9ACAAPQAgAGEAdwBhAGkAdAAgAHMAdQBwAGEAYgBhAHMAZQAKACAAIAAgACAAIAAgAC4AZgByAG8AbQAoACcAYwByAGUAdwBzACcAKQAKACAAIAAgACAAIAAgAC4AcwBlAGwAZQBjAHQAKAApAAoAIAAgACAAIAAgACAALgBvAHIAZABlAHIAKAAnAHQAeQBwAGUAJwAsACAAewAgAGEAcwBjAGUAbgBkAGkAbgBnADoAIAB0AHIAdQBlACAAfQApAAoAIAAgACAAIAAgACAALgBvAHIAZABlAHIAKAAnAGMAcgBlAHcAXwBsAGEAYgBlAGwAJwAsACAAewAgAGEAcwBjAGUAbgBkAGkAbgBnADoAIAB0AHIAdQBlACAAfQApAAoAIAAgACAAIABpAGYAIAAoAGUAcgByAG8AcgApACAAdABoAHIAbwB3ACAAbgBlAHcAIABFAHIAcgBvAHIAKABlAHIAcgBvAHIALgBtAGUAcwBzAGEAZwBlACkACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAZABhAHQAYQA7AAoAIAAgAH0ACgB9AA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by geoguide** [comment]
It seems like it works in the playground, but it doesn't work on vs code. I've restarted by editor twice. It works perfectly on tsx files which is confusing

**Comment by Sec-ant** [comment]
I cannot reproduce this issue. Can you check:

- Is the CLI able to format the `.ts` files as expected?
- Are there any other formatter extensions involved? Can you run the format command explicitly (`Cmd` + `Shift` + `P` > Format Document) and make sure its Biome that doing the formatting and check the result?
- Are `.ts` files associated with the `TypeScript` language id? You can check the language mode of an opened file in the bottom right corner of the VS Code window.
- If nothing suspicious is going on, can you provide a minimal repro in a repo?

**Comment by geoguide** [comment]
> I cannot reproduce this issue. Can you check:
> 
> * Is the CLI able to format the `.ts` files as expected?

Yes it does

> * Are there any other formatter extensions involved? Can you run the format command explicitly (`Cmd` + `Shift` + `P` > Format Document) and make sure its Biome that doing the formatting and check the result?

I ran it that way and it made me configure it even though it was already configured. Now it seems to work? Thanks!
