### ISSUE TITLE
💅 `noDuplicateJsonKeys` always marks the first key in object

### ISSUE THREAD

**Issue by luckydye** [biomejs/biome#2366]
### Environment information

```bash
CLI:
  Version:                      1.6.4
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "screen-256color"
  JS_RUNTIME_VERSION:           "v21.6.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "bun/1.1.1"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 false

Linter:
  Recommended:                  false
  All:                          false
  Rules:                        a11y/useKeyWithClickEvents = "off"
                                complexity/noForEach = "warn"
                                complexity/noStaticOnlyClass = "off"
                                nursery/noDuplicateJsonKeys = "error"
                                nursery/useSortedClasses = {"level":"warn","options":{"attributes":["class","className","classList"],"functions":["clsx","cva","twMerge","tw"]}}
                                style/noDefaultExport = "warn"
                                suspicious/noArrayIndexKey = "off"
                                suspicious/noConsoleLog = "warn"
                                suspicious/noExplicitAny = "warn"

Workspace:
  Open Documents:               0
```

### Rule name

noDuplicateJsonKeys

### Playground link

https://biomejs.dev/playground/?indentStyle=space&indentWidth=8&lintRules=all&files.main.json=ewAKACAAIAAiAG8AcAB0AGkAbwBuADEAIgA6ACAAIgBPAHAAdABpAG8AbgAgADEAIgAsAAoAIAAgACIAbwB0AGgAZQByAE8AcAB0AGkAbwBuACIAOgAgACIATwB0AGgAZQByACAAbwBwAHQAaQBvAG4AIgAsAAoAIAAgACIAZAB1AHAAbABpAGMAYQB0AGUASwBlAHkAIgA6ACAAIgBEAHUAcABsAGkAYwBhAHQAZQAgAGsAZQB5ACIALAAKACAAIAAiAGQAdQBwAGwAaQBjAGEAdABlAEsAZQB5ACIAOgAgACIARAB1AHAAbABpAGMAYQB0AGUAIABrAGUAeQAiACwACgAgACAAIgBsAGEAcwB0AE8AcAB0AGkAbwBuACIAOgAgACIATABhAHMAdAAgAG8AcAB0AGkAbwBuACIACgB9AA%3D%3D

### Expected result

The lint error should be at the key that is actually a duplicate.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by arendjr** [comment]
I think our diagnostics have the ability to highlight them both. I agree it might make more sense to display the main error on the second occurrence, and then we can add an additional info with something like “key already occurred here”.

**Comment by arendjr** [comment]
Do we have the same problem with JS object literals, btw? Might be good to use the same approach for both.

**Comment by Sec-ant** [comment]
@arendjr you may misunderstand the issue, the rule currently always marks the first key, even if it's not a duplicate key.

**Comment by arendjr** [comment]
Oh, haha. Yeah, that's definitely an issue :D
