### ISSUE TITLE
☂️ Website migration

### ISSUE THREAD

**Issue by nhedger** [biomejs/biome#2369]
### Description

We're migrating the website to its [own repository](https://github.com/biomejs/website), and you might be able to help.

Here's a list of things to be done (updated as we go):

- [x] https://github.com/biomejs/website/issues/1 @nhedger 
- [x] https://github.com/biomejs/website/issues/3 @nhedger
- [x] https://github.com/biomejs/website/issues/4 @nhedger
- [x] https://github.com/biomejs/website/issues/5 @nhedger
- [x] https://github.com/biomejs/website/issues/6 @nhedger
- [x] https://github.com/biomejs/website/issues/7 @nhedger
- [x] https://github.com/biomejs/website/pull/27 @Sec-ant
- [x] https://github.com/biomejs/website/pull/21 @Sec-ant
- [x] https://github.com/biomejs/website/pull/26 @Sec-ant
- [x] Transfer documentation issues to the new repo @biomejs/maintainers
- [x] https://github.com/biomejs/website/pull/17 @nhedger
- [x] Update source repository on Netlify @nhedger 
- [x] Synchronize the contents from the main repo to the website repo one last time @Sec-ant 
    - [x] Cleanup main repo when the migration is done
- [x] Transfer code Rust generation
	- [x] Setup rust toolchain in the repository @ematipico 
	- [x] `lintdoc` - generation of rule page and rules sources
	- [x] `generate_website.rs` @ematipico 
	- [x] Create workflows that trigger when changes occur in the main repository and will trigger the codegen @Sec-ant
- [x] Update issue template config to point the website repository https://github.com/biomejs/biome/commit/b7c30aa64af45c0aee51cf1798c1b0f6060a4bf4 @nhedger 
- [x] Add detailed contribution guide

If you'd like to help, please let us know in the comments, and we'll assign you to an issue.

**Comment by Sec-ant** [comment]
Automatically update contributors: https://github.com/biomejs/website/pull/21

**Comment by Sec-ant** [comment]
Update README: https://github.com/biomejs/website/pull/26

**Comment by Sec-ant** [comment]
My thought on the cross-repo triggering:

When the main repo has a new commit on main, use repository dispatch to issue a PR in the website repo to update the submodule commit hash to that exact new commit. That PR will trigger the codegen tasks and some ci checks. If all the checks pass, that PR should be automatically merged. If something goes wrong, we'll know which commit fails the check and we can decide to drop or merge that PR manually.

**Comment by Sec-ant** [comment]
Add checks for Japanese documentation: https://github.com/biomejs/website/pull/27

**Comment by ematipico** [comment]
Codegen for the lint rule  https://github.com/biomejs/website/pull/30

**Comment by ematipico** [comment]
Workflow to update the linter pages https://github.com/biomejs/website/pull/34

**Comment by ematipico** [comment]
I just transferred the website issues to the other repo.

@Sec-ant are the workflows of the `website` repo, ready?

**Comment by ematipico** [comment]
Thank you, I'm halfway through setting up the bot! 

The account is there, I should be able to create the tokens by the end of the day: https://github.com/biome-cookie

**Comment by nhedger** [comment]
Unless there's more, we can copy over recently modified content and switch the flip on Netlify. The contribution guide can certainly be contributed once this is done.

**Comment by ematipico** [comment]
I think we can now

**Comment by nhedger** [comment]
Website is now being deployed from the new repository.

Let's start cleaning up!

**Comment by ematipico** [comment]
The `website/` was removed from the monorepo
