### ISSUE TITLE
🐛 `lint/style/useConsistentArrayType` rule with `"options": { "syntax": "generic" }` provided consumes very high amount of CPU and it takes too long (or even infinity) time to perform `check` command

### ISSUE THREAD

**Issue by supfiger** [biomejs/biome#2375]
### Environment information

```block
CLI:
  Version:                      1.6.4
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.6.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

Source code only of `biome.jsonc` file:
https://codesandbox.io/p/devbox/blissful-leftpad-553k59?file=%2Fbiome.jsonc%3A49%2C23-49%2C28&workspaceId=36350c97-d8d0-4e2f-a6df-1e3521079bbf

I could reproduce the issue ONLY when `useConsistentArrayType` is an object with `"options": { "syntax": "generic" }` provided.

But It works totally OK when:
- `"useConsistentArrayType": { "level": "error" | "warn" | "off", "options": { "syntax": "shorthand" } }`, or
- `useConsistentArrayType` is `"error" | "warn" | "off"`.

### I took screenshots:
**1. Normal usage of my CPU before running any `biome`'s commands:**

<img width="434" alt="before" src="https://github.com/biomejs/biome/assets/18213629/9ea5bb8a-c75e-4448-b3f2-be3e01b4cc8a"> <br>

**2. Usage of my CPU just after about 3 seconds after running `biome check --no-errors-on-unmatched --error-on-warnings --log-level=error --verbose --apply-unsafe`  command. (with `"options": { "syntax": "generic" }` in the rule in config)** <br>
<img width="432" alt="useConsistentArrayType_enabled_with_options" src="https://github.com/biomejs/biome/assets/18213629/67b4621c-d939-4a41-bb90-94c1bd78ce44"> <br>

**3. Here should be a third screenshot of other [good, OK] cases when running without that value of the rule, but your tool is so fast, it performs very quickly so that I could not even make a screenshot.**

Also I tried to wait some time while this unusual process make its job, but my computer started to buzz and get very hot, so I didn't keep it the biome command running more than 40-50 seconds, so, I interrupted it.

### Expected result

1. It should done the job without consuming so much CPU.
2. It should done the job successfully.
3. It should done the job quickly.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
We require at least some snippet that we can use to test it. The reproduction doesn't contain any file  to test against
