### ISSUE TITLE
How do I disable semicolon? I don't want to see semicolon in my code.

### ISSUE THREAD

**Issue by titsex** [biomejs/biome#2390]
### Environment information

```bash
CLI:
  Version:                      1.6.4
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v21.6.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.15.5"

Biome Configuration:
  Error:                        Expected a property but instead found '}'.
  Error:                        Found an unknown value ``.
  Status:                       Loaded with errors
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Formatter:
  Format with errors:           false
  Indent style:                 Tab
  Indent size:                  2
  Indent width:                 2
  Line ending:                  Lf
  Line width:                   80
  Attribute position:           Auto
  Ignore:                       []
  Include:                      []

JavaScript Formatter:
  Enabled:                      false
  JSX quote style:              Double
  Quote properties:             AsNeeded
  Trailing comma:               All
  Semicolons:                   Always
  Arrow parentheses:            Always
  Bracket spacing:              false
  Bracket same line:            false
  Quote style:                  Double
  Indent style:                 unset
  Indent size:                  unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           Auto

JSON Formatter:
  Enabled:                      true
  Indent style:                 unset
  Indent width:                 unset
  Indent size:                  unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
	"$schema": "https://biomejs.dev/schemas/1.6.4/schema.json",
	"organizeImports": {
		"enabled": true
	},
	"linter": {
		"enabled": true,
		"rules": {
			"recommended": true,
		}
	},
	"javascript": {
		"formatter": {
			"semicolons": "how can I disable it??" 
		}
	}
}
```

### Playground link

https://biomejs.dev/playground/

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment]
Please check the document: https://biomejs.dev/reference/configuration/#javascriptformattersemicolons

**Comment by theonetheycallneo** [comment]
Shouldn't "none" be an option?

**Comment by arendjr** [comment]
No, because that could leave your code in a broken state. The link from the docs explains it more in-depth: https://en.wikibooks.org/wiki/JavaScript/Automatic_semicolon_insertion

**Comment by andersonbosa** [comment]
@theonetheycallneo that was my solution (unfortunately): https://eslint.style/rules/js/semi

**Comment by Frexuz** [comment]
> No, because that could leave your code in a broken state. The link from the docs explains it more in-depth: [en.wikibooks.org/wiki/JavaScript/Automatic_semicolon_insertion](https://en.wikibooks.org/wiki/JavaScript/Automatic_semicolon_insertion)

"Could" is a long-shot. I've had semi as `off` for almost 10 years and **never ever ever, a single time, nope never** encountered a problem in a react codebase

like these:

```
function MyComponent() {
  return (
    <>
        {arr.map((x) => {
            return <CompA x={x} />; <------------ RLY??
        })}
    </>
  ); <----------- RLY??
}
```

just let US decide if we don't want them??

**Comment by WilliamJohnDavisIII** [comment]
It's a big red flag when libraries make opinionated decisions like this. It reminds me of Next Auth discouraging the use of passwords.

**Comment by siketyan** [comment]
By setting `asNeeded` to the `semicolons` option, Biome won't insert any semicolons to your code unless it's technically impossible to remove. If you've never seen a single semicolon in your code, Biome will never insert ones, too.

The limitation that your code sometimes needs some semicolons is coming from the ASI in ECMAScript. We can't lift the limitation without dropping support for ECMAScript/TypeScript.

**Comment by kristian-nst** [comment]
> Biome will never insert ones, too.

that's just not true:
as above example shows:
```
        {arr.map((x) => {
            return <CompA x={x} />; <------------ RLY??
        })}
```
i have NEVER seen one there in any of my codebases, ever.
using `asNeeded` setting

**Comment by siketyan** [comment]
@kristian-nst Can you share a reproduction? I could not reproduce it in the playground: https://biomejs.dev/playground/?semicolons=as-needed&code=ZgB1AG4AYwB0AGkAbwBuACAAQwBvAG0AcABvAG4AZQBuAHQAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAPgAKACAAIAAgACAAIAAgAHsAYQByAHIALgBtAGEAcAAoACgAeAApACAAPQA%2BACAAewAKACAAIAAgACAAIAAgACAAIAByAGUAdAB1AHIAbgAgADwAQwBvAG0AcABBACAAeAA9AHsAeAB9ACAALwA%2BADsACgAgACAAIAAgACAAIAB9ACkAfQAKACAAIAAgACAAPAAvAD4ACgAgACAAKQA7AAoAfQAKAA%3D%3D

**Comment by kristian-nst** [comment]
I will try :)

**Comment by damartripamungkas** [comment]
Same issue i`m migration from eslint + prettier
