### ISSUE TITLE
💅"lint --apply" is not working for "Provide an explicit type prop for the button element."

### ISSUE THREAD

**Issue by cl-r-shibata** [biomejs/biome#2395]
### Environment information

```bash
CLI:
  Version:                      1.6.4
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.2.3"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  Recommended:                  true
  All:                          false
  Rules:
Workspace:
  Open Documents:               0
```

### Rule name

lint/a11y/useButtonType

### Playground link

https://biomejs.dev/playground/?code=ZgB1AG4AYwB0AGkAbwBuACAAQQBwAHAAKAApACAAewAKACAAIABjAG8AbgBzAHQAIABbAGMAbwB1AG4AdAAsACAAcwBlAHQAQwBvAHUAbgB0AF0AIAA9ACAAdQBzAGUAUwB0AGEAdABlACgAMAApADsACgAKACAAIAByAGUAdAB1AHIAbgAgACgACgAgACAAIAAgADwAPgAKACAAIAAgACAAIAAgADwAZABpAHYAPgAKACAAIAAgACAAIAAgACAAIAA8AGEAIABoAHIAZQBmAD0AIgBoAHQAdABwAHMAOgAvAC8AdgBpAHQAZQBqAHMALgBkAGUAdgAiACAAdABhAHIAZwBlAHQAPQAiAF8AYgBsAGEAbgBrACIAIAByAGUAbAA9ACIAbgBvAHIAZQBmAGUAcgByAGUAcgAiAD4ACgAgACAAIAAgACAAIAAgACAAIAAgADwAaQBtAGcAIABzAHIAYwA9AHsAdgBpAHQAZQBMAG8AZwBvAH0AIABjAGwAYQBzAHMATgBhAG0AZQA9ACIAbABvAGcAbwAiACAAYQBsAHQAPQAiAFYAaQB0AGUAIABsAG8AZwBvACIAIAAvAD4ACgAgACAAIAAgACAAIAAgACAAPAAvAGEAPgAKACAAIAAgACAAIAAgACAAIAA8AGEAIABoAHIAZQBmAD0AIgBoAHQAdABwAHMAOgAvAC8AcgBlAGEAYwB0AC4AZABlAHYAIgAgAHQAYQByAGcAZQB0AD0AIgBfAGIAbABhAG4AawAiACAAcgBlAGwAPQAiAG4AbwByAGUAZgBlAHIAcgBlAHIAIgA%2BAAoAIAAgACAAIAAgACAAIAAgACAAIAA8AGkAbQBnACAAcwByAGMAPQB7AHIAZQBhAGMAdABMAG8AZwBvAH0AIABjAGwAYQBzAHMATgBhAG0AZQA9ACIAbABvAGcAbwAgAHIAZQBhAGMAdAAiACAAYQBsAHQAPQAiAFIAZQBhAGMAdAAgAGwAbwBnAG8AIgAgAC8APgAKACAAIAAgACAAIAAgACAAIAA8AC8AYQA%2BAAoAIAAgACAAIAAgACAAPAAvAGQAaQB2AD4ACgAgACAAIAAgACAAIAA8AGgAMQA%2BAFYAaQB0AGUAIAArACAAUgBlAGEAYwB0ADwALwBoADEAPgAKACAAIAAgACAAIAAgADwAZABpAHYAIABjAGwAYQBzAHMATgBhAG0AZQA9ACIAYwBhAHIAZAAiAD4ACgAgACAAIAAgACAAIAAgACAAPABiAHUAdAB0AG8AbgAgAG8AbgBDAGwAaQBjAGsAPQB7ACgAKQAgAD0APgAgAHMAZQB0AEMAbwB1AG4AdAAoACgAYwBvAHUAbgB0ACkAIAA9AD4AIABjAG8AdQBuAHQAIAArACAAMQApAH0APgAKACAAIAAgACAAIAAgACAAIAAgACAAYwBvAHUAbgB0ACAAaQBzACAAewBjAG8AdQBuAHQAfQAKACAAIAAgACAAIAAgACAAIAA8AC8AYgB1AHQAdABvAG4APgAKACAAIAAgACAAIAAgACAAIAA8AHAAPgAKACAAIAAgACAAIAAgACAAIAAgACAARQBkAGkAdAAgADwAYwBvAGQAZQA%2BAHMAcgBjAC8AQQBwAHAALgB0AHMAeAA8AC8AYwBvAGQAZQA%2BACAAYQBuAGQAIABzAGEAdgBlACAAdABvACAAdABlAHMAdAAgAEgATQBSAAoAIAAgACAAIAAgACAAIAAgADwALwBwAD4ACgAgACAAIAAgACAAIAA8AC8AZABpAHYAPgAKACAAIAAgACAAIAAgADwAcAAgAGMAbABhAHMAcwBOAGEAbQBlAD0AIgByAGUAYQBkAC0AdABoAGUALQBkAG8AYwBzACIAPgAKACAAIAAgACAAIAAgACAAIABDAGwAaQBjAGsAIABvAG4AIAB0AGgAZQAgAFYAaQB0AGUAIABhAG4AZAAgAFIAZQBhAGMAdAAgAGwAbwBnAG8AcwAgAHQAbwAgAGwAZQBhAHIAbgAgAG0AbwByAGUACgAgACAAIAAgACAAIAA8AC8AcAA%2BAAoAIAAgACAAIAA8AC8APgAKACAAIAApADsACgB9AAoACgBlAHgAcABvAHIAdAAgAGQAZQBmAGEAdQBsAHQAIABBAHAAcAA7AAoA

### Expected result

I was hoping it would fix the button type error.
However, the following error occurred.

````bash
app.tsx:21:9 lint/a11y/useButtonType ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Provide an explicit type prop for the button element.

    19 │       <h1>Vite + React</h1>
    20 │       <div className="card">
  > 21 │         <button onClick={() => setCount((count) => count + 1)}>
       │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    22 │           count is {count}
    23 │         </button>

  ℹ The default type of a button is submit, which causes the submission of a form when placed inside a `form` element. This is likely not the behaviour that you want inside a React application.

  ℹ Allowed button types are: submit, button or reset


Checked 1 file in 2ms. No fixes needed.
Found 1 error.
lint ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━        

  ✖ Some errors were emitted while running checks.
````

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
The rule doesn't provide a code action, check the diagnostic. The diagnostic is **suggesting** you to add one of the two options: `button` or `reset`. 

Biome can't know which option you need, so it can't provide a code action to automatically fix the problem.
