### ISSUE TITLE
🐛 useLiteralKeys conflicts with TypeScript noPropertyAccessFromIndexSignature

### ISSUE THREAD

**Issue by BorisZubchenko** [biomejs/biome#2416]
### Environment information

```block
CLI:
  Version:                      1.6.4
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v20.11.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.15.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

Having the following `tsconfig.json`:
```jsonc
{
  "compilerOptions": {
    "noPropertyAccessFromIndexSignature": true
    //  etc
  }
}
```
This code gives an error, as expected:
```ts
// TS4111: Property MY_ENV comes from an index signature, so it must be accessed with [MY_ENV].
console.log(process.env.MY_ENV)
```
But changing it to the element access gives the `useLiteralKeys` error:
```ts
// The computed expression can be simplified without the use of a string literal.
console.log(process.env[MY_ENV])
```

### Expected result

When `noPropertyAccessFromIndexSignature` is true, an element access syntax should be a valid case for properties that come from an index signature.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by castarco** [comment]
@BorisZubchenko See https://github.com/biomejs/biome/issues/463 , I opened a similar issue some time ago. For now the recommended approach is to disable this rule.

You can disable it only for TypeScript files with the `overrides` section if you want to be more specific.

**Comment by BorisZubchenko** [comment]
Closing due to https://github.com/biomejs/biome/issues/463#issuecomment-1742449424
