### ISSUE TITLE
🐛 Applying `biome check --apply*` goes over `files.include`. `biome.jsonc` specifically

### ISSUE THREAD

**Issue by FedericoBiccheddu** [biomejs/biome#2420]
### Environment information

```block
CLI:
  Version:                      1.6.4
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm"
  JS_RUNTIME_VERSION:           "v20.11.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.15.6"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

With the following config `biome.jsonc`:
```jsonc
{
	"$schema": "https://biomejs.dev/schemas/1.6.4/schema.json",
	"files": {
		"ignoreUnknown": true,
		"include": ["config/**/*.ts", "source/**/*.ts", "server.ts"],
		"ignore": ["var/**/*"]
	},
    // snip
```
1. Run `biome check --config-path ./ --apply-unsafe ./`
2. `biome.jsonc` is formatted even if not explicitly present in `include`.

This is a problem because in VSCode we cannot use specific extension to format **specific files** so when we format `biome.jsonc` via editor, the output will be always different creating useless changes in git.

### Expected result

I expect `--apply*` to work ONLY on files matching the `include` patterns.

In fact I see `ignore` in this specific case redundant because the folder is not `include`d. 

The problem seems to arise because of the required `PATH` in `biome check [PATH]` (`./` in this case). Given a config AND and `include`, `PATH` seems to be redundant and unnecessary. Even confusing given that checks files that are not `include`d (both the `exclude`d folder and `biome.jsonc' in my case). 

Probably I'm missing something that requires `[PATH]` to be provided.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
You don't need to specify `--config-path ./` because the configuration file is in the working directory.

It is intentional that `biome.json` and `biome.jsonc` are always formatted. This was a user request.
Why do you want to ignore `biome.jsonc`?

**Comment by FedericoBiccheddu** [comment]
> You don't need to specify --config-path ./ because the configuration file is in the working directory.
Thanks, didn't know that.

> It is intentional that biome.json and biome.jsonc are always formatted. This was a user request.
> Why do you want to ignore biome.jsonc?
Because in VSCode json files are formatted with another extension (JSON Language Features) and cannot overridethis just for `biome.jsonc` leading to always have a change in git.

Anyway, I think the problem with `[PATH]` and `include`/`exclude` still applies.

**Comment by GabenGar** [comment]
Actually you can change default JSON formatter in VSCode and even enforce it on the repo level.
Create `settings.json` in `.vscode` folder with this content:
```json
{
  "[json]": {
    "editor.defaultFormatter": "biomejs.biome"
  },
  "[jsonc]": {
    "editor.defaultFormatter": "biomejs.biome"
  }
}
```
As long as you commit this file into the repo, the only way contributors can format JSON files any other way is by explicitly choosing to, because settings in `.vscode/settings.json` have [higher precedence](https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence) over user and workspace settings.

**Comment by FedericoBiccheddu** [comment]
> Actually you can change default JSON formatter in VSCode and even enforce it on the repo level. Create `settings.json` in `.vscode` folder with this content:
> 
> ```json
> {
>   "[json]": {
>     "editor.defaultFormatter": "biomejs.biome"
>   },
>   "[jsonc]": {
>     "editor.defaultFormatter": "biomejs.biome"
>   }
> }
> ```
> 
> As long as you commit this file into the repo, the only way contributors can format JSON files any other way is by explicitly choosing to, because settings in `.vscode/settings.json` have [higher precedence](https://code.visualstudio.com/docs/getstarted/settings#_settings-precedence) over user and workspace settings.

This changes the formatter for EVERY json file, not just for the `biome.json(c)` as I stated before.

Now I think the issue title is misleading. Should I change it with "Biome apply changes to files regardless of `files.include`" or something like that?

**Comment by GabenGar** [comment]
Well the title of the issue is biome CLI formatting its own config, while message I replied to is about VSCode formatting it differently by default. In fact even the OP message mentions it being about VSCode.

**Comment by ematipico** [comment]
If you decide to ignore `biome.json`, you are exposed to potential errors that only our LSP is able to catch.

This is surely a strange edge case. Why can't Biome format its own file configuration?? 🤔

**Comment by FedericoBiccheddu** [comment]
Because VSCode uses JSON Language Features as formatter for a language, not a specific single file. I cannot tell VSCode "use this formatter (`biomejs.biome`) just for `biome.jsonc`. With "Format on save", `biome.jsonc` it will be formatted by VSCode.

Then launching`biome check --apply*` the content changes creating a changeset in git. You have to remember to reformat the code via VSCode if you don't want to commit this kind of changes.

Applying the previous suggestion will going to format every JSON file in my project on save in VSCode with biome and I don't want that.

I can resolve this by putting `biome.jsonc` in `files.ignore` and it works as expected.

---

I can update the original post, remove the `biome.jsonc` part and focus on what to me is the real issue:
launching `biome check --apply ./` with `"include": ["config/**/*.ts", "source/**/*.ts", "server.ts"],` formats OTHERS folders (like `var/**/*`) that are not under `files.include`. I do not expect to format other folders and have to curate a list of `files.ignore`d paths because of that.

Should I update the issue?

**Comment by ematipico** [comment]
Yes @FedericoBiccheddu, we should focus on one single issue. Also, make sure to update to the latest. Maybe your issue was fixed.
