### ISSUE TITLE
📎 Implement `lint/useJsxCurlyBraceConvention` - `react/jsx-curly-brace-presence`

### ISSUE THREAD

**Issue by itsyoboieltr** [biomejs/biome#2435]
### Description
Implement [react/jsx-curly-brace-presence](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md).

Want to contribute? Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

I think the original naming is a bit misleading, as this is not only for react. Other frameworks using jsx can benefit from this, like [Solid](https://www.solidjs.com)

Suggested name: `useJsxCurlyBraceConvention`

**Comment by ematipico** [comment]
Are you going to implement the rule @itsyoboieltr?

**Comment by Geczy** [comment]
Also looking forward to this a lot! @itsyoboieltr

**Comment by itsyoboieltr** [comment]
Unfortunately, I don't have time to commit to this in the near future, but I opened the issue as I would love to see this implemented.

**Comment by ematipico** [comment]
Thank you, but usually, we want to go through a discussion first instead of opening tasks without context and agreeing on something. In this case, can you comment here? https://github.com/biomejs/biome/discussions/3

Maybe someone already expressed interest.

**Comment by dyc3** [comment]
I would like to give this a shot.

**Comment by izakfilmalter** [comment]
Busy migrating from es-lint / prettier to biome.  Could we get an option similare to 'always' from `react/jsx-curly-brace-presence`?
