### ISSUE TITLE
When there's a duplicate named import, the formatter removes all existing named imports

### ISSUE THREAD

**Issue by aliarasea** [biomejs/biome#2488]
### Environment information

```block
CLI:
  Version:                      1.6.4
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

1. open a project code base which has multiple files in visual studio code
2. import duplicated named import a file then organize imports with biome

### Expected result

It removes all existing named imports

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Please provide a reproduction or detailed instructions to reproduce the issue.

**Comment by aliarasea** [comment]
1. I have duplicate import as below;
<img width="667" alt="Screenshot 2024-04-18 at 12 34 08" src="https://github.com/biomejs/biome/assets/8797590/f05fc9d2-9292-46c7-981d-80e8f5ccd97a">


2. I organize imports with biome
<img width="948" alt="Screenshot 2024-04-18 at 10 26 25" src="https://github.com/biomejs/biome/assets/8797590/cb472af8-2b70-4e40-b9cb-b3b42e9e0a4d">

3. It removes all existing named imports 
<img width="191" alt="Screenshot 2024-04-18 at 12 34 54" src="https://github.com/biomejs/biome/assets/8797590/b6637528-f04b-4610-9eb6-f1ab7b0c8992">



I have an Nx project where I use ESLint and Biome together, and I encountered this issue there. When I created a new project and used only Biome, I couldn't reproduce the issue.

[package.json](https://github.com/biomejs/biome/files/15023030/package.json)
[nx.json](https://github.com/biomejs/biome/files/15023031/nx.json)

**Comment by ematipico** [comment]
Sorry @aliarasea but we require a minimal reproduction that we can download and play with. Maybe a codesandbox or a repository.

**Comment by afonsojramos** [comment]
This was happening to me if I had both `source.organizeImports.biome` and `source.organizeImports` enabled, can you double check that @aliarasea.
@ematipico maybe we can add a warning related to this in the docs, if not already

**Comment by ematipico** [comment]
If that's a bug, it should be fixed. However, no reproduction is provided, so we can't help.
