### ISSUE TITLE
📎  Implement unit-no-unknown

### ISSUE THREAD

**Issue by togami2864** [biomejs/biome#2515]
Implmenet [unit-no-unknown](https://stylelint.io/user-guide/rules/unit-no-unknown)

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by neokidev** [comment]
Hello! While I haven't contributed to biome before, I'm interested in tackling this issue.

**Comment by togami2864** [comment]
@neokidev Thanks! Feel free to ask if you have any questions, as the documents aren't organized yet:)

**Comment by neokidev** [comment]
I've implemented the basic rules, but I'm still working out the details and have some questions:

- Currently, the `F` unit specified in `@font-face`'s `unicode-range` is being rejected. It seems that we need to check the parent node. Do you have any suggestions for a solution?
- Also, dimensions including the unit `x` are being parsed as `CssRegularDimension` and accepted. Is this tokenization correct?
- How closely should we mimic `stylelint`'s `unit-no-unknown` rule?
  - Should we implement `stylelint`'s options such as `ignoreUnits` and `ignoreFunctions`?
  - Should we cover syntaxes like `postcss-scss` and `postcss-less` as well? (These were included in `stylelint`'s test cases)

You can find the test code for `stylelint` here:
https://github.com/stylelint/stylelint/blob/main/lib/rules/unit-no-unknown/__tests__/index.mjs

I've created a draft PR ([link](https://github.com/biomejs/biome/pull/2535)) with my current implementation, which you can refer to for more context. Thank you for your help!

**Comment by togami2864** [comment]
> Currently, the F unit specified in `@font-face`'s unicode-range is being rejected. It seems that we need to check the parent node. Do you have any suggestions for a solution?

I think this is parser's bug.

> Also, dimensions including the unit x are being parsed as CssRegularDimension and accepted. Is this tokenization correct?

I think the parser [corrects](https://developer.mozilla.org/en-US/docs/Web/CSS/resolution#:~:text=image%2Dresolution.-,x,Alias%20for%20dppx.,-Note%3A%20Although) but it's a edge case of this rule. If it's too difficult to solve, please skip it and file an issue.

> Should we implement stylelint's options such as ignoreUnits and ignoreFunctions?

If possible. You can split another PR.

> Should we cover syntaxes like postcss-scss and postcss-less as well? (These were included in stylelint's test cases)

You can ignore them right now.

**Comment by neokidev** [comment]
I have created the PR (#2535).

However, implementing the options will require more time to catch up, so I will address this in another PR. Additionally, there are conflicts present, but given the frequent updates expected for biome_css_analyzer, I thought it would be best to resolve these conflicts after the review.
