### ISSUE TITLE
🐛 command `@biomejs/biome migrate`don't read config in package.json

### ISSUE THREAD

**Issue by alex-maxime** [biomejs/biome#2516]
### Environment information

```block
CLI:
  Version:                      1.7.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.11.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

1.  Install biome with `npm install --save-dev --save-exact @biomejs/biome@latest`
2. Initialize with `npx @biomejs/biome init` . `biome.json` is created with this content : 
```json
{
	"$schema": "https://biomejs.dev/schemas/1.7.0/schema.json",
	"organizeImports": {
		"enabled": true
	},
	"linter": {
		"enabled": true,
		"rules": {
			"recommended": true
		}
	}
}
```
3. make sure you have `eslintConfig` and `prettier` rules inside `package.json` : 
<img width="541" alt="image" src="https://github.com/biomejs/biome/assets/3592127/eb93e401-0d20-46c1-bce0-4c75b3877022">
4. run `npx @biomejs/biome migrate`
5. Nothing happen `biome.json` is still the same

You can test it with this repos :
https://github.com/alex-maxime/nestjs-playground

### Expected result

biome should also read config inside package.json for pretier and elsint 

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
Did you use the subcommands `@biomejs/biome migrate prettier` and `@biomejs/biome migrate eslint`?

`@biomejs/biome migrate` ,migrates between different Biome versions:

**Comment by alex-maxime** [comment]
@Conaclos thank you, i did not realise i should add eslint or prettier.
`npx @biomejs/biome migrate eslint` & `npx @biomejs/biome migrate prettier` work.
i close the issue ☺️
