### ISSUE TITLE
🐛 Suppression comments on top of the file have no effect

### ISSUE THREAD

**Issue by Zombobot1** [biomejs/biome#2517]
### Environment information

```block
Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

When migrating from ESLint, I found that there was no way to disable a lint rule for a file using a comment. This was one of the reasons my team couldn't migrate from ESLint to Biome. I can find open issues for other problems that bock us. I think this issue might be helpful for other teams considering migrating from ESLint.

### Expected result

Suppression comment on top of the file disables the rule across it matching ESLint behavior.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
I am going to close it because it isn't a bug, but a missing feature.

Other people requested the feature in discussions. For example https://github.com/biomejs/biome/discussions/605
