### ISSUE TITLE
📎 Implement `noUselessUndefinedInitialization` - `eslint/no-undef-init`

### ISSUE THREAD

**Issue by unvalley** [biomejs/biome#2533]
### Description

[no-undef-init - ESLint - Pluggable JavaScript Linter](https://eslint.org/docs/latest/rules/no-undef-init/)

Want to contribute? Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our contributing guide and analyzer contributing guide.

**Comment by lutaok** [comment]
Hello @unvalley , I would like to take this on if that's okay!

**Comment by Conaclos** [comment]
We could shorten a bit the name using `Init` instead of `Initialization`?

**Comment by unvalley** [comment]
It's a bit redundant but we use `initializers` in lint rule name. 
e.g, [useEnumInitializers (since v1.0.0) | Biome](https://biomejs.dev/linter/rules/use-enum-initializers/#_top)

I think `Initialization` can be differentiate from that.
