### ISSUE TITLE
📎  Implement keyframe-declaration-no-important

### ISSUE THREAD

**Issue by togami2864** [biomejs/biome#2536]
## Description

Implement [keyframe-declaration-no-important](https://stylelint.io/user-guide/rules/keyframe-declaration-no-important)

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by isnakode** [comment]
i'm interested

**Comment by ematipico** [comment]
@isnakode Remember to follow the rule pillars when writing the diagnostics: https://biomejs.dev/linter/#rule-pillars

**Comment by isnakode** [comment]
should i name the lint noImportantKeyframeDeclaration or noImportantInKeyframeDeclaration? or u have better suggestion?

**Comment by ematipico** [comment]
`noImportantInKeyframe`?

**Comment by togami2864** [comment]
close #2542
