### ISSUE TITLE
💅 [noMisplacedAssertion] Not supporting expect matchers from vitest/jest outside of it, it.each, test, test.each

### ISSUE THREAD

**Issue by motss** [biomejs/biome#2547]
### Environment information

```bash
❯ ppm biome rage --linter
CLI:
  Version:                      1.7.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.0.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.15.7"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 false

Linter:
  Recommended:                  true
  All:                          false
  Rules:                        a11y/all = true
                                complexity/all = true
                                complexity/noExcessiveCognitiveComplexity = "off"
                                complexity/noStaticOnlyClass = "off"
                                complexity/noUselessSwitchCase = "off"
                                correctness/all = true
                                nursery/all = true
                                nursery/noConsole = "off"
                                nursery/useImportRestrictions = "off"
                                performance/all = true
                                security/all = true
                                style/all = true
                                style/useNamingConvention = {"level":"error","options":{"strictCase":false}}
                                suspicious/all = true
                                suspicious/useAwait = "off"

Workspace:
  Open Documents:               0
```

### Rule name

noMisplacedAssertion

### Playground link

[Link](https://biomejs.dev/playground/?lintRules=all&files.main.tsx=aQBtAHAAbwByAHQAIAB7ACAAaQB0ACwAIABlAHgAcABlAGMAdAAgAH0AIABmAHIAbwBtACAAJwB2AGkAdABlAHMAdAAnADsACgBpAG0AcABvAHIAdAAgAHsAIAB0AGUAcwB0AEMAYQBzAGUAcwAgAH0AIABmAHIAbwBtACAAJwAuAC8AdABlAHMAdAAtAGMAYQBzAGUAcwAnADsACgAKAC8ALwAgAHIAZQBkAHUAYwBlAGQAIABjAG8AZABlACAAZgBvAHIAIABiAHIAZQB2AGkAdAB5AAoAZABlAGMAbABhAHIAZQAgAGYAdQBuAGMAdABpAG8AbgAgAHMAbwBtAGUARgBuACgAaQBuAHAAdQB0ADoAIABzAHQAcgBpAG4AZwApADoAIAB2AG8AaQBkADsACgAvAC8AIAByAGUAZAB1AGMAZQBkACAAYwBvAGQAZQAgAGYAbwByACAAYgByAGUAdgBpAHQAeQAKAGQAZQBjAGwAYQByAGUAIABmAHUAbgBjAHQAaQBvAG4AIABzAG8AbQBlAEkAbgB0AGUAcgBuAGEAbABGAG4AKAApADoAIAB2AG8AaQBkADsACgAKAGUAeABwAGUAYwB0AC4AZQB4AHQAZQBuAGQAKAB7AAoAIAB0AG8AQgBlAEYAbwBvADoAIAAoAHIAZQBjAGUAaQB2AGUAZAAsACAAZQB4AHAAZQBjAHQAZQBkACkAIAA9AD4AIAB7AAoAIAAgACAAIABpAGYAIAAoAHIAZQBjAGUAaQB2AGUAZAAgACEAPQA9ACAAJwBmAG8AbwAnACkAIAB7AAoAIAAgACAAIAAgACAAcgBlAHQAdQByAG4AIAB7AAoAIAAgACAAIAAgACAAIAAgAG0AZQBzAHMAYQBnAGUAOgAgACgAKQAgAD0APgAgAGAAZQB4AHAAZQBjAHQAZQBkACAAJAB7AHIAZQBjAGUAaQB2AGUAZAB9ACAAdABvACAAYgBlACAAZgBvAG8AYAAsAAoAIAAgACAAIAAgACAAIAAgAHAAYQBzAHMAOgAgAGYAYQBsAHMAZQAsAAoAIAAgACAAIAAgACAAfQAKACAAIAAgACAAfQAKACAAIAB9ACwACgB9ACkAOwAKAAoAZQB4AHAAZQBjAHQACgAuAGEAZABkAEUAcQB1AGEAbABpAHQAeQBUAGUAcwB0AGUAcgBzAAoAKABbAC8AKgAqACAAdAByAHUAbgBjAGEAdABlAGQAIABmAG8AcgAgAGIAcgBlAHYAaQB0AHkAIAAqAC8AXQApADsACgAKAGUAeABwAGUAYwB0AC4AYQBkAGQAUwBuAGEAcABzAGgAbwB0AFMAZQByAGkAYQBsAGkAegBlAHIAKAB7ACAALwAqACoAIAB0AHIAdQBuAGMAYQB0AGUAZAAgAGYAbwByACAAYgByAGUAdgBpAHQAeQAgACoALwAgAH0AKQA7AAoACgBpAHQALgBlAGEAYwBoACgAdABlAHMAdABDAGEAcwBlAHMAKQAoACcAdABlAHMAdAAnACwAIAAoAHsAIABpAG4AcAB1AHQALAAgAG8AdQB0AHAAdQB0ACAAfQApACAAPQA%2BACAAewAKACAAIABzAG8AbQBlAEYAbgAoAGkAbgBwAHUAdAApADsACgAKACAAIABlAHgAcABlAGMAdAAoACcAdABlAHMAdAAnACkALgB0AG8AQgBlAEYAbwBvACgAKQA7AAoAIAAgAGUAeABwAGUAYwB0ACgAcwBvAG0AZQBJAG4AdABlAHIAbgBhAGwARgBuACkALgB0AG8AQgBlAEMAYQBsAGwAZQBkAFcAaQB0AGgAKABpAG4AcAB1AHQALAAgAG8AdQB0AHAAdQB0ACkAOwAKAH0AKQA7AA%3D%3D&files.test-cases.ts=aQBtAHAAbwByAHQAIAB7ACAAZQB4AHAAZQBjAHQAIAB9ACAAZgByAG8AbQAgACcAdgBpAHQAZQBzAHQAJwA7AAoACgBlAHgAcABvAHIAdAAgAGMAbwBuAHMAdAAgAHQAZQBzAHQAQwBhAHMAZQBzACAAPQAgAFsACgAgACAAewAKACAAIAAgACAAaQBuAHAAdQB0ADoAIAAnAGUAeABwAGUAYwB0AC4AYQBuAHkAJwAsAAoAIAAgACAAIABvAHUAdABwAHUAdAA6ACAAZQB4AHAAZQBjAHQALgBhAG4AeQAoAFMAdAByAGkAbgBnACkALAAKACAAIAB9ACwACgAgACAAewAKACAAIAAgACAAaQBuAHAAdQB0ADoAIAAnAGUAeABwAGUAYwB0AC4AYQBuAHkAdABoAGkAbgBnACcALAAKACAAIAAgACAAbwB1AHQAcAB1AHQAOgAgAGUAeABwAGUAYwB0AC4AYQBuAHkAdABoAGkAbgBnACgAKQAsAAoAIAAgAH0ALAAKACAAIAB7AAoAIAAgACAAIABpAG4AcAB1AHQAOgAgACcAZQB4AHAAZQBjAHQALgBjAGwAbwBzAGUAVABvACcALAAKACAAIAAgACAAbwB1AHQAcAB1AHQAOgAgAGUAeABwAGUAYwB0AC4AYwBsAG8AcwBlAFQAbwAoADAALAAgADEAKQAsAAoAIAAgAH0ALAAKACAAIAB7AAoAIAAgACAAIABpAG4AcAB1AHQAOgAgACcAZQB4AHAAZQBjAHQALgBhAHIAcgBhAHkAQwBvAG4AdABhAGkAbgBpAG4AZwAnACwACgAgACAAIAAgAG8AdQB0AHAAdQB0ADoAIABlAHgAcABlAGMAdAAuAGEAcgByAGEAeQBDAG8AbgB0AGEAaQBuAGkAbgBnACgAWwAxACwAMgAsADMAXQApACwACgAgACAAfQAsAAoAIAAgAHsACgAgACAAIAAgAGkAbgBwAHUAdAA6ACAAJwBlAHgAcABlAGMAdAAuAG8AYgBqAGUAYwB0AEMAbwBuAHQAYQBpAG4AaQBuAGcAJwAsAAoAIAAgACAAIABvAHUAdABwAHUAdAA6ACAAZQB4AHAAZQBjAHQALgBvAGIAagBlAGMAdABDAG8AbgB0AGEAaQBuAGkAbgBnACgAewAgAGEAOgAgADEAIAB9ACkALAAKACAAIAB9ACwACgAgACAAewAKACAAIAAgACAAaQBuAHAAdQB0ADoAIAAnAGUAeABwAGUAYwB0AC4AcwB0AHIAaQBuAGcAQwBvAG4AdABhAGkAbgBpAG4AZwAnACwACgAgACAAIAAgAG8AdQB0AHAAdQB0ADoAIABlAHgAcABlAGMAdAAuAHMAdAByAGkAbgBnAEMAbwBuAHQAYQBpAG4AaQBuAGcAKAAnADEAMgAzACcAKQAKACAAIAB9ACwACgAgACAAewAKACAAIAAgACAAaQBuAHAAdQB0ADoAIAAnAGUAeABwAGUAYwB0AC4AcwB0AHIAaQBuAGcATQBhAHQAYwBoAGkAbgBnACcALAAKACAAIAAgACAAbwB1AHQAcAB1AHQAOgAgAGUAeABwAGUAYwB0AC4AcwB0AHIAaQBuAGcATQBhAHQAYwBoAGkAbgBnACgALwB0AGUAcwB0AC8AaQApAAoAIAAgAH0ALAAKAF0AOwA%3D)

### Expected result

The following matchers should be allowed outside of `it()`, `it.each()`, `test()`, and `test.each()`:

1. `expect.any(<constructor>)` - [vitest](https://vitest.dev/api/expect.html#expect-any), [jest](https://jestjs.io/docs/expect#expectanyconstructor)
2. `expect.anything()` - [vitest](https://vitest.dev/api/expect.html#expect-anything), [jest](https://jestjs.io/docs/expect#expectanything)
3. `expect.closeTo` - [vitest](https://vitest.dev/api/expect.html#expect-closeto), [jest](https://jestjs.io/docs/expect#expectclosetonumber-numdigits)
4. `expect.arrayContaining` - [vitest](https://vitest.dev/api/expect.html#expect-arraycontaining), [jest](https://jestjs.io/docs/expect#expectarraycontainingarray)
5. `expect.objectContaining` - [vitest](https://vitest.dev/api/expect.html#expect-objectcontaining), [jest](https://jestjs.io/docs/expect#expectobjectcontainingobject)
6. `expect.stringContaining` - [vitest](https://vitest.dev/api/expect.html#expect-stringcontaining), [jest](https://jestjs.io/docs/expect#expectstringcontainingstring)
7. `expect.stringMatching` - [vitest](https://vitest.dev/api/expect.html#expect-stringmatching), [jest](https://jestjs.io/docs/expect#expectstringmatchingstring--regexp)
8. `expect.extend` - [vitest](https://vitest.dev/api/expect.html#expect-extend), [jest](https://jestjs.io/docs/expect#expectextendmatchers)
9. `expect.addEqualityTesters` - [vitest](https://vitest.dev/api/expect.html#expect-addequalitytesters), [jest](https://jestjs.io/docs/expect#expectaddequalitytesterstesters)
10. `expect.addSnapshotSerializer` - [vitest](https://vitest.dev/api/expect.html#expect-addsnapshotserializer), [jest](https://jestjs.io/docs/expect#expectaddsnapshotserializerserializer)

It does not seem to affect [expect](https://deno.land/x/expect@v0.4.0) from `Deno.test`.

## Actual behavior

Getting the error/ warning below when `expect.any(<constructor>)` and `expect.anything()` is outside of `it()`, `it.each()`, `test()`, and `test.each()`:

> The assertion isn't inside a it(), test() or Deno.test() function call.biome[lint/nursery/noMisplacedAssertion](https://biomejs.dev/linter/rules/no-misplaced-assertion)

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Where is `expect.anything` coming from? Which framework/runtime uses it ?

**Comment by motss** [comment]
vitest and jest use them.

**Comment by motss** [comment]
> Where is `expect.anything` coming from? Which framework/runtime uses it ?

`vitest` and `jest` have them. There are 10 `expect` matchers that need to be included, I've included them in the `Expected result` section.

**Comment by ematipico** [comment]
This is really easy to fix, I'm happy to point people to the right direction

**Comment by fujiyamaorange** [comment]
@ematipico 
May I try this issue? 👀

**Comment by ematipico** [comment]
All yours
