### ISSUE TITLE
📎 Implement `useExplicitLengthCheck` - `unicorn/explicit-length-check`

### ISSUE THREAD

**Issue by minht11** [biomejs/biome#2564]
### Description

Implement [unicorn/explicit-length-check](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/explicit-length-check.md)

This rule takes around 10% of lint time in one of my projects, so it should be nice perf improvement for people migrating to biome.

Questions:
1. Should support comparison options?
<img width="1042" alt="image" src="https://github.com/biomejs/biome/assets/8914032/9399a718-c2a0-4355-bc01-2e21bbc92c33">
I would go with no for now. Github code search for the rule][1] returns only 62 results, including false positives. Since this rule is recomended by unicorn vast majority users will be using `greater-than`. I personally do not see much value for the option, but I can be convinced.

2. Which properties to support checks on? Unicorn supports only `length` and `size`, but I can see value in supporting additional properties such as `byteLength`, `byteOffset`.

[1] https://github.com/search?q=not-equal+%22unicorn%2Fexplicit-length-check%22++-language%3AMarkdown+&type=code

**Comment by minht11** [comment]
Will try to work on it.

**Comment by Conaclos** [comment]
Yeah, I don't think we need any option.

> Which properties to support checks on? Unicorn supports only length and size, but I can see value in supporting additional properties such as byteLength, byteOffset.

Good point.
