### ISSUE TITLE
💅 `useJsxKeyInIterable` bugs

### ISSUE THREAD

**Issue by nstepien** [biomejs/biome#2590]
### Environment information

```bash
Playground
```

### Rule name

useJsxKeyInIterable

### Playground link

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&lintRules=all&code=ZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABUAGUAcwB0ACgAKQAgAHsACgAgACAAcgBlAHQAdQByAG4AIABbAF0ALgBtAGEAcAAoACgAaQB0AGUAbQApACAAPQA%2BACAAewAKACAAIAAgACAAYwBvAG4AcwB0ACAAZABpAHYAIAA9ACAAPABkAGkAdgAgAGsAZQB5AD0AewBpAHQAZQBtAC4AaQBkAH0AIAAvAD4AOwAKAAoAIAAgACAAIAAvAC8AIABPAEsACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAaQB0AGUAbQAuAGMAbwBuAGQAaQB0AGkAbwBuACAAPwAgAGQAaQB2ACAAOgAgADwAZABpAHYAIABrAGUAeQA9AHsAaQB0AGUAbQAuAGkAZAB9AD4AewBkAGkAdgB9ADwALwBkAGkAdgA%2BADsACgAgACAAfQApADsACgB9AAoACgBlAHgAcABvAHIAdAAgAGYAdQBuAGMAdABpAG8AbgAgAFQAZQBzAHQAMQAoACkAIAB7AAoAIAAgAHIAZQB0AHUAcgBuACAAWwBdAC4AbQBhAHAAKAAoAGkAdABlAG0AKQAgAD0APgAgAHsACgAgACAAIAAgAC8ALwAgAHMAaABvAHUAbABkACAAZgBsAGEAZwAgAHQAaABpAHMACgAgACAAIAAgAGMAbwBuAHMAdAAgAGQAaQB2ACAAPQAgADwAZABpAHYAIAAvAD4AOwAKAAoAIAAgACAAIAByAGUAdAB1AHIAbgAgAGkAdABlAG0ALgBjAG8AbgBkAGkAdABpAG8AbgAgAD8AIABkAGkAdgAgADoAIAA8AGQAaQB2ACAAawBlAHkAPQB7AGkAdABlAG0ALgBpAGQAfQA%2BAHsAZABpAHYAfQA8AC8AZABpAHYAPgA7AAoAIAAgAH0AKQA7AAoAfQAKAAoAZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABUAGUAcwB0ADIAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgAFsAXQAuAG0AYQBwACgAKABpAHQAZQBtACkAIAA9AD4AIAB7AAoAIAAgACAAIABjAG8AbgBzAHQAIABkAGkAdgAgAD0AIAA8AGQAaQB2ACAAawBlAHkAPQB7AGkAdABlAG0ALgBpAGQAfQAgAC8APgA7AAoACgAgACAAIAAgAC8ALwAgAHMAaABvAHUAbABkACAAbgBvAHQAIABmAGwAYQBnACAAdABoAGkAcwAKACAAIAAgACAAcgBlAHQAdQByAG4AIAA8AD4AewBpAHQAZQBtAC4AYwBvAG4AZABpAHQAaQBvAG4AIAA%2FACAAZABpAHYAIAA6ACAAPABkAGkAdgAgAGsAZQB5AD0AewBpAHQAZQBtAC4AaQBkAH0APgB7AGQAaQB2AH0APAAvAGQAaQB2AD4AfQA8AC8APgA7AAoAIAAgAH0AKQA7AAoAfQAKAAoAZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABUAGUAcwB0ADMAKAApACAAewAKACAAIAByAGUAdAB1AHIAbgAgAFsAXQAuAG0AYQBwACgAKABpAHQAZQBtACkAIAA9AD4AIAB7AAoAIAAgACAAIABpAGYAIAAoAGkAdABlAG0ALgBjAG8AbgBkAGkAdABpAG8AbgApACAAewAKACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAPABkAGkAdgAgAGsAZQB5AD0AewBpAHQAZQBtAC4AaQBkAH0AIAAvAD4AOwAKACAAIAAgACAAfQAKAAoAIAAgACAAIAAvAC8AIABPAEsACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAbgB1AGwAbAA7AAoAIAAgAH0AKQA7AAoAfQAKAAoAZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABUAGUAcwB0ADQAKAB7ACAAZABhAHQAYQAgAH0AKQAgAHsACgAgACAAcgBlAHQAdQByAG4AIAAoAAoAIAAgACAAIAA8AD4ACgAgACAAIAAgACAAIAB7AFsAXQAuAG0AYQBwACgAKABpAHQAZQBtACkAIAA9AD4AIAB7AAoAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAaQB0AGUAbQAuAGMAbwBuAGQAaQB0AGkAbwBuACkAIAB7AAoAIAAgACAAIAAgACAAIAAgACAAIAByAGUAdAB1AHIAbgAgADwAZABpAHYAIABrAGUAeQA9AHsAaQB0AGUAbQAuAGkAZAB9ACAALwA%2BADsACgAgACAAIAAgACAAIAAgACAAfQAKAAoAIAAgACAAIAAgACAAIAAgAC8ALwAgAHMAaABvAHUAbABkACAAbgBvAHQAIABmAGwAYQBnACAAdABoAGkAcwAKACAAIAAgACAAIAAgACAAIAByAGUAdAB1AHIAbgAgAG4AdQBsAGwAOwAKACAAIAAgACAAIAAgAH0AKQB9AAoAIAAgACAAIAAgACAAewAvACoAIABzAGgAbwB1AGwAZAAgAG4AbwB0ACAAZgBsAGEAZwAgAHQAaABpAHMAIAAqAC8AfQAKACAAIAAgACAAIAAgAHsAZABhAHQAYQAuAHIAZQBkAHUAYwBlACgAKAB0AG8AdABhAGwALAAgAG4AZQB4AHQAKQAgAD0APgAgAHQAbwB0AGEAbAAgACsAIABuAGUAeAB0AC4AdgBhAGwAdQBlACwAIAAwACkAfQAKACAAIAAgACAAPAAvAD4ACgAgACAAKQA7AAoAfQA%3D

### Expected result

I found some false positives when enabling this rule in our codebase.
Looks like there are discrepancies when the array or returned value are not wrapped in JSX.

Also, Biome warns
>Cannot determine whether this child has the required key prop.

I don't find this message helpful, it's not actionable, what do you want me to do?

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by erictaylor** [comment]
Additionally, I have noticed that components like the following are flagged:

```tsx
const items = [
  {
    condition: true,
    key: 'foo',
    label: 'foo',
  },
  {
    condition: false,
    key: 'bar',
    label: 'bar',
  }
];

const DemoComponent = () => {
  return (
    <ul>
      {/* marked for "Cannot determine whether this child has the required key prop" */}
      {items.map((item) => item.condition && (<li key={item.key}>{item.label}</li>))}
    </ul>
  );
};
```
[Playground link](https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&lintRules=all&code=YwBvAG4AcwB0ACAAaQB0AGUAbQBzACAAPQAgAFsACgAgACAAewAKACAAIAAgACAAYwBvAG4AZABpAHQAaQBvAG4AOgAgAHQAcgB1AGUALAAKACAAIAAgACAAawBlAHkAOgAgACcAZgBvAG8AJwAsAAoAIAAgACAAIABsAGEAYgBlAGwAOgAgACcAZgBvAG8AJwAsAAoAIAAgAH0ALAAKACAAIAB7AAoAIAAgACAAIABjAG8AbgBkAGkAdABpAG8AbgA6ACAAZgBhAGwAcwBlACwACgAgACAAIAAgAGsAZQB5ADoAIAAnAGIAYQByACcALAAKACAAIAAgACAAbABhAGIAZQBsADoAIAAnAGIAYQByACcALAAKACAAIAB9AAoAXQA7AAoACgBjAG8AbgBzAHQAIABEAGUAbQBvAEMAbwBtAHAAbwBuAGUAbgB0ACAAPQAgACgAKQAgAD0APgAgAHsACgAgACAAcgBlAHQAdQByAG4AIAAoAAoAIAAgACAAIAA8AHUAbAA%2BAAoAIAAgACAAIAAgACAAewAvACoAIABtAGEAcgBrAGUAZAAgAGYAbwByACAAIgBDAGEAbgBuAG8AdAAgAGQAZQB0AGUAcgBtAGkAbgBlACAAdwBoAGUAdABoAGUAcgAgAHQAaABpAHMAIABjAGgAaQBsAGQAIABoAGEAcwAgAHQAaABlACAAcgBlAHEAdQBpAHIAZQBkACAAawBlAHkAIABwAHIAbwBwACIAIAAqAC8AfQAKACAAIAAgACAAIAAgAHsAaQB0AGUAbQBzAC4AbQBhAHAAKAAoAGkAdABlAG0AKQAgAD0APgAgAGkAdABlAG0ALgBjAG8AbgBkAGkAdABpAG8AbgAgACYAJgAgACgAPABsAGkAIABrAGUAeQA9AHsAaQB0AGUAbQAuAGsAZQB5AH0APgB7AGkAdABlAG0ALgBsAGEAYgBlAGwAfQA8AC8AbABpAD4AKQApAH0ACgAgACAAIAAgADwALwB1AGwAPgAKACAAIAApADsACgB9ADsA)

**Comment by dyc3** [comment]
I'm a little confused by one of the tests in the linked playground.

```jsx
export function Test2() {
  return [].map((item) => {
    const div = <div id={item.id} />;

    // should not flag this
    return <>{item.condition ? div : <div key={item.id}>{div}</div>}</>;
  });
}
```

The `const div` doesn't have a `key` prop. Is `id` supposed to be `key`?

**Comment by nstepien** [comment]
Yes my bad, I've updated the playground link

**Comment by dyc3** [comment]
I'd like to be assigned this.

**Comment by Sec-ant** [comment]
> I'd like to be assigned this.

Done :)
