### ISSUE TITLE
📝 Formatter replaces emojis

### ISSUE THREAD

**Issue by melMass** [biomejs/biome#2604]
### Environment information

```bash
CLI:
  Version:                      1.7.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Formatter:
  Format with errors:           false
  Indent style:                 Tab
  Indent size:                  0
  Indent width:                 0
  Line ending:                  Lf
  Line width:                   80
  Attribute position:           Auto
  Ignore:                       []
  Include:                      []

JavaScript Formatter:
  Enabled:                      false
  JSX quote style:              Double
  Quote properties:             AsNeeded
  Trailing comma:               All
  Semicolons:                   AsNeeded
  Arrow parentheses:            Always
  Bracket spacing:              false
  Bracket same line:            false
  Quote style:                  Single
  Indent style:                 unset
  Indent size:                  unset
  Indent width:                 2
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           Auto

JSON Formatter:
  Enabled:                      true
  Indent style:                 unset
  Indent width:                 unset
  Indent size:                  unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
    "$schema": "https://biomejs.dev/schemas/1.6.1/schema.json",
    "organizeImports": {
        "enabled": true
    },
    "linter": {
        "enabled": true,
        "rules": {
            "recommended": true
        }
    },
    "formatter": {
        "lineEnding": "lf"
    },
    "javascript": {
        "formatter": {
            "quoteStyle": "single",
            "semicolons": "asNeeded",
            "indentWidth": 2
        }
    }
}
```

### Playground link

https://biomejs.dev/playground/?code=CgBlAHgAcABvAHIAdAAgAGMAbwBuAHMAdAAgAGkAbgBmAG8ATABvAGcAZwBlAHIAIAA9ACAAYwByAGUAYQB0AGUATABvAGcAZwBlAHIAKAAnADkhD%2F4nACwAIAAnAHkAZQBsAGwAbwB3ACcAKQAKAGUAeABwAG8AcgB0ACAAYwBvAG4AcwB0ACAAdwBhAHIAbgBMAG8AZwBnAGUAcgAgAD0AIABjAHIAZQBhAHQAZQBMAG8AZwBnAGUAcgAoACcAoCYP%2FicALAAgACcAbwByAGEAbgBnAGUAJwAsACAAJwB3AGEAcgBuACcAKQAKAGUAeABwAG8AcgB0ACAAYwBvAG4AcwB0ACAAZQByAHIAbwByAEwAbwBnAGcAZQByACAAPQAgAGMAcgBlAGEAdABlAEwAbwBnAGcAZQByACgAJwA92CXdJwAsACAAJwByAGUAZAAnACwAIAAnAGUAcgByAG8AcgAnACkACgBlAHgAcABvAHIAdAAgAGMAbwBuAHMAdAAgAHMAdQBjAGMAZQBzAHMATABvAGcAZwBlAHIAIAA9ACAAYwByAGUAYQB0AGUATABvAGcAZwBlAHIAKAAnAAUnJwAsACAAJwBnAHIAZQBlAG4AJwApAAoACgA%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by melMass** [comment]
I can't reproduce the issue on the playground, but this is what happens in neovim:

![biome_emojis](https://github.com/biomejs/biome/assets/7041726/e0424f86-defc-41f4-8e68-f4780582483e)

**Comment by huijiewei** [comment]
webstorm has same problem

**Comment by redbmk** [comment]
looks like it might have something to do with the way neovim is exporting to stdout:

before:
```typescript
console.log("⚠️ ")
```

highlight the line with `V`, then:
```vim
:'<,'>!bunx biome format --stdin-file-path=asdf.ts
```

after:
```typescript
console.log("! ");
```

but if I copy and paste that directly into the console it seems fine:

```shell
❯ echo 'console.log("⚠<fe0f> ")' | bunx biome check --apply --stdin-file-path=asdf.ts
console.log("⚠️ ");
```

I'm not entirely sure where the `<fe0f>` is coming from, but when I paste into zsh/iterm2 that shows up.

**Comment by redbmk** [comment]
ok it might still have something to do with biome not quite understanding what encoding stdin is in or something...

```vim
:'<,'>!cat
```
leaves it untouched, and:

```vim
:'<,'>!cat > temp.ts && bunx biome check --apply temp.ts && cat temp.ts
```

gives me:

```typescript
Checked 1 file in 2ms. Fixed 1 file.
console.log("⚠️ ");
```

**Comment by redbmk** [comment]
Hmm I'm also finding this pretty confusing. Without `--apply` it seems to print an error but the exit code is still `0`. With `--apply` the output looks identical.

![image](https://github.com/biomejs/biome/assets/83964/41b298df-6c7a-437d-844b-caa053fdc43f)

When putting them through `diff` or piping through stdin they do look different though, so I guess it's not actually a neovim issue

![image](https://github.com/biomejs/biome/assets/83964/0b497a4f-dbaa-4df8-b9e5-1e25791cb197)

**Comment by redbmk** [comment]
OK I think I figured it out. I believe biome is trying to strip ansi characters when it detects that the output is not interactive (e.g. to a pipe or a file). In this case its instead converting the emoji into a plain string. As a workaround, if you use `--colors=force` then it will keep the emoji.

![image](https://github.com/biomejs/biome/assets/83964/f3d0210a-4810-4861-816b-9472cb4da705)

A slightly different bug seems to be in the check mode where it prints the output first, then a message saying it would have printed the following content. So it's backwards and it's also reporting an error when there actually shouldn't be one.

![image](https://github.com/biomejs/biome/assets/83964/b927c9a5-b163-4a28-884e-bfc9990ff378)

**Comment by ematipico** [comment]
I know we have the issue, but I am unable to replicate it, maybe because I have a shell that supports Ansi? I wished there was a consistent way - at least for me - to get an invalid output.

BTW, if anyone wants to help, we use the `termcolor` crate to setup the stdout stream. Maybe someone can suggest a better option out of these variants: https://docs.rs/termcolor/1.4.1/termcolor/enum.ColorChoice.html#variants

**Comment by melMass** [comment]
Sorry I can't track exactly when/how but it's now working properly!
Just to note that it wasn't happening for all emojis but only some.
I'm going to close the issue

**Comment by marc-at-brightnight** [comment]
I'm confused as to why this issue was closed, when it's still very much a problem in Webstorm.

**Comment by Lysak** [comment]
The issue still exists. I am using a helper.

```
export function getWarningEmoji(): string {
  return '\u{26A0}' // !
}

export function getKeycapEmoji(symbol: string | number): string | undefined {
  const keycaps: Record<string | number, string> = {
    '#': '\u0023\uFE0F\u20E3', // #
    '*': '\u002A\uFE0F\u20E3', // *
    0: '\u0030\u20E3', // 0
    1: '\u0031\u20E3', // 1
    2: '\u0032\u20E3', // 2
    3: '\u0033\u20E3', // 3
    4: '\u0034\u20E3', // 4
    5: '\u0035\u20E3', // 5
    6: '\u0036\u20E3', // 6
    7: '\u0037\u20E3', // 7
    8: '\u0038\u20E3', // 8
    9: '\u0039\u20E3', // 9
    10: '\u{1F51F}', // 🔟
  }

  return keycaps[symbol]
}

```
