### ISSUE TITLE
📎  Implement  selector-pseudo-element-no-unknown

### ISSUE THREAD

**Issue by togami2864** [biomejs/biome#2624]
## Description

Implement [selector-pseudo-element-no-unknown](https://stylelint.io/user-guide/rules/selector-pseudo-element-no-unknown)

> [!IMPORTANT]
> - Please skip implementing options for now since we will evaluate users actually want them later.
> - Please ignore handling extended CSS language cases such as `sass` and `less`.
> - Please skip custom function since we haven't syntax model yet.

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by keita-hino** [comment]
Can I work on this issue?
