### ISSUE TITLE
📎 Implement `useThrowNewError` - `unicorn/throw-new-error`

### ISSUE THREAD

**Issue by minht11** [biomejs/biome#2633]
### Description

Implement [unicorn/throw-new-error](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/throw-new-error.md)

Naming:
So far I've come up with `useConsistentNewErrorThrow`, but maybe there is a better name.

**Comment by minht11** [comment]
Will try to work on it myself.

**Comment by Conaclos** [comment]
> So far I've come up with useConsistentNewErrorThrow, but maybe there is a better name.

`useThrowNewError`?

**Comment by minht11** [comment]
Tried to mimic useConsistentNewBuiltin, but yeah shorter version is prob better.
