### ISSUE TITLE
Autofix on save leaves empty import

### ISSUE THREAD

**Issue by OliverJAsh** [biomejs/biome#2668]
### VS Code version

1.88.1

### Extension version

2.2.2

### Biome version

1.7.2

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

When `noUnusedImports` is enabled, autofix on save leaves an empty import.

### Steps to reproduce

Given:

`biome.json`:
```json
{
    "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
    "linter": {
      "enabled": true,
      "rules": {
        "correctness": {
          "noUnusedImports": "warn"
        }
      }
    }
  }
  
```

`.vscode/settings.json`:
```json
{
    "editor.codeActionsOnSave": {
      "quickfix.biome": "explicit"
    }
  }
  
```

`index.ts`:
```ts
import { A, B } from 'foo';

// edit this comment and save the file

```

When I save `index.ts` and the autofix runs, I end up with an empty import:

```ts
import {} from 'foo';

```

### Expected behavior

Import is removed.

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

**Comment by samhh** [comment]
If it helps narrow the issue down, I can't repro this with `biome lint --apply`. The import statement is fully removed. I also can't repro with code actions in my editor (not VS Code), however I'm applying them manually.

**Comment by krismarv** [comment]
I have the same issue and the empty import is not removed on save, with `biome lint --apply` or with `biome check --fix`. VS Code 1.92.2, Biome extension 2.3.0, Biome 1.8.3, macOS

**Comment by richardgorman** [comment]
Same issue for me using VS Code extension v2.3.0

**Comment by OliverJAsh** [comment]
This doesn't seem to be an issue when using `source.fixAll.biome` instead of `quickfix.biome`.

**Comment by ematipico** [comment]
@OliverJAsh can you close the issue?

**Comment by OliverJAsh** [comment]
Sure, but I think the documentation still needs to be updated to mention the new command.
