### ISSUE TITLE
📎 Upgrade to `tower-lsp` 0.20

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#2672]
### Description

[`tower-lsp` 0.20](https://github.com/ebkalderon/tower-lsp/releases/tag/v0.20.0) have some breaking changes. We should update the code and carefully test if everything works as expected.

**Comment by Sec-ant** [comment]
I love bumping deps, I can give this a whirl.

**Comment by ematipico** [comment]
FYI I already did that in https://github.com/biomejs/biome/pull/2607, if you want to take a look

**Comment by eMerzh** [comment]
we should close this no ? as #2607  is merged
