### ISSUE TITLE
🐛 Latest version (1.7.2) keeps crashing

### ISSUE THREAD

**Issue by angel-luis** [biomejs/biome#2681]
### VS Code version

1.88.1

### Extension version

2.2.2

### Biome version

1.7.2

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

The extension stops to work after some minutes.
<img width="465" alt="image" src="https://github.com/biomejs/biome-vscode/assets/17672548/90a1968b-041a-483b-8d27-e06da778667a">

### Steps to reproduce

I've upgraded and also tried to reinstall the extension

### Expected behavior

Don't crash, with the 1.7.1 doesn't crash.

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

### Logs

```plain text
Connecting to "/Users/angelluis/Library/Caches/dev.biomejs.biome/biome-socket-1.7.2" ...
[Info  - 17:35:11] Server initialized with PID: 70417
[Error - 17:50:25] Client Biome: connection to server is erroring. Shutting down server.
[Error - 17:50:25] Client Biome: connection to server is erroring. Shutting down server.
[Error - 17:50:25] Sending document notification textDocument/didOpen failed.
Error: write EPIPE
	at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
[Error - 17:50:25] Stopping server failed
  Message: This socket has been ended by the other party
  Code: -32099 
[Error - 17:50:25] Stopping server failed
  Message: This socket has been ended by the other party
  Code: -32099 
[Error - 17:50:25] Stopping server failed
  Message: This socket has been ended by the other party
  Code: -32099
```

**Comment by Sec-ant** [comment]
This might be caused by some panic when the lsp is analyzing an opened file, so it would be much helpful if someone can provide the opened file/code when the error shows, so we can know which one caused it.

It will also be helpful to try using the CLI (`check` or `ci` command) and see if there're any panics in the current project.

**Comment by angel-luis** [comment]
Now I can't even choose the 1.7.1 version... when I click in the extension does nothing (I've reinstalled several times).

**Comment by Sec-ant** [comment]
> Running biome check ./app (1.7.1 and 1.7.2) in the project it founds 24 errors, all of them the same error of be sorted

Errors are not the problem. I was expecting there may be some program crashes (panics) that cause the server to shutdown.

> Now I can't even choose the 1.7.1 version... when I click in the extension does nothing (I've reinstalled several times).

The extension will install the latest biome when it cannot find one in your system path or in your project dependencies. So I think you can just change the version of biome in your project or in global to force the extension to use that version.

**Comment by Conaclos** [comment]
Have you tried disabling the linter and/or the formatter and/or the import organizer and see if the error persists? This is hard to help you without more precise information... Could you provide us the file that makes the Biome LSP crashes?

**Comment by angel-luis** [comment]
> Have you tried disabling the linter and/or the formatter and/or the import organizer and see if the error persists? This is hard to help you without more precise information... Could you provide us the file that makes the Biome LSP crashes?

I've always used Biome with the VSC without any Biome packing or CLI, so for me the options are enable or disable the extension. I'm 100% sure that before the 1.7.2 it has never crashed, and I've been using Biome at least 3-4 months. Above I've provided one file that causes the crash, I would be happy to provide more info, but I need to now exactly the steps to provide it!

**Comment by angel-luis** [comment]
> The extension will install the latest biome when it cannot find one in your system path or in your project dependencies. So I think you can just change the version of biome in your project or in global to force the extension to use that version.

Before, if I clicked the extension, it showed me a list of all the versions. Now shows nothing. Very weird.

**Comment by angel-luis** [comment]
After some testing, it crashes when importing `import Link from "next/link";`.

**Comment by ematipico** [comment]
@angel-luis can you please provide us with some logs?

You can retrieve them manually: https://biomejs.dev/guides/integrate-in-editor/#daemon-logs

Please make sure to copy the logs written right before the extension crashes

**Comment by angel-luis** [comment]
> @angel-luis can you please provide us with some logs?
> 
> You can retrieve them manually: https://biomejs.dev/guides/integrate-in-editor/#daemon-logs
> 
> Please make sure to copy the logs written right before the extension crashes

Cleaned log:

[server.log.2024-05-03-09.txt](https://github.com/biomejs/biome/files/15197969/server.log.2024-05-03-09.txt)

**Comment by Conaclos** [comment]
Thanks for the log, this was really helpful!

Biome crashes because of #2659 (TLDR: Biome crashes on conditional types with TypeScript `infer`). I fixed the issue two days ago. We will release a patch version soon because this affects many users.

**Comment by angel-luis** [comment]
Thanks to you and the rest of the team, then we will wait to the patch! 👍
