### ISSUE TITLE
Arrow function body indentation affected by its type length

### ISSUE THREAD

**Issue by kalekseev** [biomejs/biome#2736]
### Environment information

```bash
CLI:
  Version:                      1.6.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "screen-256color"
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              true
  Organize imports disabled:    true
  VCS disabled:                 true

Formatter:
  Format with errors:           true
  Indent style:                 Space
  Indent size:                  0
  Indent width:                 2
  Line ending:                  Lf
  Line width:                   90
  Attribute position:           Auto
  Ignore:                       []
  Include:                      []

JavaScript Formatter:
  Enabled:                      false
  JSX quote style:              Double
  Quote properties:             AsNeeded
  Trailing comma:               Es5
  Semicolons:                   Always
  Arrow parentheses:            Always
  Bracket spacing:              false
  Bracket same line:            false
  Quote style:                  Single
  Indent style:                 unset
  Indent size:                  unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           Auto

JSON Formatter:
  Enabled:                      true
  Indent style:                 unset
  Indent width:                 unset
  Indent size:                  unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
  "$schema": "https://biomejs.dev/schemas/1.6.3/schema.json",
  "organizeImports": {
    "enabled": false
  },
  "linter": {
    "enabled": false
  },
  "formatter": {
    "enabled": true,
    "indentStyle": "space",
    "indentWidth": 2,
    "lineWidth": 90,
    "formatWithErrors": true
  },
  "javascript": {
    "formatter": {
      "trailingComma": "es5",
      "quoteStyle": "single"
    }
  }
}
```

### Playground link

https://biomejs.dev/playground/?lineWidth=90&code=YwBvAG4AcwB0ACAAVgBhAGwAdQBlAE0AZQBuAHUARABpAHYAaQBkAGUAcgA6ACAAUgBlAGEAYwB0AC4ARgBDADwAewAgAHYAYQBsAHUAZQA6ACAAcwB0AHIAaQBuAGcAIAB9ACAAJgAgAE8AbQBpAHQAPABNAGUAbgB1AEQAaQB2AGkAZABlAHIAUAByAG8AcABzACwAIAAnAHMAdgBhAGwAdQBlACcAPgA%2BACAAPQAgACgAewAgAHYAYQBsAHUAZQAgAH0AKQAgAD0APgAgAHsACgAgACAAcgBlAHQAdQByAG4AIAA8AE8AcgBpAGcAaQBuAGEAbABNAGUAbgB1AEQAaQB2AGkAZABlAHIAIAAvAD4AOwAKAH0AOwAKAAoACgAKAGMAbwBuAHMAdAAgAFYAYQBsAHUAZQBNAGUAbgB1AEQAaQB2AGkAZABlAHIAMgA6ACAAUgBlAGEAYwB0AC4ARgBDADwAewAgAHYAYQBsAHUAZQA6ACAAcwB0AHIAaQBuAGcAIAB9ACAAJgAgAE8AbQBpAHQAPABNAGUAbgB1AEQAaQB2AGkAZABlAHIAUAByAG8AcABzACwAIAAnAHMAdgBhAGwAdQBlACcALAAgACcAYQBuAG8AdABoAGUAcgB2AGEAbAB1AGUAJwA%2BAD4AIAA9ACAAKAB7ACAAdgBhAGwAdQBlACAAfQApACAAPQA%2BACAAewAKACAAIAByAGUAdAB1AHIAbgAgADwATwByAGkAZwBpAG4AYQBsAE0AZQBuAHUARABpAHYAaQBkAGUAcgAgAC8APgA7AAoAfQA7AAoA

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by dyc3** [comment]
I'd like to give this a shot.

**Comment by dyc3** [comment]
I have a smaller repro here: https://biomejs.dev/playground/?code=YwBvAG4AcwB0ACAAVgBhAGwATQBlAG4AdQBEAGkAdgBpAGQAZQA6ACAAUgBlAGEAYwB0AEYARgBDADwATQBlAGQAZABkAGQAZABkAGQAZABkAE0AZQBuAHUARABpAHYAaQBkAGUAcgBQAHIAbwBwAHMATQBlAG4AdQBEAGkAdgBpAGQAZQByAFAAcgBvAHAAcwB6AHoAegA%2BAD0AKAB4ACkAIAA9AD4AIAA1ADsACgA%3D

**Comment by dyc3** [comment]
I've been combing over the code for a while now, and I think I understand what's going on. Mostly notes for myself:

The variable declaration group is higher up in the IR tree than the type annotation group. When the tree gets flattened into `FormatElement`s, the variable declaration group gets evaluated first to see if it breaks (and since it's long enough, it breaks). Then the type annotation group gets evaluated, and its not long enough, so it doesn't break. This evaluation happens here:

https://github.com/biomejs/biome/blob/01c440d78343a1217271f874c64c05ffcb725077/crates/biome_formatter/src/printer/mod.rs#L184-L188

I think the best way to fix this is to introduce some kind of "break priority" field to the `Group` struct, and then favor breaking type annotations.

**Comment by ah-yu** [comment]
> I think one way to fix this is to introduce some kind of "break priority" field to the Group struct, and then favor breaking type annotations, but I think that could introduce some complexity.

It seems that this approach assumes the current generated IR is accurate. Perhaps we could compare the IR generated by `Biome` and `Prettier` to identify differences between them and address these disparities to see if the issue is resolved.

**Comment by dyc3** [comment]
Ok yeah, I was looking at the IR before and it looked identical, but I'm looking at it again and it is definitely not. Biome is emitting an extra `group`.
