### ISSUE TITLE
💅 useFilenamingConvention and multiple ignore statements collide

### ISSUE THREAD

**Issue by zauni** [biomejs/biome#2754]
### Environment information

```bash
CLI:
  Version:                      1.7.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.12.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.5.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  Recommended:                  true
  All:                          false
  Rules:                        style/useFilenamingConvention = {"level":"error","options":{"filenameCases":["kebab-case"]}}

Workspace:
  Open Documents:               0
```

### Rule name

useFilenamingConvention

### Playground link

https://codesandbox.io/p/devbox/happy-platform-ttyzxt?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clvw9u14a00053b6hhkt4qi1c%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clvw9u14a00023b6h0zvqg14v%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clvw9u14a00033b6h7u4v83r0%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clvw9u14a00043b6hjjr38gcg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clvw9u14a00023b6h0zvqg14v%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvw9u14a00013b6huurd5atv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clvw9vrmc00483b6h2b720xin%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A5%252C%2522startColumn%2522%253A6%252C%2522endLineNumber%2522%253A5%252C%2522endColumn%2522%253A6%257D%255D%252C%2522filepath%2522%253A%2522%252Fbiome.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clvw9u14a00023b6h0zvqg14v%2522%252C%2522activeTabId%2522%253A%2522clvw9vrmc00483b6h2b720xin%2522%257D%252C%2522clvw9u14a00043b6hjjr38gcg%2522%253A%257B%2522id%2522%253A%2522clvw9u14a00043b6hjjr38gcg%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clvw9u14a00033b6h7u4v83r0%2522%253A%257B%2522id%2522%253A%2522clvw9u14a00033b6h7u4v83r0%2522%252C%2522activeTabId%2522%253A%2522clvw9wltm001n3b6gv6rb99z1%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clvw9wltm001n3b6gv6rb99z1%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clvw9wlvj000rdjip0ia40mwc%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Expected result

If I use the `useFilenamingConvention` rule and I have a filename that is not compatible with this rule it is possible to ignore that.
E.g. Expo Router has the convention of using [] in the filename to indicate path parameters. But this is not a problem when I use the comment `// biome-ignore lint/style/useFilenamingConvention: expo router convention`

But as soon as there is another `// biome-ignore` in the file (see the codesandbox link, where I have another biome-ignore) the ignore of the useFilenamingConvention rule is not working anymore. It even complains, that this ignore is not used and warns me about that. But at the same time it complains again about the wrong file name.

This is the output of the linter when I have only one biome-ignore:

`Checked 2 files in 1669µs. No fixes needed.`

And with two biome-ignore's:

```
./src/[test].jsx lint/style/useFilenamingConvention ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ The filename should be in kebab-case.
  
  ℹ The filename could be renamed to one of the following names:
    -test.jsx
  

./src/[test].jsx:1:1 suppressions/unused ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ⚠ Suppression comment is not being used
  
  > 1 │ // biome-ignore lint/style/useFilenamingConvention: expo router convention
      │ ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2 │ 
    3 │ import { useEffect, useState } from "react";
  

Checked 2 files in 3ms. No fixes needed.
Found 1 error.
Found 1 warning.
lint ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Some errors were emitted while running checks.
```

Maybe someone has an idea of why two biome-ignores could trigger that behavior. Thanks!

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Sec-ant** [comment]
> If I use the `useFilenamingConvention` rule and I have a filename that is not compatible with this rule it is possible to ignore that.
> E.g. Expo Router has the convention of using [] in the filename to indicate path parameters. But this is not a problem when I use the comment `// biome-ignore lint/style/useFilenamingConvention: expo router convention`

This looks like a bug to me because `// biome-ignore` is for [ignoring a code line](https://biomejs.dev/linter/#ignoring-code) instead of [a file](https://biomejs.dev/linter/#ignoring-files). And the repoduction you provide seems the correct behavior.

If you want to ignore a rule for a specific set of files, you should use [`overrides`](https://biomejs.dev/reference/configuration/#overrides).

**Comment by zauni** [comment]
Ah, that of course makes much more sense. Funny that it worked with just one `// biome-ignore` 🙂 

So I will close this one as the overrides is sufficent for this use case.
Thanks for the explanation and links!

**Comment by Conaclos** [comment]
> Ah, that of course makes much more sense. Funny that it worked with just one // biome-ignore 🙂

It works because internally, the rule queries the root node of a file. Not sure why this doesn't work when there are multiple biome-ignore comments.

**Comment by zauni** [comment]
So for anybody looking for a solution, add this to your `biome.json`

```json
"overrides": [
  {
    "include": ["**/[[]*].tsx"],
    "linter": {
      "rules": {
        "style": {
          "useFilenamingConvention": {
            "level": "off",
            "options": {}
          }
        }
      }
    }
  }
]
```

The include pattern looks a bit weird, but it includes every file with brackets like e.g. `[something].tsx` or `[...spread].tsx` is included
