### ISSUE TITLE
Expose metadata inside the lint rule

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#2798]
This is a **very easy task**.

You should add this:

```rs
    pub fn metadata(&self) -> &RuleMetadata {
        &R::METADATA
    }
```

In here: https://github.com/biomejs/biome/blob/42135279b8c3f80dc51c5f94f9f17b3fdad1848f/crates/biome_analyze/src/context.rs#L25

Please make sure to add proper documentation for the new function

**Comment by dyc3** [comment]
I can pick this up.
