### ISSUE TITLE
Compute fix kind from metatadata

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#2799]
The `RuleAction` now accepts an `applicability` field, determining whether the action is safe/unsafe. 

However, we also provide the same information to our `RuleMeta`, which is `fix_kind`. 

Once https://github.com/biomejs/biome/issues/2798 is completed, we can retrieve the `fix_kind` using `ctx.metadata().fix_kind`.

The idea is to create a method inside `FixKind` called `into_applicability` that returns `Applicability`. This method should panic (use .`expect()`) if the fix kind isn't provided via macro.

The field `applicability` should become **private** (remove `pub`), however do that at the end. I suggest to create a new method called `new` inside `RuleAction`, and then progressively phase out the manual construction of the struct

```rs
impl RuleAction {
	pub fn new(category: ActionCategory, applicability: Applicability, message: MarkupBuf, mutation: BatchMutation) -> Self {
		Self {
			category,
			applicability,
			message,
			mutation
		}
	}
}
```

As a rule, we should have:

```rs

        Some(JsRuleAction {
            category: ActionCategory::QuickFix,
            applicability: ctx.metadata().to_applicability(),
            message: markup! { "" }.to_owned(),
            mutation,
        })
```

**Comment by dyc3** [comment]
I can pick this up.
