### ISSUE TITLE
Make `JsxRuntime` optional inside the analyzer

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#2800]
Make this as an `Option<JsxRuntime>`:

https://github.com/biomejs/biome/blob/42135279b8c3f80dc51c5f94f9f17b3fdad1848f/crates/biome_analyze/src/options.rs#L61

And here should become something like `.expect("Runtime should be provided")`: 

https://github.com/biomejs/biome/blob/42135279b8c3f80dc51c5f94f9f17b3fdad1848f/crates/biome_analyze/src/context.rs#L106

The compiler will fail in some other places where you need to provide `Some`.

**Comment by Kazuhiro-Mimaki** [comment]
I'm interested in tackling this issue 🦀

**Comment by Kazuhiro-Mimaki** [comment]
I'd like to know why `JsxRuntime` should be optional.

**Comment by ematipico** [comment]
> Just for the sake of curiosity, I'd like to know why `JsxRuntime` should be optional.

Because `AnalyzerOptions` is a type that is used across languages, and JSON/CSS languages don't need/require is option.
