### ISSUE TITLE
📎  Implement declaration-block-no-shorthand-property-overrides

### ISSUE THREAD

**Issue by togami2864** [biomejs/biome#2807]
## Description

Implement [declaration-block-no-shorthand-property-overrides](https://stylelint.io/user-guide/rules/declaration-block-no-shorthand-property-overrides)

> [!IMPORTANT]
> - Please skip implementing options for now since we will evaluate users actually want them later.
> - Please ignore handling extended CSS language cases such as `sass` and `less`.
> - Please skip custom function since we haven't syntax model yet.

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by neokidev** [comment]
Hello! I'm interested in tackling this issue.

**Comment by ematipico** [comment]
We should come up with a better name. The current name is very long. What do you suggest @togami2864 ?

**Comment by togami2864** [comment]
How about `noShorthandPropertyOverrides`? I think it's fine not to include declaration-block since there's only one override rule.

**Comment by neokidev** [comment]
I have some questions regarding the implementation:

**Specification:**

- Should we skip handling vendor prefixes such as `-webkit` for now in this rule? It appears that we ignored them in the previously implemented `noUnknownProperty` rule.

**Implementation:**

- For this rule, it would be easier if the `run` method of `Rule` trait could be executed with `Ast<CssDeclarationBlock>` as the query, allowing for multiple diagnostics to be set from there. Is this feasible in Biome? (Currently, I am proceeding with the implementation by specifying `Ast<CssGenericProperty>` as the query.)

**Comment by neokidev** [comment]
I've pushed to #2958 an implementation that handles the basic patterns, though there are still some issues remaining. Could you review the PR and check my approach? Additionally, I've left some comments on the PR with questions. I would appreciate it if you could check those as well.

**Comment by ematipico** [comment]
@neokidev I answered some of your questions
