### ISSUE TITLE
📎  Implement function-linear-gradient-no-nonstandard-direction

### ISSUE THREAD

**Issue by togami2864** [biomejs/biome#2808]
## Description

Implement [function-linear-gradient-no-nonstandard-direction](https://stylelint.io/user-guide/rules/function-linear-gradient-no-nonstandard-direction)

> [!IMPORTANT]
> - Please skip implementing options for now since we will evaluate users actually want them later.
> - Please ignore handling extended CSS language cases such as `sass` and `less`.
> - Please skip custom function since we haven't syntax model yet.

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by mdm317** [comment]
Can i try this?

**Comment by ematipico** [comment]
@togami2864 what's the suggested name for this rule? Can you give us some directions?

**Comment by togami2864** [comment]
How about `noInvalidDirectionInLinearGradient`??
