### ISSUE TITLE
📎 React Compiler rules

### ISSUE THREAD

**Issue by felix-bohlin** [biomejs/biome#2881]
### Description

With React 19 around the corner, the team has announced an Eslint plugin with compiler rules.
Any thoughts on this or plans to implement?

https://react.dev/learn/react-compiler#installing-eslint-plugin-react-compiler

**Comment by ematipico** [comment]
Please, use this discussion for new lint rules: https://github.com/biomejs/biome/discussions/3

We usually open issues for bugs and tracking tasks.

**Comment by dyc3** [comment]
For anyone finding this issue via search, see the discussion here: https://github.com/biomejs/biome/discussions/3#discussioncomment-9470057
