### ISSUE TITLE
🐛 Biomejs server crashes in a specific scenario

### ISSUE THREAD

**Issue by mozesstumpf** [biomejs/biome#2886]
### Environment information

```block
CLI:
  Version:                      1.5.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.18.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

The biomejs server crashes if we start typing characters between the `const [` and `(`
The bug is reproducible with the following config:
`biome.json`:
```
{
  "$schema": "https://biomejs.dev/schemas/1.7.3/schema.json",
  "linter": {
    "rules": {
      "correctness": {
        "noUnusedVariables": "warn"
      }
    }
  }
}

```
e.g.: `const [TypeHereToCauseTheServerCrash(`

Repo to reproduce: https://github.com/mozesstumpf/biome-server-crash

### Expected result

It should not crash the server.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
It's not crashing. It isn't working on purpose. Check the `biome rage` command you just pasted, and also check the terminal output of the VSCode extension.

You have an old configuration. If you fix the configuration, it should work again.

**Comment by mozesstumpf** [comment]
@ematipico 
> You have an old configuration. If you fix the configuration, it should work again.

That's true, when I executed the `biome rage` command, it was with the old configuration and that's why it showed the error.
With the valid config (that I've passed in the **`What happened?`** section, the server still crashes.

I've updated the `Environment information`.
