### ISSUE TITLE
💅 useExhaustiveDependencies ignores duplicate dependencies

### ISSUE THREAD

**Issue by printfn** [biomejs/biome#2956]
### Environment information

```bash
CLI:
  Version:                      1.7.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v22.2.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.7.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Rule name

useExhaustiveDependencies

### Playground link

https://biomejs.dev/playground/?lintRules=all&code=aQBtAHAAbwByAHQAIAB7ACAAdQBzAGUAQwBhAGwAbABiAGEAYwBrACAAfQAgAGYAcgBvAG0AIAAnAHIAZQBhAGMAdAAnADsACgAKAGUAeABwAG8AcgB0ACAAZgB1AG4AYwB0AGkAbwBuACAAQwBvAG0AcABvAG4AZQBuAHQAKAB7ACAAYQAgAH0AOgAgAHsAIABhADoAIABzAHQAcgBpAG4AZwAgAH0AKQAgAHsACgAgACAAYwBvAG4AcwB0ACAAaABhAG4AZABsAGUAIAA9ACAAdQBzAGUAQwBhAGwAbABiAGEAYwBrACgAKAApACAAPQA%2BACAAewAKACAAIAAgACAAYQBsAGUAcgB0ACgAYQApADsACgAgACAAfQAsACAAWwBhACwAIABhAF0AKQA7AAoACgAgACAAcgBlAHQAdQByAG4AIAA8AGIAdQB0AHQAbwBuACAAdAB5AHAAZQA9ACIAYgB1AHQAdABvAG4AIgAgAG8AbgBDAGwAaQBjAGsAPQB7AGgAYQBuAGQAbABlAH0APgBCAHUAdAB0AG8AbgA8AC8AYgB1AHQAdABvAG4APgA7AAoAfQA%3D

### Expected result

The `exhaustive-deps` rule in `eslint-plugin-react-hooks` errors when dependencies are duplicated. I think `useExhaustiveDependencies` should do the same.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by tunamaguro** [comment]
Hello.
Can I work on this?
