### ISSUE TITLE
🐛 https://biomejs.dev/ is not accessible  

### ISSUE THREAD

**Issue by JohnnyJumper** [biomejs/biome#2961]
### Environment information

```block
not applicable
```

### What happened?

Trying to visit the biomejs.dev and met the following issue:
![Screenshot 2024-05-23 at 9 09 32 AM](https://github.com/biomejs/biome/assets/16522024/4a85b304-f1b1-4fdc-a897-06175608cd95)

there is no problem browsing through phone though.

Reproducible on Chrome and Safari (haven't test it with others)

Opening this issue just to get some attention, probably not needed => never know 🤷 

### Expected result

I should be able to visit the homepage

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by JohnnyJumper** [comment]
nope. nothing of the sort

**Comment by ematipico** [comment]
All good here though https://www.netlifystatus.com/

Not sure what's the issue

**Comment by JohnnyJumper** [comment]
so strange. I will bug someone at my building to see if we are using proxy of any sort that I am not familiar with

**Comment by JohnnyJumper** [comment]
Looks like there is a sort of proxy in the building! 

Sorry for bothering. :) I will close this issue
