### ISSUE TITLE
🐛 Incorrect formatting in function chain

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#300]
### Environment information

```block
main
```

### What happened?

Formatting for function chaining is [wonky and different from prettier](https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&jsxQuoteStyle=single&lintRules=all&code=YwBvAG4AcwB0ACAAYQAgAD0AIAB7AAoAIAAgAGwAbwBjAGEAbABlAHMAOgAgAHoALgByAGUAYwBvAHIAZAAoAAoAIAAgACAAIABsAG8AYwBhAGwAZQBLAGUAeQBTAGMAaABlAG0AYQAsAAoAIAAgACAAIAB6AC4AcwB0AHIAaQBuAGcAKAApAC4AbQBpAG4AKAAyACkALgByAGUAZwBlAHgAKAAvAF4AWwBhAC0AegBBAC0AWgBcAC0AXQArACQALwBnAG0ALAAgAHsACgAgACAAIAAgACAAIABtAGUAcwBzAGEAZwBlADoAIAAnAE8AbgBsAHkAIABFAG4AZwBsAGkAcwBoACAAYQBsAHAAaABhAGIAZQB0ACAAcwB5AG0AYgBvAGwAcwAgAGEAbgBkACAAaAB5AHAAaABlAG4AIABhAGwAbABvAHcAZQBkACcALAAKACAAIAAgACAAfQApAAoAIAAgACkALAAKAH0A) 

### Expected result

It should correctly format function chaining

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by victor-teles** [comment]
@ematipico I'll work on this one
