### ISSUE TITLE
Implement a lint rule to highlight the deprecated `@value` at-rule.

### ISSUE THREAD

**Issue by denbezrukov** [biomejs/biome#3001]
Implement `no-value-at-rule`.

Many tools, such as lightningcss and swc, consider the @value at-rule deprecated in favor of CSS variables.

References:

- [LightningCSS Documentation](https://lightningcss.dev/css-modules.html#unsupported-features):  "The @value rule – superseded by standard CSS variables."
- [SWC Project](https://github.com/swc-project/swc/blob/ab32e694a0688d1bd9803a0aa6ffb4d00dafa7b5/crates/swc_css_parser/src/error.rs#L75)

Want to contribute? Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by denbezrukov** [comment]
Hi @togami2864 ,

Could you please help me with this? Do you have any thoughts or suggestions?

Thank you!

**Comment by denbezrukov** [comment]
> Should this rule only apply to files with `.module.css`🤔

Hmm, interesting. We have a project with css modules but we don't write `.module.css`.
I think it’s better to analyze all .css files, but the rule must work only if the option is enabled.

**Comment by togami2864** [comment]
> I think it’s better to analyze all .css files, but the rule must work only if the option is enabled.

Makes sense. We can ignore when the option is disabled since the parser will give a warning.
https://biomejs.dev/playground/?lineWidth=120&files.main.css=QAB2AGEAbAB1AGUAIABiAGwAdQBlADoAIAAjADAAYwA3ADcAZgA4ADsA

**Comment by rishabh3112** [comment]
@denbezrukov interested in contributing this change.
