### ISSUE TITLE
📎 Upgrade prettier version in the playground

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#302]
### Description

At the moment, we still use 2.* version of prettier. We should use the latest.

Prettier 3.* changed their APIs to be all async, so there's some work.

[Starting](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md#website) the website is failing easy. FYI use Chrome, sometimes Firefox doesn't work.

**Comment by DerTimonius** [comment]
I'd like to take a shot at this! 🙂

**Comment by Conaclos** [comment]
Assigned :)

**Comment by DerTimonius** [comment]
Thanks!

Currently trying to setup the project, kinda stuck at the setup for the `Node.js development`. I followed the installation guide:
- installed `wasm-pack` globally
- ran `pnpm build` in the `backend-jsonrpc` package
- ran `pnpm build:wasm-node-dev`, which failed with the following error (I ran it twice, just to check):
```
> pnpm build:wasm-node-dev

> @biomejs/js-api@0.3.0 build:wasm-node-dev /Users/timonjurschitsch/Coding/OpenSource/biome/packages/@biomejs/js-api
> wasm-pack build --out-dir ../../packages/@biomejs/wasm-nodejs --target nodejs --dev --scope biomedev ../../../crates/biome_wasm

[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
    Finished dev [unoptimized + debuginfo] target(s) in 0.33s
[INFO]: ⬇️  Installing wasm-bindgen...
error: failed getting Wasm module for '/Users/timonjurschitsch/Coding/OpenSource/biome/target/wasm32-unknown-unknown/debug/biome_wasm.wasm'

Caused by:
    0: failed to parse input as wasm
    1: failed to parse code section
    2: locals exceed maximum (at offset 20068453)
Error: Running the wasm-bindgen CLI
Caused by: Running the wasm-bindgen CLI
Caused by: failed to execute `wasm-bindgen`: exited with exit status: 1
  full command: "/Users/timonjurschitsch/Library/Caches/.wasm-pack/wasm-bindgen-3db0f537558d06d8/wasm-bindgen" "/Users/timonjurschitsch/Coding/OpenSource/biome/target/wasm32-unknown-unknown/debug/biome_wasm.wasm" "--out-dir" "../../../crates/biome_wasm/../../packages/@biomejs/wasm-nodejs" "--typescript" "--target" "nodejs" "--debug"
```

Deleted everything and started again from the beginning, but I'm still getting the same error. Maybe you have an idea @Conaclos ?

**Comment by ematipico** [comment]
@DerTimonius use the release command `pnpm build:wasm-node` It takes longer but it won't fail.
