### ISSUE TITLE
noConfusingVoidType errors on optional disposer returns

### ISSUE THREAD

**Issue by cpakken** [biomejs/biome#3023]
### Environment information

```bash
CLI:
  Version:                      1.7.3    
  Color support:                true     

Platform:
  CPU Architecture:             x86_64   
  OS:                           windows  

Environment:
  BIOME_LOG_DIR:                unset    
  NO_COLOR:                     unset    
  TERM:                         unset    
  JS_RUNTIME_VERSION:           "v22.0.0"
  JS_RUNTIME_NAME:              "node"   
  NODE_PACKAGE_MANAGER:         unset    

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  Recommended:                  true
  All:                          false
  Rules:                        suspicious/noConfusingVoidType = "off"
                                suspicious/noExplicitAny = "off"

Workspace:
  Open Documents:               0
```

### Rule name

noConfusingVoidType

### Playground link

https://biomejs.dev/playground/?code=ZgB1AG4AYwB0AGkAbwBuACAAYwByAGUAYQB0AGUATABpAHMAdABlAG4AZQByACgAYwBhAGwAbABiAGEAYwBrADoAIAAoACkAIAA9AD4AIAAoACgAKQAgAD0APgAgAHYAbwBpAGQAKQAgAHwAIAB2AG8AaQBkACkAewAKACAAIAByAGUAdAB1AHIAbgAgAG4AdQBsAGwACgB9AA%3D%3D

### Expected result

Sometimes I have a callback that can optionally return a disposer
```ts
function createListener(callback: (e) => (() => void) | void))
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
I think that the function could better be typed with `undefined` because you are likely to check if the result is not undefined.

```ts
function createListener(callback: (e) => (() => void) | undefined)) {}
```

**Comment by Conaclos** [comment]
I think we should not address this, because the function returns something. `undefined` should be used instead of `void` here.
