### ISSUE TITLE
📎 Implement `useConsistentArrayApis`

### ISSUE THREAD

**Issue by minht11** [biomejs/biome#3039]
### Description

This rule will include following unicorn apis:

[prefer-array-find](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-array-find.md)
[prefer-array-flat-map](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-array-flat-map.md)
[prefer-array-index-of](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-array-index-of.md)
[prefer-array-some](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-array-some.md)
[prefer-at](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-at.md)

For now I am not planning on providing any options to turn of any of them of individually.

Since there are a lot of rules I am gonna start with prefer-array-index and then I implement other rules later.

**Comment by Conaclos** [comment]
Note: [useFlatMap](https://biomejs.dev/linter/rules/use-flat-map/) already exists.
Also it seems you missed [prefer-array-flat](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-array-flat.md).

I am [the one that proposed merging all these rules](https://github.com/biomejs/biome/discussions/3#eslint-plugin-unicorn). However, I expected some discussions about this before opening a task and implementing it.

I first suggested merging these rules to avoid the multiplication of API rules.
However, users might want to disable some specific APIs, especially APIs that are not yet supported by their target (e.g., `Array#at'). If we had access to the ECMAScript target, we could disable unsupported APIs. However, this might be the first rule to do so. Do we want it? Could other rules benefit of it?

Maybe it is better to keep them separated? This will ease migration.

Also we should come up with a consistent naming convention for such rules. Is `useConsistentStringFunctions` (#2817) similar to this rule? If yes, then should we consider `useConsistentArrayFunctions` or renaming `useConsistentStringFunctions` to `useConsistentStringApis`?

**Comment by ematipico** [comment]
I think these rules should be separated. They would be more portable and easy to configure.

**Comment by Conaclos** [comment]
> About naming consistency, I prefer the Functions instead of Apis.

I thought about a third option: Methods.

**Comment by minht11** [comment]
That list has a lot of rules, so documenting and implementing them should be easier as separate rule each.
Semantically I see appeal on merging them together, though [proposed ruleSets](https://github.com/biomejs/biome/discussions/689) if we ever need them might be better here.

So if we agree, I can close this issue and start implementing each rule separately?

**Comment by Conaclos** [comment]
I wonder if we should reconsider the separation of rules in #2817

**Comment by ematipico** [comment]
Usually rules should do one single job, and do it well.

If they happen to do multiple jobs, we should split them

**Comment by minht11** [comment]
Looking in isolation as per my [previous comment](https://github.com/biomejs/biome/issues/2817#issuecomment-2118054481) keeping `useConsistentStringFunctions` together seems fine, however given context of this issue, to be consistent it should prob be split. By splitting them we can also add new String function rules easier in a future.

> Usually rules should do one single job, and do it well.
> If they happen to do multiple jobs, we should split them.
Should this be documented somewhere and maybe even `useConsistentArrayApis` given as example?

In any case I am closing this issue. Will open new one for each array rule.
