### ISSUE TITLE
💅 possible difference in scope between biome useliteralkeys and eslint dot-notation rules

### ISSUE THREAD

**Issue by scharkthemark** [biomejs/biome#3085]
### Environment information

```bash
CLI:
  Version:                      1.7.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v20.13.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.5.2"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  Recommended:                  false
  All:                          false
  Rules:                        unset

Workspace:
  Open Documents:               0
```

### Rule name

useLiteralKeys

### Playground link

https://biomejs.dev/playground/?lineWidth=100&indentStyle=space&quoteProperties=preserve&indentWidth=4&code=YwBvAG4AcwB0ACAAdABlAHMAdAAgAD0AIAB7AAoAIAAgACAAIAAiAHQAZQBzAHQAIgA6ACAAMQAsAAoAIAAgACAAIAAiAHQAZQBzAHQAIAAyACIAOgAgADIALAAKACAAIAAgACAAIgB0AGUAcwB0ADMAIgA6ACAAMQAsAAoAfQA7AAoACgB0AGUAcwB0AFsAIgB0AGUAcwB0ACIAXQAgAD0AIAAyAA%3D%3D

### Expected result

Hey folks,

There seems to be a possible difference between the scope of biome's `useLiteralKeys` linter rule and the scope of eslint's `dot-notation` linter rule. In particular, eslint seems to only apply the rule when the property of an object is being accessed, but biome seems to apply the rule both when the property is being accessed AND when the properties are being defined/created within a new object. For instance:

```
const test = {
    "hello": 1
}
```

In this example, eslint won't throw an error, but biome will and suggest to simplify by not using a string literal. You can view results in ESLint [here](https://eslint.org/play/#eyJ0ZXh0IjoiLyogZXNsaW50IHF1b3RlczogW1wiZXJyb3JcIiwgXCJkb3VibGVcIl0gKi9cbmNvbnN0IHRlc3QgPSB7XG4gICAgXCJ0ZXN0XCI6IDEsXG4gICAgXCJ0ZXN0IDJcIjogMixcbiAgICBcInRlc3QzXCI6IDEsXG59O1xuXG50ZXN0W1widGVzdFwiXSA9IDIiLCJvcHRpb25zIjp7InJ1bGVzIjp7ImFjY2Vzc29yLXBhaXJzIjpbImVycm9yIl0sImFycmF5LWJyYWNrZXQtbmV3bGluZSI6WyJlcnJvciJdLCJhcnJheS1icmFja2V0LXNwYWNpbmciOlsiZXJyb3IiXSwiYXJyYXktY2FsbGJhY2stcmV0dXJuIjpbImVycm9yIl0sImFycmF5LWVsZW1lbnQtbmV3bGluZSI6WyJlcnJvciJdLCJhcnJvdy1ib2R5LXN0eWxlIjpbImVycm9yIl0sImFycm93LXBhcmVucyI6WyJlcnJvciJdLCJhcnJvdy1zcGFjaW5nIjpbImVycm9yIl0sImJsb2NrLXNjb3BlZC12YXIiOlsiZXJyb3IiXSwiYmxvY2stc3BhY2luZyI6WyJlcnJvciJdLCJicmFjZS1zdHlsZSI6WyJlcnJvciJdLCJjYWxsYmFjay1yZXR1cm4iOlsiZXJyb3IiXSwiY2FtZWxjYXNlIjpbImVycm9yIl0sImNhcGl0YWxpemVkLWNvbW1lbnRzIjpbImVycm9yIl0sImNsYXNzLW1ldGhvZHMtdXNlLXRoaXMiOlsiZXJyb3IiXSwiY29tbWEtZGFuZ2xlIjpbImVycm9yIl0sImNvbW1hLXNwYWNpbmciOlsiZXJyb3IiXSwiY29tbWEtc3R5bGUiOlsiZXJyb3IiXSwiY29tcGxleGl0eSI6WyJlcnJvciJdLCJjb21wdXRlZC1wcm9wZXJ0eS1zcGFjaW5nIjpbImVycm9yIl0sImNvbnNpc3RlbnQtcmV0dXJuIjpbImVycm9yIl0sImNvbnNpc3RlbnQtdGhpcyI6WyJlcnJvciJdLCJjb25zdHJ1Y3Rvci1zdXBlciI6WyJlcnJvciJdLCJjdXJseSI6WyJlcnJvciJdLCJkZWZhdWx0LWNhc2UiOlsiZXJyb3IiXSwiZGVmYXVsdC1jYXNlLWxhc3QiOlsiZXJyb3IiXSwiZGVmYXVsdC1wYXJhbS1sYXN0IjpbImVycm9yIl0sImRvdC1sb2NhdGlvbiI6WyJlcnJvciJdLCJkb3Qtbm90YXRpb24iOlsiZXJyb3IiXSwiZW9sLWxhc3QiOlsiZXJyb3IiXSwiZXFlcWVxIjpbImVycm9yIl0sImZvci1kaXJlY3Rpb24iOlsiZXJyb3IiXSwiZnVuYy1jYWxsLXNwYWNpbmciOlsiZXJyb3IiXSwiZnVuYy1uYW1lLW1hdGNoaW5nIjpbImVycm9yIl0sImZ1bmMtbmFtZXMiOlsiZXJyb3IiXSwiZnVuYy1zdHlsZSI6WyJlcnJvciJdLCJmdW5jdGlvbi1jYWxsLWFyZ3VtZW50LW5ld2xpbmUiOlsiZXJyb3IiXSwiZnVuY3Rpb24tcGFyZW4tbmV3bGluZSI6WyJlcnJvciJdLCJnZW5lcmF0b3Itc3Rhci1zcGFjaW5nIjpbImVycm9yIl0sImdldHRlci1yZXR1cm4iOlsiZXJyb3IiXSwiZ2xvYmFsLXJlcXVpcmUiOlsiZXJyb3IiXSwiZ3JvdXBlZC1hY2Nlc3Nvci1wYWlycyI6WyJlcnJvciJdLCJndWFyZC1mb3ItaW4iOlsiZXJyb3IiXSwiaGFuZGxlLWNhbGxiYWNrLWVyciI6WyJlcnJvciJdLCJpZC1ibGFja2xpc3QiOlsiZXJyb3IiXSwiaWQtZGVueWxpc3QiOlsiZXJyb3IiXSwiaWQtbGVuZ3RoIjpbImVycm9yIl0sImlkLW1hdGNoIjpbImVycm9yIl0sImltcGxpY2l0LWFycm93LWxpbmVicmVhayI6WyJlcnJvciJdLCJpbmRlbnQiOlsiZXJyb3IiXSwiaW5kZW50LWxlZ2FjeSI6WyJlcnJvciJdLCJpbml0LWRlY2xhcmF0aW9ucyI6WyJlcnJvciJdLCJqc3gtcXVvdGVzIjpbImVycm9yIl0sImtleS1zcGFjaW5nIjpbImVycm9yIl0sImtleXdvcmQtc3BhY2luZyI6WyJlcnJvciJdLCJsaW5lLWNvbW1lbnQtcG9zaXRpb24iOlsiZXJyb3IiXSwibGluZWJyZWFrLXN0eWxlIjpbImVycm9yIl0sImxpbmVzLWFyb3VuZC1jb21tZW50IjpbImVycm9yIl0sImxpbmVzLWFyb3VuZC1kaXJlY3RpdmUiOlsiZXJyb3IiXSwibGluZXMtYmV0d2Vlbi1jbGFzcy1tZW1iZXJzIjpbImVycm9yIl0sImxvZ2ljYWwtYXNzaWdubWVudC1vcGVyYXRvcnMiOlsiZXJyb3IiXSwibWF4LWNsYXNzZXMtcGVyLWZpbGUiOlsiZXJyb3IiXSwibWF4LWRlcHRoIjpbImVycm9yIl0sIm1heC1sZW4iOlsiZXJyb3IiXSwibWF4LWxpbmVzIjpbImVycm9yIl0sIm1heC1saW5lcy1wZXItZnVuY3Rpb24iOlsiZXJyb3IiXSwibWF4LW5lc3RlZC1jYWxsYmFja3MiOlsiZXJyb3IiXSwibWF4LXBhcmFtcyI6WyJlcnJvciJdLCJtYXgtc3RhdGVtZW50cyI6WyJlcnJvciJdLCJtYXgtc3RhdGVtZW50cy1wZXItbGluZSI6WyJlcnJvciJdLCJtdWx0aWxpbmUtY29tbWVudC1zdHlsZSI6WyJlcnJvciJdLCJtdWx0aWxpbmUtdGVybmFyeSI6WyJlcnJvciJdLCJuZXctY2FwIjpbImVycm9yIl0sIm5ldy1wYXJlbnMiOlsiZXJyb3IiXSwibmV3bGluZS1hZnRlci12YXIiOlsiZXJyb3IiXSwibmV3bGluZS1iZWZvcmUtcmV0dXJuIjpbImVycm9yIl0sIm5ld2xpbmUtcGVyLWNoYWluZWQtY2FsbCI6WyJlcnJvciJdLCJuby1hbGVydCI6WyJlcnJvciJdLCJuby1hcnJheS1jb25zdHJ1Y3RvciI6WyJlcnJvciJdLCJuby1hc3luYy1wcm9taXNlLWV4ZWN1dG9yIjpbImVycm9yIl0sIm5vLWF3YWl0LWluLWxvb3AiOlsiZXJyb3IiXSwibm8tYml0d2lzZSI6WyJlcnJvciJdLCJuby1idWZmZXItY29uc3RydWN0b3IiOlsiZXJyb3IiXSwibm8tY2FsbGVyIjpbImVycm9yIl0sIm5vLWNhc2UtZGVjbGFyYXRpb25zIjpbImVycm9yIl0sIm5vLWNhdGNoLXNoYWRvdyI6WyJlcnJvciJdLCJuby1jbGFzcy1hc3NpZ24iOlsiZXJyb3IiXSwibm8tY29tcGFyZS1uZWctemVybyI6WyJlcnJvciJdLCJuby1jb25kLWFzc2lnbiI6WyJlcnJvciJdLCJuby1jb25mdXNpbmctYXJyb3ciOlsiZXJyb3IiXSwibm8tY29uc29sZSI6WyJlcnJvciJdLCJuby1jb25zdC1hc3NpZ24iOlsiZXJyb3IiXSwibm8tY29uc3RhbnQtYmluYXJ5LWV4cHJlc3Npb24iOlsiZXJyb3IiXSwibm8tY29uc3RhbnQtY29uZGl0aW9uIjpbImVycm9yIl0sIm5vLWNvbnN0cnVjdG9yLXJldHVybiI6WyJlcnJvciJdLCJuby1jb250aW51ZSI6WyJlcnJvciJdLCJuby1jb250cm9sLXJlZ2V4IjpbImVycm9yIl0sIm5vLWRlYnVnZ2VyIjpbImVycm9yIl0sIm5vLWRlbGV0ZS12YXIiOlsiZXJyb3IiXSwibm8tZGl2LXJlZ2V4IjpbImVycm9yIl0sIm5vLWR1cGUtYXJncyI6WyJlcnJvciJdLCJuby1kdXBlLWNsYXNzLW1lbWJlcnMiOlsiZXJyb3IiXSwibm8tZHVwZS1lbHNlLWlmIjpbImVycm9yIl0sIm5vLWR1cGUta2V5cyI6WyJlcnJvciJdLCJuby1kdXBsaWNhdGUtY2FzZSI6WyJlcnJvciJdLCJuby1kdXBsaWNhdGUtaW1wb3J0cyI6WyJlcnJvciJdLCJuby1lbHNlLXJldHVybiI6WyJlcnJvciJdLCJuby1lbXB0eSI6WyJlcnJvciJdLCJuby1lbXB0eS1jaGFyYWN0ZXItY2xhc3MiOlsiZXJyb3IiXSwibm8tZW1wdHktZnVuY3Rpb24iOlsiZXJyb3IiXSwibm8tZW1wdHktcGF0dGVybiI6WyJlcnJvciJdLCJuby1lbXB0eS1zdGF0aWMtYmxvY2siOlsiZXJyb3IiXSwibm8tZXEtbnVsbCI6WyJlcnJvciJdLCJuby1ldmFsIjpbImVycm9yIl0sIm5vLWV4LWFzc2lnbiI6WyJlcnJvciJdLCJuby1leHRlbmQtbmF0aXZlIjpbImVycm9yIl0sIm5vLWV4dHJhLWJpbmQiOlsiZXJyb3IiXSwibm8tZXh0cmEtYm9vbGVhbi1jYXN0IjpbImVycm9yIl0sIm5vLWV4dHJhLWxhYmVsIjpbImVycm9yIl0sIm5vLWV4dHJhLXBhcmVucyI6WyJlcnJvciJdLCJuby1leHRyYS1zZW1pIjpbImVycm9yIl0sIm5vLWZhbGx0aHJvdWdoIjpbImVycm9yIl0sIm5vLWZsb2F0aW5nLWRlY2ltYWwiOlsiZXJyb3IiXSwibm8tZnVuYy1hc3NpZ24iOlsiZXJyb3IiXSwibm8tZ2xvYmFsLWFzc2lnbiI6WyJlcnJvciJdLCJuby1pbXBsaWNpdC1jb2VyY2lvbiI6WyJlcnJvciJdLCJuby1pbXBsaWNpdC1nbG9iYWxzIjpbImVycm9yIl0sIm5vLWltcGxpZWQtZXZhbCI6WyJlcnJvciJdLCJuby1pbXBvcnQtYXNzaWduIjpbImVycm9yIl0sIm5vLWlubGluZS1jb21tZW50cyI6WyJlcnJvciJdLCJuby1pbm5lci1kZWNsYXJhdGlvbnMiOlsiZXJyb3IiXSwibm8taW52YWxpZC1yZWdleHAiOlsiZXJyb3IiXSwibm8taW52YWxpZC10aGlzIjpbImVycm9yIl0sIm5vLWlycmVndWxhci13aGl0ZXNwYWNlIjpbImVycm9yIl0sIm5vLWl0ZXJhdG9yIjpbImVycm9yIl0sIm5vLWxhYmVsLXZhciI6WyJlcnJvciJdLCJuby1sYWJlbHMiOlsiZXJyb3IiXSwibm8tbG9uZS1ibG9ja3MiOlsiZXJyb3IiXSwibm8tbG9uZWx5LWlmIjpbImVycm9yIl0sIm5vLWxvb3AtZnVuYyI6WyJlcnJvciJdLCJuby1sb3NzLW9mLXByZWNpc2lvbiI6WyJlcnJvciJdLCJuby1tYWdpYy1udW1iZXJzIjpbImVycm9yIl0sIm5vLW1pc2xlYWRpbmctY2hhcmFjdGVyLWNsYXNzIjpbImVycm9yIl0sIm5vLW1peGVkLW9wZXJhdG9ycyI6WyJlcnJvciJdLCJuby1taXhlZC1yZXF1aXJlcyI6WyJlcnJvciJdLCJuby1taXhlZC1zcGFjZXMtYW5kLXRhYnMiOlsiZXJyb3IiXSwibm8tbXVsdGktYXNzaWduIjpbImVycm9yIl0sIm5vLW11bHRpLXNwYWNlcyI6WyJlcnJvciJdLCJuby1tdWx0aS1zdHIiOlsiZXJyb3IiXSwibm8tbXVsdGlwbGUtZW1wdHktbGluZXMiOlsiZXJyb3IiXSwibm8tbmF0aXZlLXJlYXNzaWduIjpbImVycm9yIl0sIm5vLW5lZ2F0ZWQtY29uZGl0aW9uIjpbImVycm9yIl0sIm5vLW5lZ2F0ZWQtaW4tbGhzIjpbImVycm9yIl0sIm5vLW5lc3RlZC10ZXJuYXJ5IjpbImVycm9yIl0sIm5vLW5ldyI6WyJlcnJvciJdLCJuby1uZXctZnVuYyI6WyJlcnJvciJdLCJuby1uZXctbmF0aXZlLW5vbmNvbnN0cnVjdG9yIjpbImVycm9yIl0sIm5vLW5ldy1vYmplY3QiOlsiZXJyb3IiXSwibm8tbmV3LXJlcXVpcmUiOlsiZXJyb3IiXSwibm8tbmV3LXN5bWJvbCI6WyJlcnJvciJdLCJuby1uZXctd3JhcHBlcnMiOlsiZXJyb3IiXSwibm8tbm9ub2N0YWwtZGVjaW1hbC1lc2NhcGUiOlsiZXJyb3IiXSwibm8tb2JqLWNhbGxzIjpbImVycm9yIl0sIm5vLW9iamVjdC1jb25zdHJ1Y3RvciI6WyJlcnJvciJdLCJuby1vY3RhbCI6WyJlcnJvciJdLCJuby1vY3RhbC1lc2NhcGUiOlsiZXJyb3IiXSwibm8tcGFyYW0tcmVhc3NpZ24iOlsiZXJyb3IiXSwibm8tcGF0aC1jb25jYXQiOlsiZXJyb3IiXSwibm8tcGx1c3BsdXMiOlsiZXJyb3IiXSwibm8tcHJvY2Vzcy1lbnYiOlsiZXJyb3IiXSwibm8tcHJvY2Vzcy1leGl0IjpbImVycm9yIl0sIm5vLXByb21pc2UtZXhlY3V0b3ItcmV0dXJuIjpbImVycm9yIl0sIm5vLXByb3RvIjpbImVycm9yIl0sIm5vLXByb3RvdHlwZS1idWlsdGlucyI6WyJlcnJvciJdLCJuby1yZWRlY2xhcmUiOlsiZXJyb3IiXSwibm8tcmVnZXgtc3BhY2VzIjpbImVycm9yIl0sIm5vLXJlc3RyaWN0ZWQtZXhwb3J0cyI6WyJlcnJvciJdLCJuby1yZXN0cmljdGVkLWdsb2JhbHMiOlsiZXJyb3IiXSwibm8tcmVzdHJpY3RlZC1pbXBvcnRzIjpbImVycm9yIl0sIm5vLXJlc3RyaWN0ZWQtbW9kdWxlcyI6WyJlcnJvciJdLCJuby1yZXN0cmljdGVkLXByb3BlcnRpZXMiOlsiZXJyb3IiXSwibm8tcmVzdHJpY3RlZC1zeW50YXgiOlsiZXJyb3IiXSwibm8tcmV0dXJuLWFzc2lnbiI6WyJlcnJvciJdLCJuby1yZXR1cm4tYXdhaXQiOlsiZXJyb3IiXSwibm8tc2NyaXB0LXVybCI6WyJlcnJvciJdLCJuby1zZWxmLWFzc2lnbiI6WyJlcnJvciJdLCJuby1zZWxmLWNvbXBhcmUiOlsiZXJyb3IiXSwibm8tc2VxdWVuY2VzIjpbImVycm9yIl0sIm5vLXNldHRlci1yZXR1cm4iOlsiZXJyb3IiXSwibm8tc2hhZG93IjpbImVycm9yIl0sIm5vLXNoYWRvdy1yZXN0cmljdGVkLW5hbWVzIjpbImVycm9yIl0sIm5vLXNwYWNlZC1mdW5jIjpbImVycm9yIl0sIm5vLXNwYXJzZS1hcnJheXMiOlsiZXJyb3IiXSwibm8tc3luYyI6WyJlcnJvciJdLCJuby10YWJzIjpbImVycm9yIl0sIm5vLXRlbXBsYXRlLWN1cmx5LWluLXN0cmluZyI6WyJlcnJvciJdLCJuby10ZXJuYXJ5IjpbImVycm9yIl0sIm5vLXRoaXMtYmVmb3JlLXN1cGVyIjpbImVycm9yIl0sIm5vLXRocm93LWxpdGVyYWwiOlsiZXJyb3IiXSwibm8tdHJhaWxpbmctc3BhY2VzIjpbImVycm9yIl0sIm5vLXVuZGVmIjpbImVycm9yIl0sIm5vLXVuZGVmLWluaXQiOlsiZXJyb3IiXSwibm8tdW5kZWZpbmVkIjpbImVycm9yIl0sIm5vLXVuZGVyc2NvcmUtZGFuZ2xlIjpbImVycm9yIl0sIm5vLXVuZXhwZWN0ZWQtbXVsdGlsaW5lIjpbImVycm9yIl0sIm5vLXVubW9kaWZpZWQtbG9vcC1jb25kaXRpb24iOlsiZXJyb3IiXSwibm8tdW5uZWVkZWQtdGVybmFyeSI6WyJlcnJvciJdLCJuby11bnJlYWNoYWJsZSI6WyJlcnJvciJdLCJuby11bnJlYWNoYWJsZS1sb29wIjpbImVycm9yIl0sIm5vLXVuc2FmZS1maW5hbGx5IjpbImVycm9yIl0sIm5vLXVuc2FmZS1uZWdhdGlvbiI6WyJlcnJvciJdLCJuby11bnNhZmUtb3B0aW9uYWwtY2hhaW5pbmciOlsiZXJyb3IiXSwibm8tdW51c2VkLWV4cHJlc3Npb25zIjpbImVycm9yIl0sIm5vLXVudXNlZC1sYWJlbHMiOlsiZXJyb3IiXSwibm8tdW51c2VkLXByaXZhdGUtY2xhc3MtbWVtYmVycyI6WyJlcnJvciJdLCJuby11bnVzZWQtdmFycyI6WyJlcnJvciJdLCJuby11c2UtYmVmb3JlLWRlZmluZSI6WyJlcnJvciJdLCJuby11c2VsZXNzLWFzc2lnbm1lbnQiOlsiZXJyb3IiXSwibm8tdXNlbGVzcy1iYWNrcmVmZXJlbmNlIjpbImVycm9yIl0sIm5vLXVzZWxlc3MtY2FsbCI6WyJlcnJvciJdLCJuby11c2VsZXNzLWNhdGNoIjpbImVycm9yIl0sIm5vLXVzZWxlc3MtY29tcHV0ZWQta2V5IjpbImVycm9yIl0sIm5vLXVzZWxlc3MtY29uY2F0IjpbImVycm9yIl0sIm5vLXVzZWxlc3MtY29uc3RydWN0b3IiOlsiZXJyb3IiXSwibm8tdXNlbGVzcy1lc2NhcGUiOlsiZXJyb3IiXSwibm8tdXNlbGVzcy1yZW5hbWUiOlsiZXJyb3IiXSwibm8tdXNlbGVzcy1yZXR1cm4iOlsiZXJyb3IiXSwibm8tdmFyIjpbImVycm9yIl0sIm5vLXZvaWQiOlsiZXJyb3IiXSwibm8td2FybmluZy1jb21tZW50cyI6WyJlcnJvciJdLCJuby13aGl0ZXNwYWNlLWJlZm9yZS1wcm9wZXJ0eSI6WyJlcnJvciJdLCJuby13aXRoIjpbImVycm9yIl0sIm5vbmJsb2NrLXN0YXRlbWVudC1ib2R5LXBvc2l0aW9uIjpbImVycm9yIl0sIm9iamVjdC1jdXJseS1uZXdsaW5lIjpbImVycm9yIl0sIm9iamVjdC1jdXJseS1zcGFjaW5nIjpbImVycm9yIl0sIm9iamVjdC1wcm9wZXJ0eS1uZXdsaW5lIjpbImVycm9yIl0sIm9iamVjdC1zaG9ydGhhbmQiOlsiZXJyb3IiXSwib25lLXZhciI6WyJlcnJvciJdLCJvbmUtdmFyLWRlY2xhcmF0aW9uLXBlci1saW5lIjpbImVycm9yIl0sIm9wZXJhdG9yLWFzc2lnbm1lbnQiOlsiZXJyb3IiXSwib3BlcmF0b3ItbGluZWJyZWFrIjpbImVycm9yIl0sInBhZGRlZC1ibG9ja3MiOlsiZXJyb3IiXSwicGFkZGluZy1saW5lLWJldHdlZW4tc3RhdGVtZW50cyI6WyJlcnJvciJdLCJwcmVmZXItYXJyb3ctY2FsbGJhY2siOlsiZXJyb3IiXSwicHJlZmVyLWNvbnN0IjpbImVycm9yIl0sInByZWZlci1kZXN0cnVjdHVyaW5nIjpbImVycm9yIl0sInByZWZlci1leHBvbmVudGlhdGlvbi1vcGVyYXRvciI6WyJlcnJvciJdLCJwcmVmZXItbmFtZWQtY2FwdHVyZS1ncm91cCI6WyJlcnJvciJdLCJwcmVmZXItbnVtZXJpYy1saXRlcmFscyI6WyJlcnJvciJdLCJwcmVmZXItb2JqZWN0LWhhcy1vd24iOlsiZXJyb3IiXSwicHJlZmVyLW9iamVjdC1zcHJlYWQiOlsiZXJyb3IiXSwicHJlZmVyLXByb21pc2UtcmVqZWN0LWVycm9ycyI6WyJlcnJvciJdLCJwcmVmZXItcmVmbGVjdCI6WyJlcnJvciJdLCJwcmVmZXItcmVnZXgtbGl0ZXJhbHMiOlsiZXJyb3IiXSwicHJlZmVyLXJlc3QtcGFyYW1zIjpbImVycm9yIl0sInByZWZlci1zcHJlYWQiOlsiZXJyb3IiXSwicHJlZmVyLXRlbXBsYXRlIjpbImVycm9yIl0sInF1b3RlLXByb3BzIjpbImVycm9yIl0sInF1b3RlcyI6WyJlcnJvciJdLCJyYWRpeCI6WyJlcnJvciJdLCJyZXF1aXJlLWF0b21pYy11cGRhdGVzIjpbImVycm9yIl0sInJlcXVpcmUtYXdhaXQiOlsiZXJyb3IiXSwicmVxdWlyZS11bmljb2RlLXJlZ2V4cCI6WyJlcnJvciJdLCJyZXF1aXJlLXlpZWxkIjpbImVycm9yIl0sInJlc3Qtc3ByZWFkLXNwYWNpbmciOlsiZXJyb3IiXSwic2VtaSI6WyJlcnJvciJdLCJzZW1pLXNwYWNpbmciOlsiZXJyb3IiXSwic2VtaS1zdHlsZSI6WyJlcnJvciJdLCJzb3J0LWltcG9ydHMiOlsiZXJyb3IiXSwic29ydC1rZXlzIjpbImVycm9yIl0sInNvcnQtdmFycyI6WyJlcnJvciJdLCJzcGFjZS1iZWZvcmUtYmxvY2tzIjpbImVycm9yIl0sInNwYWNlLWJlZm9yZS1mdW5jdGlvbi1wYXJlbiI6WyJlcnJvciJdLCJzcGFjZS1pbi1wYXJlbnMiOlsiZXJyb3IiXSwic3BhY2UtaW5maXgtb3BzIjpbImVycm9yIl0sInNwYWNlLXVuYXJ5LW9wcyI6WyJlcnJvciJdLCJzcGFjZWQtY29tbWVudCI6WyJlcnJvciJdLCJzdHJpY3QiOlsiZXJyb3IiXSwic3dpdGNoLWNvbG9uLXNwYWNpbmciOlsiZXJyb3IiXSwic3ltYm9sLWRlc2NyaXB0aW9uIjpbImVycm9yIl0sInRlbXBsYXRlLWN1cmx5LXNwYWNpbmciOlsiZXJyb3IiXSwidGVtcGxhdGUtdGFnLXNwYWNpbmciOlsiZXJyb3IiXSwidW5pY29kZS1ib20iOlsiZXJyb3IiXSwidXNlLWlzbmFuIjpbImVycm9yIl0sInZhbGlkLXR5cGVvZiI6WyJlcnJvciJdLCJ2YXJzLW9uLXRvcCI6WyJlcnJvciJdLCJ3cmFwLWlpZmUiOlsiZXJyb3IiXSwid3JhcC1yZWdleCI6WyJlcnJvciJdLCJ5aWVsZC1zdGFyLXNwYWNpbmciOlsiZXJyb3IiXSwieW9kYSI6WyJlcnJvciJdfSwibGFuZ3VhZ2VPcHRpb25zIjp7InBhcnNlck9wdGlvbnMiOnsiZWNtYUZlYXR1cmVzIjp7fX19fX0=). If that's the intended nature, all good, though would prefer parity with eslint as much as possible to help teams migrating; if that's not the intended nature, then there is probably a bug. 

Thanks for your great work on this project, I love using it!

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
I believe this is intentional, but it does not seem to be properly documented.

I question this behavior because our formatter is able to remove unnecessary quotes around properties.
In fact, `useLiteralKeys` conflicts with the `quoteProperties` configuration of our JavaScript formatter.

So, personally, I am in favor of reducing the scope of `useLiteralKeys` to property access.

**Comment by ematipico** [comment]
> So, personally, I am in favor of reducing the scope of useLiteralKeys to property access.

It's not very clear what reducing scope means. If I understand correctly, the code action should only remove the brackets and keep the quotes, correct? E.g.

```js
// original
const a = {
  ["f"]: b
}
```

New code action
```diff
const a = {
-  f: b
+  'f': b
}
```

**Comment by Conaclos** [comment]
> It's not very clear what reducing scope means.

The rule could only apply to property access:

```diff
- a.b["c"];
+ a.b.c;
```

Your example could be untouched.
However, I noticed that our formatter doesn't remove brackets when they are not needed. This follows Prettier. Should we diverge from Prettier here? It could make sense?

**Comment by scharkthemark** [comment]
> In fact, useLiteralKeys conflicts with the quoteProperties configuration of our JavaScript formatter.

This is actually what tipped me off that something might be funky in the first place. I had set `quoteProperties: "preserve"` and ran it on this code:

```
const test = {
    "test": 1,
    "test 2": 2,
    "test3": 1,
};
```

The formatter preserved the quotes around the properties, but the linter threw errors. The only way to fix was to unquote the `"test"` and `"test3"` properties, which seems to contradict the intended nature of `quoteProperties: "preserve"`

Reducing the scope of `useLiteralKeys` makes sense to me.

**Comment by ematipico** [comment]
Yeah sounds good. We could consider this a fix, since it oversteps the formatter boundaries
