### ISSUE TITLE
🐛 "Unexpected value or character. biome(parse)" can i disable biome css parser?

### ISSUE THREAD

**Issue by nevirum** [biomejs/biome#3107]
### Environment information

```block
CLI:
  Version:                      1.8.0
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm"
  JS_RUNTIME_VERSION:           "v20.14.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/9.1.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

Biome show error due to @media query
<img width="445" alt="image" src="https://github.com/biomejs/biome/assets/31209923/cfea7b62-3c11-46d7-9f1e-3f703a996bc0">

### Expected result

Disable parser via biome.json

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by pikeas** [comment]
Similar issue here:

```
main {
    div:is(.other) {
        color: black;
    }
}
```

Biome is unable to parse this: `Expected a declaration item but instead found ','`.

The issue here is that I have Biome disabled for CSS files:

```
{
	"files": {
		"include": [
			"**/*.js",
			"**/*.json",
			"**/*.jsonc",
			"**/*.jsx",
			"**/*.ts",
			"**/*.tsx"
		]
	},
}
```

Biome should not report errors for ignored files, as well as syntaxes for which both linting and formatting are disabled. Ideally it would never parse them in the first place.

**Comment by Conaclos** [comment]
@pikeas
Could you open new issues for each one?

As a workaround, I think you can completely disable CSS parsing, by disabling ll features (formatter and linter) for CSS:

```json
{
  "css": {
    "formatter": { "enabled": false },
    "linter": { "enabled": false }
  }
}
```

**Comment by OliverJAsh** [comment]
As mentioned [here](https://github.com/biomejs/biome-vscode/pull/222#issuecomment-2150517928) I've been having similar problems. Interestingly this doesn't occur with the pre-release version of the extension. Not sure why that is?
