### ISSUE TITLE
📎 Forbid `undefined` as type name

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#3121]
### Description

[TypeScript 5.5 now forbids `undefined` as type name](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-rc/#undefined-is-no-longer-a-definable-type-name). We should update our parser in order to reject `undefined` as type name in the following cases:

```ts
type undefined = 0;
interface undefined {}
```

It seems that TypeScript also rejects the following code:

```ts
class undefined {}
enum undefined {}
```

**Comment by ematipico** [comment]
Does it forbid it also for JavaScript files?

**Comment by Conaclos** [comment]
> Does it forbid it also for JavaScript files?

I don't know. We have to investigate the case,

**Comment by fireairforce** [comment]
oh sorry, maybe i will deal the typescript case first

**Comment by ematipico** [comment]
This issue was marked for Biome 2.0, but it was merged to `main`.

@Conaclos should we revert it?

**Comment by Conaclos** [comment]
> should we revert it?

I think it is fine since we consider it as a fix.
