### ISSUE TITLE
🐛 Code highlighting is missing 

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#315]
### Environment information

```block
Online playground
```

### What happened?

Code highlighting is absent.
This could be caused by the recent [update of the playground](https://github.com/biomejs/biome/pull/311).

### Expected result

Code highlighting should be present in the playground.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
@DerTimonius any idea?

**Comment by DerTimonius** [comment]
Hm...maybe a side effect when running `pnpm install`? Could be that another dependency did upgrade when I upgraded prettier. Will look into it later today

**Comment by nissy-dev** [comment]
This is likely because the codemirror-related packages were updated due to `pnpm install`. I have encountered a similar issue before. It seems that we should roll back these updates and pin these packages (not use `^x.x.x` or `~x.x.x`).

**Comment by DerTimonius** [comment]
I was able to fix it in #328. I followed the idea of @nissy-dev to pin the package versions of the codemirror dependencies
