### ISSUE TITLE
📎 Change `bitflags` for `enumflags2`

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#3157]
### Description

Inside the `biome_js_analyze`, we started using `enumflags2`, and the DX has been positive.

This is a task to remove `bitflags` from the codebase, and use `enumflags2`. This is an example of definition:

https://github.com/biomejs/biome/blob/b75d30e8c48f64dfc44b93585e1e280f8abda8cc/crates/biome_js_syntax/src/modifier_ext.rs#L12-L27

Feel free to send multiple PRs to address this, we use `bit_flags` in different places of the repository.

**Comment by mvares** [comment]
@ematipico, is there still work to be done here?

**Comment by dyc3** [comment]
Nope, this should have been closed in #3529.

**Comment by dyc3** [comment]
Wait, nevermind, the package name is actually `bitflags` without the underscore. We still depend on that.

**Comment by ematipico** [comment]
> @ematipico, is there still work to be done here?

@mvares yes, mostly `biome_js_parser`

There, I suggest porting one bitflag at the time, because there are a lot.

**Comment by mvares** [comment]
@ematipico I'll start contribuing to biome. If I'd have some help, can I ask here?

**Comment by ematipico** [comment]
Of course!

**Comment by Javimtib92** [comment]
I would like to contribute for the first time to Biome, could I contribute to this issue as well @ematipico ? .  I would work on refactoring `biome_diagnostics`  if that's ok to you.

**Comment by dyc3** [comment]
Yes, absolutely. As previously stated though, refactor one flag per PR so it's easier for us to review.
