### ISSUE TITLE
📝 CSS formatter converts custom identifiers to lowercase

### ISSUE THREAD

**Issue by joshwooding** [biomejs/biome#3184]
### Environment information

```bash
Playground link
```

### Playground link

https://biomejs.dev/playground/?files.main.css=LgBjAG8AbgB0AGEAaQBuAGUAcgAgAHsACgAgACAAZwByAGkAZAAtAHQAZQBtAHAAbABhAHQAZQAtAGEAcgBlAGEAcwA6ACAAIgBsAGEAYgBlAGwAIABmAG8AcgBtAEMAbwBuAHQAcgBvAGwAIgAKAH0ACgAKAC4AYwBvAG4AdABhAGkAbgBlAHIAIABpAG4AcAB1AHQAIAB7AAoAIAAgAGcAcgBpAGQALQBhAHIAZQBhADoAIABmAG8AcgBtAEMAbwBuAHQAcgBvAGwAOwAKAH0A

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by joshwooding** [comment]
Potentially related issue/solution: #3068

**Comment by denbezrukov** [comment]
@ematipico 

Hmm,

I’m not sure that this is the best or easiest solution here. I think we have two ways to solve it:

	1.	Don’t change the case at all.
	2.	Change the case only for reserved words. However, to achieve this, we have to know all of them inside the parser/formatter.

**Comment by ematipico** [comment]
> Don’t change the case at all.

Maybe we should evaluate this solution. The formatter doesn't have any semantic knowledge of the document, so I suppose any "unknown" things should be left untouched.
