### ISSUE TITLE
🐛  Request textDocument/formatting failed

### ISSUE THREAD

**Issue by majkl-zumberi** [biomejs/biome#3213]
### Environment information

```block
CLI:
  Version:                      1.8.1
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.19.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/1.22.22"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

Hi, i'm new into the biome environment
today i tried to install it and configure biome in my react project
i removed every eslint and prettier related dev deps
and configured biome
"@biomejs/biome": "1.8.1",

biome.json
```
{
	"$schema": "https://biomejs.dev/schemas/1.8.1/schema.json",
	"organizeImports": {
		"enabled": true
	},
	"linter": {
		"enabled": true,
		"rules": {
			"recommended": true
		}
	}
}
```

i'm using VScode so i installed the recommended vscode plugin 
after that i get this error 
```
  Request textDocument/formatting failed.
  Message: missing field tabSize
  Code: -32602
```

where this property should be added? and why isn't automatically added when the yarn biome init is being fired?

### Expected result

it should not throw an error

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Biome doesn't have a `tabSize` option. It seems your editor is calling some other formatter. Make sure that your default formatter is set to be Biome for the file extensions you're trying to format.

https://biomejs.dev/reference/vscode/#default-formatter
