### ISSUE TITLE
📝 Biome cannot handle JSON formatting but Prettier can

### ISSUE THREAD

**Issue by dalisoft** [biomejs/biome#3221]
### Environment information

```bash
CLI:
  Version:                      1.8.1
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.13.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "bun/1.1.13"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              true
  Organize imports disabled:    false
  VCS disabled:                 true

Formatter:
  Format with errors:           false
  Indent style:                 Space
  Indent width:                 2
  Line ending:                  Lf
  Line width:                   80
  Attribute position:           Auto
  Ignore:                       []
  Include:                      []

JavaScript Formatter:
  Enabled:                      true
  JSX quote style:              Double
  Quote properties:             AsNeeded
  Trailing commas:              None
  Semicolons:                   AsNeeded
  Arrow parentheses:            Always
  Bracket spacing:              true
  Bracket same line:            false
  Quote style:                  Single
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           Auto

JSON Formatter:
  Enabled:                      true
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset

CSS Formatter:
  Enabled:                      false
  Indent style:                 Tab
  Indent width:                 2
  Line ending:                  Lf
  Line width:                   80
  Quote style:                  Double

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
  "$schema": "https://biomejs.dev/schemas/1.8.1/schema.json",
  "formatter": {
    "enabled": true,
    "formatWithErrors": false,
    "lineWidth": 80,
    "indentStyle": "space",
    "indentWidth": 2,
    "lineEnding": "lf"
  },
  "linter": {
    "enabled": false
  },
  "javascript": {
    "formatter": {
      "enabled": true,
      "quoteStyle": "single",
      "trailingCommas": "none",
      "arrowParentheses": "always",
      "bracketSpacing": true,
      "bracketSameLine": true
    }
  },
  "json": {
    "parser": {
      "allowComments": true,
      "allowTrailingCommas": false
    },
    "formatter": {
      "enabled": true
    }
  }
}
```

### Playground link

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&semicolons=as-needed&bracketSameLine=true&enabledLinting=false&importSortingEnabled=false&files.prettier.json=ewAKACAAIABzAGkAbgBnAGwAZQBRAHUAbwB0AGUAOgAgAHQAcgB1AGUALAAKACAAIABwAHIAaQBuAHQAVwBpAGQAdABoADoAIAA4ADAALAAKACAAIAB0AHIAYQBpAGwAaQBuAGcAQwBvAG0AbQBhADoAIAAnAG4AbwBuAGUAJwAsAAoAIAAgAGEAcgByAG8AdwBQAGEAcgBlAG4AcwA6ACAAJwBhAGwAdwBhAHkAcwAnACwACgAgACAAYgByAGEAYwBrAGUAdABTAHAAYQBjAGkAbgBnADoAIAB0AHIAdQBlACwACgAgACAAYgByAGEAYwBrAGUAdABTAGEAbQBlAEwAaQBuAGUAOgAgAHQAcgB1AGUALAAKACAAIAB1AHMAZQBUAGEAYgBzADoAIABmAGEAbABzAGUALAAKACAAIABlAG0AYgBlAGQAZABlAGQATABhAG4AZwB1AGEAZwBlAEYAbwByAG0AYQB0AHQAaQBuAGcAOgAgACcAYQB1AHQAbwAnACwACgAgACAAcwBpAG4AZwBsAGUAQQB0AHQAcgBpAGIAdQB0AGUAUABlAHIATABpAG4AZQA6ACAAdAByAHUAZQAsAAoAIAAgAGUAbgBkAE8AZgBMAGkAbgBlADoAIAAnAGwAZgAnAAoAfQA%3D

### Video demo

https://github.com/biomejs/biome/assets/3511344/b9a3782c-6e3b-4b10-beb6-30c7f5ec32d7

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by SuperchupuDev** [comment]
biome only formats known JSON extensions (.json, .jsonc etc), and `.prettierrc` is not one of them. i believe prettier supports `.prettierrc.json` though, renaming the prettier config file to that should work

**Comment by ematipico** [comment]
Biome doesn't know how to handle `rc` files, so it's not a bug.

RC files can contain three languages: JavaScript, JSON or YAML, hence Biome can't handle them

**Comment by dalisoft** [comment]
@SuperchupuDev @ematipico I am set type of file as JSON on VSCode then captured video demo, please see. Or look at playground link and output differs even i am set file type to json

**Comment by SuperchupuDev** [comment]
the playground link you sent contains invalid JSON, with things not supported by JSON such as unquoted keys and single quotes

**Comment by dalisoft** [comment]
@SuperchupuDev and prettier formats it pretty well. So seems currently (or even on future) Biome formats strictly without any unsafe formats for invalid JSON format to JSON formatting?

**Comment by SuperchupuDev** [comment]
it looks like the format you're trying to use is [json5](https://json5.org/) which is supported by prettier but not biome. there was a discussion about it #282, it's not widely supported across developer tools
