### ISSUE TITLE
🐛 Files and paths from the `/nix/store` directory are checked by default

### ISSUE THREAD

**Issue by zimeg** [biomejs/biome#3261]
### Environment information

```block
CLI:
  Version:                      1.8.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "screen-256color"
  JS_RUNTIME_VERSION:           "v20.12.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.5.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

Running `npx @biomejs/biome check` in a project directory checks the files in that directory but also unexpected files in the `/nix/store` directory.

When running the command in the `/code/project/example` directory all of these checks might happen: 

```txt
/code/project/example/src/app.js format ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  ✖ Formatter would have printed the following content:

     9  9 │
    10    │ - app.message('hello',·async·({·say·})·=>·{
    11    │ - ··await·say('howdy');
       10 │ + app.message("hello",·async·({·say·})·=>·{
       11 │ + ··await·say("howdy");
    12 12 │   });
    13 13 │
```

```txt
/nix/store/34j0a2fmayyf7bmr5jfl7v0svk1p91gh-source/project/example/src/app.js format ━━━━━━━━━━━━━━━━━

  ✖ Formatter would have printed the following content:

     9  9 │
    10    │ - app.message('hello',·async·({·say·})·=>·{
    11    │ - ··await·say('howdy');
       10 │ + app.message("hello",·async·({·say·})·=>·{
       11 │ + ··await·say("howdy");
    12 12 │   });
    13 13 │
```

And other paths from the `/code/project` directory - a version controlled repository - might be checked too:

```txt
/nix/store/34j0a2fmayyf7bmr5jfl7v0svk1p91gh-source/project/other/src/index.ts format ━━━━━━━━━━

  ✖ Formatter would have printed the following content:

     1    │ - import·{·helper·}·from·'is-even';
        1 │ + import·{·helper·}·from·"is-even";
     2  2 │
```

I'm finding that adding the following to `biome.json` will ignore the unexpected checks:

```diff
  {
    "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
    "organizeImports": {
      "enabled": true,
+     "ignore": ["/nix/store/*"]
    },
    "formatter": {
+     "ignore": ["/nix/store/*"],
      "indentStyle": "space"
    },
    "linter": {
      "enabled": true,
+     "ignore": ["/nix/store/*"],
      "rules": {
        "recommended": false
      }
    }
  }
```

I'm not sure what's causing this, but perhaps it's an unexpected `NODE_PATH`:

```sh
$ echo $NODE_PATH
/nix/store/5rrp93ky54xgwnnmzbdffr739lxc6iy1-nodejs-20.12.2/lib/node_modules
```

```sh
$ which npx
/nix/store/5rrp93ky54xgwnnmzbdffr739lxc6iy1-nodejs-20.12.2/bin/npx
```

The `biome` CLI is found in the example project `node_modules` too - not as a global install:

```
/code/project/example/node_modules/@biomejs/biome/bin/biome
```

### Expected result

It'd be nice if those paths didn't need to be ignored in `biome.json`! But not a big problem at all since ignoring works and the linting and formatting checks work super well 👏 

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by zimeg** [comment]
😅 This might be too specific to my setups, but I also found that the `.direnv` directory from [direnv](https://direnv.net) had to be ignored to avoid permission errors when using `--write` too:

```
/nix/store/34j0a2fmayyf7bmr5jfl7v0svk1p91gh-source/project/other/src/index.ts internalError/io  INTERNAL  ━━━━━━━━━━

  ✖ Permission denied (os error 13)

  ⚠ This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.

```

**Comment by ematipico** [comment]
I don't know Nix, but is it possible that there are some possible symbolic links in your project that end up pointing to `/nix/store`?

**Comment by zimeg** [comment]
@ematipico Other than the `node` / `npx` / `npm` binaries, not as far as I can tell. These are isolated from other dependencies and projects  - just the installation of Node exists here - and are all found under the same path:

```
/nix/store/5rrp93ky54xgwnnmzbdffr739lxc6iy1-nodejs-20.12.2
```

Project dependencies seem to be installed to just the project `node_modules` too:

```
$ npm ls
example@2024.06.22 /code/project/example
├── @biomejs/biome@1.8.2
├── nodemon@3.1.4
└── src@ -> ./src
```

**Comment by zimeg** [comment]
> ...is it possible that there are some possible symbolic links in your project that end up pointing to `/nix/store`?

@ematipico Wait, you called it! These were hiding in `.direnv`:

```sh
$ ls .direnv
bin/
flake-inputs/
flake-profile-a5d5b61aa8a61b7d9d765e1daf971a9a578f1cfa -> /nix/store/fc45711vc062fwhahn1qrxifgcqxg9p1-nix-shell-env
```

It seems common to `.gitignore` this path so the following config hides all of the unexpected files just fine:

```json
{
  "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
  "vcs": {
    "enabled": true,
    "clientKind": "git"
  }
}
```

This seems like a solid fix so going to close the issue! Thank you for taking a look at this 🙏
