### ISSUE TITLE
📎 Implement `stylelint/no-irregular-whitespace`

### ISSUE THREAD

**Issue by chansuke** [biomejs/biome#3264]
## Description

Implement [no-irregular-whitespace](https://stylelint.io/user-guide/rules/no-irregular-whitespace/)

> [!IMPORTANT]
>   - Please skip implementing options for now since we will evaluate users actually want them later.
>   - Please ignore handling extended CSS language cases such as sass and less.
>   - Please skip custom function since we haven't syntax model yet.

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by DerTimonius** [comment]
Might I take a shot at this? 🙂

**Comment by ematipico** [comment]
@DerTimonius 

A person is already implementing the same rule for JavaScript https://github.com/biomejs/biome/issues/2511#issuecomment-2202751073

We can definitely reuse the same logic across grammars

**Comment by chansuke** [comment]
@DerTimonius 
https://github.com/biomejs/biome/pull/3333 has been merged :)
Can you please take a look?

**Comment by DerTimonius** [comment]
will do!

**Comment by chansuke** [comment]
🚀
