### ISSUE TITLE
☂️ GraphQL formatter 

### ISSUE THREAD

**Issue by denbezrukov** [biomejs/biome#3311]
### Description

- [x] #3319
- [x]  Comments: Handling of comments within GraphQL files for consistent formatting.  https://github.com/biomejs/biome/blob/main/crates/biome_graphql_formatter/tests/specs/prettier/graphql/comments/interfaces.graphql
https://github.com/biomejs/biome/blob/main/crates/biome_graphql_formatter/tests/specs/prettier/graphql/interface/separator-detection.graphql

- [x]  Performance tests
- [x]  Integration with VSCode
- [ ]  Integration with IntelliJ
- [x] Integration with zed

**Comment by chansuke** [comment]
:rocket:

**Comment by denbezrukov** [comment]
For VSCode https://github.com/biomejs/biome-vscode/pull/252 should be enough, right?

**Comment by ematipico** [comment]
@denbezrukov yes
