### ISSUE TITLE
Proposal to rename "quickfix.biome" to "source.fixAll.biome"

### ISSUE THREAD

**Issue by predragnikolic** [biomejs/biome#3339]
### Description

Hello,

Currently biome exposes a `"quickfix.biome"` code action on save. (see the [docs](https://biomejs.dev/reference/vscode/#fix-on-save))
The proposal is to rename `quickfix.biome` to `source.fixAll.biome` because it adheres to the LSP spec more:

https://github.com/microsoft/language-server-protocol/issues/1629#issuecomment-1380267878
> For code actions on save: the client will ask with a specific kind for code actions on save. The kind is CodeActionKind.SourceFixAll

```
export namespace CodeActionKind {
	export const Empty: CodeActionKind = '';

	/**
	 * Base kind for quickfix actions: 'quickfix'.
	 */
	export const QuickFix: CodeActionKind = 'quickfix';

	// ...
	/**
	 * Base kind for a 'fix all' source action: `source.fixAll`.
	 *
	 * 'Fix all' actions automatically fix errors that have a clear fix that
	 * do not require user input. They should not suppress errors or perform
	 * unsafe fixes such as generating new types or classes.
	 *
	 * @since 3.17.0
	 */
	export const SourceFixAll: CodeActionKind = 'source.fixAll';
}
```

Related issues:
https://github.com/sublimelsp/LSP/issues/2495

**Comment by ematipico** [comment]
That's definitely a sound proposal. I wouldn't change it right away because it would break people's code.

We can add it, deprecate the current when, and remove it in V2. How does that sound?

**Comment by predragnikolic** [comment]
@ematipico yes, sounds good. Not breaking anyone workflow is a good option.

**Comment by suxin2017** [comment]
<img width="1366" alt="image" src="https://github.com/user-attachments/assets/5adee6bb-4ed6-46b8-8352-eb94b2c9aadb">
I noticed this code action already exist

**Comment by suxin2017** [comment]
https://github.com/biomejs/biome/blob/fe09cab96b5abccb03b73d46ce6c3bddec1c95d8/crates/biome_lsp/src/handlers/analysis.rs#L24-L25

https://github.com/biomejs/biome/blob/fe09cab96b5abccb03b73d46ce6c3bddec1c95d8/crates/biome_lsp/src/handlers/analysis.rs#L63-L74

https://github.com/biomejs/biome/blob/fe09cab96b5abccb03b73d46ce6c3bddec1c95d8/crates/biome_lsp/src/handlers/analysis.rs#L199

```json
{
  "editor.codeActionsOnSave": {
    "source.fixAll.biome": "explicit"
  }
}
```

I see that the code here has fix-all, and my vscode can also work properly, is I looking for the wrong location？

**Comment by ematipico** [comment]
Nice analysis! I believe it's an issue in our documentation then

**Comment by rchl** [comment]
Note that biome must also report that code actions through `codeActionProvider.codeActionKinds` server capability. See https://github.com/microsoft/language-server-protocol/issues/1629#issuecomment-2245413255

**Comment by suxin2017** [comment]
> Note that biome must also report that code action through `codeActionProvider.codeActionKinds` server capability. See [microsoft/language-server-protocol#1629 (comment)](https://github.com/microsoft/language-server-protocol/issues/1629#issuecomment-2245413255)

<img width="965" alt="image" src="https://github.com/user-attachments/assets/f7456c98-fdf0-48ee-a3bb-55788281b98f">

I think it's set to true, but I'm not sure if true will meet your needs

**Comment by suxin2017** [comment]
<img width="1101" alt="image" src="https://github.com/user-attachments/assets/02da5807-278c-427d-be6a-85e2777ec0e8">
I see what you mean, I mean so far 'codeActionProvider: true' is set, do we have to set codeActionKinds to declare source.fixAll.biome as an array?
I see the lsp protocol supports the bool definition
[language-server-protocol](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#:~:text=honorsChangeAnnotations%3F%3A%20boolean%3B%0A%7D-,Server%20Capability%3A,for%20a%20code%20action.%0A%09%20*%0A%09%20*%20%40since%203.16.0%0A%09%20*/%0A%09resolveProvider%3F%3A%20boolean%3B%0A%7D,-Registration%20Options%3A%20CodeActionRegistrationOptions%20defined)

**Comment by predragnikolic** [comment]
@suxin2017 this comment should answer your question ->
https://github.com/microsoft/language-server-protocol/issues/1629#issuecomment-2268446838

**Comment by rchl** [comment]
The LSP spec author admitted in https://github.com/microsoft/language-server-protocol/issues/1629#issuecomment-2268446838 that if the code action is not registered in `codeActionProvider.codeActionKinds` that if the code action is not registered there then editor should utilize it for the "code actions on save" functionality.

That said, it was also said that VSCode doesn't follow that now.
And also, not sure how the `codeActionProvider: true` response should be treated in this case...

I would say that specifying the code action should be ideal and most compatible with different LSP clients.

**Comment by suxin2017** [comment]
Ok, I got it. Can you check this pr

**Comment by predragnikolic** [comment]
reopening this as part of https://github.com/biomejs/biome/pull/3897

**Comment by plaa** [comment]
Should this be updated in the [documentation](https://biomejs.dev/reference/vscode/#fix-on-save) or is that pending something?

**Comment by ematipico** [comment]
You can send a PR to update it

**Comment by ematipico** [comment]
I believe there's some confusion:
- `source.fixAll.biome` is a particular filter that is meant to apply safe code actions on save
- `quickfix.biome` is a particular filter that is meant to tell the LSP to **show** code fixes when a diagnostic is raised. In VSCode, it is usually shown as a lightbulb. 

@ljukas if "apply fix on save" doesn't work, then it's possible you're affected by https://github.com/biomejs/biome/issues/5488, which is fixed (but not released yet)

**Comment by ljukas** [comment]
The confusion is increased then. But yes I seem to be affected by the "apply fix on save" not working. So I will wait until next beta release and hope it starts working.

**Comment by connorb08** [comment]
> I believe there's some confusion:
> 
> * `source.fixAll.biome` is a particular filter that is meant to apply safe fixes on save
> * `quickfix.biome` is a particular filter that is meant to tell the LSP to **show** code fixes when a diagnostic is raised. In VSCode, it is usually shown as a lightbulb.
> 
> [@ljukas](https://github.com/ljukas) if "apply fix on save" doesn't work, then it's possible you're affected by [#5488](https://github.com/biomejs/biome/issues/5488), which is fixed (but not released yet)

That doesn't seem to be the behavior for me. By default, the quick fix dialog is available in VSCode. When I tried to setup fix on save, I used this config as outlined in the docs:

```json
"editor.codeActionsOnSave": {
    "source.fixAll.biome": "explicit",
    "source.organizeImports.biome": "explicit"
},
```

With those settings, the quick fix dialog was showing up, and the biome CLI was able to apply fixes, but in VSCode, they were not being applied on save. Adding `"quickfix.biome": "explicit"` to the settings fixed the issue:

```json
"editor.codeActionsOnSave": {
    "source.fixAll.biome": "explicit",
    "quickfix.biome": "explicit",
    "source.organizeImports.biome": "explicit"
},
```

This [README](https://github.com/biomejs/biome-vscode/blob/2.x/README.md) indicates that the correct setting for fix on save is `quickfix.biome`, which is what worked for me, but the [web docs](https://biomejs.dev/reference/vscode/#fix-on-save) say to use `source.fixAll.biome`, which doesn't work for me.
