### ISSUE TITLE
🐛 Parser errors on for loop label named `out`

### ISSUE THREAD

**Issue by lgarron** [biomejs/biome#3410]
### Environment information

```block
Reproduces in the Playground. I have version 1.8.3 locally.
```

### What happened?

I was refactoring roughly the following real-world code. I can reformat it and add annotations but I need to preserve the actual structure:

```ts

export function detectFacelet(facelets: number[][], f: number[], perm: number[], ori: number[], divcol: number) {
  for (let i = 0; i < facelets.length; i++) {
    const n_ori = facelets[i].length;
    out: for (let j = 0; j < facelets.length + 1; j++) {
      if (j === facelets.length) {
        return -1;
      }
      if (facelets[j].length !== n_ori) {
        continue;
      }
      for (let o = 0; o < n_ori; o++) {
        let isMatch = true;
        for (let t = 0; t < n_ori; t++) {
          if (~~(facelets[j][t] / divcol) !== f[facelets[i][(t + o) % n_ori]]) {
            isMatch = false;
            break;
          }
        }
        if (isMatch) {
          perm[i] = j;
          ori[i] = o;
          break out;
        }
      }
    }
  }
  return 0;
}
```

[Playground link](https://biomejs.dev/playground/?code=CgBlAHgAcABvAHIAdAAgAGYAdQBuAGMAdABpAG8AbgAgAGQAZQB0AGUAYwB0AEYAYQBjAGUAbABlAHQAKABmAGEAYwBlAGwAZQB0AHMAOgAgAG4AdQBtAGIAZQByAFsAXQBbAF0ALAAgAGYAOgAgAG4AdQBtAGIAZQByAFsAXQAsACAAcABlAHIAbQA6ACAAbgB1AG0AYgBlAHIAWwBdACwAIABvAHIAaQA6ACAAbgB1AG0AYgBlAHIAWwBdACwAIABkAGkAdgBjAG8AbAA6ACAAbgB1AG0AYgBlAHIAKQAgAHsACgAgACAAZgBvAHIAIAAoAGwAZQB0ACAAaQAgAD0AIAAwADsAIABpACAAPAAgAGYAYQBjAGUAbABlAHQAcwAuAGwAZQBuAGcAdABoADsAIABpACsAKwApACAAewAKACAAIAAgACAAYwBvAG4AcwB0ACAAbgBfAG8AcgBpACAAPQAgAGYAYQBjAGUAbABlAHQAcwBbAGkAXQAuAGwAZQBuAGcAdABoADsACgAgACAAIAAgAG8AdQB0ADoAIABmAG8AcgAgACgAbABlAHQAIABqACAAPQAgADAAOwAgAGoAIAA8ACAAZgBhAGMAZQBsAGUAdABzAC4AbABlAG4AZwB0AGgAIAArACAAMQA7ACAAagArACsAKQAgAHsACgAgACAAIAAgACAAIABpAGYAIAAoAGoAIAA9AD0APQAgAGYAYQBjAGUAbABlAHQAcwAuAGwAZQBuAGcAdABoACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAALQAxADsACgAgACAAIAAgACAAIAB9AAoAIAAgACAAIAAgACAAaQBmACAAKABmAGEAYwBlAGwAZQB0AHMAWwBqAF0ALgBsAGUAbgBnAHQAaAAgACEAPQA9ACAAbgBfAG8AcgBpACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAGMAbwBuAHQAaQBuAHUAZQA7AAoAIAAgACAAIAAgACAAfQAKACAAIAAgACAAIAAgAGYAbwByACAAKABsAGUAdAAgAG8AIAA9ACAAMAA7ACAAbwAgADwAIABuAF8AbwByAGkAOwAgAG8AKwArACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAGwAZQB0ACAAaQBzAE0AYQB0AGMAaAAgAD0AIAB0AHIAdQBlADsACgAgACAAIAAgACAAIAAgACAAZgBvAHIAIAAoAGwAZQB0ACAAdAAgAD0AIAAwADsAIAB0ACAAPAAgAG4AXwBvAHIAaQA7ACAAdAArACsAKQAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAfgB%2BACgAZgBhAGMAZQBsAGUAdABzAFsAagBdAFsAdABdACAALwAgAGQAaQB2AGMAbwBsACkAIAAhAD0APQAgAGYAWwBmAGEAYwBlAGwAZQB0AHMAWwBpAF0AWwAoAHQAIAArACAAbwApACAAJQAgAG4AXwBvAHIAaQBdAF0AKQAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABpAHMATQBhAHQAYwBoACAAPQAgAGYAYQBsAHMAZQA7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAYgByAGUAYQBrADsACgAgACAAIAAgACAAIAAgACAAIAAgAH0ACgAgACAAIAAgACAAIAAgACAAfQAKACAAIAAgACAAIAAgACAAIABpAGYAIAAoAGkAcwBNAGEAdABjAGgAKQAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgAHAAZQByAG0AWwBpAF0AIAA9ACAAagA7AAoAIAAgACAAIAAgACAAIAAgACAAIABvAHIAaQBbAGkAXQAgAD0AIABvADsACgAgACAAIAAgACAAIAAgACAAIAAgAGIAcgBlAGEAawAgAG8AdQB0ADsACgAgACAAIAAgACAAIAAgACAAfQAKACAAIAAgACAAIAAgAH0ACgAgACAAIAAgAH0ACgAgACAAfQAKACAAIAByAGUAdAB1AHIAbgAgADAAOwAKAH0A)

1. The line with `break out;` shows "Expected a semicolon or an implicit semicolon after a statement, but found nonebiome(parse)". I cannot find anything in the help that lets me tell Biome to ignore the `break out;` line. 🫠
2. The `break out;` shows an error saying it's unreachable.
3. The `out:` label has an error saying it's unused.

### Expected result

As far as I can tell, all of the errors are false positives. I have no idea what's going on. 😭

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by lgarron** [comment]
Okay, I was able to reduce the repro to:

```ts
let count = 0;

out: for (let i = 0; i < 10; i++) {
  count++;
  if (Math.random() < 0.5) {
      break out;
    }
  }

console.log(count)
```

This runs perfectly fine in:

- `bun`
- `node`
- `deno`
- Chrome
- Firefox
- Safari

So it definitely seems to me that the issue is with Biome.

**Comment by lgarron** [comment]
Woah, it looks like this is happening because the label is called `out`. I can't reproduce it with another name.

**Comment by Sec-ant** [comment]
`out` somehow is not recognized as a label, if you change it to another name like `outer` the problem will be gone.

**Comment by Sec-ant** [comment]
`in` and `out` are defined as TypeScript modifiers in the grammar: https://github.com/biomejs/biome/blob/6b1e5189b5c3f67ee85190000b60b3917d7f7b8c/xtask/codegen/js.ungram#L659-L660

Using a modifier in the label position seems to choke the parser.
