### ISSUE TITLE
🐛 extends option not extending

### ISSUE THREAD

**Issue by Naoto-Ida** [biomejs/biome#343]
### Environment information

```block
│ │ ├─0ms INFO biome_lsp::session Loaded workspace settings: Configuration {
│ │ │     schema: None,
│ │ │     vcs: None,
│ │ │     files: Some(
│ │ │         FilesConfiguration {
│ │ │             max_size: None,
│ │ │             ignore: Some(
│ │ │                 StringSet(
│ │ │                     {
│ │ │                         "node_modules/",
│ │ │                         "__generated__/",
│ │ │                         "storybook-static/",
│ │ │                         ".next/",
│ │ │                         ".swc/",
│ │ │                         "persisted_queries.json",
│ │ │                         ".vscode/settings.json",
│ │ │                         ".yarn/",
│ │ │                         "coverage",
│ │ │                         "out/",
│ │ │                         "package.json",
│ │ │                         "public/",
│ │ │                     },
│ │ │                 ),
│ │ │             ),
│ │ │             ignore_unknown: None,
│ │ │         },
│ │ │     ),
│ │ │     formatter: None,
│ │ │     organize_imports: Some(
│ │ │         OrganizeImports {
│ │ │             enabled: Some(
│ │ │                 false,
│ │ │             ),
│ │ │             ignore: None,
│ │ │         },
│ │ │     ),
│ │ │     linter: Some(
│ │ │         LinterConfiguration {
│ │ │             enabled: Some(
│ │ │                 false,
│ │ │             ),
│ │ │             rules: Some(
│ │ │                 Rules {
│ │ │                     recommended: Some(
│ │ │                         true,
│ │ │                     ),
│ │ │                     all: None,
│ │ │                     a11y: None,
│ │ │                     complexity: None,
│ │ │                     correctness: None,
│ │ │                     nursery: None,
│ │ │                     performance: None,
│ │ │                     security: None,
│ │ │                     style: None,
│ │ │                     suspicious: None,
│ │ │                 },
│ │ │             ),
│ │ │             ignore: None,
│ │ │         },
│ │ │     ),
│ │ │     javascript: Some(
│ │ │         JavascriptConfiguration {
│ │ │             formatter: None,
│ │ │             parser: None,
│ │ │             globals: None,
│ │ │             organize_imports: None,
│ │ │         },
│ │ │     ),
│ │ │     json: None,
│ │ │     extends: Some(
│ │ │         StringSet(
│ │ │             {
│ │ │                 "./node_modules/@company/biome-config/formatter.json",
│ │ │             },
│ │ │         ),
│ │ │     ),
│ │ │ }
```

### What happened?

It seems that the `extends` option is not working [as documented](https://biomejs.dev/guides/big-projects/).

- We're using `@biomejs/biome@1.2.2`.
- We wanted to have the same `formatter` configuration across all projects using Biome.
- `extends` doesn't extend the `formatter` configuration from the specified JSON.

Repro:
1. Create/release a package outside of the project which contains biome configs OR create a local one.
2. In the root `biome.json`, use `extends: ['./node_modules/@company/biome-config/formatter.json'] or `['./my-other-biome-config.json']`.
3. The extension contains `{ "formatter": "indentStyle": "space" }`, whereas the project in question has no entry for `formatter`.
4. Running `yarn biome rage` reveals that the `formatter` configuration is now `None`.

### Expected result

Extending another configuration should not set the project one to `None`. This seems to happen with `linter`, as well as `javascript`.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Naoto-Ida** [comment]
Woops, sorry, I mean to say `./node_modules/@company/biome-config/formatter.json`.

**Comment by ematipico** [comment]
> In the root biome.json, use extends: ['./node_modules/@company/biome-config/formatter.json'] or ['./my-other-biome-config.json']`.

Did you make sure that those paths are reachable by biome? Package managers tend to different stuff. For example `pnpm` creates symbolic links. What about your yarn setup?

**Comment by jrson83** [comment]
> In my case, `extends` is completely ignored by the VSCode extension.

Same for me.

**Comment by ematipico** [comment]
Someone please create a reproduction repository. Without it, it's not possible to help you guys

**Comment by jrson83** [comment]
> Someone please create a reproduction repository. Without it, it's not possible to help you guys

Repo: https://github.com/jrson83/biome-extends-issue

1. `git clone https://github.com/jrson83/biome-extends-issue.git`
2. Run `pnpm install`

**Expected behaviour**

`./packages/module-a/biome.json` and `./packages/module-b/biome.json` extend `["../../biome.json"]`.

**module-a**

Running `pnpm format` in root should format `./src/index.ts` with an `indentSize` of `4`.

```json
{
  "$schema": "https://biomejs.dev/schemas/1.2.2/schema.json",
  "extends": ["../../biome.json"],
  "formatter": {
    "indentSize": 4
  }
}
```

**module-b**

Opening `./src/index.ts`, the linter should not throw any errors on both disabled rules:

```json
{
  "$schema": "https://biomejs.dev/schemas/1.2.2/schema.json",
  "extends": ["../../biome.json"],
  "linter": {
    "enabled": true,
    "rules": {
      "suspicious": {
        "noConsoleLog": "off",
        "noExplicitAny": "off"
      }
    }
  }
}
```

**Actual behaviour**

**module-a**

Running `pnpm format` in root formats `./src/index.ts` with an `indentSize` of `2`.

**module-b**

Opening `./src/index.ts`, the linter throws errors on both disabled rules.

![2023-09-28_17h53_53](https://github.com/biomejs/biome/assets/45284565/db4228ce-5455-4024-8fb9-ad74714654f0)

**Comment by Rainson12** [comment]
this is a deal breaker, we are experiencing the same issue, forcing same rules between frontend and backend folder

**Comment by ematipico** [comment]
Thank you @jrson83 

I see now what you mean. I believe I made some wrong assumptions on how `extends` works. It should be an easy fix, that will be shipped in the next minor.

**Comment by Naoto-Ida** [comment]
Thanks @ematipico for this fix, as well as @jrson83 for the better example than mine :)

Now we can format/lint all our projects consistently once its released 🎉

**Comment by ematipico** [comment]
Tomorrow/Sunday I'll make a nightly release so you can try it

**Comment by Naoto-Ida** [comment]
Just came back to report that this now seems to work the way that I expect `extends` to be as well. Thanks :)
