### ISSUE TITLE
🐛 JSX inside `.vue` files can not be formatted

### ISSUE THREAD

**Issue by ccforeverd** [biomejs/biome#3464]
### Environment information

```block
CLI:
  Version:                      1.8.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v16.20.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/8.19.4"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

1. `node16` and `Nuxt2` (`Vue2`) project
2. There is some `jsx` code inside `.vue` files
3. Vscode biome plugin show error `type assertion are a TypeScript only feature. Convert your file to a TypeScript file or remove the syntax.biome(parse)`

### Expected result

Support `vue-jsx` format

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ccforeverd** [comment]
![image](https://github.com/user-attachments/assets/6bde9628-0c0c-4aa3-adeb-45f984ea98ce)

**Comment by ccforeverd** [comment]
↑ screen shot in a `.vue` file

**Comment by ematipico** [comment]
@ccforeverd could you provide us with an example of source code? We will use that inside our test suite

**Comment by ccforeverd** [comment]
> @ccforeverd could you provide us with an example of source code? We will use that inside our test suite

https://github.com/ccforeverd/vue2-jsx-biome-example

**Comment by ccforeverd** [comment]
1. `pnpm i`
2. `pnpm dev`

**Comment by ccforeverd** [comment]
<img width="1298" alt="image" src="https://github.com/user-attachments/assets/150e958a-708c-49be-911f-99dccba5781e">

**Comment by ccforeverd** [comment]
<img width="1089" alt="image" src="https://github.com/user-attachments/assets/658a9d8e-4514-4cf7-8b9d-9f54e2a66974">

**Comment by ccforeverd** [comment]
And another bug for rsbuild :P

<https://github.com/web-infra-dev/rsbuild/issues/2964>
