### ISSUE TITLE
🐛 `--write` applies fixes to all rules ignoring `--only`

### ISSUE THREAD

**Issue by michalvankodev** [biomejs/biome#3470]
### Environment information

```block
CLI:
  Version:                      1.8.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "alacritty"
  JS_RUNTIME_VERSION:           "v18.20.3"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  JavaScript enabled:           true
  JSON enabled:                 true
  CSS enabled:                  false
  Recommended:                  true
  All:                          false
```

### What happened?

I've opted to start using biome on a project with multiple workspaces.
After initial setup with `npx @biome-js/biome init` and no changes to the config I received around 8000 errors. I wanted to know what rules trigger these errors and apply safe fixes gradually.

Trying to execute `npx biome lint --only=complexity/useArrowFunction` I was presented with only 12 occurrences with this error. So I wanted to apply fixes just to this rule with:

`npx biome lint --only=complexity/useArrowFunction --write`

biome has resolved all fixable errors instead of the 12 `complexity/useArrowFunction`.

Instead of the strategy of resolving errors gradually I had to skip rules in the output to get the list of all rules that have been reported. I've ended up with this command:

```
npx biome lint --skip=style/useImportType --skip=complexity/useArrowFunction --skip=complexity/noUselessFragments --skip=style/useNodejsImportProtocol --skip=style/useAsConstAssertion --skip=style/useSelfClosingElements --skip=suspicious/noArrayIndexKey --skip=correctness/useJsxKeyInIterable --skip=style/useNumberNamespace --skip=a11y/noBlankTarget --skip=a11y/useKeyWithClickEvents --skip=suspicious/noShadowRestrictedNames --skip=style/noUnusedTemplateLi
teral --skip=suspicious/noConsoleLog --skip=suspicious/noGlobalIsNan --skip=a11y --skip=style/noParameterAssign --skip=style/noUselessElse --skip=style/useTemplate --skip=complexity/useOptionalChain --skip=correctness/useExhaustiv
eDependencies --skip=correctness/noChildrenProp --skip=suspicious/noImplicitAnyLet --skip=complexity/useLiteralKeys --skip=style/noInferrableType
```

### Expected result

Executing `npx biome lint --only=complexity/useArrowFunction --write` should only fix the `useArrowFunction` rule 

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
This doesn't fix the issue, however note that you can also skip an entire group `--skip=correctness`. This could make easier your life in the meantime.
