### ISSUE TITLE
JSX doesn't format correctly 🐛

### ISSUE THREAD

**Issue by subhoghoshX** [biomejs/biome#3478]
### Environment information

```block
CLI:
  Version:                      1.8.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.15.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### What happened?

In a component like this:

```jsx
export default function App() {
  return (
    <main>
      <h1>Hello</h1> <p>Some paragraph</p> </main>
  );
}
```

Biome does nothing, no matter how I mess the up jsx code. It is formatting other parts of JavaScript just fine.

Note: I'm calling `vim.lsp.buf.format()` in neovim. If I do it through `biome format --write file.tsx` it seems to work fine.

### Expected result

A well formatted JSX, like:

```
export default function App() {
  return (
    <main>
      <h1>Hello</h1>
      <p>Some paragraph</p>
    </main>
  );
}
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
I believe there are some inconsistencies in how you set up your IDE and how it should call the Biome daemon (LSP). Unfortunately, I don't use Vim. I suggest reaching out to the VIM community or seeking help on our Discord. 

I close the issue, since this isn't a bug

**Comment by subhoghoshX** [comment]
I think I found the fix. I didn't create a `biome.json` file in the root of the project, because the doc says there's no need to create it if I accept the default settings.

Anyone facing this issue, create a `biome.json` (or `biome.jsonc`) file.
