### ISSUE TITLE
📎 Strip useless quotes for import attributes

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#3484]
### Description

Similarly to Prettier, we should respect `javascript.formatter.quoteProperties` for import attributes.

For example, if the option is set to `asNeeded`, then the quotes should be removed as shown in this example:

```diff
- import J from "file.json" with { "type": "json" }
+ import J from "file.json" with { type: "json" }
```

Note that when the option is set to `preserve`, we should also take `quoteStyle` into account.

**Comment by suxin2017** [comment]
Can I do this
