### ISSUE TITLE
📎 Implement `lint/noInvalidNewBuiltin` - `eslint/no-new-native-nonconstructor`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#352]
### Description

[no-new-native-nonconstructor](https://eslint.org/docs/latest/rules/no-new-native-nonconstructor/)

Want to contribute? Lets us know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

See the implementation of the rule `noNewSymbol`.

**Comment by lucasweng** [comment]
👋🏻 @Conaclos I'd like to try this one.
