### ISSUE TITLE
📎 Implement `lint/useRegexLiterals` - `eslint/prefer-regex-literals`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#353]
### Description

[prefer-regex-literals](https://eslint.org/docs/latest/rules/prefer-regex-literals/)

Want to contribute? Lets we know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by Yuiki** [comment]
I'm insterested in this issue. Can I work on this issue?

**Comment by unvalley** [comment]
@Yuiki Off course!
