### ISSUE TITLE
📎 Implement `lint/useShorthandFunctionType` - `typescript-eslint/prefer-function-type`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#354]
### Description

[prefer-function-type](https://typescript-eslint.io/rules/prefer-function-type/)

Want to contribute? Lets us know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by seitarof** [comment]
I tried to work on this, but it looks like it's already implemented in #670

**Comment by ematipico** [comment]
@seitarof 

The rule isn't finished yet, look at this comment: https://github.com/biomejs/biome/pull/670#pullrequestreview-1727244683

**Comment by seitarof** [comment]
@ematipico 
Oh, sorry. I missed this comment.
If no one is working on this issue, I would like to take on challenge.

**Comment by ematipico** [comment]
All yours
