### ISSUE TITLE
📎 Implement `lint/noApproximativeNumericConstant`, `clippy/approx_constant`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#355]
### Description

[approx_constant](https://rust-lang.github.io/rust-clippy/master/#/approx_constant/)

Want to contribute? Lets us know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

Other suggested name: `useNumericConstants`

**Comment by nikeee** [comment]
I'd like to try contribute this one

**Comment by ematipico** [comment]
It's all yours @nikeee

**Comment by nikeee** [comment]
While implementing this rule, how about an additional rule like `noComputedKnownConstant` that warns when the user does something like `Math.sqrt(2)` instead of `Math.SQRT2` or `Math.log10(Math.E)` instead of `Math.LOG10E`?
