### ISSUE TITLE
🐛 The Biome CLI package doesn't ship with prebuilt binaries for your platform yet. You can still use the CLI by cloning the biome/tools repo from GitHub, and follow the instructions there to build the CLI for your platform.

### ISSUE THREAD

**Issue by Indept-Studios** [biomejs/biome#3555]
### Environment information

```block
Doesn't work on my machine. I'm not able to install the Biome CLI
Edition	Windows 11 Home
Version	23H2
build	22631.3880

node: V20.16.0
npm: V10.8.1
```

### What happened?

i write a node.js project 
1. i run npm install --save-dev --save-exact @biomejs/biome
2. After that I created a biome.json with the { } content
3.  After running biome check --write i get the following error message:
`The Biome CLI package doesn't ship with prebuilt binaries for your platform yet. You can still use the CLI by cloning the biome/tools repo from GitHub, and follow the instructions there to build the CLI for your platform.`

### Expected result

biome formating my code

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
For some reason your package manager didn't install the optional dependencies required for your platform. Or, your platform isn't supported. In case the package manage is at fault, you can install it manually by using one of them https://www.npmjs.com/search?q=%40biomejs%2Fcli-

If your platform isn't supported, we can't fix it, and you'll have to compile biome yourself

**Comment by Indept-Studios** [comment]
@ematipico 
The following message appears when running the npm

npm i @biomejs/cli-win32-x64
npm error code EBADPLATFORM
npm error notsup Unsupported platform for @biomejs/cli-win32-x64@1.8.3: wanted {"os":"win32","cpu":"x64"} (current: {"os":"win32","cpu":"ia32"})
npm error notsup Valid os:   win32
npm error notsup Actual os:  win32
npm error notsup Valid cpu:  x64
npm error notsup Actual cpu: ia32
npm error A complete log of this run can be found in: C:\Users\XXX\AppData\Local\npm-cache_logs\2024-08-01T09_14_05_917Z-debug-0.log

If I have seen correctly it tells me that my Intel processor is not supported. But I have AMD

AMD Ryzen 7 3700X
