### ISSUE TITLE
📝 Leading Trivia JsDoc | TsDoc Trailing White Space at end of line removed

### ISSUE THREAD

**Issue by mjbergman92** [biomejs/biome#3567]
### Environment information

```bash
CLI:
  Version:                      1.8.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.20.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/1.22.22"

Biome Configuration:
  Error:                        Expected a property but instead found '}'.
  Status:                       Loaded with errors
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Formatter:
  Format with errors:           true
  Indent style:                 Tab
  Indent width:                 2
  Line ending:                  Lf
  Line width:                   80
  Attribute position:           Auto
  Ignore:                       []
  Include:                      []

JavaScript Formatter:
  Enabled:                      true
  JSX quote style:              Double
  Quote properties:             AsNeeded
  Trailing commas:              All
  Semicolons:                   Always
  Arrow parentheses:            AsNeeded
  Bracket spacing:              false
  Bracket same line:            false
  Quote style:                  Double
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           Auto

JSON Formatter:
  Enabled:                      true
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset

CSS Formatter:
  Enabled:                      false
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Quote style:                  Double

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
	"linter": {
		"enabled": true
	},
	"formatter": {
		"enabled": true,
		"formatWithErrors": true
	},
	"javascript": {
		"formatter": {
			"enabled": true,
			"semicolons": "always",
			"trailingCommas": "all",
			"arrowParentheses": "asNeeded"
		}
	}
}
```

### Playground link

https://biomejs.dev/playground/?code=aQBtAHAAbwByAHQAIAB7ACAAegAgAH0AIABmAHIAbwBtACAAIgB6AG8AZAAiADsACgAKAC8AKgAqAAoAIAAqACAAQwByAGUAYQB0AGUAcwAgAGEAIABzAGMAaABlAG0AYQAgAGYAbwByACAAcgBlAHAAcgBlAHMAZQBuAHQAaQBuAGcAIABwAGEAZwBpAG4AYQB0AGUAZAAgAHEAdQBlAHIAeQAgAHIAZQBzAHUAbAB0AHMALgAgACAACgAgACoACgAgACoAIABAAHQAZQBtAHAAbABhAHQAZQAgAFMAYwBoAGUAbQBhACAAVABoAGUAIABaAG8AZAAgAHMAYwBoAGUAbQBhACAAbwBmACAAdABoAGUAIABpAG4AZABpAHYAaQBkAHUAYQBsACAAZABhAHQAYQAgAGkAdABlAG0AcwAgAGkAbgAgAHQAaABlACAAYQByAHIAYQB5AC4AIAAgAAoAIAAqACAAQABwAGEAcgBhAG0AIAB7AFMAYwBoAGUAbQBhAH0AIABzACAALQAgAFQAaABlACAAcwBjAGgAZQBtAGEAIABvAGYAIAB0AGgAZQAgAGkAbgBkAGkAdgBpAGQAdQBhAGwAIABkAGEAdABhACAAaQB0AGUAbQBzAC4AIAAgAAoAIAAqACAAQAByAGUAdAB1AHIAbgBzACAAewB6AC4AWgBvAGQATwBiAGoAZQBjAHQAfQAgAEEAIABaAG8AZAAgAG8AYgBqAGUAYwB0ACAAcwBjAGgAZQBtAGEAIABmAG8AcgAgAHQAaABlACAAcABhAGcAaQBuAGEAdABlAGQAIAByAGUAcwB1AGwAdABzAC4AIAAgAAoAIAAqAC8ACgBlAHgAcABvAHIAdAAgAGMAbwBuAHMAdAAgAHAAYQBnAGkAbgBhAHQAZQBkAFEAdQBlAHIAeQBTAGMAaABlAG0AYQAgAD0AIAA8AFMAYwBoAGUAbQBhACAAZQB4AHQAZQBuAGQAcwAgAHoALgBaAG8AZABTAGMAaABlAG0AYQA%2BACgAcwA6ACAAUwBjAGgAZQBtAGEAKQAgAD0APgAKAAkAegAuAG8AYgBqAGUAYwB0ACgAewAKAAkACQAvACoAKgAKAAkACQAgACoAIABBAG4AIABhAHIAcgBhAHkAIABjAG8AbgB0AGEAaQBuAGkAbgBnACAAdABoAGUAIABkAGEAdABhACAAaQB0AGUAbQBzACAAZgBvAHIAIAB0AGgAZQAgAGMAdQByAHIAZQBuAHQAIABwAGEAZwBlAC4AIAAgAAoACQAJACAAKgAgAFQAaABlACAAcwBpAHoAZQAgAG8AZgAgAHQAaABpAHMAIABhAHIAcgBhAHkAIABpAHMAIABsAGkAbQBpAHQAZQBkACAAYgB5ACAAdABoAGUAIABgAHAAYQBnAGUAUwBpAHoAZQBgACAAcABhAHIAYQBtAGUAdABlAHIAIABpAG4AIAB0AGgAZQAgAHEAdQBlAHIAeQAuACAAIAAKAAkACQAgACoALwAKAAkACQBkAGEAdABhADoAIAB6AC4AYQByAHIAYQB5ACgAcwApACwACgAKAAkACQAvACoAKgAKAAkACQAgACoAIABNAGUAdABhAGQAYQB0AGEAIABhAGIAbwB1AHQAIAB0AGgAZQAgAHAAYQBnAGkAbgBhAHQAaQBvAG4AIABvAGYAIAB0AGgAZQAgAHIAZQBzAHUAbAB0AHMALgAgACAACgAJAAkAIAAqAC8ACgAJAAkAcABhAGcAaQBuAGEAdABpAG8AbgA6ACAAegAuAG8AYgBqAGUAYwB0ACgAewAKAAkACQAJAC8AKgAqAAoACQAJAAkAIAAqACAAVABoAGUAIAB0AG8AdABhAGwAIABuAHUAbQBiAGUAcgAgAG8AZgAgAGkAdABlAG0AcwAgAGEAYwByAG8AcwBzACAAYQBsAGwAIABwAGEAZwBlAHMALgAgACAACgAJAAkACQAgACoALwAKAAkACQAJAHQAbwB0AGEAbABDAG8AdQBuAHQAOgAgAHoALgBuAHUAbQBiAGUAcgAoACkALgBnAHQAZQAoADAAKQAsAAoACgAJAAkACQAvACoAKgAKAAkACQAJACAAKgAgAFQAaABlACAAYwB1AHIAcgBlAG4AdAAgAHAAYQBnAGUAIABuAHUAbQBiAGUAcgAgACgAcwB0AGEAcgB0AGkAbgBnACAAZgByAG8AbQAgADEAKQAuACAAIAAKAAkACQAJACAAKgAgAFQAaABpAHMAIABjAG8AcgByAGUAcwBwAG8AbgBkAHMAIAB0AG8AIAB0AGgAZQAgAGAAcABhAGcAZQBOAHUAbQBiAGUAcgBgACAAcABhAHIAYQBtAGUAdABlAHIAIAB1AHMAZQBkACAAaQBuACAAdABoAGUAIABxAHUAZQByAHkALgAgACAACgAJAAkACQAgACoALwAKAAkACQAJAHAAYQBnAGUATgB1AG0AYgBlAHIAOgAgAHoALgBuAHUAbQBiAGUAcgAoACkALgBwAG8AcwBpAHQAaQB2AGUAKAApACwACgAKAAkACQAJAC8AKgAqAAoACQAJAAkAIAAqACAAVABoAGUAIABuAHUAbQBiAGUAcgAgAG8AZgAgAGkAdABlAG0AcwAgAGkAbgBjAGwAdQBkAGUAZAAgAHAAZQByACAAcABhAGcAZQAuACAAIAAKAAkACQAJACAAKgAgAFQAaABpAHMAIABjAG8AcgByAGUAcwBwAG8AbgBkAHMAIAB0AG8AIAB0AGgAZQAgAGAAcABhAGcAZQBTAGkAegBlAGAAIABwAGEAcgBhAG0AZQB0AGUAcgAgAHUAcwBlAGQAIABpAG4AIAB0AGgAZQAgAHEAdQBlAHIAeQAuACAAIAAKAAkACQAJACAAKgAvAAoACQAJAAkAcABhAGcAZQBTAGkAegBlADoAIAB6AC4AbgB1AG0AYgBlAHIAKAApAC4AcABvAHMAaQB0AGkAdgBlACgAKQAsAAoACQAJAH0AKQAsAAoACQB9ACkAOwAKAA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by mjbergman92** [comment]
I simply would like a way to ignore all leading jsdoc across the entire codebase

**Comment by ematipico** [comment]
I opened the playground, read the title, and still I don't understand what the issue is.

Considering that the link shows an exact match with Prettier, I won't consider this a bug.

I would suggest opening a discussion and **clearly explain the proposed result**, because, unfortunately, I don't understand what you're proposing.

**Comment by mjbergman92** [comment]
I understand your confusion, and I will plan on doing so in hopes of figuring out how to make this possible for myself and others.

The object of my interest here is the two spaces that I have put at the end of each line of my documentation. These spaces serve as an indication to break the line syntactically when it comes to the interpretation of these documentation comments.

It is not immediately apparent unless I had actually suggested you look at the spaces at the end of each line and how they are remove by the formatter. Take a look again and you will see the spaces are remove from every line,  meaning if I go through and I do this, then I forget and I save automatically... I just keep deleting my work over and over of putting these spaces in.

I have decided in the mean time to put an entire additional line in between, but that adds to the length of the code, reduces readability of both the code and the documentation, and it just doesn't look right.

If you could direct me on how I can make a well informed start to a discussion, I would appreciate it so that the discussion has the best chance of survival.

Thank you so much for your feedback. I will make sure to be clearer as to what exactly I am interested in next time.

**Comment by ematipico** [comment]
You can use this link as a start 

https://github.com/biomejs/biome/discussions/new?category=ideas

There's no template, you're to suggest the idea as much as you want

**Comment by mjbergman92** [comment]
Well, thank you.

I guess if I'm bothering you, then disregard this; however, I really do hope to get your thought on what sort of details I should include in my original discussion post, kind of like a template, that will most likely lend to more traction, especially with the biomejs project growing in size (pretty rapidly too!).

I have to imagine that other people have struggled with this and are currently using workaround s... honestly, I wish that GitHub had more of a survey feature so that you could not only rate a repository, but the owner of the repository could offer a survey of their own format to users right in the application to possibly open up allowing community members to create surveys to collect desired feedback in a more controlled and reliable method.

**Comment by ematipico** [comment]
@mjbergman92 

When writing a proposal, you usually want to:
1. Highlight the problem.
2. Propose a solution to the problem.
3. Explain a solution (examples, design).
4. Goals and non-goals.

If you are good at explaining your problem and your solution, there's a higher chance that you get upvoted by other people who struggled with the same problem.
