### ISSUE TITLE
📎 noUnusedImports should remove empty imports

### ISSUE THREAD

**Issue by KurtGokhan** [biomejs/biome#3574]
### Rule name

noUnusedImports

### Playground link

https://codesandbox.io/p/devbox/biome-starter-cbs-rky6zq

### Expected result

The fix for `noUnusedImports` should remove imports like:

```
import {} from 'module';
```

### Context

A while ago, I noticed empty imports like above in in our codebase. I would expect Biome's `noUnusedImports` to remove this kind of imports, as the import is unused, and clearly not intended to be written that way.

The interesting thing is, the empty imports are also caused by auto-fix of `noUnusedImports`. An unused import like this is successfully removed:

```
import { A } from 'module';
```

But when there are one or more imports and all are unused, it generates an empty import.

```
import { A, B } from 'module';
// After fix it becomes
import {} from 'module';
```

This doesn't happen in CLI and only happens in IDE (VSCode). I noticed that when fixing this code, I can briefly see that code is converted to `import { A, } from 'module';` first. I think this happens because the fixer applies the fixes step-by-step as @Conaclos noted [here](https://github.com/biomejs/biome/discussions/3015#discussioncomment-10222273).

Note that `noUnusedImports` is known to cause some other related issues (#3383).

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by danielsht86** [comment]
Is there a workaround for this? Perhaps another rule that would remove the empty imports?

**Comment by Conaclos** [comment]
> Is there a workaround for this? Perhaps another rule that would remove the empty imports?

I think we can extend the behavior of this rule to remove such imports. What do you think?

**Comment by danielsht86** [comment]
> > Is there a workaround for this? Perhaps another rule that would remove the empty imports?
> 
> I think we can extend the behavior of this rule to remove such imports. What do you think?

That sounds great to me! That would be amazing

**Comment by h-a-n-a** [comment]
> I think we can extend the behavior of this rule to remove such imports. What do you think?

I would love to help ;-)

**Comment by Conaclos** [comment]
Hi @h-a-n-a I already started a wider fix for several issues related to `noUnusedImports`.

**Comment by h-a-n-a** [comment]
> Hi @h-a-n-a I already started a wider fix for several issues related to `noUnusedImports`.

@Conaclos I see! Just out of curious if https://github.com/biomejs/biome/pull/3761 is conflicting to your fix?
