### ISSUE TITLE
📎 Improve diagnostic of `noHeaderScope`

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#358]
### Description

Rule [here](https://biomejs.dev/linter/rules/no-header-scope)

We should add a new note that explains why `scope` on a div is not valid.

Small reference: https://www.a11yproject.com/checklist/#tables

Also, we could add another note that provide the two links we have in the documentation: https://biomejs.dev/linter/rules/no-header-scope#accessibility-guidelines

**Comment by unvalley** [comment]
I guess this is completed.
