### ISSUE TITLE
📎 Improve diagnostic of `noPositiveTabindex`

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#359]
### Description

Documentation: https://biomejs.dev/linter/rules/no-positive-tabindex

We have two options:
- provide a code fix (unsafe) to change the number to `0`
- add a note that explains what the user should do: use `0` or `-1`

**Comment by Conaclos** [comment]
> add a note that explains what the user should do: use 0 or -1

I don't think it makes sense to provide a code fix. This seems really unsafe to suggest using `0` instead of the current index.

**Comment by vasucp1207** [comment]
Since +ve indexes are not recommended to use, the value 0 includes an element in the natural tab order of the content, also this is an unsafe fix for the elements like modal and form errors.

**Comment by Conaclos** [comment]
> Since +ve indexes are not recommended to use, the value 0 includes an element in the natural tab order of the content, also this is an unsafe fix for the elements like modal and form errors.

Which difference between setting the tab index to `0` and just removing the tabIndex?

**Comment by ematipico** [comment]
> > Since +ve indexes are not recommended to use, the value 0 includes an element in the natural tab order of the content, also this is an unsafe fix for the elements like modal and form errors.
> 
> Which difference between setting the tab index to `0` and just removing the tabIndex?

With tabindex to 0, you make focusable  even elements that usually aren't focusable by default

**Comment by vasucp1207** [comment]
Or if anyone sets a +ve index to elements like `button` and `a`.

> > > Since +ve indexes are not recommended to use, the value 0 includes an element in the natural tab order of the content, also this is an unsafe fix for the elements like modal and form errors.
> > 
> > 
> > Which difference between setting the tab index to `0` and just removing the tabIndex?
> 
> With tabindex to 0, you make focusable even elements that usually aren't focusable by default. Keeping the tabindex is the safer choice we have.

Or if anyone sets +ve index on elements like `button`, but also at the same time we have to keep in mind that their interaction is handled automatically by the browser.
