### ISSUE TITLE
`--github` hides formatter errors in the output when running `biome ci`

### ISSUE THREAD

**Issue by tylerlaprade** [biomejs/biome#3605]
### Environment information

```bash
GitHub Actions runner
```

### Configuration

```JSON
{
    "formatter": {
		"formatWithErrors": true,
		"indentStyle": "space",
		"lineWidth": 120
	}
}
```

### Playground link

https://biomejs.dev/playground/?lintRules=all&enabledLinting=false&code=YwBvAG4AcwB0ACAAeAAgACAAPQAgADMAOwA%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by dyc3** [comment]
I believe this was fixed in #3594
