### ISSUE TITLE
🐛 CLI setting --staged checks unstaged changes

### ISSUE THREAD

**Issue by hrasekj** [biomejs/biome#3608]
### Environment information

```block
CLI:
  Version:                      1.8.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-color"
  JS_RUNTIME_VERSION:           "v20.12.2"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

Hello, 

i have pre-commit hook in git which looks like this:
```
./node_modules/.bin/biome check --staged --no-errors-on-unmatched
```

The issue is that Biome checks staged **files**, but i have unstaged changes, that may cause linter error.

For now i ended up with this workaround:
```shell
# get staged file names
stage_files=$(git diff --cached --name-only)

err_output=""
# check each staged file via biome check
# @see https://biomejs.dev/reference/cli/
for file in $stage_files; do
    file_content=$(git show ":$file")
    err_output="$err_output"`echo "$file_content" | ./node_modules/.bin/biome lint --no-errors-on-unmatched --stdin-file-path="$file" 2>&1 > /dev/null`
done

if [ -n "$err_output" ]; then
    echo "$err_output"
    exit 1
fi
```

### Expected result

Would be nice, that biome could have options like `--staged-files` and `--staged-changes`.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Can you provide a reproduction, or a least some steps to reproduce it locally?

**Comment by hrasekj** [comment]
Yes, 
- make some changes in file, that are ok with linter
- git stage that file
- make some changes in the same file, that you know will have lint error
- now call `biome lint --staged`
- You should obtain linter error on unstaged changes

**Comment by ematipico** [comment]
@hrasekj this is the expected behaviour, because the VCS integration isn't enabled by default. Please refer to this page https://biomejs.dev/guides/integrate-in-vcs/

**Comment by hrasekj** [comment]
@ematipico I've also tested this behavior with VCS enabled, the result was the same.

Ok, then i made gist for thar pre-commit hook. maybe it helps to someone with the same issue.
https://gist.github.com/hrasekj/ec6eb27491643306aed3e04efbd1fda6

**Comment by ematipico** [comment]
> @ematipico I've also tested this behavior with VCS enabled, the result was the same.

Sorry, that wasn't stated in your instructions. Please create a reproduction
