### ISSUE TITLE
Allowlist a domain for `lint/a11y/noBlankTarget`

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#3609]
### Discussed in https://github.com/biomejs/biome/discussions/3513

<div type='discussions-op-text'>

<sup>Originally posted by **GRA0007** July 24, 2024</sup>
We have a few sites that we manage, and currently any links between them we manually disable the `lint/a11y/noBlankTarget` rule so our analytics can track clicks between them. We're not worried about security given that all the sites are ours.

This results in about 100 or so links with a manual ignore comment. I'd like to propose a config option that allowlists certain domains to allow `target="_blank"` without `noreferrer` set.

Something like this would be great:

```json
{
  "noBlankTarget": {
    "options": {
      "allowDomains": ["ourdomain.com", "oursubdomain.hostingprovider.net"]
    }
  }
}
```

I believe this aligns with the ethos of this rule, as it's designed to prevent security issues with 3rd party sites, but managing multiple sites and linking between them is a common use-case.</div>

**Comment by Jayllyz** [comment]
Can i work on this?

**Comment by ematipico** [comment]
All yours @Jayllyz 

Feel free to ask any questions here
