### ISSUE TITLE
🐛 lint-staged + .d.ts file

### ISSUE THREAD

**Issue by dmythro** [biomejs/biome#3617]
### Environment information

```block
CLI:
  Version:                      1.8.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.14.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.7.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

Well, because of the issues I have `**/*.d.ts` files ignored by Biome:

```json
{
  "$schema": "https://biomejs.dev/schemas/1.8.3/schema.json",
  "files": {
    "include": ["**/*.js", "**/*.json", "src/**/*.css", "src/**/*.ts", "src/**/*.tsx"],
    "ignore": [".next", ".vscode", "migrations/**", "**/*.d.ts"]
  }
}
```

But still, I can't commit changes to those with `lint-staged`.

I was trying to ignore those files for lint-staged:

```json
{
  "lint-staged": {
    "*.{js,ts,!d.ts,tsx,css,md}": "npm run lint && npm run format"
  }
}
```

Seems like it didn't work as well, so here is a full log:

```
STARTED] Preparing lint-staged...
[COMPLETED] Preparing lint-staged...
[STARTED] Running tasks for staged files...
[STARTED] package.json — 1 file
[STARTED] *.{js,ts,!d.ts,tsx,css,md} — 1 file
[STARTED] npm run lint && npm run format
[FAILED] npm run lint && npm run format [FAILED]
[FAILED] npm run lint && npm run format [FAILED]
[COMPLETED] Running tasks for staged files...
[STARTED] Applying modifications from tasks...
[SKIPPED] Skipped because of errors from tasks.
[STARTED] Reverting to original state because of errors...
[COMPLETED] Reverting to original state because of errors...
[STARTED] Cleaning up temporary files...
[COMPLETED] Cleaning up temporary files...

✖ npm run lint && npm run format:
&& internalError/io  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × No such file or directory (os error 2)
  
  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
  

npm internalError/io  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × No such file or directory (os error 2)
  
  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
  

run internalError/io  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × No such file or directory (os error 2)
  
  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
  

format internalError/io  INTERNAL  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × No such file or directory (os error 2)
  
  ! This diagnostic was derived from an internal Biome error. Potential bug, please report it if necessary.
  

internalError/io ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  × No files were processed in the specified paths.
  


> ir-dam@2.0.0 lint
> biome lint && npm run format /Users/.../Repo/.../src/global.d.ts

Checked 0 files in 1536µs. No fixes applied.
husky - pre-commit script failed (code 1)
```

### Expected result

At least, ignored files give no error.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by dmythro** [comment]
UPD: Just tried to move ignore `.d.ts` files to `linter` section and it seems working without an error now (which is pretty weird tbh):

```json
{
  "linter": {
    "enabled": true,
    "ignore": ["**/*.d.ts"]
  }
}
```

P.S. You really need to support global `.d.ts` files. I have a lot of non-existing issues there, like not finding global types, TypeScript directives like `Partial`, unused types (but they're all made global in this case) etc.

<img width="805" alt="image" src="https://github.com/user-attachments/assets/35150529-a79b-42bb-9ace-9dd0bdcef07c">

<img width="657" alt="image" src="https://github.com/user-attachments/assets/b4c3927a-6804-4838-b6ac-4a4b84171510">

**Comment by Conaclos** [comment]
I recommend you to take a look at our [website documentation](https://biomejs.dev/recipes/git-hooks/#lint-staged). You should find answers there. I made a quick test and following the docs everything is fine for me.

> TypeScript directives like Partial

`Partial` should not be reported as undeclared. As you can see in [our playground](https://biomejs.dev/playground/?lintRules=all&files.main.d.ts=dAB5AHAAZQAgAFgAIAA9ACAAUABhAHIAdABpAGEAbAA8AG4AdQBtAGIAZQByAD4A), I don't see any issue. Are you sure you are using Biome 1.8.3 in your IDE and not a standalone binary?

> unused types (but they're all made global in this case)

This was fixed some days ago. It will be part of the next release (start of September). You can test it with our last nightly.

**Comment by dmythro** [comment]
> Are you sure you are using Biome 1.8.3 in your IDE and not a standalone binary?

Yes, pretty sure. I have official VS Code extension and this exact version (strictly) in my `package.json`.

**Comment by dmythro** [comment]
> I recommend taking a look at our [website documentation](https://biomejs.dev/recipes/git-hooks/#lint-staged). You should find answers there. I made a quick test and following the docs everything is fine for me.

Thanks for this. Also, I'll probably try switching to Lefthook, looks more efficient.

**Comment by ematipico** [comment]
> > Are you sure you are using Biome 1.8.3 in your IDE and not a standalone binary?
> 
> Yes, pretty sure. I have official VS Code extension and this exact version (strictly) in my `package.json`.

It's possible you have multiple daemons running. Open your task manager, check for `biome` process. Kill all of them and restart VSCode. It should fix your issue.

I aim to fix this issue in the next major of the VSCode extension

**Comment by dmythro** [comment]
Thanks for info, I'll check next time.

Well, if you're aware of this issue I'd prefer you close this ticket when the fix is released. Or provide a related one to subscribe to.

**Comment by veralex11** [comment]
I'm currently facing the same issue with husky+biome+lintstaged if there are no ts/tsx/json/jsonc files in the commit. Here's my config

`.lintstagerc`
```
{
    "*.{ts,tsx,json,jsonc}": "biome check --fix --log-level=error --colors=force --config-path=./biome.jsonc"
}
```
