### ISSUE TITLE
📎 Make install script that keeps biome.json $schema version in sync with package version

### ISSUE THREAD

**Issue by bitofbreeze** [biomejs/biome#3622]
### Description

biome.json uses a versioned JSON schema:

```
{
	"$schema": "https://biomejs.dev/schemas/1.8.3/schema.json",
    ...
}
```

It would be nice if whenever @biomejs/biome is part of the package manager install, [an install lifecycle script](https://docs.npmjs.com/cli/v10/using-npm/scripts#npm-install) is run to sync the version in the biome config if it exists.

**Comment by ematipico** [comment]
`biome migrate` is meant for that
