### ISSUE TITLE
biome check --stdin-file-path=file.ts doesn't return stdout

### ISSUE THREAD

**Issue by janos-r** [biomejs/biome#3633]
### Environment information

```block
CLI:
  Version:                      1.8.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v22.6.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### What happened?

1) Use a index.ts file with unsorted imports, and necessary formatting
2) run `biome format index.ts` -> see diff output
3) run `cat index.ts | biome format --stdin-file-path=file.ts` -> see the result of that diff in standard output
4) try the previous two steps with `check` instead of `format` -> The first output is as expected. But the pipe output makes no sense! It is one part original (unchanged) standard output, and second part the previous format diff.

### Expected result

To get just the standard output of both diffs applied.

I am using the `biome format --stdin-file-path` to format code in helix for a while, this works well. But I tried to add also import sorting today. And to have that working, I would expect to just change the word `format` to `check` and get the same standardized output when providing the --stdin-file-path - the official docs say the same.
https://biomejs.dev/reference/cli/#biome-check -> the `--stdin-file-path` looks the same in both check and format, but only in format you get an output that is usable for the LSP.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
> The first output is as expected. But the pipe output makes no sense! It is one part original (unchanged) standard output, and second part the previous format diff.

I believe you're talking about something in particular, but without a visual aid we can't understand what you're referring to 

> To get just the standard output of both diffs applied.

To **apply** the diffs, you must pass **--fix**

**Comment by janos-r** [comment]
If you run `cat index.ts | biome check --stdin-file-path=file.ts` in the terminal, in the stdout you SHOULD get only text that shows how the result would look like. This is for LSP purposes. That is also how the `format` command works.
But instead you get a diff.

This is what you should get (and what format correctly gives)
![image](https://github.com/user-attachments/assets/38c79195-5ebb-46cd-a8bd-cb958607f588)


But instead you get this:
![image](https://github.com/user-attachments/assets/493895c8-9612-4962-aeac-76da9a42f672)

**Comment by ematipico** [comment]
Thank you, this screenshot makes things way more clear
