### ISSUE TITLE
📎 Improve diagnostic of `useValidAriaProps`

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#364]
### Description

Rule https://biomejs.dev/linter/rules/use-valid-aria-props

We have few options here, we can implement all of them or some of them:
- provide a note like "Did you mean ... ?"
- maybe add a **unsafe** code action that removes it

**Comment by vasucp1207** [comment]
Can we put a list of all valid `aria` props on the website and link to that in diagnostic?

**Comment by ematipico** [comment]
How long is the list of aria properties? I think we apply your suggestion. The list of aria properties rarely changes, so I think we can have a hardcoded list in the rule's documentation page.

**Comment by vasucp1207** [comment]
[Here](https://github.com/biomejs/biome/blob/a65f1ab2bd268d70c8feac96ca6b82015b766f5a/crates/biome_aria_metadata/build.rs#L12) 48 in total
