### ISSUE TITLE
Ignored files are not ignored when using --staged or explicitly specified in CLI

### ISSUE THREAD

**Issue by Florian-crg** [biomejs/biome#3659]
### Environment information

```block
CLI:
  Version:                      1.8.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

Files specified in the Biome configuration's "ignore" list are still being linted when:
1. Using the `--staged` flag
2. Explicitly specifying the file in the CLI command

This behavior occurs even when VCS is enabled in the Biome configuration. The ignored files are not present in the `.gitignore` file.

Steps to reproduce:
1. Set up a project with Biome.js
2. Create a biome.json configuration file with the following "ignore" setting:
   ```json
   {
       "files": {
           "ignore": [
               "file.ts",
               "other_file.js"
           ]
       }
   }
   ```
3. Create the files specified in the "ignore" list (file.ts and other_file.js)
4. Run `biome check --staged`
5. Run `biome check file.ts`
6. Observe that the ignored files are still being linted

### Expected result

Files specified in the "ignore" list should be ignored in all scenarios, including:
1. When using the --staged flag
2. When explicitly specifying the file in the CLI command

The current behavior makes it difficult to use Biome with external tools like lefthook, Husky or in custom scripts. Ignoring specific file is a critical feature when using GraphQL or other tool that will create auto-generated files.

Possible solution:
1. Ensure that ignored files are consistently skipped in all scenarios, including when using --staged or specifying files directly in the CLI.
2. Consider implementing an `--include-ignored` flag for cases where users explicitly want to lint ignored files.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

EDIT: See comment below: https://github.com/biomejs/biome/issues/3659#issuecomment-2296122930

**Comment by dyc3** [comment]
I'm not too sure about evaluating ignores when files are explicitly provided via cli args. As a user, I would expect all files provided via cli args to be processed, regardless of ignores because I _explicitly_ pointed biome to the file.

Doing this for `--staged` definitely makes sense though.

**Comment by Florian-crg** [comment]
Thank you for your prompt attention to this issue. I appreciate your perspective on how CLI arguments might be interpreted.

While I understand the logic behind processing explicitly provided files, this approach can lead to unexpected behavior, especially when integrating Biome with other tools or scripts. Consistent handling of ignored files across all scenarios would provide several benefits:

**Consistency:** It's easier to reason about and maintain a system where ignore rules are always respected.
**Unintended consequences:** Tools like lefthook, husky, custom scripts, or other use case often rely on consistent behavior, including respects for ignores.

I agree that addressing this for `--staged` is crucial. Considering an optional `--include-ignored` flag for cases where users want to override ignore rules is the only option giving consistency by maintaining expected behavior without unintended consequences while offering flexibility when needed.

Very interested to also have others opinion, @ematipico what do you think of it?

**Comment by ematipico** [comment]
Based on your reproduction, that's the expected behaviour because ignoring files from VCS is an opt-in operation. However, from the rage summary, I can see that's enabled. Can you please update your instructions?

**Comment by Florian-crg** [comment]
Update: I've identified the root cause while reproducing the issue in a monorepo setup like ours.

1. The issue occurs when `biome.json` is at the root level, but the command is run in a subfolder where the package is installed.
2. File paths in `biome.json` are interpreted relative to the command execution location, not the JSON file location.
3. The ignore functionality itself works as expected, correctly ignoring specified files.

The main problem:
Relative paths in `biome.json` don't work as expected when the config is not in the same directory as the command execution. This is particularly problematic for monorepo architectures.

Reproduction:
I've created a minimal reproduction in a CodeSandbox: https://codesandbox.io/p/devbox/adoring-wilbur-dxckdw?file=%2Fbiome.json%3A19%2C3

To reproduce:
1. Open the CodeSandbox
2. Run `npx biome check --staged` in the terminal

Expected behavior:
Biome should interpret paths in `biome.json` relative to the config file's location, ensuring consistent behavior across monorepo subfolders.

This issue mainly impacts monorepo setups and needs addressing for better usability in complex project structures.

**Comment by ematipico** [comment]
> Relative paths in biome.json don't work as expected when the config is not in the same directory as the command execution. 

That's **the expected** way, we document this: https://biomejs.dev/guides/configure-biome/#ignore-files

> Biome resolves the globs relatively from the working directory. The working directory is the directory where you usually run a CLI command. This means that you have to place **particular attention** when the configuration file is placed in a different directory from where you execute your command. In the case of an editor (LSP) the working directory is the root directory of your project.
