### ISSUE TITLE
🐛 assertion failed: p.state().name_map.is_empty()

### ISSUE THREAD

**Issue by ityuany** [biomejs/biome#3740]
### Environment information

```block
mac m3
```

### What happened?

1. js code as 
```js
(self.webpackChunkmetric = self.webpackChunkmetric || []).push([
  ["8227"],
  {
    3684: function (t, e, n) {
      function E({
        root: t,
        data: e,
        x: n,
        y: r,
        render: i,
        event: o,
        single: a,
        position: u = "right-bottom",
        enterable: s = !1,
        css: l,
        mount: f,
        bounding: d,
        offset: h,
      }) {
        let y = w(t, f),
          {
            tooltipElement: x = (function (
              t,
              e,
              n,
              r,
              i,
              o,
              a,
              u = {},
              s = [10, 10]
            ) {
              let l = new p.u({});
              return t.appendChild(l.HTMLTooltipElement), l;
            })(y, n, r, u, s, m, b, l, h),
          } = g;
      }
    },
  },
]);

```

2.  rust code  as 
```rust
let parse_result = parse(
        source_code,
        JsFileSource::js_module(),
        JsParserOptions::default(),
    );
```

### Expected result

expected: 
   no error
   
   
actual : 

assertion failed: p.state().name_map.is_empty()
stack backtrace:

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
I'm not sure what kind of error you're filing. But if you there's a parsing error for the JS code you pasted, it works on the [playground](https://biomejs.dev/playground/?code=KABzAGUAbABmAC4AdwBlAGIAcABhAGMAawBDAGgAdQBuAGsAbQBlAHQAcgBpAGMAIAA9ACAAcwBlAGwAZgAuAHcAZQBiAHAAYQBjAGsAQwBoAHUAbgBrAG0AZQB0AHIAaQBjACAAfAB8ACAAWwBdACkALgBwAHUAcwBoACgAWwAKACAAIABbACIAOAAyADIANwAiAF0ALAAKACAAIAB7AAoAIAAgACAAIAAzADYAOAA0ADoAIABmAHUAbgBjAHQAaQBvAG4AIAAoAHQALAAgAGUALAAgAG4AKQAgAHsACgAgACAAIAAgACAAIABmAHUAbgBjAHQAaQBvAG4AIABFACgAewAKACAAIAAgACAAIAAgACAAIAByAG8AbwB0ADoAIAB0ACwACgAgACAAIAAgACAAIAAgACAAZABhAHQAYQA6ACAAZQAsAAoAIAAgACAAIAAgACAAIAAgAHgAOgAgAG4ALAAKACAAIAAgACAAIAAgACAAIAB5ADoAIAByACwACgAgACAAIAAgACAAIAAgACAAcgBlAG4AZABlAHIAOgAgAGkALAAKACAAIAAgACAAIAAgACAAIABlAHYAZQBuAHQAOgAgAG8ALAAKACAAIAAgACAAIAAgACAAIABzAGkAbgBnAGwAZQA6ACAAYQAsAAoAIAAgACAAIAAgACAAIAAgAHAAbwBzAGkAdABpAG8AbgA6ACAAdQAgAD0AIAAiAHIAaQBnAGgAdAAtAGIAbwB0AHQAbwBtACIALAAKACAAIAAgACAAIAAgACAAIABlAG4AdABlAHIAYQBiAGwAZQA6ACAAcwAgAD0AIAAhADEALAAKACAAIAAgACAAIAAgACAAIABjAHMAcwA6ACAAbAAsAAoAIAAgACAAIAAgACAAIAAgAG0AbwB1AG4AdAA6ACAAZgAsAAoAIAAgACAAIAAgACAAIAAgAGIAbwB1AG4AZABpAG4AZwA6ACAAZAAsAAoAIAAgACAAIAAgACAAIAAgAG8AZgBmAHMAZQB0ADoAIABoACwACgAgACAAIAAgACAAIAB9ACkAIAB7AAoAIAAgACAAIAAgACAAIAAgAGwAZQB0ACAAeQAgAD0AIAB3ACgAdAAsACAAZgApACwACgAgACAAIAAgACAAIAAgACAAIAAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB0AG8AbwBsAHQAaQBwAEUAbABlAG0AZQBuAHQAOgAgAHgAIAA9ACAAKABmAHUAbgBjAHQAaQBvAG4AIAAoAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHQALAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABlACwACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAbgAsAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHIALAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABpACwACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAbwAsAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGEALAAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAB1ACAAPQAgAHsAfQAsAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHMAIAA9ACAAWwAxADAALAAgADEAMABdAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAKQAgAHsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAbABlAHQAIABsACAAPQAgAG4AZQB3ACAAcAAuAHUAKAB7AH0AKQA7AAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgAHIAZQB0AHUAcgBuACAAdAAuAGEAcABwAGUAbgBkAEMAaABpAGwAZAAoAGwALgBIAFQATQBMAFQAbwBvAGwAdABpAHAARQBsAGUAbQBlAG4AdAApACwAIABsADsACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB9ACkAKAB5ACwAIABuACwAIAByACwAIAB1ACwAIABzACwAIABtACwAIABiACwAIABsACwAIABoACkALAAKACAAIAAgACAAIAAgACAAIAAgACAAfQAgAD0AIABnADsACgAgACAAIAAgACAAIAB9AAoAIAAgACAAIAB9ACwACgAgACAAfQAsAAoAXQApADsACgA%3D)

**Comment by ityuany** [comment]
Now you can just run ， He'll report an error.

```rust
#[test]
pub fn quick_test() {
    let code = r#"
(self.webpackChunkmetric = self.webpackChunkmetric || []).push([
  ["8227"],
  {
    3684: function (t, e, n) {
      function E({
        root: t,
        data: e,
        x: n,
        y: r,
        render: i,
        event: o,
        single: a,
        position: u = "right-bottom",
        enterable: s = !1,
        css: l,
        mount: f,
        bounding: d,
        offset: h,
      }) {
        let y = w(t, f),
          {
            tooltipElement: x = (function (
              t,
              e,
              n,
              r,
              i,
              o,
              a,
              u = {},
              s = [10, 10]
            ) {
              let l = new p.u({});
              return t.appendChild(l.HTMLTooltipElement), l;
            })(y, n, r, u, s, m, b, l, h),
          } = g;
      }
    },
  },
]);

    "#;

    let root = parse(
        code,
        JsFileSource::ts(),
        JsParserOptions::default().with_parse_class_parameter_decorators(),
    );
}

```


```toml
[dependencies]
biome_js_parser = { git = "https://github.com/biomejs/biome", tag = "cli/v1.8.3"}
biome_js_syntax = { git = "https://github.com/biomejs/biome", tag = "cli/v1.8.3" }
biome_js_semantic = { git = "https://github.com/biomejs/biome", tag = "cli/v1.8.3" }
biome_rowan = { git = "https://github.com/biomejs/biome", tag = "cli/v1.8.3" } 
```

**Comment by ityuany** [comment]
biome_js_parser::parse should return exceptions that can be caught by the user, so that at least there's no panic.

**Comment by Conaclos** [comment]
Minimal code to reproduce the panic in debug mode:

```js
let {
    p = function () { let l; },
} = o;
```
