### ISSUE TITLE
📝 Output is different based on initial formatting of input

### ISSUE THREAD

**Issue by parnavh** [biomejs/biome#3766]
### Environment information

```bash
CLI:
  Version:                      1.8.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "foot"
  JS_RUNTIME_VERSION:           "v20.15.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/9.5.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Formatter:
  Format with errors:           false
  Indent style:                 Space
  Indent width:                 2
  Line ending:                  Lf
  Line width:                   80
  Attribute position:           Auto
  Ignore:                       []
  Include:                      []

JavaScript Formatter:
  Enabled:                      true
  JSX quote style:              Double
  Quote properties:             AsNeeded
  Trailing commas:              All
  Semicolons:                   Always
  Arrow parentheses:            Always
  Bracket spacing:              true
  Bracket same line:            false
  Quote style:                  Double
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           Auto

JSON Formatter:
  Enabled:                      true
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset

CSS Formatter:
  Enabled:                      false
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Quote style:                  Double

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
  "$schema": "https://biomejs.dev/schemas/1.8.3/schema.json",
  "organizeImports": {
    "enabled": true
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true
    }
  },
  "formatter": {
    "indentStyle": "space"
  }
}
```

### Playground link

[original][og-url]
[refined][refined-url] thanks @suxin2017!

[og-url]: https://biomejs.dev/playground/?lineWidth=1000&indentStyle=space&quoteProperties=preserve&code=ZgB1AG4AYwB0AGkAbwBuACAAZwBlAHQAVABlAHgAdAAoAAoAIAAgAGQAbwBuAGUAQwBvAHUAbgB0ADoAIABuAHUAbQBiAGUAcgAsAAoAIAAgAHQAbwB0AGEAbABDAG8AdQBuAHQAOgAgAG4AdQBtAGIAZQByACwACgAgACAAZABvAG4AZQBTAGUAYwBzADoAIABuAHUAbQBiAGUAcgAsAAoAIAAgAHQAbwB0AGEAbABTAGUAYwBzADoAIABuAHUAbQBiAGUAcgAsAAoAKQA6ACAAcwB0AHIAaQBuAGcAIAB7AAoAIAAgAGkAZgAgACgAZABvAG4AZQBDAG8AdQBuAHQAIAA9AD0APQAgADAAKQAgAHsACgAgACAAIAAgAHIAZQB0AHUAcgBuACAAYABMAGUAYwB0AHUAcgBlAHMAOgAgACQAewB0AG8AdABhAGwAQwBvAHUAbgB0AH0AIAB8ACAATQBpAG4AcwA6ACAAJAB7ACgAdABvAHQAYQBsAFMAZQBjAHMAIAAvACAANgAwACkALgB0AG8ARgBpAHgAZQBkACgACgAgACAAIAAgACAAIAAyAAoAIAAgACAAIAApAH0AIAB8ACAASABvAHUAcgBzADoAIAAkAHsAKAB0AG8AdABhAGwAUwBlAGMAcwAgAC8AIAAzADYAMAAwACkALgB0AG8ARgBpAHgAZQBkACgACgAgACAAIAAgACAAIAAyAAoAIAAgACAAIAApAH0AYAA7AAoAIAAgAH0ACgAKACAAIAByAGUAdAB1AHIAbgAgAGAATABlAGMAdAB1AHIAZQBzADoAIAAkAHsAZABvAG4AZQBDAG8AdQBuAHQAfQAvACQAewB0AG8AdABhAGwAQwBvAHUAbgB0AH0AIAB8ACAATQBpAG4AcwA6ACAAJAB7ACgAZABvAG4AZQBTAGUAYwBzACAALwAgADYAMAApAC4AdABvAEYAaQB4AGUAZAAoAAoAIAAgACAAIAAyACwACgAgACAAKQB9AC8AJAB7ACgAdABvAHQAYQBsAFMAZQBjAHMAIAAvACAANgAwACkALgB0AG8ARgBpAHgAZQBkACgACgAgACAAIAAgADIALAAKACAAIAApAH0AfAAgAEgAbwB1AHIAcwA6ACAAJAB7ACgAZABvAG4AZQBTAGUAYwBzACAALwAgADMANgAwADAAKQAuAHQAbwBGAGkAeABlAGQAKAAKACAAIAAgACAAMgAsAAoAIAAgACkAfQAvACQAewAoAHQAbwB0AGEAbABTAGUAYwBzACAALwAgADMANgAwADAAKQAuAHQAbwBGAGkAeABlAGQAKAAKACAAIAAgACAAMgAsAAoAIAAgACkAfQBgADsACgB9AAoACgBmAHUAbgBjAHQAaQBvAG4AIABnAGUAdABUAGUAeAB0ADIAKAAKACAAIABkAG8AbgBlAEMAbwB1AG4AdAA6ACAAbgB1AG0AYgBlAHIALAAKACAAIAB0AG8AdABhAGwAQwBvAHUAbgB0ADoAIABuAHUAbQBiAGUAcgAsAAoAIAAgAGQAbwBuAGUAUwBlAGMAcwA6ACAAbgB1AG0AYgBlAHIALAAKACAAIAB0AG8AdABhAGwAUwBlAGMAcwA6ACAAbgB1AG0AYgBlAHIALAAKACkAOgAgAHMAdAByAGkAbgBnACAAewAKACAAIABpAGYAIAAoAGQAbwBuAGUAQwBvAHUAbgB0ACAAPQA9AD0AIAAwACkAIAB7AAoAIAAgACAAIAByAGUAdAB1AHIAbgAgAGAATABlAGMAdAB1AHIAZQBzADoAIAAkAHsAdABvAHQAYQBsAEMAbwB1AG4AdAB9ACAAfAAgAE0AaQBuAHMAOgAgACQAewAoAHQAbwB0AGEAbABTAGUAYwBzACAALwAgADYAMAApAC4AdABvAEYAaQB4AGUAZAAoADIAKQB9ACAAfAAgAEgAbwB1AHIAcwA6ACAAJAB7ACgAdABvAHQAYQBsAFMAZQBjAHMAIAAvACAAMwA2ADAAMAApAC4AdABvAEYAaQB4AGUAZAAoADIAKQB9AGAAOwAKACAAIAB9AAoACgAgACAAcgBlAHQAdQByAG4AIABgAEwAZQBjAHQAdQByAGUAcwA6ACAAJAB7AGQAbwBuAGUAQwBvAHUAbgB0AH0ALwAkAHsAdABvAHQAYQBsAEMAbwB1AG4AdAB9ACAAfAAgAE0AaQBuAHMAOgAgACQAewAoAGQAbwBuAGUAUwBlAGMAcwAgAC8AIAA2ADAAKQAuAHQAbwBGAGkAeABlAGQAKAAyACkAfQAvACQAewAoAHQAbwB0AGEAbABTAGUAYwBzACAALwAgADYAMAApAC4AdABvAEYAaQB4AGUAZAAoADIAKQB9AHwAIABIAG8AdQByAHMAOgAgACQAewAoAGQAbwBuAGUAUwBlAGMAcwAgAC8AIAAzADYAMAAwACkALgB0AG8ARgBpAHgAZQBkACgAMgApAH0ALwAkAHsAKAB0AG8AdABhAGwAUwBlAGMAcwAgAC8AIAAzADYAMAAwACkALgB0AG8ARgBpAHgAZQBkACgAMgApAH0AYAA7AAoAfQA%3D

[refined-url]: https://biomejs.dev/playground/?indentStyle=space&quoteProperties=preserve&code=YwBvAG4AcwB0ACAAYQAgAD0AIABgAEwAZQBjAHQAdQByAGUAcwA6ACAAJAB7AGQAbwBuAGUAQwBvAHUAbgB0AH0ALwAkAHsAdABvAHQAYQBsAEMAbwB1AG4AdAB9ACAAfAAgAE0AaQBuAHMAOgAgACQAewAoAGQAbwBuAGUAUwBlAGMAcwAgAC8AIAA2ADAAKQAuAHQAbwBGAGkAeABlAGQAKAAKACAAIAAgACAAMgAsAAoAIAAgACkAfQAvACQAewAoAHQAbwB0AGEAbABTAGUAYwBzACAALwAgADYAMAApAC4AdABvAEYAaQB4AGUAZAAoAAoAIAAgACAAIAAyACwACgAgACAAKQB9AHwAIABIAG8AdQByAHMAOgAgACQAewAoAGQAbwBuAGUAUwBlAGMAcwAgAC8AIAAzADYAMAAwACkALgB0AG8ARgBpAHgAZQBkACgACgAgACAAIAAgADIALAAKACAAIAApAH0ALwAkAHsAKAB0AG8AdABhAGwAUwBlAGMAcwAgAC8AIAAzADYAMAAwACkALgB0AG8ARgBpAHgAZQBkACgACgAgACAAIAAgADIALAAKACAAIAApAH0AYAA7AAoACgBjAG8AbgBzAHQAIABiACAAPQAgAGAATABlAGMAdAB1AHIAZQBzADoAIAAkAHsAZABvAG4AZQBDAG8AdQBuAHQAfQAvACQAewB0AG8AdABhAGwAQwBvAHUAbgB0AH0AIAB8ACAATQBpAG4AcwA6ACAAJAB7ACgAZABvAG4AZQBTAGUAYwBzACAALwAgADYAMAApAC4AdABvAEYAaQB4AGUAZAAoADIAKQB9AC8AJAB7ACgAdABvAHQAYQBsAFMAZQBjAHMAIAAvACAANgAwACkALgB0AG8ARgBpAHgAZQBkACgAMgApAH0AfAAgAEgAbwB1AHIAcwA6ACAAJAB7ACgAZABvAG4AZQBTAGUAYwBzACAALwAgADMANgAwADAAKQAuAHQAbwBGAGkAeABlAGQAKAAyACkAfQAvACQAewAoAHQAbwB0AGEAbABTAGUAYwBzACAALwAgADMANgAwADAAKQAuAHQAbwBGAGkAeABlAGQAKAAyACkAfQBgADsACgAgAA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by parnavh** [comment]
As seen in the playground, prettier gives consistent results with both of the functions with different initial formatting, but biome has 2 different outputs. Shouldn't this be the same? since the output should always be consistent after formatting.

Also while locally testing, in some cases if I formatted the code more than once repeatedly, the output would change. i.e the line in the playground:

```ts
return `Lectures: ${doneCount}/${totalCount} | Mins: ${(
		doneSecs / 60
	).toFixed(2)}/${(totalSecs / 60).toFixed(2)}| Hours: ${(
		doneSecs / 3600
	).toFixed(2)}/${(totalSecs / 3600).toFixed(2)}`;
```

would become

```ts
return `Lectures: ${doneCount}/${totalCount} | Mins: ${(
		doneSecs / 60
	).toFixed(2)}/${(totalSecs / 60).toFixed(2)}| Hours: ${(doneSecs / 3600).toFixed(2)}/${(totalSecs / 3600).toFixed(2)}`;
```

and then 

```ts
return `Lectures: ${doneCount}/${totalCount} | Mins: ${(doneSecs / 60).toFixed(2)}/${(totalSecs / 60).toFixed(2)}| Hours: ${(doneSecs / 3600).toFixed(2)}/${(totalSecs / 3600).toFixed(2)}`;
```

**Comment by suxin2017** [comment]
This problem is caused by the line width configuration. When the two sides are configured to 120, the behive of the two sides is consistent, and when the two sides are configured to 1000, they start to differ. biome Max line width = 320 will use the default 80 when it is greater than 320 and all the configurations will use the default configuration (for example, semicolons always configuration will also be broken), so the difference is caused

The following link sets line-wdth=322, which breaks the always configuration for semicolons
https://biomejs.dev/playground/?lineWidth=322&indentStyle=space&quoteProperties=preserve&code=YwBvAG4AcwB0ACAAYQA9ACAAIABgAEwAZQBjAHQAdQByAGUAcwA6ACAAJAB7AGQAbwBuAGUAQwBvAHUAbgB0AH0ALwAkAHsAdABvAHQAYQBsAEMAbwB1AG4AdAB9ACAAfAAgAE0AaQBuAHMAOgAgACQAewAoAGQAbwBuAGUAUwBlAGMAcwAgAC8AIAA2ADAAKQAuAHQAbwBGAGkAeABlAGQAKAAKACAAIAAgACAAMgAsAAoAIAAgACkAfQAvACQAewAoAHQAbwB0AGEAbABTAGUAYwBzACAALwAgADYAMAApAC4AdABvAEYAaQB4AGUAZAAoAAoAIAAgACAAIAAyACwACgAgACAAKQB9AHwAIABIAG8AdQByAHMAOgAgACQAewAoAGQAbwBuAGUAUwBlAGMAcwAgAC8AIAAzADYAMAAwACkALgB0AG8ARgBpAHgAZQBkACgACgAgACAAIAAgADIALAAKACAAIAApAH0ALwAkAHsAKAB0AG8AdABhAGwAUwBlAGMAcwAgAC8AIAAzADYAMAAwACkALgB0AG8ARgBpAHgAZQBkACgACgAgACAAIAAgADIALAAKACAAIAApAH0AYAA7AAoACgBjAG8AbgBzAHQAIABiACAAPQAgAGAATABlAGMAdAB1AHIAZQBzADoAIAAkAHsAZABvAG4AZQBDAG8AdQBuAHQAfQAvACQAewB0AG8AdABhAGwAQwBvAHUAbgB0AH0AIAB8ACAATQBpAG4AcwA6ACAAJAB7ACgAZABvAG4AZQBTAGUAYwBzACAALwAgADYAMAApAC4AdABvAEYAaQB4AGUAZAAoADIAKQB9AC8AJAB7ACgAdABvAHQAYQBsAFMAZQBjAHMAIAAvACAANgAwACkALgB0AG8ARgBpAHgAZQBkACgAMgApAH0AfAAgAEgAbwB1AHIAcwA6ACAAJAB7ACgAZABvAG4AZQBTAGUAYwBzACAALwAgADMANgAwADAAKQAuAHQAbwBGAGkAeABlAGQAKAAyACkAfQAvACQAewAoAHQAbwB0AGEAbABTAGUAYwBzACAALwAgADMANgAwADAAKQAuAHQAbwBGAGkAeABlAGQAKAAyACkAfQBgADsACgAgAA%3D%3D

**Comment by parnavh** [comment]
Hi!

The different I am talking about is between the different output of string a and b. I am not comparing with prettier, I am comparing the string a with string b when formatted by biome. The strings are the same, I just manually formatted string a in a different way than b which results in a different output. I see that even prettier has the same output as biome, but i believe if the strings are the same just with different whitespaces, the end result should be same.

Biome seems to agree with me since when I copy the output of the first iteration and [format it again][new-url], it makes both string a and b the same, the only problem being that it violates the line width of 80 and places everything in a single line when the line can be broken down. Prettier does not change its output (the 2 strings are not formatted the same, but the number of runs does not change its output). This is weird now since the output also depends on how many times biome is run.

This might be a weird edge case and is problematic since now I have to be aware of the initial whitespace placement as well and if anything changes after multiple runs

[new-url]: https://biomejs.dev/playground/?indentStyle=space&quoteProperties=preserve&code=YwBvAG4AcwB0ACAAYQAgAD0AIABgAEwAZQBjAHQAdQByAGUAcwA6ACAAJAB7AGQAbwBuAGUAQwBvAHUAbgB0AH0ALwAkAHsAdABvAHQAYQBsAEMAbwB1AG4AdAB9ACAAfAAgAE0AaQBuAHMAOgAgACQAewAoAAoAIAAgAGQAbwBuAGUAUwBlAGMAcwAgAC8AIAA2ADAACgApAC4AdABvAEYAaQB4AGUAZAAoADIAKQB9AC8AJAB7ACgAdABvAHQAYQBsAFMAZQBjAHMAIAAvACAANgAwACkALgB0AG8ARgBpAHgAZQBkACgAMgApAH0AfAAgAEgAbwB1AHIAcwA6ACAAJAB7ACgACgAgACAAZABvAG4AZQBTAGUAYwBzACAALwAgADMANgAwADAACgApAC4AdABvAEYAaQB4AGUAZAAoADIAKQB9AC8AJAB7ACgAdABvAHQAYQBsAFMAZQBjAHMAIAAvACAAMwA2ADAAMAApAC4AdABvAEYAaQB4AGUAZAAoADIAKQB9AGAAOwAKAAoAYwBvAG4AcwB0ACAAYgAgAD0AIABgAEwAZQBjAHQAdQByAGUAcwA6ACAAJAB7AGQAbwBuAGUAQwBvAHUAbgB0AH0ALwAkAHsAdABvAHQAYQBsAEMAbwB1AG4AdAB9ACAAfAAgAE0AaQBuAHMAOgAgACQAewAoAGQAbwBuAGUAUwBlAGMAcwAgAC8AIAA2ADAAKQAuAHQAbwBGAGkAeABlAGQAKAAyACkAfQAvACQAewAoAHQAbwB0AGEAbABTAGUAYwBzACAALwAgADYAMAApAC4AdABvAEYAaQB4AGUAZAAoADIAKQB9AHwAIABIAG8AdQByAHMAOgAgACQAewAoAGQAbwBuAGUAUwBlAGMAcwAgAC8AIAAzADYAMAAwACkALgB0AG8ARgBpAHgAZQBkACgAMgApAH0ALwAkAHsAKAB0AG8AdABhAGwAUwBlAGMAcwAgAC8AIAAzADYAMAAwACkALgB0AG8ARgBpAHgAZQBkACgAMgApAH0AYAA7AAoA

**Comment by suxin2017** [comment]
Thank you for your reply, I probably found the problem location, let me see how to fix it
