### ISSUE TITLE
🐛  `useSemanticElements` false alarm on `role="alert"`

### ISSUE THREAD

**Issue by baileys-li** [biomejs/biome#3858]
### What happened?

>   ✖ The elements with the following roles can be changed to the following elements: `<alert>`

 — [Playground](https://biomejs.dev/playground/?lintRules=all&files.main.jsx=PABkAGkAdgAgAHIAbwBsAGUAPQAiAGEAbABlAHIAdAAiAD4ACgAgAFkAbwB1AHIAIABsAG8AZwAgAGkAbgAgAHMAZQBzAHMAaQBvAG4AIAB3AGkAbABsACAAZQB4AHAAaQByAGUAIABpAG4AIAAyACAAbQBpAG4AdQB0AGUAcwAKADwALwBkAGkAdgA%2BAA%3D%3D)

### Expected result

There is html element `<alert>` neither in MDN, nor in HTML Spec. So [`lint/a11y/useSemanticElements`](https://biomejs.dev/linter/rules/use-semantic-elements)  should do nothing with `alert` role tho

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by baileys-li** [comment]
@ematipico I guess it's better not to force any tag at all. 
For example it's could be any tag with `popup` attribute

**Comment by Conaclos** [comment]
Reopening because my fix (#3868) was ineffective.
