### ISSUE TITLE
📝 CSS Formatter inverts comma separated elements and comments

### ISSUE THREAD

**Issue by Th3S4mur41** [biomejs/biome#3873]
### Environment information

```bash
CLI:
  Version:                      1.9.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v22.6.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.8.2"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Formatter:
  Format with errors:           false
  Indent style:                 Tab
  Indent width:                 2
  Line ending:                  Lf
  Line width:                   120
  Attribute position:           Auto
  Bracket spacing:              BracketSpacing(true)
  Ignore:                       []
  Include:                      []

JavaScript Formatter:
  Enabled:                      false
  JSX quote style:              Double
  Quote properties:             AsNeeded
  Trailing commas:              All
  Semicolons:                   Always
  Arrow parentheses:            Always
  Bracket spacing:              unset
  Bracket same line:            false
  Quote style:                  Single
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Attribute position:           unset

JSON Formatter:
  Enabled:                      true
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Trailing Commas:              unset

CSS Formatter:
  Enabled:                      false
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Quote style:                  Single

GraphQL Formatter:
  Enabled:                      false
  Indent style:                 unset
  Indent width:                 unset
  Line ending:                  unset
  Line width:                   unset
  Bracket spacing:              unset
  Quote style:                  unset

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
	"$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
	"linter": {
		"enabled": true,
		"rules": {
			"recommended": true
		}
	},
	"formatter": {
		"enabled": true,
		"lineWidth": 120
	},
	"javascript": {
		"formatter": {
			"quoteStyle": "single"
		}
	},
	"css": {
		"formatter": {
			"quoteStyle": "single"
		}
	},
	"files": {
		"ignore": [".devcontainer", ".history", "coverage", "package-lock.json", "CHANGELOG.md"]
	},
	"vcs": {
		"enabled": true,
		"clientKind": "git",
		"useIgnoreFile": true
	}
}
```

### Playground link

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&jsxQuoteStyle=single&lintRules=all&files.main.css=YwBvAGQAZQAsAAoAawBiAGQALAAgAC8AKgAgAEsAZQB5AGIAbwByAGEAZAAgAGkAbgBwAHUAdAAgACoALwAKAHAAcgBlACwAIAAvACoAIABQAHIAZQBmAG8AcgBtAGEAdAB0AGUAZAAgAHQAZQB4AHQAIAAqAC8ACgB2AGEAcgAgAHsACgAJAGYAbwBuAHQALQBmAGEAbQBpAGwAeQA6ACAAbQBvAG4AbwBzAHAAYQBjAGUAOwAKAH0A

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by vohoanglong0107** [comment]
It seems that Prettier doesn't format anything when it comes to comments interleaved between selectors. For example, it doesn't do anything to this CSS:

```css
pre          , /* Preformatted text */
var {
  font-family: monospace;
}
```

So, I think in this case, it's better for Biome to enforce a consistent comment style for selectors.

**Comment by vohoanglong0107** [comment]
Feel free to comment on this if you have a different opinion

**Comment by Th3S4mur41** [comment]
I'm all for a consistent style...
I'm just not sure moving the comment before the coma, which is also adding a trailing space into the selector is a good idea.

**Comment by ematipico** [comment]
@vohoanglong0107 while your observation is true, Biome still fails to position the comments **after** the comma.

Also, Prettier isn't good with trivia in general. Biome has a better infrastructure and can achieve better results, like in this case.

I re-open this issue as it's a bug

**Comment by ematipico** [comment]
Closing. This is a Prettier bug, which is inconsistent. Check how comments are placed in a very similar structure in JavaScript file

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&jsxQuoteStyle=single&lintRules=all&files.main.css=YwBvAGQAZQAsAAoAawBiAGQALAAgAC8AKgAgAEsAZQB5AGIAbwByAGEAZAAgAGkAbgBwAHUAdAAgACoALwAKAHAAcgBlACwAIAAvACoAIABQAHIAZQBmAG8AcgBtAGEAdAB0AGUAZAAgAHQAZQB4AHQAIAAqAC8ACgB2AGEAcgAgAHsACgAJAGYAbwBuAHQALQBmAGEAbQBpAGwAeQA6ACAAbQBvAG4AbwBzAHAAYQBjAGUAOwAKAH0A&files.file.js=YwBvAG4AcwB0ACAAZgAgAD0AIAB7AAoAIAAgAGgAZQB5ADoAIAAnACcALAAgACAALwAqACAAcwBvAG0AZQB0AGgAaQBuAGcAIAAqAC8ACgAgACAAZgBvAHIAOgAgACcAJwAgAC8AKgAgAHMAbwBtAGUAdABoAGkAbgBnACAAKgAvAAoAfQA%3D

**Comment by Conaclos** [comment]
@ematipico I think the example you posted is not the one you wanted to.

**Comment by ematipico** [comment]
> @ematipico I think the example you posted is not the one you wanted to.

It is. Check the files on the left, there's a `file.js` AND a `main.css` :)
