### ISSUE TITLE
🐛A `unset` value in editorconfig is not supported. 

### ISSUE THREAD

**Issue by hidekatsu-izuno** [biomejs/biome#3886]
### Environment information

```block
CLI:
  Version:                      1.9.0
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

1. I have the next .editorconfig on project root
```
# EditorConfig is awesome: https://EditorConfig.org

# top-most EditorConfig file
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[/tests/data/**]
charset = unset
end_of_line = unset
insert_final_newline = unset
trim_trailing_whitespace = unset
indent_style = unset
indent_size = unset
```
2. I set formatter.useEditorconfig to true
3. I saw the next error message
```
  ✖ Failed to parse the .editorconfig file.
    
    Caused by:
      Custom("unknown variant `unset`, expected one of `lf`, `crlf`, `cr`")
```

### Expected result

The `unset` value for the property seems to be the correct value according to the [editorconfig site](https://editorconfig.org/).
I use for ignoring test files.

Hopefully this feature will be supported. 

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by dyc3** [comment]
Huh, I missed that part of the spec. I'm not entirely sure if we have a "revert to default" behavior for our configuration, so it's a little unclear how exactly this would map onto our logic.

**Comment by Conaclos** [comment]
> Huh, I missed that part of the spec. I'm not entirely sure if we have a "revert to default" behavior for our configuration, so it's a little unclear how exactly this would map onto our logic.

We could emit a warning as the one we emit when we encounter a setting we don't handle.
