### ISSUE TITLE
📎 Implement `lint/noImplicitAnyLet`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#389]
### Description

See #381 for some context.

The rule should only apply to TypeScript files.
It should report variable declared with `var` or `let` without type annotation and without initializer.

Want to contribute? Lets us know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by b4s36t4** [comment]
Would love to work on this.
