### ISSUE TITLE
📎 Implement `useParseIntRadix` - `eslint/radix`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#3932]
### Description

Implement [eslint/radix](https://eslint.org/docs/latest/rules/radix/).

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

The implementer could take some inspirations from the implementation of existing rules such as  `useNumberToFixedDigitsArgument`.

Sugggested names: `useParseIntRadix` or `useParseIntRadixArgument`.

**Comment by abhishekpaturkar** [comment]
Hey, I want to contribute. Can you give the location where to put the files.

**Comment by dyc3** [comment]
See this: https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md

I'll go ahead and assign you.

**Comment by Conaclos** [comment]
@abhishekpaturkar
Any update?

**Comment by Aditya-PS-05** [comment]
I am interested. Can you assign me this issue?

**Comment by Conaclos** [comment]
Assigned ;)

**Comment by Jantje19** [comment]
Hi, since there hasn't been an update in a couple of weeks, I have taken a stab at it: https://github.com/Jantje19/biome

**Comment by dyc3** [comment]
@Jantje19 You will need to make a PR against this repo.
