### ISSUE TITLE
📎 Implement `noDocumentCookie` -  `unicorn/no-document-cookie`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#3940]
### Description

Implement [unicorn/no-document-cookie](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/no-document-cookie.md).

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by tunamaguro** [comment]
Hello.
Can I work on this?
