### ISSUE TITLE
📎 Replace Clippy `allow` with `expect`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#3969]
### Description

Rust 1.81 stabilizes Clippy's  [`expect` attribute](https://blog.rust-lang.org/2024/09/05/Rust-1.81.0.html#expectlint). This attribute ensures that a lint diagnostic is emitted where the attribute appears.

We should replace `allow` attribute with `expect`.

We should also retsrict the use of `allow` by denying [clippy::allow_attributes](https://rust-lang.github.io/rust-clippy/master/index.html#/allow_attributes).

**Comment by ematipico** [comment]
I just noticed you don't use 1.81.0 yet, so this task needs to wait until to move to 1.81

**Comment by Conaclos** [comment]
> so this task needs to wait until to move to 1.81

Done in #3972
