### ISSUE TITLE
📝 HTML void tags should always emit a `/` token

### ISSUE THREAD

**Issue by dyc3** [biomejs/biome#3975]
### Environment information

```bash
playground
```

### Playground link

https://biomejs.dev/playground?files.main.html=PABpAG0AZwA%2BAA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by dyc3** [comment]
Note that HTML doesn't work in the playground without:
- #3967
- #3892
- biomejs/website#1089

**Comment by suxin2017** [comment]
can you assign it to me?
