### ISSUE TITLE
📝 Contents of `<pre>` elements should not be formatted

### ISSUE THREAD

**Issue by dyc3** [biomejs/biome#4021]
### Environment information

```bash
playground
```

### Playground link

https://biomejs.dev/playground/?quoteStyle=single&indentWidth=4&arrowParentheses=as-needed&files.main.html=PABwAHIAZQA%2BAAoACgAgACAAIAAgACAAIAAgACAAVABlAHgAdAAgAGkAbgAgAGEAIABwAHIAZQAgAGUAbABlAG0AZQBuAHQACgAKACAAIAAgACAAaQBzACAAZABpAHMAcABsAGEAeQBlAGQAIABpAG4AIABhACAAZgBpAHgAZQBkAC0AdwBpAGQAdABoAAoACgAgACAAIABmAG8AbgB0ACwAIABhAG4AZAAgAGkAdAAgAHAAcgBlAHMAZQByAHYAZQBzAAoACgAgACAAIABiAG8AdABoACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAcwBwAGEAYwBlAHMAIABhAG4AZAAKAAoAIAAgACAAbABpAG4AZQAgAGIAcgBlAGEAawBzAAoACgA8AC8AcAByAGUAPgA%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
When we do fix this issue, let's please add some docs that explain why we shouldn't format contents inside this tag.

The issue doesn't explain that

**Comment by dyc3** [comment]
The [MDN docs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/pre) explain it pretty well, but I'll go ahead and elaborate here:

The `<pre>` element is "Preformatted Text", meaning that the author has already formatted the contents of the element appropriately. A common use case is example code blocks in web pages.
