### ISSUE TITLE
Project names need to be at least 1 character long.

### ISSUE THREAD

**Issue by arolson101** [biomejs/biome#4082]
### Environment information

```block
> npx biome rage
```
(there is no output)
```


### What happened?

I run biome init to try out this project and get this error message.  My package.json has a "name" key ("name": "todo"), so I don't understand what project name it's referring to.

```
> npx biome init  
Need to install the following packages:
biome@0.3.3
Ok to proceed? (y) y

npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated har-validator@5.1.5: this library is no longer supported
npm warn deprecated rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
npm warn deprecated request-promise@3.0.0: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm warn deprecated fs-promise@0.5.0: Use mz or fs-extra^3.0 with Promise Support
npm warn deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
npm warn deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm warn deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
Project names need to be at least 1 character long.
Error: Project names need to be at least 1 character long.
    at C:\Users\...\AppData\Local\npm-cache\_npx\b040de3f3c289dd6\node_modules\biome\dist\init.js:70:13
```

### Expected result

it should report where it's looking for this empty project name

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
You're using an incorrect package. Our package is called `@biomejs/biome` . You can check our website

**Comment by arolson101** [comment]
I see; this error happens if you fail to install `@biomejs/biome` before running npx biome command

**Comment by okineadev** [comment]
> You're using an incorrect package. Our package is called `@biomejs/biome` . You can check our website

Thanks!
