### ISSUE TITLE
🐛 Formatter seems broken in the Playground

### ISSUE THREAD

**Issue by fireairforce** [biomejs/biome#4086]
### Environment information

```block
No
```

### What happened?

1. Visit https://biomejs.dev/playground, my commit version is [9261a69](https://github.com/biomejs/biome/tree/9261a69aeedee1da91938aff20bfc876b32b6545)
2. Write a simple code:

![image](https://github.com/user-attachments/assets/1356cb65-35ee-4d7f-a524-6c7dba6aa948)

Nothing show at `Formatter` and `Syntex`.

### Expected result

it should work normal.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
The playground seems also broken for me (the formatter part).

**Comment by dyc3** [comment]
II just fixed this in: https://github.com/biomejs/website/pull/1219

**Comment by fireairforce** [comment]
lol, I thought it took so long for no one to respond because only my playground was down...

**Comment by ematipico** [comment]
It seems that the formatter IR isn't printed. Sorry guys

**Comment by ematipico** [comment]
Next time, please file an issue in the website repository

**Comment by fireairforce** [comment]
ok~
