### ISSUE TITLE
🐛 VS Code extension fails to start 

### ISSUE THREAD

**Issue by olivierdelomez** [biomejs/biome#412]
### Environment information

```block
CLI:
  Version:                      1.2.2
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v19.4.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.2.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0

Discovering running Biome servers...

Running Biome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ The client isn't connected to any server but rage discovered this running Biome server.
✖ Failed to connect: the request to the remote workspace timed out

Biome Server Log:
```

### What happened?

followed the installation instruction on the website (both CLI and VScode extension).
Biome CLI is working
Biome VS Code extension does not start (format with doesn't show Biome as an option)

running `npx biome version` returns

```
CLI:        1.2.2
Server:     not connected
```

Biome output in VSCode

```
Configuration file required, looking for one.
Config file found at /Users/*****/workspace/scaffold/biome.json, enabling Biome extension
Using Biome from /Users/*****/workspace/scaffold/node_modules/.bin/biome
[cli-stdout] data 68
[cli-stderr] end
[cli-stdout] end
[cli] exit 0
Connecting to "/var/folders/8h/drtc0lfx1hl9wsp4qg566zbw0000gp/T/biome-socket-1.2.2" ...
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli] close 0
[cli-stderr] close
```

I tried to downgrade the extension, restarted VS Code, clean and install again etc..

### Expected result

Expected the Biome VSCode extension to work. 

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
>  Biome VS Code extension does not start (format with doesn't show Biome as an option)

The extension starts sending events when you open a file recognised by Biome. Try opening a JS file and you should be able to see the Biome from the "Format With...".

Did you try to increase the trace level and check if "Biome Trace" channel is sending eventS?

**Comment by olivierdelomez** [comment]
I tried with a js file but Biome is not in the option's list.
I've set the trace level to verbose, I have a single event`[Trace - 11:40:29] Sending request 'initialize - (0)'.` followed by a  `Params` object.

At the bottom right of VS Code window, Biome has a "reload" icon.

<img width="132" alt="Screenshot 2023-09-25 at 11 29 19" src="https://github.com/biomejs/biome/assets/3940004/3c7a6206-e64b-4ce3-b2fb-58554ee83ee5">

I've tried to force it with `"editor.defaultFormatter": "biomejs.biome",`   but the VS Code outputs 
```
FormattingExtension 'Biome' is configured as formatter but it cannot format 'JavaScript'-files
```

I've disabled all the extensions but Biome

**Comment by ematipico** [comment]
Do you have a repository you can share? That will help us to triage the issue

**Comment by olivierdelomez** [comment]
literally it's a just a `yarn create vite` with typescript template to test out Biome...

**Comment by ematipico** [comment]
I run `create vite`, and the Biome works fine with VSCode. There's probably something else.

**Comment by tbeseda** [comment]
I get a similar problem. 

some info and reports:

the repo I chose: https://github.com/tbeseda/waylon (very small), but I get similar results in other, larger repos

```
CLI:
  Version:                      1.2.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.18.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.8.1"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0

Discovering running Biome servers...

Server:
  Status:                       stopped
```

```
Configuration file required, looking for one.
Config file found at ~/waylon/biome.json, enabling Biome extension
Using Biome from ~/waylon/node_modules/.bin/biome
[cli-stderr] data 37
[cli-stderr] end
[cli-stdout] end
[cli] exit 127
[Error - 9:37:20 PM] Biome client: couldn't create connection to server.
Error: Command "~/waylon/node_modules/.bin/biome __print_socket" exited with code 127
Output:
env: node: No such file or directory

	at getSocket (~/.vscode/extensions/biomejs.biome-1.4.2-darwin-arm64/out/main.js:19600:11)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async createMessageTransports (~/.vscode/extensions/biomejs.biome-1.4.2-darwin-arm64/out/main.js:19615:16)
	at async LanguageClient2.createConnection (~/.vscode/extensions/biomejs.biome-1.4.2-darwin-arm64/out/main.js:15576:28)
	at async LanguageClient2.start (~/.vscode/extensions/biomejs.biome-1.4.2-darwin-arm64/out/main.js:15152:30)
	at async activate (~/.vscode/extensions/biomejs.biome-1.4.2-darwin-arm64/out/main.js:19421:3)
	at async E.n (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:6206)
	at async E.m (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:6169)
	at async E.l (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/api/node/extensionHostProcess.js:107:5626)
[cli-stderr] finish
[cli-stdout] finish
[cli-stdout] close
[cli] close 127
[cli-stderr] close
```

**Comment by olivierdelomez** [comment]
Just restarted/updated my macbook and now Biome works fine...

**Comment by fifv** [comment]
I met similar problem, in my case I found a `biome.exe` is executed busily at background, which I used to format a heavy file to test performance but it got stuck.
After terminating it, the extension started smoothly.

**Comment by gethari** [comment]
> Just restarted/updated my macbook and now Biome works fine...

# This worked for me in 2025

Thanks

**Comment by Yuvi-Luminos** [comment]
For what it's worth, I was able to troubleshoot a similar issue by identifying that a biome server was running globally, and I'm causiosly attributing it to the biome server in VS Code conflicting with a global biome installation via Homebrew (on macOS) that was also running the server:

```shell
which biome
# Output:
#    /opt/homebrew/bin/biome

biome stop
# Output:
#     The Biome server was successfully stopped

biome rage --daemon-logs
# Output:
#     ...
#     Server:
#       Status:                       stopped
#     ...
```

@olivierdelomez my guess is that your MacBook restart stopped a conflicting biome server (it could also be a global npm package - in my case it was installed via Homebrew).

**Comment by olsonpm** [comment]
I spent a long time debugging some weird biome issues including it not starting - a desktop restart also fixed my case.

environment:
- Arch Linux
- vscodium@1.126.04524
- @biomejs/biome@2.5.7
- biome vscode extension 3.7.1
