### ISSUE TITLE
🐛 Format compat issues with Prettier

### ISSUE THREAD

**Issue by nstepien** [biomejs/biome#419]
### Environment information

```block
playground
```

### What happened?

- [x] https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&code=ZgB1AG4AYwB0AGkAbwBuACAAcgBlAGEAdQB0AGgAZQBuAHQAaQBjAGEAdABlACgAKQAgAHsACgAgACAAaQBmACAAKAAhAG0AbwB1AG4AdABlAGQAKQAgAHIAZQB0AHUAcgBuADsACgAgACAAdABpAG0AZQBvAHUAdAAgAD0AIAB3AGkAbgBkAG8AdwAuAHMAZQB0AFQAaQBtAGUAbwB1AHQAKAAKACAAIAAgACAAKAApACAAPQA%2BACAAewAKACAAIAAgACAAIAAgAHIAZQBmAHIAZQBzAGgAVABvAGsAZQBuACgAKQAuAHQAaABlAG4AKAByAGUAYQB1AHQAaABlAG4AdABpAGMAYQB0AGUAKQA7AAoAIAAgACAAIAB9ACwACgAgACAAIAAgADUAIAAqACAANgAwACAAKgAgADEAMAAwADAACgAgACAAKQA7AAoAfQAKAA%3D%3D
- [x] https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&code=YQB3AGEAaQB0ACAAdQBzAGUAcgBFAHYAZQBuAHQALgBjAGwAaQBjAGsAKAAKACAAIAAoAGEAdwBhAGkAdAAgAHMAYwByAGUAZQBuAC4AZgBpAG4AZABBAGwAbABCAHkAUgBvAGwAZQAoACcAYgB1AHQAdABvAG4AJwAsACAAewAgAG4AYQBtAGUAOgAgACcAQwBsAG8AcwBlACcAIAB9ACkAKQBbADEAXQAKACkAOwAKAA%3D%3D
- [x] https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&code=ZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABEAGEAdABlAFIAYQBuAGcAZQBGAG8AcgBtAGEAdAB0AGUAcgAoAHsAIABkAGEAdABlAEYAcgBvAG0ALAAgAGQAYQB0AGUAVABvACAAfQA6ACAARABhAHQAZQBSAGEAbgBnAGUAUAByAG8AcABzACkAIAB7AAoAIAAgAHIAZQB0AHUAcgBuACAAZABhAHQAZQBGAHIAbwBtACAAJgAmACAAZABhAHQAZQBUAG8AIAA%2FACAAKAAKACAAIAAgACAAPAA%2BAAoAIAAgACAAIAAgACAAPABEAGEAdABlAEYAbwByAG0AYQB0AHQAZQByACAAdgBhAGwAdQBlAD0AewBkAGEAdABlAEYAcgBvAG0AfQAgAC8APgAKACAAIAAgACAAIAAgAC0ACgAgACAAIAAgACAAIAA8AEQAYQB0AGUARgBvAHIAbQBhAHQAdABlAHIAIAB2AGEAbAB1AGUAPQB7AGQAYQB0AGUAVABvAH0AIAAvAD4ACgAgACAAIAAgADwALwA%2BAAoAIAAgACkAIAA6ACAAbgB1AGwAbAA7AAoAfQA%3D
- [x] https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&code=YwBvAG4AcwB0ACAAbABvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBuAGcAVgBhAGwAdQBlACAAPQAKACAAIABhAHcAYQBpAHQAIABjAGwAaQBlAG4AdABzAC4AYwByAGUAYQB0AGUAVABhAHgAUwBlAHQAdABpAG4AZwAoAHQAYQB4AFMAZQB0AHQAaQBuAGcAKQA7AA%3D%3D
- [x] https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&code=dAB5AHAAZQAgAFQAeQBwAGUAIAA9ACAAdAB5AHAAZQBvAGYAIABvAGIAagBbAG4AdQBtAGIAZQByAF0AOwA%3D
- [x] https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&trailingComma=none&code=YwBvAG4AcwB0ACAAewAgAGwAbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbwBvAG8AbgBnAFYAYQBsAHUAZQAgAH0AIAA9ACAAYQB3AGEAaQB0ACAAcwBlAHQAdQBwACgAMgApADsA

### Expected result

Formatting parity with prettier.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by faultyserver** [comment]
Taking a look at these, 4 and 6 seem to already be fixed, but weren't referenced.

I've got a fix for 5 (`typeof` expressions), and will start looking at 1, 2, and 3 next.

**Comment by Conaclos** [comment]
This was fixed in #707

**Comment by TaKO8Ki** [comment]
Can I work on this issue?

**Comment by Conaclos** [comment]
@TaKO8Ki Of course :) One particular case or the three remaining cases?

**Comment by TaKO8Ki** [comment]
@Conaclos For now, I'll try the first one!

**Comment by nstepien** [comment]
Looks like all the compat issues I raised are now fixed, thanks all!
