### ISSUE TITLE
📝 Vue SFC not formatted if code starts on same line of tag

### ISSUE THREAD

**Issue by davidglezz** [biomejs/biome#4221]
### Environment information

```bash
CLI:
  Version:                      1.9.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.17.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.8.2"

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{}
```

### Playground link

https://biomejs.dev/playground/?lineWidth=120&indentStyle=space&enabledLinting=false&importSortingEnabled=false&files.example.vue=PAB0AGUAbQBwAGwAYQB0AGUAPgAKACAAIAA8AHMAZQBjAHQAaQBvAG4APgAKACAAIAAgACAAIAAgACAAIAAgACAAPABoADEAPgBOAG8AdAAgAGYAbwByAG0AYQB0AHQAZQBkACAAOgAoADwALwBoADEAPgAKACAAIAA8AC8AcwBlAGMAdABpAG8AbgA%2BAAoAPAAvAHQAZQBtAHAAbABhAHQAZQA%2BAAoACgA8AHMAYwByAGkAcAB0ACAAbABhAG4AZwA9ACIAdABzACIAIABzAGUAdAB1AHAAPgBjAG8AbgBzAHQAIAB4ACAAPQAgADEAOwAKACAAIABjAG8AbgBzAHQAIAB5ACAAPQAgADIAOwAKACAAIAAgACAAYwBvAG4AcwB0ACAAegAgACAAIAAgACAAPQAgADMAOwAKADwALwBzAGMAcgBpAHAAdAA%2BAAoACgA8AHMAdAB5AGwAZQAgAGwAYQBuAGcAPQAiAHMAYwBzAHMAIgAgAHMAYwBvAHAAZQBkAD4ACgAgACAALwAqACAAbgBvAHQAIABmAG8AcgBtAGEAdAB0AGUAZAAgADoAKAAgACoALwAKACAAIAAuAHQAZQBzAHQAIAAgACAAIAAgACAAewAgAGMAbwBsAG8AcgA6ACAAIAAgACAAcgBlAGQAOwAgAH0ACgA8AC8AcwB0AHkAbABlAD4ACgA%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

#### Input
```vue
<script lang="ts" setup>const x = 1;
  const y = 2;
    const z     = 3;
</script>
```

#### Expected Output
```vue
<script lang="ts" setup>
const x = 1;
const y = 2;
const z = 3;
</script>
```

**Comment by ematipico** [comment]
We are likely not going to fix this one, due to our partial support
