### ISSUE TITLE
🐛 Playground Prettier does not format like the real prettier CLI

### ISSUE THREAD

**Issue by davidglezz** [biomejs/biome#4223]
### Environment information

```block
Unrelated
```

### What happened?

Creating a issue, I discovered that the prettier output of the playground does not match with the prettier output doin `npx prettier --write test.vue`

Wrong Prettier output:
- css not formatted.
- script content no formatted correctly.

```vue
<template>
  <section>
    <h1>hi</h1>
  </section>
</template>

<script lang="ts" setup>
const x = 1;
  const y = 2;
    const z     = 3;
</script>

<style lang="scss" scoped>
/* hi */
.test      { color:    red; }
</style>

```

https://biomejs.dev/playground/?lineWidth=120&indentStyle=space&files.example.vue=PAB0AGUAbQBwAGwAYQB0AGUAPgAKACAAIAA8AHMAZQBjAHQAaQBvAG4APgAKACAAIAAgACAAIAAgACAAIAAgACAAPABoADEAPgBoAGkAPAAvAGgAMQA%2BAAoAIAAgADwALwBzAGUAYwB0AGkAbwBuAD4ACgA8AC8AdABlAG0AcABsAGEAdABlAD4ACgAKADwAcwBjAHIAaQBwAHQAIABsAGEAbgBnAD0AIgB0AHMAIgAgAHMAZQB0AHUAcAA%2BAGMAbwBuAHMAdAAgAHgAIAA9ACAAMQA7AAoAIAAgAGMAbwBuAHMAdAAgAHkAIAA9ACAAMgA7AAoAIAAgACAAIABjAG8AbgBzAHQAIAB6ACAAIAAgACAAIAA9ACAAMwA7AAoAPAAvAHMAYwByAGkAcAB0AD4ACgAKADwAcwB0AHkAbABlACAAbABhAG4AZwA9ACIAcwBjAHMAcwAiACAAcwBjAG8AcABlAGQAPgAKACAAIAAvACoAIABoAGkAIAAqAC8ACgAgACAALgB0AGUAcwB0ACAAIAAgACAAIAAgAHsAIABjAG8AbABvAHIAOgAgACAAIAAgAHIAZQBkADsAIAB9AAoAPAAvAHMAdAB5AGwAZQA%2BAAoA

### Expected result
Prettier panel should have:
```vue
<template>
  <section>
    <h1>hi</h1>
  </section>
</template>

<script lang="ts" setup>
const x = 1;
const y = 2;
const z = 3;
</script>

<style lang="scss" scoped>
/* hi */
.test {
  color: red;
}
</style>

```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ah-yu** [comment]
Since Biome currently doesn't support embedded formatting, we've disabled embedded formatting in Prettier as well to keep the configurations consistent between Biome and Prettier. However, Prettier enables embedded formatting by default, which is why you're seeing different outputs.
