### ISSUE TITLE
📎 Refactor `biome_aria` to **not** use macros

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#4236]
### Description

At the moment, the crate `biome_aria` defines various roles using a macro. 

While these macros are convenient code-wise, they are slow and they have an impact on the compilation time of the crate.

This task is a **good opportunity** for first time contributors to do an internal refactor without knowing too much about how Biome works.

You can use this PR as an example to see how the refactor should be done. If the reactor is correct, it should compile successfully and all current tests should pass.

https://github.com/biomejs/biome/pull/4235

**Comment by andrewgremlich** [comment]
Can I claim this?
