### ISSUE TITLE
💅 `useNamingConvention` forbids the `readonly` modifier for `indexParameter` selector kind

### ISSUE THREAD

**Issue by sepruko** [biomejs/biome#4277]
### Environment information

```bash
CLI:
  Version:                      1.9.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           windows

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         unset
  JS_RUNTIME_VERSION:           "v20.18.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Error:                        The `readonly` modifier cannot be used with the `index parameter` kind.
  Status:                       Loaded with errors
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  JavaScript enabled:           true
  JSON enabled:                 true
  CSS enabled:                  true
  GraphQL enabled:              false
  Recommended:                  false
  All:                          false
  Enabled rules:
  style/useNamingConvention

Workspace:
  Open Documents:               0
```

### Rule name

style/useNamingConvention

### Playground link

https://github.com/sepruko/biome-repro/tree/style/use-naming-convention-0

### Expected result

When configured to ensure index parameters with the `readonly` modifier are of specific formats and/or patterns, it should successfully parse its configuration file and emit the correct diagnostics.

The [TypeScript Handbook](https://www.typescriptlang.org/docs/handbook/2/objects.html#index-signatures) clearly includes an example showing an index parameter marked as `readonly`, and the official `tsc` compiler has no issue handling this code.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
The configuration you provided has errors, the rage output confirms it.

Can you please make sure to fix that?

**Comment by sepruko** [comment]
> The configuration you provided has errors, the rage output confirms it.
> 
> Can you please make sure to fix that?

The error is the problem, it is complaining that the `readonly` modifier is incompatible with the `indexParameter` kind when [TypeScript itself says it is, in fact, not](https://github.com/microsoft/TypeScript/blob/main/tests/cases/compiler/propertyAccessOfReadonlyIndexSignature.ts).
