### ISSUE TITLE
Make https://biomejs.dev/linter/rules/use-exhaustive-dependencies/ not recommended

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#4293]

**Comment by arendjr** [comment]
I don't think this is a good idea, since it would be a regression for React users that rely on the rule for enforcing the rules of hooks. However, we're in the process of adding a `reportUnnecessaryDependencies` option that I think _does_ make sense to disable by default for 2.0. See the dicussion here: https://github.com/biomejs/biome/issues/630#issuecomment-2379057647

**Comment by ematipico** [comment]
It is a regression, and that's why it's part of v2.0. The reason why we should not recommend it:
- this is a rule for react and react native projects, and people that don't use react are going to use a rule that's not needed in their projects 
- the other rule isn't recommended https://biomejs.dev/linter/rules/use-hook-at-top-level/, this is a bit inconsistent 
- we are starting to have rules that work on other frameworks (solidjs), and I think library/framework rules should be online opt-in

**Comment by Conaclos** [comment]
> I remember there was some discussion at some point about revamping the linter config, where we could add better categories to rules. Maybe we should focus on that first?

I plan to revisit it for Biome 2.0

**Comment by ematipico** [comment]
> A large part of the appeal of Biome is that it works out-of-the-box without too much hassle configuration-wise, so if people need to look themselves which rules apply to their libraries/frameworks and enable them manually, that sounds like a red flag.

You and I both agree. Since the scope Biome is slowly increasing, by spanning over other realities such as Next.js and Solid, we need to revisit our approach of "working out of the box" 

We can opt-in certain rules by checking the project manifests, and look for specific dependencies e.g. `react`, `next`, `solid` and more

> I remember there was some discussion at some point about revamping the linter config, where we could add better categories to rules. Maybe we should focus on that first?

And that's why we have this discussion where we proposed `projects`/`linter.domains`:

https://github.com/biomejs/biome/discussions/689#discussioncomment-7987718

**Comment by arendjr** [comment]
> I plan to revisit it for Biome 2.0

Glad to hear it!

> We can opt-in certain rules by checking the project manifests, and look for specific dependencies e.g. `react`, `next`, `solid` and more

Cool, then I'm totally on board yeah :) Just wanted to make sure we don't leave that out.

**Comment by kurtextrem** [comment]
Hey - just came across this. I'm sorry in advance if the question is a duplicate or has already been touched, but just making sure: Changes like this will end up in the changelog or upgrade guide, right? I assume many people use the recommended preset and if some rules disappear from it without noticing, it'd be bad.

**Comment by ematipico** [comment]
Of course they will
