### ISSUE TITLE
📎 Implement `lint/useCollapsedElseIf` - `eslint/no-lonely-if`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#43]
### Description

[no-lonely-if](https://eslint.org/docs/latest/rules/no-lonely-if)

**Comment by ematipico** [comment]
I would suggest a name similar to clippy: https://rust-lang.github.io/rust-clippy/stable/index.html#collapsible_else_if

**Comment by ematipico** [comment]
Why not `useCollapsibleElseIf`? 😮

**Comment by Conaclos** [comment]
Because `collapsible` highlights a capability (can be collapsed). Maybe it is ok? Otherwise, I am thinking about `useCollapsedElseIf`?

**Comment by Conaclos** [comment]
Implemented in #160

**Comment by Conaclos** [comment]
Implemented in https://github.com/biomejs/biome/pull/160
