### ISSUE TITLE
📎 add support for graphql-tag formatting 

### ISSUE THREAD

**Issue by wmboult94** [biomejs/biome#430]
### Description

We just started using biome over prettier/eslint, and loving it overall! This is the first thing we've found we miss from prettier as we use `gql` template expressions across our project.

The request: just as [prettier does](https://github.com/prettier/prettier/pull/2092), it would be very useful to be able to format `graphql-tag`'s `gql` tagged template expressions.

Eg:

```
gql`
  query GetSomething {
    getSomething {
      foo
    }
  }
`;
```

**Comment by ematipico** [comment]
We don't support GraphQL, and it's not in our roadmap yet.

You can upvote https://github.com/biomejs/biome/discussions/297 in the meantime. If it reaches enough votes we will consider it

**Comment by wmboult94** [comment]
Thanks for the response, have upvoted that issue!

**Comment by BramKaashoek** [comment]
I believe this issue should be reopened, as GraphQL is now supported.

**Comment by ematipico** [comment]
Even though GraphQL is supported, Biome formatter doesn't support embedded formatting yet. Check https://github.com/biomejs/biome/issues/3334

Also, we open tasks (issues that start with 📎 ) when it's planned and have the resources to do it.
