### ISSUE TITLE
Analyzer top-level suppressions

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#4305]
TL;DR

```js
/** biome-ignore lint/style/useConst: reason */

let foo = 1;
let bar = 12;
```

The top-level suppression comment will suppress `style/useConst` for the whole file

**Comment by terion-name** [comment]
![Image](https://github.com/user-attachments/assets/fb5edb46-7c3f-4735-93d8-7b8bbe4c5202)

doesn't work

**Comment by Gbensky** [comment]
`/** biome-ignore assist/source/organizeImports: intended */`

doesn't work.  It seems organizeImports can't be ignored on a file level

**Comment by ematipico** [comment]
@Gbensky https://next.biomejs.dev/linter/#top-level-suppressions

**Comment by Gbensky** [comment]
> [@Gbensky](https://github.com/Gbensky) https://next.biomejs.dev/linter/#top-level-suppressions

Thank You. I was able to get it to work.

Apparently, adding a comment after the biome-ignore line makes the suppression void, so I added the comment before the biome-ignore line.
