### ISSUE TITLE
📎 Implement noGlobalDirnameFilename rule

### ISSUE THREAD

**Issue by kibertoad** [biomejs/biome#4331]
### Description

`__dirname` doesn't work in ESM context, but is not easily caught by tests, as e. g. vitest injects `__dirname`, so it works correctly there, but then fails in production. __filename is also in a similar situation. 

Prior art: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-module.md

Also see https://github.com/biomejs/biome/discussions/4245

**Comment by kibertoad** [comment]
@ematipico I don't know Rust, so unfortunately can't implement it myself.

**Comment by kibertoad** [comment]
@ematipico I've linked previous discussion, see https://github.com/biomejs/biome/discussions/4245

There was an ask to open a task for it from one of the collaborators.

**Comment by unvalley** [comment]
We have the noCommonJs rule, but it only applies to imports and exports.

If we want to add a rule to prefer modules, I think we should break it down into a few specific rules.

- Disallows 'use strict' directive.
	- [ ] `noUseStrict`?
- Disallows “Global Return”.
	- [ ] `noGlobalReturn`? 
- Disallows the global variables `__dirname and __filename.
	- [ ] `noLegacyPathGlobals` this issue
- Disallows `require(…)`.
	- [x] `noCommonJs` done this
- Disallows `exports` and `module.exports`. 
	- [x] `noCommonJs` done this

**Comment by unvalley** [comment]
`noGlobalLegacyPath` might be better, because we have already noGlobalXXX rules.

**Comment by dyc3** [comment]
IMO from a user's perspective "noGlobalLegacyPath" reads like it's banning something related to paths, not global variables

**Comment by unvalley** [comment]
`noGlobalDirnameAndFilename`? It's not cool but expressing itself directly and easy to search.

**Comment by Conaclos** [comment]
> Disallows 'use strict' directive.

Is this not covered by [noRedundantUseStrict](https://biomejs.dev/linter/rules/no-redundant-use-strict/)?

> Disallows “Global Return”. 

It is already a syntax error in module. Do I miss something?

> Disallows the global variables `__dirname and __filename. 

I wonder, is there reason to create a dedicated rule or should we ad this to `noCommonJs`?

**Comment by dyc3** [comment]
> should we add this to `noCommonJs`

From a quick search, it looks like these globals _are_ only valid in commonjs environments. So I think yeah, it would make sense to put it in the same rule. However, things against this that I can think of is:
- that we could be taking some granularity away from users.
- vitest injects these variables when it runs, so these can be available in esm looking environments, IIRC.

For those reasons I think it would make sense to keep this as a separate rule, or have options for the `noCommonJs` rule to enable/disable these different aspects of the rule. Adding rule options would be weird IMO, we generally tend to add rules and minimize the scope of those rules as much as possible.

**Comment by unvalley** [comment]
> Is this not covered by [noRedundantUseStrict](https://biomejs.dev/linter/rules/no-redundant-use-strict/)?

It's covered! I missed it.

Ok, I'll add the implementation to `noCommonJs`.

**Comment by Conaclos** [comment]
> For those reasons I think it would make sense to keep this as a separate rule, or have options for the `noCommonJs` rule to enable/disable these different aspects of the rule. Adding rule options would be weird IMO, we generally tend to add rules and minimize the scope of those rules as much as possible.

You made a good point. Let's keep the rule separated. We should certainly add a pointer to the new rule in `noCommonJs`.
