### ISSUE TITLE
BREAKING: don't exit with an error for max limit files

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#4375]

**Comment by Conaclos** [comment]
@ematipico Could you motivate this change?

**Comment by ematipico** [comment]
It was pointed out to me that this diagnostic is emitted as an error **to the user**, while it's an expected behaviour inside the library. Biome by default doesn't handle the size of a certain limit, and since it's the default, it should ignore those files.

Now, the user that pointed out was a jerk and ignored them, however, that is true.

So I plan to change the logic, emit a diagnostic with a different severity, but still make the CLI working. It should not exit with an error code.

**Comment by ematipico** [comment]
Closed by https://github.com/biomejs/biome/pull/4474
