### ISSUE TITLE
BREAKING: don't parse JSX in `.js` and `.ts` files

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#4385]

**Comment by arendjr** [comment]
For `.ts` I understand, since the TypeScript compiler makes the same distinction, but why would we do this for `.js` files? There are plenty of codebases that use `.js` files with JSX content and it's an accepted practice.

**Comment by ematipico** [comment]
It's an **old** and debatable practice. Nowadays, new projects always use `.tsx` and `.jsx` straightaway. New and modern projects should rely on file extensions and prior config, see `.mjs` and `.cjs` and `pakcage.json#type`, for example.

We intend to provide an option to opt in to the old behaviour (there's already a task for that in the checklist).
