### ISSUE TITLE
📝 Formatting via LSP sends full text instead of text edits, resulting in loss of editor-related metadata

### ISSUE THREAD

**Issue by chrisgrieser** [biomejs/biome#4393]
### The problem

It took me a bit to figure this out, but it appears that when formatting via LSP, biome sends the full formatted text instead of the text edits.

This is relevant for editors like [nvim, where using the full formatted text results in a loss of metadata](https://github.com/neovim/neovim/issues/21783), such as fold state or the internal list of changes. For instance, using the formatting command `vim.lsp.buf.format()` results in all folds being opened.

When using an intermediary plugin like [conform.nvim, which transforms full text overwrites to text edits](https://github.com/stevearc/conform.nvim?tab=readme-ov-file#features), this problem goes away (i.e., folds are preserved) indicating to me that this is indeed the problem.

With other LSPs, such as `ruff`, this does not happen.

### Environment information

```bash
CLI:
  Version:                      1.9.4
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v22.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### Configuration
happens with default config

### Playground link
not applicable?

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Great spot on, going to send a fix
