### ISSUE TITLE
📎 Implement `lint/noUnusedPrivateClassMembers` - `eslint/no-unused-private-class-members`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#44]
### Description

[no-unused-private-class-members](https://eslint.org/docs/latest/rules/no-unused-private-class-members/)

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by victor-teles** [comment]
@Conaclos I'll work on this one.

This rule should also cover private members in typescript ? or only es6 class private members ?

**Comment by ematipico** [comment]
I'd say both, because we can :)

**Comment by Conaclos** [comment]
Not sure, because private TypeScript field are not ensured to leak. I mean:

```ts
class A {
    private n: number;
}

declare const a: A;
const n = (a as { a: number }).a
```

This could make the code fix unsafe?

**Comment by victor-teles** [comment]
@Conaclos I get it.
TS private fields can also be leaked like this:

```typescript
class Biomex {
  private secretKey = 12345;
}

const bio = new Biomex();

console.log(bio.secretKey) // type checking error
console.log(bio['secretKey']); // works
```

So i think it can make the code unsafe!
But you think we can make it unsafe just for TS context?

**Comment by Conaclos** [comment]
> But you think we can make it unsafe just for TS context?

We previously had some rules with both safe and unsafe fixes. However, we decided to keep only one type of fix for every rule.
Thus we have several options:

1. create two different rules for each
3. keep a single rule and choose between (ii) providing only a safe code fix for removing unused `#private', (ii) providing unsafe code fixes for both, or (iii) providing no fixes.

(1) could be confusing for users? We should also find good names for two closely related rules... We could also just forget about Typescript's private fields.

Maybe (3) (iii)?

**Comment by victor-teles** [comment]
@Conaclos 

 (1) I agree it can be confusing for the user
 (2) I believe that (ii) is more convenient to the user and they can decide if they want to fix the code or not

**Comment by victor-teles** [comment]
@Conaclos Which solution do we go with?

**Comment by Conaclos** [comment]
@victor-teles 

I think you are right, we can choose (2) (ii), i.e. `keep a single rule and provide unsafe code fixes`.

**Comment by victor-teles** [comment]
@Conaclos @ematipico Need some help from you 😄

I'm trying to figure out how to use Semantic query type to find all references of class members, But I didn't manage to

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&jsxQuoteStyle=single&lintRules=all&code=YwBsAGEAcwBzACAAVAB5AHAAZQBTAGMAcgBpAHAAdABGAG8AbwAgAHsACgAJAHAAcgBpAHYAYQB0AGUAIAB1AHMAZQBkAE8AbgBsAHkAVABvAFUAcABkAGEAdABlAEkAdABzAGUAbABmACAAPQAgADUAOwAKAAoACQBtAGUAdABoAG8AZAAoACkAIAB7AAoACQAJAAkAdABoAGkAcwAuAHUAcwBlAGQATwBuAGwAeQBUAG8AVQBwAGQAYQB0AGUASQB0AHMAZQBsAGYAKwArADsACgAJAH0ACgB9AAoA

I've this class, and trying to find references of `usedOnlyToUpdateItself` field, do you have any suggestions?

**Comment by Conaclos** [comment]
The current semantic model doesn't include methods and properties. I am not sure if we should add this in the semantic model. For now, you can [implement your own visitor](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md#custom-visitors). You can take a look at the rules that use this strategy: `noUnusedLabels`, `noExcessiveComplexity`, ...

**Comment by Conaclos** [comment]
Another possibility is executing the rule for every class, so collect all definition of private properties (including parameter properties), and traverse every method (using a `syntax().preorder` iterator?), removing every registered properties that is used at least once. We could ignore write-only use of a property as we do with unused variables. You could reuse some code or logic from `noUnusedVariables`.

**Comment by victor-teles** [comment]
@Conaclos Thank you for clarifying

**Comment by Conaclos** [comment]
I think the second option is simpler.
