### ISSUE TITLE
🐛 organizeImports will move imports above an existing header comment

### ISSUE THREAD

**Issue by numso** [biomejs/biome#4408]
### Playground link

https://biomejs.dev/playground/?indentStyle=space&quoteStyle=single&semicolons=as-needed&code=LwAqAAoAIAAgAGkAbQBwAG8AcgB0AGEAbgB0ACAAbABpAGMAZQBuAHMAZQAgAGMAbwBtAG0AZQBuAHQAIAB0AGgAYQB0ACAAZwBvAGUAcwAgAGEAdAAgAHQAaABlACAAdABvAHAAIABvAGYAIAB0AGgAZQAgAGYAaQBsAGUACgAqAC8ACgBpAG0AcABvAHIAdAAgAGMAIABmAHIAbwBtACAAJwAuAC8AYwAuAGoAcwAnAAoAaQBtAHAAbwByAHQAIABhACAAZgByAG8AbQAgACcALgAvAGEALgBqAHMAJwAKAGkAbQBwAG8AcgB0ACAAYgAgAGYAcgBvAG0AIAAnAC4ALwBiAC4AagBzACcACgA%3D

### What happened?

1. visit the playground link
2. click on the "import sorting" tab

### Expected result

The comment on line 1 of the file stays on line 1; imports are sorted below the comment.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
This isn't a bug, it works as expected because the comment belongs to the import that is being moved.

If you wish to keep at the bottom, add two newlines: https://biomejs.dev/analyzer/import-sorting/#grouped-imports
