### ISSUE TITLE
🐛 Formatter inserts syntax errors in TypeScript `import()` types since 1.9.4

### ISSUE THREAD

**Issue by simon-paris** [biomejs/biome#4421]
### Environment information

```block
CLI:
  Version:                      1.9.4
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v22.8.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/1.22.22"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    true
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

The JS import statement (JsImportCallExpression) allows a trailing comma after the import path, the typescript import statement (TsImportType) does not.

Since 1.9.4, the formatter will insert trailing commas after long import paths, causing syntax errors.

It was likely introduced here: https://github.com/biomejs/biome/pull/3462.

Playground link: https://biomejs.dev/playground/?code=LwAvACAAbwBrACAALQAgAHQAcgBhAGkAbABpAG4AZwAgAGMAbwBtAG0AYQAgAGkAcwAgAGEAbABsAG8AdwBlAGQAIABoAGUAcgBlAAoAYwBvAG4AcwB0ACAAYQAgAD0AIABpAG0AcABvAHIAdAAoACIALgAvAHAAYQB0AGgAIgAsACkALgBkAGUAZgBhAHUAbAB0AAoACgAvAC8AIABpAG4AYwBvAHIAcgBlAGMAdAAgAC0AIAB0AHIAYQBpAGwAaQBuAGcAIABjAG8AbQBtAGEAIABoAGUAcgBlACAAcwBoAG8AdQBsAGQAIABiAGUAIABhACAAcwB5AG4AdABhAHgAIABlAHIAcgBvAHIACgB0AHkAcABlACAAYgAgAD0AIAB0AHkAcABlAG8AZgAgAGkAbQBwAG8AcgB0ACgAIgAuAC8AcABhAHQAaAAiACwAKQAuAGQAZQBmAGEAdQBsAHQACgAKAC8ALwAgAGkAbgBjAG8AcgByAGUAYwB0ACAALQAgAGYAbwByAG0AYQB0AHQAZQByACAAaQBuAHMAZQByAHQAcwAgAGEAIABzAHkAbgB0AGEAeAAgAGUAcgByAG8AcgAKAHQAeQBwAGUAIABjACAAPQAgAHQAeQBwAGUAbwBmACAAaQBtAHAAbwByAHQAKAAiAC4ALwBsAG8AbgBnAC8AbABvAG4AZwAvAGwAbwBuAGcALwBsAG8AbgBnAC8AbABvAG4AZwAvAGwAbwBuAGcALwBsAG8AbgBnAC8AbABvAG4AZwAvAHAAYQB0AGgALwBsAG8AbgBnAC8AbABvAG4AZwAvAGwAbwBuAGcALwBsAG8AbgBnAC8AcABhAHQAaAAiACkALgBkAGUAZgBhAHUAbAB0AAoA

### Expected result

Parsing the arguments as JsCallArgumentList is correct for JsImportCallExpression, but not for TsImportType. Typescript parses it completely differently, even though it looks the same.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by simon-paris** [comment]
Ooops, I see this is a duplicate of #4334

**Comment by fireairforce** [comment]
i got it, i will update the `ungram` here, thanks for your feedback, it's very useful for me.
