### ISSUE TITLE
💅 correctness/noConstructorReturn rule seems to conflict with singleton pattern use case

### ISSUE THREAD

**Issue by mpacary** [biomejs/biome#4453]
### Environment information

```bash
CLI:
  Version:                      1.9.4
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v18.19.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/9.2.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  JavaScript enabled:           true
  JSON enabled:                 true
  CSS enabled:                  true
  GraphQL enabled:              false
  Recommended:                  true
  All:                          false
  Enabled rules:
  performance/noDelete
  suspicious/noCatchAssign
  suspicious/noUnsafeNegation
  complexity/useLiteralKeys
  style/useImportType
  complexity/noMultipleSpacesInRegularExpressionLiterals
  a11y/useValidLang
  complexity/noUselessEmptyExport
  suspicious/useNamespaceKeyword
  suspicious/useValidTypeof
  a11y/useValidAriaRole
  correctness/noConstantCondition
  a11y/useAriaActivedescendantWithTabindex
  suspicious/noAssignInExpressions
  style/useDefaultParameterLast
  complexity/noEmptyTypeParameters
  correctness/noConstructorReturn
  style/useSelfClosingElements
  suspicious/noDuplicateParameters
  suspicious/noDuplicateSelectorsKeyframeBlock
  correctness/noUnknownProperty
  style/useTemplate
  correctness/noUnusedLabels
  complexity/noUselessTernary
  correctness/noUnreachableSuper
  suspicious/noCompareNegZero
  suspicious/noExplicitAny
  correctness/noSwitchDeclarations
  a11y/noAutofocus
  correctness/noUnsafeOptionalChaining
  correctness/noConstAssign
  suspicious/noControlCharactersInRegex
  complexity/noUselessTypeConstraint
  style/noVar
  suspicious/noDoubleEquals
  suspicious/noRedundantUseStrict
  style/useLiteralEnumMembers
  suspicious/noGlobalIsNan
  suspicious/noEmptyInterface
  suspicious/noConstEnum
  suspicious/noMisleadingCharacterClass
  correctness/noPrecisionLoss
  a11y/noLabelWithoutControl
  suspicious/noRedeclare
  correctness/noStringCaseMismatch
  correctness/noSetterReturn
  correctness/noInvalidConstructorSuper
  suspicious/noImplicitAnyLet
  suspicious/noFallthroughSwitchClause
  suspicious/noUnsafeDeclarationMerging
  correctness/noUnreachable
  a11y/useKeyWithClickEvents
  suspicious/noDuplicateObjectKeys
  complexity/noUselessThisAlias
  complexity/noThisInStatic
  complexity/useOptionalChain
  correctness/noInnerDeclarations
  style/noParameterAssign
  suspicious/noDuplicateCase
  a11y/useValidAnchor
  complexity/useRegexLiterals
  correctness/noSelfAssign
  correctness/noInvalidBuiltinInstantiation
  style/noUselessElse
  style/useShorthandFunctionType
  suspicious/noShadowRestrictedNames
  correctness/noInvalidDirectionInLinearGradient
  suspicious/noImportantInKeyframe
  a11y/useMediaCaption
  complexity/noUselessLabel
  complexity/noUselessCatch
  correctness/noUnsafeFinally
  a11y/useAriaPropsForRole
  correctness/noNonoctalDecimalEscape
  style/useEnumInitializers
  a11y/useHtmlLang
  suspicious/noDuplicateTestHooks
  complexity/noStaticOnlyClass
  style/useWhile
  complexity/useArrowFunction
  style/noInferrableTypes
  a11y/noNoninteractiveTabindex
  complexity/useSimpleNumberKeys
  correctness/useYield
  a11y/noInteractiveElementToNoninteractiveRole
  style/useNumericLiterals
  correctness/noUnnecessaryContinue
  suspicious/noApproximativeNumericConstant
  suspicious/noImportAssign
  suspicious/noLabelVar
  correctness/noGlobalObjectCalls
  suspicious/useDefaultSwitchClauseLast
  a11y/useAltText
  correctness/noEmptyCharacterClassInRegex
  correctness/noUnknownUnit
  suspicious/noSparseArray
  a11y/useIframeTitle
  complexity/noBannedTypes
  a11y/noSvgWithoutTitle
  correctness/noVoidElementsWithChildren
  style/useAsConstAssertion
  correctness/useJsxKeyInIterable
  style/useExportType
  complexity/noUselessLoneBlockStatements
  suspicious/noDebugger
  a11y/useValidAriaValues
  style/noArguments
  suspicious/noCommentText
  a11y/useFocusableInteractive
  correctness/noUnmatchableAnbSelector
  suspicious/noGlobalAssign
  suspicious/noDuplicateJsxProps
  suspicious/noMisleadingInstantiator
  a11y/noPositiveTabindex
  correctness/noEmptyPattern
  complexity/noExcessiveNestedTestSuites
  security/noDangerouslySetInnerHtmlWithChildren
  a11y/useKeyWithMouseEvents
  suspicious/noExtraNonNullAssertion
  suspicious/noPrototypeBuiltins
  correctness/noRenderReturnValue
  correctness/useExhaustiveDependencies
  security/noGlobalEval
  style/noNonNullAssertion
  a11y/noRedundantRoles
  complexity/useFlatMap
  correctness/useIsNan
  style/useConst
  suspicious/noGlobalIsFinite
  suspicious/noSelfCompare
  suspicious/noShorthandPropertyOverrides
  suspicious/noAsyncPromiseExecutor
  suspicious/noDuplicateFontNames
  suspicious/noThenProperty
  suspicious/useGetterReturn
  security/noDangerouslySetInnerHtml
  style/useNodejsImportProtocol
  a11y/noDistractingElements
  suspicious/noArrayIndexKey
  complexity/noWith
  suspicious/noDuplicateClassMembers
  complexity/noExtraBooleanCast
  performance/noAccumulatingSpread
  a11y/useValidAriaProps
  a11y/noRedundantAlt
  correctness/noChildrenProp
  correctness/noUnknownFunction
  correctness/noInvalidPositionAtImportRule
  suspicious/noConfusingLabels
  suspicious/noSuspiciousSemicolonInJsx
  suspicious/noConfusingVoidType
  suspicious/noFocusedTests
  a11y/useButtonType
  a11y/useSemanticElements
  a11y/noAriaUnsupportedElements
  correctness/noInvalidGridAreas
  correctness/noFlatMapIdentity
  a11y/noBlankTarget
  a11y/useHeadingContent
  correctness/useValidForDirection
  correctness/noVoidTypeReturn
  correctness/noInvalidUseBeforeDeclaration
  a11y/noAriaHiddenOnFocusable
  a11y/useGenericFontNames
  correctness/noUnknownMediaFeatureName
  a11y/useAnchorContent
  complexity/noUselessRename
  style/useNumberNamespace
  complexity/noUselessConstructor
  a11y/noAccessKey
  style/useExponentiationOperator
  style/noUnusedTemplateLiteral
  complexity/noUselessSwitchCase
  style/useSingleVarDeclarator
  suspicious/noExportsInTest
  a11y/noNoninteractiveElementToInteractiveRole
  style/noCommaOperator
  suspicious/noDuplicateAtImportRules
  suspicious/useIsArray
  a11y/noHeaderScope
  complexity/noUselessFragments
  suspicious/noMisrefactoredShorthandAssign
  complexity/noForEach
  suspicious/noClassAssign
  suspicious/noEmptyBlock
  suspicious/noFunctionAssign

Workspace:
  Open Documents:               0
```

### Rule name

correctness/noConstructorReturn

### Playground link

https://biomejs.dev/playground/?indentStyle=space&code=YwBsAGEAcwBzACAATQB5AEMAbABhAHMAcwAgAHsACgAgACAAYwBvAG4AcwB0AHIAdQBjAHQAbwByACgAKQAgAHsACgAgACAAIAAgAGkAZgAgACgATQB5AEMAbABhAHMAcwAuAF8AaQBuAHMAdABhAG4AYwBlACkAIAB7AAoAIAAgACAAIAAgACAAcgBlAHQAdQByAG4AIABNAHkAQwBsAGEAcwBzAC4AXwBpAG4AcwB0AGEAbgBjAGUAOwAKACAAIAAgACAAfQAKACAAIAAgACAATQB5AEMAbABhAHMAcwAuAF8AaQBuAHMAdABhAG4AYwBlACAAPQAgAHQAaABpAHMAOwAKAAoAIAAgACAAIAAvAC8AIAAuAC4ALgAgAFkAbwB1AHIAIAByAGUAcwB0ACAAbwBmACAAdABoAGUAIABjAG8AbgBzAHQAcgB1AGMAdABvAHIAIABjAG8AZABlACAAZwBvAGUAcwAgAGEAZgB0AGUAcgAgAHQAaABpAHMACgAgACAAfQAKAH0ACgAKAGMAbwBuAHMAdAAgAGkAbgBzAHQAYQBuAGMAZQBPAG4AZQAgAD0AIABuAGUAdwAgAE0AeQBDAGwAYQBzAHMAKAApADsACgBjAG8AbgBzAHQAIABpAG4AcwB0AGEAbgBjAGUAVAB3AG8AIAA9ACAAbgBlAHcAIABNAHkAQwBsAGEAcwBzACgAKQA7AAoACgBjAG8AbgBzAG8AbABlAC4AbABvAGcAKABpAG4AcwB0AGEAbgBjAGUATwBuAGUAIAA9AD0APQAgAGkAbgBzAHQAYQBuAGMAZQBUAHcAbwApADsAIAAvAC8AIABMAG8AZwBzACAAIgB0AHIAdQBlACIACgA%3D

### Expected result

When looking at [solutions to implement Singleton pattern in Javascript](https://stackoverflow.com/questions/1479319/simplest-cleanest-way-to-implement-a-singleton-in-javascript), returning the existing instance (if it exists) in the constructor is often suggested and seems a valid use case.

Currently, **correctness/noConstructorReturn** rule **prevents returning with a value in any case** and states "_Returning a value from a constructor is ignored_".

**Expected:** (suggestion)
- No error for such "Singleton pattern" use cases, though it may be hard to differentiate them from other situations
- In any case, adapting the statement "_Returning a value from a constructor is ignored_", which seems inaccurate. After some testing, whether the value is ignored depends on the type of the returned value. For example, if you put `return { foo: "bar" };` in the constructor, that object is actually returned by the `new MyClass()` instruction.

**Note:** a workaround satisfying the **noConstructorReturn** rule consists in retrieving the instance with a static `getInstance()` method, which gives `const instance = MyClass.getInstance();`. However the constructor method then must prevent using `const instance = new MyClass();` by mistake.

Would an approach like this be recommended & documented, from Biome team standpoint?
```
class MyClass {
  static #instance;

  constructor() {
    // prevent constructor from being called directly
    const getInstanceMethodName = "MyClass.getInstance";
    if (getCaller() !== getInstanceMethodName) {
      throw new Error(`You must retrieve the singleton instance by calling ${getInstanceMethodName}()`);
    }
    MyClass.#instance = this;
  }

  static getInstance() {
    if (MyClass.#instance) {
      return MyClass.#instance;
    }
    return new MyClass();
  }
}

// inspired from https://stackoverflow.com/a/57023880/488666
function getCaller() {
  return (new Error()).stack?.split("\n")[3]?.trim().split(" ")[1];
}

try {
  const instanceOne = MyClass.getInstance();
  const instanceTwo = MyClass.getInstance();
  console.log(instanceOne === instanceTwo); // Logs "true"
  
  const wrongInstance = new MyClass(); // throws an error
  console.log(wrongInstance);
} catch (err) {
  console.error(err);
}
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by arendjr** [comment]
Let me preface this by responding to this:

> adapting the statement "Returning a value from a constructor is ignored", which seems inaccurate

Agreed, I think we should improve our diagnostics here.

---

Now, it took a little bit to respond properly to the singleton request. There's a few ways I think we can resolve this, though I believe none of them should change how the rule works. The reason for this is there are many ways of implementing the singleton pattern, especially if we let go of the rigidity with which it was originally implemented in Java. I'll try to cover a few...

## Using module state

The first is the simplest, and relies upon the realization that JavaScript, unlike Java, has proper modules:

```js
let privateState;

export function publicFunction() {
    // Do stuff with `privateState`.
}
```

There are no classes, so no instances, but we get all the benefits that singletons provide: convenient access to functions that operate on private state.

It also shares the same downside as a singleton: If you try to unit test code that directly calls `publicFunction()`, you'll find that you cannot inject it anymore, so mocking becomes harder.

## Using a class and an instance function

```js
let instance;

export function getMyInstance() {
    if (!instance) {
        instance = new MyClass();
    }
    return instance;
}

class MyClass {
    #privateState;

    publicMethod() {
        // Do stuff with `#privateState`.
    }
}
```

This adds quite some ceremony to the previous example, and the benefit is dubious. After all, the point of a singleton is that you _don't_ pass the instances around since there's only one. But in this example you can see how it looks more like the classic singleton pattern from Java.

One advantage this approach still has is that `MyClass` cannot be constructed by code outside the module, since it's never exported.

## Using a class with a static instance method

The previous example could also be rewritten using a static instance method:

```js
export class MyClass {
    static #instance;

    #privateState;

    static getInstance() {
        if (!MyClass.#instance) {
            MyClass.#instance = new MyClass();
        }
        return MyClass.#instance;
    }

    publicMethod() {
        // Do stuff with `#privateState`.
    }
}
```

Personally I find `static` to be mostly a redundant concept in JavaScript, since as the previous example shows, we already have module-level variables that can do the same thing. But I understand some people like them for familiarity reasons, or because they feel it connects the variable to the class more.

Unfortunately, this example has another downside compared to the previous example: Code outside the module can now use `new MyClass()` to create instances, which is what we don't want.

If you use TypeScript, that disadvantage is easily remedied by adding a `private constructor() {}`, but if you use plain JS you can't. At the same time, if you use plain JS, you don't have static typing either, so I guess it's par for the course.

## Using a class with a static instance method and a guarded constructor

But if you really insist on using plain JavaScript _and_ also on using static methods _and_ guarding the constructor, you can do so like this:

```js
export class MyClass {
    static #instance;
    static #instantiating = false;

    #privateState;

    static getInstance() {
        if (!MyClass.#instance) {
            MyClass.#instantiating = true;
            MyClass.#instance = new MyClass();
        }
        return MyClass.#instance;
    }

    constructor() {
        if (!MyClass.#instantiating) {
            throw new Error("Use MyClass.getInstance() instead");
        }
        MyClass.#instantiating = false;
    }

    publicMethod() {
        // Do stuff with `#privateState`.
    }
}
```

---

As we can see, there's many ways to skin a cat, but notably, none of these interfere with the `noConstructorReturn` rule.

My personal recommendation would be to stick with the first example, but depending on your needs/wants you can scale it up as desired.

There's a few things I would explicitly recommend *against* though:

> returning the existing instance (if it exists) in the constructor is often suggested and seems a valid use case

I would recommend against this because it changes the semantics of the constructor. Suddenly `new MyClass()` doesn't return a _new_ instance anymore. That's misleading your caller.

> ```function getCaller() {
>   return (new Error()).stack?.split("\n")[3]?.trim().split(" ")[1];
> }```

I would recommend against relying on stack traces for such use cases, because implementations are engine-specific.

**Comment by Conaclos** [comment]
Great write-up @arendjr! I agree with your point. I never see the pattern of returning a singleton in the constructor and I found it puzzling. `new Something` should always return a new instance. If you want to prevent usage of the constructor, the class could be kept private (not exported). If you use TypeScript, the constructor could be marked as private, ...

We could indeed improve the diagnostic and the documentation.

**Comment by mpacary** [comment]
Many thanks @arendjr for your detailed explanations and providing sensible options for implementing the singleton pattern while keeping constructor semantics unchanged 👍

**Comment by arendjr** [comment]
Updated the diagnostic here: https://github.com/biomejs/biome/pull/4492

Also made a blog post out of my recommendation, since I figured it might be nice for a wider audience :) https://arendjr.nl/blog/2024/11/singletons-in-javascript/

**Comment by Conaclos** [comment]
@arendjr We could add a note about this in the rule description and maybe a link to your blog post or any relevant material.

**Comment by arendjr** [comment]
Yeah, that’s a nice idea!
