### ISSUE TITLE
📎 organizeImports: node > npm > absolute > relative

### ISSUE THREAD

**Issue by lcswillems** [biomejs/biome#449]
### Description

Right now organizeImports sorts are based on alphabetical order. That's already great, but I think it doesn't satisfy most of projects need.

In my case I would like:

- first, node imports (starting with "node:")
- then, npm imports
- then, absolute imports
- then, relative imports

This is the only thing retaining me from using Biome. I am still using ESLint because of this and everytime I setup a new project, setting up ESLint is a nightmare. I hope this could be fixed soon and I could start using Biome

**Comment by lcswillems** [comment]
Completely missed this! :open_mouth: 

The only thing here is the absolute / relative imports.

How are they handled?

**Comment by lcswillems** [comment]
@Conaclos I see nothing about this in the documentation.

**Comment by Conaclos** [comment]
Not sure. I think absolute imports appear before relative imports, because `/` precedes `./`.

**Comment by lcswillems** [comment]
By absolute, I mean that in the `tsconfig.json`, you can put `"baseUrl": "./src"` and then if you do:

```
import x from "myfolder";
```

It will import from "./src/myfolder".

I am trying on the playground. Absolute imports seems to come before relative imports. However, it seems that import from npm packages might not come before absolute imports?

![image](https://github.com/biomejs/biome/assets/5437552/ec47af17-5149-4837-80fb-375fcddf2401)

**Comment by Conaclos** [comment]
> By absolute, I mean that in the tsconfig.json, you can put "baseUrl": "./src"

Biome doesn't read `tsconfig.json` or `package.json`. And I think it is not a good idea to do so because the behavior could depend on these files.

> However, it seems that import from npm packages might not necessarily come before absolute imports?

I think the order is as follows:

- `node:`
- `npm:`
- URLs
- bare names such as "my-module"
- Absolute and relative paths (absolute path starts with `/` and come first)

**Comment by lcswillems** [comment]
This is my eslint config at the moment:

```
{
  "plugins": ["prettier"],
  "extends": ["next", "prettier"],
  "rules": {
    "import/no-duplicates": "error",
    "import/order": [
      "error",
      {
        "groups": [
          "builtin",
          "external",
          "internal",
          "parent",
          "sibling",
          "index"
        ],
        "pathGroups": [
          {
            "pattern": "~*/**",
            "group": "internal",
            "position": "before"
          },
          {
            "pattern": "$*/**",
            "group": "internal",
            "position": "before"
          }
        ],
        "alphabetize": {
          "order": "asc"
        }
      }
    ],
    "no-useless-rename": "error",
    "object-shorthand": "error",
    "prettier/prettier": "error",
    "react-hooks/exhaustive-deps": "off",
    "react/jsx-curly-brace-presence": "error",
    "react/no-unescaped-entities": "off"
  }
}
```

**Comment by ematipico** [comment]
> It is important that import {} from "myfolder" comes after import {} from "next" to avoid mistakening myfolder for a true npm package

What if a folder clashes with the name of a package? Regardless, we can't provide this at the moment because Biome doesn't use the `tsconfig.json` yet. 

I can't give you a timeline because we haven't published a roadmap yet, but I **assure you** that we _plan_ to integrate Biome with some parts of TS. 

I advise you to open a GitHub discussion and hopefully, other people will upvote it. We will consider it when we will start planning a roadmap.

**Comment by lcswillems** [comment]
@SuperchupuDev I didn't know, thanks! :pray: @ematipico Are `paths` supported by Biome?

**Comment by ematipico** [comment]
> @SuperchupuDev I didn't know, thanks! 🙏 @ematipico Are `paths` supported by Biome?

From https://github.com/biomejs/biome/issues/449#issuecomment-1742587086

> Regardless, we can't provide this at the moment because Biome doesn't use the tsconfig.json yet.

**Comment by Conaclos** [comment]
We could place `#import` (the ones that start with `#`) just before local imports because it is recognized as a [special import](https://nodejs.org/api/packages.html#subpath-imports).  @lcswillems Could this solve your issue?

**Comment by Conaclos** [comment]
> We could place `#import` (the ones that start with `#`) just before local imports because it is recognized as a [special import](https://nodejs.org/api/packages.html#subpath-imports). @lcswillems Could this solve your issue?

@arendjr Any thoughts?

**Comment by arendjr** [comment]
Wasn't aware of the special import syntax. Seems good to add indeed :+1: Agreed they should go between the library imports and the relative imports.

**Comment by lcswillems** [comment]
In my codebase, I rather use "$import" and "~import", but I could rename to #import. Also, in eslint, I can say what names have the special imports.

**Comment by lcswillems** [comment]
Thanks for the great work @Conaclos !! :pray:
