### ISSUE TITLE
💅 Nest.js app breaks with useImportType rule

### ISSUE THREAD

**Issue by aak-lear** [biomejs/biome#4514]
### Environment information

```bash
CLI:
  Version:                      1.9.4
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.10.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Linter:
  JavaScript enabled:           true
  JSON enabled:                 true
  CSS enabled:                  true
  GraphQL enabled:              false
  Recommended:                  true
  All:                          false
  Enabled rules:
  performance/noDelete
  suspicious/noCatchAssign
  suspicious/noUnsafeNegation
  complexity/useLiteralKeys
  style/useImportType
  complexity/noMultipleSpacesInRegularExpressionLiterals
  a11y/useValidLang
  complexity/noUselessEmptyExport
  suspicious/useNamespaceKeyword
  suspicious/useValidTypeof
  a11y/useValidAriaRole
  correctness/noConstantCondition
  a11y/useAriaActivedescendantWithTabindex
  suspicious/noAssignInExpressions
  style/useDefaultParameterLast
  complexity/noEmptyTypeParameters
  correctness/noConstructorReturn
  style/useSelfClosingElements
  suspicious/noDuplicateParameters
  suspicious/noDuplicateSelectorsKeyframeBlock
  correctness/noUnknownProperty
  style/useTemplate
  correctness/noUnusedLabels
  complexity/noUselessTernary
  correctness/noUnreachableSuper
  suspicious/noCompareNegZero
  suspicious/noExplicitAny
  correctness/noSwitchDeclarations
  a11y/noAutofocus
  correctness/noUnsafeOptionalChaining
  correctness/noConstAssign
  suspicious/noControlCharactersInRegex
  complexity/noUselessTypeConstraint
  style/noVar
  suspicious/noDoubleEquals
  suspicious/noRedundantUseStrict
  style/useLiteralEnumMembers
  suspicious/noGlobalIsNan
  suspicious/noEmptyInterface
  suspicious/noConstEnum
  suspicious/noMisleadingCharacterClass
  correctness/noPrecisionLoss
  a11y/noLabelWithoutControl
  suspicious/noRedeclare
  correctness/noStringCaseMismatch
  correctness/noSetterReturn
  correctness/noInvalidConstructorSuper
  suspicious/noImplicitAnyLet
  suspicious/noFallthroughSwitchClause
  suspicious/noUnsafeDeclarationMerging
  correctness/noUnreachable
  a11y/useKeyWithClickEvents
  suspicious/noDuplicateObjectKeys
  complexity/noUselessThisAlias
  complexity/noThisInStatic
  complexity/useOptionalChain
  correctness/noInnerDeclarations
  style/noParameterAssign
  suspicious/noDuplicateCase
  a11y/useValidAnchor
  complexity/useRegexLiterals
  correctness/noSelfAssign
  correctness/noInvalidBuiltinInstantiation
  style/noUselessElse
  style/useShorthandFunctionType
  suspicious/noShadowRestrictedNames
  correctness/noInvalidDirectionInLinearGradient
  suspicious/noImportantInKeyframe
  a11y/useMediaCaption
  complexity/noUselessLabel
  complexity/noUselessCatch
  correctness/noUnsafeFinally
  a11y/useAriaPropsForRole
  correctness/noNonoctalDecimalEscape
  style/useEnumInitializers
  a11y/useHtmlLang
  suspicious/noDuplicateTestHooks
  complexity/noStaticOnlyClass
  style/useWhile
  complexity/useArrowFunction
  style/noInferrableTypes
  a11y/noNoninteractiveTabindex
  complexity/useSimpleNumberKeys
  correctness/useYield
  a11y/noInteractiveElementToNoninteractiveRole
  style/useNumericLiterals
  correctness/noUnnecessaryContinue
  suspicious/noApproximativeNumericConstant
  suspicious/noImportAssign
  suspicious/noLabelVar
  correctness/noGlobalObjectCalls
  suspicious/useDefaultSwitchClauseLast
  a11y/useAltText
  correctness/noEmptyCharacterClassInRegex
  correctness/noUnknownUnit
  suspicious/noSparseArray
  a11y/useIframeTitle
  complexity/noBannedTypes
  a11y/noSvgWithoutTitle
  correctness/noVoidElementsWithChildren
  style/useAsConstAssertion
  correctness/useJsxKeyInIterable
  style/useExportType
  complexity/noUselessLoneBlockStatements
  suspicious/noDebugger
  a11y/useValidAriaValues
  style/noArguments
  suspicious/noCommentText
  a11y/useFocusableInteractive
  correctness/noUnmatchableAnbSelector
  suspicious/noGlobalAssign
  suspicious/noDuplicateJsxProps
  suspicious/noMisleadingInstantiator
  a11y/noPositiveTabindex
  correctness/noEmptyPattern
  complexity/noExcessiveNestedTestSuites
  security/noDangerouslySetInnerHtmlWithChildren
  a11y/useKeyWithMouseEvents
  suspicious/noExtraNonNullAssertion
  suspicious/noPrototypeBuiltins
  correctness/noRenderReturnValue
  correctness/useExhaustiveDependencies
  security/noGlobalEval
  style/noNonNullAssertion
  a11y/noRedundantRoles
  complexity/useFlatMap
  correctness/useIsNan
  style/useConst
  suspicious/noGlobalIsFinite
  suspicious/noSelfCompare
  suspicious/noShorthandPropertyOverrides
  suspicious/noAsyncPromiseExecutor
  suspicious/noDuplicateFontNames
  suspicious/noThenProperty
  suspicious/useGetterReturn
  security/noDangerouslySetInnerHtml
  style/useNodejsImportProtocol
  a11y/noDistractingElements
  suspicious/noArrayIndexKey
  complexity/noWith
  suspicious/noDuplicateClassMembers
  complexity/noExtraBooleanCast
  performance/noAccumulatingSpread
  a11y/useValidAriaProps
  a11y/noRedundantAlt
  correctness/noChildrenProp
  correctness/noUnknownFunction
  correctness/noInvalidPositionAtImportRule
  suspicious/noConfusingLabels
  suspicious/noSuspiciousSemicolonInJsx
  suspicious/noConfusingVoidType
  suspicious/noFocusedTests
  a11y/useButtonType
  a11y/useSemanticElements
  a11y/noAriaUnsupportedElements
  correctness/noInvalidGridAreas
  correctness/noFlatMapIdentity
  a11y/noBlankTarget
  a11y/useHeadingContent
  correctness/useValidForDirection
  correctness/noVoidTypeReturn
  correctness/noInvalidUseBeforeDeclaration
  a11y/noAriaHiddenOnFocusable
  a11y/useGenericFontNames
  correctness/noUnknownMediaFeatureName
  a11y/useAnchorContent
  complexity/noUselessRename
  style/useNumberNamespace
  complexity/noUselessConstructor
  a11y/noAccessKey
  style/useExponentiationOperator
  style/noUnusedTemplateLiteral
  complexity/noUselessSwitchCase
  style/useSingleVarDeclarator
  suspicious/noExportsInTest
  a11y/noNoninteractiveElementToInteractiveRole
  style/noCommaOperator
  suspicious/noDuplicateAtImportRules
  suspicious/useIsArray
  a11y/noHeaderScope
  complexity/noUselessFragments
  suspicious/noMisrefactoredShorthandAssign
  complexity/noForEach
  suspicious/noClassAssign
  suspicious/noEmptyBlock
  suspicious/noFunctionAssign
```

### Rule name

lint/style/useImportType

### Playground link

https://github.com/aak-lear/biome-repro

### Expected result

When you setup the **Biome** in **Nest.js** app and `useImportType` rule is enabled, app breaks after linting.

The reason is **Biome** rewrites imports for injectable classes and **Nest.js** can't resolve dependencies.

I attached the link to reproduction repository and the expected result for file `src/app.controller.ts` is:
```typescript
import { Controller, Get } from "@nestjs/common";
import { AppService } from "./app.service"; // This class is injectable and Nest want to use its instance, but Biome will rewrite this import as import type

@Controller()
export class AppController {
	constructor(private readonly appService: AppService) {}

	@Get()
	getHello(): string {
		return this.appService.getHello();
	}
}
```
### Why This Matters
**Nest.js** is a popular **Node.js** framework widely used in the TypeScript community. Importing injectable classes without import type is essential for the proper functioning of the **Nest.js** DI container. Currently, the `useImportType` rule in **Biome** does not support ignoring specific classes, forcing developers to either break the project's style guide or add rule suppressions at the code level.

### Suggested Improvement
Add a configuration option to useImportType that allows ignoring injectable classes. This could take the form of a new option, for example:
```json
{
  "linter": {
    "rules": {
      "style": {
        "useImportType": [
          "error",
          {
            "ignoreInjectableClasses": true
          }
        ]
      }
    }
  }
}

```

The `ignoreInjectableClasses` option would enable **Biome** to skip the `useImportType` rule for classes used in DI contexts (such as classes decorated with `@Injectable()` in **Nest.js**). This change would greatly simplify working with **Nest.js,** improving compatibility with the framework and reducing the need for line-level rule suppression.

This enhancement would allow developers to maintain a consistent project style defined by **Biome** and improve compatibility with popular frameworks like **Nest.js**, where injectable classes are necessary for proper functionality.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
@aak-lear, did you read the rule documentation?  [There's a paragraph specifically for NestJS projects](https://biomejs.dev/linter/rules/use-import-type/#caveat-with-typescript-experimental-decorators).

**Comment by aak-lear** [comment]
Apologies. It seems I missed the paragraph about NestJS.

I see that there’s currently no way to specify which classes can be injectable and used as value.

In that case, it is possible to add a rule to ignore all classes? With this option the rule would suggest using import type only for types and interfaces and can be compatible with NestJS.

**Comment by ematipico** [comment]
It wouldn't help anyway, because it would create false negatives for normal classes, forcing you to use yet another override.

This decision is in line with what the counterpart - eslint rule - did.

**Comment by jayalfredprufrock** [comment]
Was bummed to discover this issue as this is one of the linting rules I value the most. For the record, eslint's `consistent-type-imports` absolutely handles this correctly: https://github.com/typescript-eslint/typescript-eslint/pull/2751/files

I'm assuming biome's architecture precludes taking the approach eslint did? If not, and this is just a matter of priority/bandwidth, I'd be willing to contribute to or sponsor the effort. 

Sorry to beat a dead horse here...I realize biomejs can't meet everybody's needs perfectly while remaining so easy to setup, but nestjs is incredibly popular, and rules like `useImportType` have a  significant effect on dx and go a long way to help prevent needless circular dependencies.

**Comment by guigaoliveira** [comment]
@ematipico this breaks nestjs applications that will always use these decorators

**Comment by BoscoDomingo** [comment]
Same thing over here. Migrating a project from ESLint and Prettier I came across this bug which was kinda hard to debug.

For the time being, this is my suggestion as a workaround (far from perfect, but at least the rest of the code can retain the rule):
```json
"overrides": [
  {
    "includes": [
      "src/**/*.service.ts",
      "src/**/*.controller.ts"
    ],
    "linter": {
      "rules": {
        "style": {
          "useImportType": "off"
        }
      }
    }
  }
]
```

**Comment by mroswald** [comment]
>     "include": [
>       "src/**/*.service.ts",
>       "src/**/*.controller.ts"
>     ],

Should be "includes", right? https://biomejs.dev/reference/configuration/#overridesitemincludes

**Comment by Conaclos** [comment]
> Should be "includes", right?

Yes.
In Biome 1.x this was `include`/`ignore`.

**Comment by Liranius** [comment]
Actually there could be a much easier fix if we just focus on Nest.js. The "Injectables" usually have naming conventions and imported by "named import". So the rule can has an additional filter to justify which named imports are to be ignored. Example is as below:
```
{
  "linter": {
    "rules": {
      "style": {
        "useImportType": [
          "error",
          {
            "ignorePatterns": ["Dto$", "Service$"]
          }
        ]
      }
    }
  }
}
```

**Comment by michael-gillett** [comment]
This was the snippet I added in Biome v2 to get around this

```json
{
  "overrides": [
    {
      "includes": ["**/*.controller.ts", "**/*.service.ts"],
      "linter": {
        "rules": {
          "style": {
            "useImportType": "off"
          }
        }
      }
    }
  ]
}
```

**Comment by adamhemzal** [comment]
I'm using the plugin in VSCode and when I save, all my NestJS services becomes types which makes my NestJS app crash. I'm using this config but still the plugin automatically converts it even when I said I don't want it.

Do you guys found a solution to work automatically on save for NestJS?

I also get `Decorators are not valid here.biome(parse)` when using the VSCode plugin with manual / global installtion using `brew`

```
    "linter": {
      "rules": {
        "style": {
          "useImportType": "off"
        }
      }
    }
```

**Comment by ayoblt** [comment]
> I'm using the plugin in VSCode and when I save, all my NestJS services becomes types which makes my NestJS app crash. I'm using this config but still the plugin automatically converts it even when I said I don't want it.
> 
> Do you guys found a solution to work automatically on save for NestJS?
> 
> I also get `Decorators are not valid here.biome(parse)` when using the VSCode plugin with manual / global installtion using `brew`
> 
> ```
>     "linter": {
>       "rules": {
>         "style": {
>           "useImportType": "off"
>         }
>       }
>     }
> ```

You need to enable unsafeParameterDecoratorEnabled too. this worked for me
```
"javascript": {
    "formatter": {
      "quoteStyle": "single"
    },
    "parser": {
      "unsafeParameterDecoratorsEnabled": true
    }
  },
  "overrides": [
    {
      "includes": ["**/*.controller.ts", "**/*.service.ts"],
      "linter": {
        "rules": {
          "style": {
            "useImportType": "off"
          }
        }
      }
    }
  ]
```
