### ISSUE TITLE
🐛 noUselessFragments fix result has invalid jsx syntax

### ISSUE THREAD

**Issue by maxmorozoff** [biomejs/biome#4553]
### Environment information

```block
(edited)

CLI:
  Version:                      1.9.4

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Linter:
  JavaScript enabled:           true
  JSON enabled:                 true
  CSS enabled:                  true
  GraphQL enabled:              false
  Recommended:                  true
  All:                          false
```

### What happened?

[Open in Biome Playground](https://biomejs.dev/playground/?code=LwAvACAASQBuAHAAdQB0ADoACgA8AFMAdQBzAHAAZQBuAHMAZQAKAAkAZgBhAGwAbABiAGEAYwBrAD0AewAKAAkACQA8AD4ACgAJAAkACQA8AHMAcABhAG4APgBMAG8AYQBkAGkAbgBnAC4ALgAuADwALwBzAHAAYQBuAD4ACgAJAAkAPAAvAD4ACgAJAH0ACgA%2BAAoACQB7AGMAaABpAGwAZAByAGUAbgB9AAoAPAAvAFMAdQBzAHAAZQBuAHMAZQA%2BADsACgAvAC8AIABCAGkAbwBtAGUAIABmAGkAeAAgAG8AdQB0AHAAdQB0ADoACgA8AFMAdQBzAHAAZQBuAHMAZQAgAGYAYQBsAGwAYgBhAGMAawA9ADwAcwBwAGEAbgA%2BAEwAbwBhAGQAaQBuAGcALgAuAC4APAAvAHMAcABhAG4APgA%2BAAoACQB7AGMAaABpAGwAZAByAGUAbgB9AAoAPAAvAFMAdQBzAHAAZQBuAHMAZQA%2BADsACgAvAC8AIABFAHgAcABlAGMAdABlAGQAOgAKADwAUwB1AHMAcABlAG4AcwBlACAAZgBhAGwAbABiAGEAYwBrAD0AewA8AHMAcABhAG4APgBMAG8AYQBkAGkAbgBnAC4ALgAuADwALwBzAHAAYQBuAD4AfQA%2BAAoACQB7AGMAaABpAGwAZAByAGUAbgB9AAoAPAAvAFMAdQBzAHAAZQBuAHMAZQA%2BADsA)

#### Input
```jsx
<Suspense
	fallback={
		<>
			<span>Loading...</span>
		</>
	}
>
	{children}
</Suspense>;
```
#### Biome fix output

```jsx
<Suspense fallback=<span>Loading...</span>>
	{children}
</Suspense>;
```

### Issue Details
The fix removes the fragment but doesn't wrap the prop value in curly braces (`{}`). This results in invalid JSX syntax, as seen in the fix output above.

### Expected result

```jsx
<Suspense fallback={<span>Loading...</span>}>
	{children}
</Suspense>;
```

Should the formatter be responsible for fixing this, or is it a linter issue?

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by fireairforce** [comment]
i will fix this~
