### ISSUE TITLE
📎 Implement `lint/noMisrefactoredShorthandAssign` - `clippy/misrefactored_assign_op`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#456]
### Description

Clippy [misrefactored_assign_op](https://rust-lang.github.io/rust-clippy/master/#/misrefactored_assign_op).

Want to contribute? Lets us know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

The implementor may take some inspirations from [useShorthandAssign](https://biomejs.dev/linter/rules/use-shorthand-assign).

**Comment by Conaclos** [comment]
@victor-teles The rule could interest you because you recently implemented [useShorthandAssign](https://biomejs.dev/linter/rules/use-shorthand-assign).

**Comment by victor-teles** [comment]
@Conaclos Sure! I'll assign it to me

**Comment by victor-teles** [comment]
@Conaclos 

Is it possible to have more than one action for one diagnostic?

I was thinking of implementing something  like this:

#### With noShorthandAssign `off`

- Diagnostic of `a += a + b` should suggest a fix to `a += b`
- Diagnostic of `a += a + b` should suggest a fix to `a = a + b`

#### With noShorthandAssign `on`

- Diagnostic of `a += a + b` should suggest a fix to `a += b`
- ~~Diagnostic of `a += a + b` should suggest a fix to `a = a + b`~~

**Comment by Conaclos** [comment]
> Is it possible to have more than one action for one diagnostic?

In the past we had a rule with two actions. However, we decided to remove one action in order to have a single action for any situation. 

I think you can stick with your first proposal:

Diagnostic of `a += a + b` should suggest a fix to `a += b`.
