### ISSUE TITLE
🐛 Panic `internal error: entered unreachable code` in `lint/correctness/use_exhaustive_dependencies.rs`

### ISSUE THREAD

**Issue by qarmin** [biomejs/biome#4568]
### Environment information

```block
CLI:
  Version:                      1.9.4
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           unset
  JS_RUNTIME_NAME:              unset
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       unset

Workspace:
  Open Documents:               0
```

### What happened?

```
timeout -v 150 biome lint TEST___FILE.ts
```
crashes with
```
Source Location: crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs:610:13
Thread Name: biome::worker_1
Message: internal error: entered unreachable code
```

File - [compressed.zip](https://github.com/user-attachments/files/17796931/compressed.zip)

### Expected result

No crash

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by arendjr** [comment]
Thanks so much for the detailed reports! It may take us a bit to get back to all of them, but rest assured they're on our radar!

**Comment by dyc3** [comment]
In this case, Biome is failing to detect that `Point` is imported, so this is a bug in the semantic model. Specifically this line is returning false:

https://github.com/biomejs/biome/blob/4721b6c7852c2c58e417ab61d6f4fb761a073489/crates/biome_js_analyze/src/lint/correctness/use_exhaustive_dependencies.rs#L488

**Comment by dyc3** [comment]
In the sample, this line is getting parsed as `JS_BOGUS_STATEMENT`, and not `JS_IMPORT`:

```js
import type {Point} from '.geomet';
```
