### ISSUE TITLE
🐛 Biome crashes in latest version of Docker Desktop

### ISSUE THREAD

**Issue by ffMathy** [biomejs/biome#4612]
### Environment information

```block
`biome rage` can't run due to the bug, but it is latest Biome as of writing, and it is latest version of Docker Desktop on a Mac M1, running inside an `ubuntu:latest` Docker image.
```

### What happened?

<img width="473" alt="image" src="https://github.com/user-attachments/assets/c7c71e67-bee9-40fd-9341-bbf80eb9a14e">

The issue only happens on Macs with an ARM CPU such as M1, M3 etc. It only happened after the latest Docker update.

### Expected result

I expected Biome to work in ARM as well.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by nhedger** [comment]
We're going to need a way to reproduce this.

Please provide a minimal Dockerfile that reproduces this issue.

**Comment by ffMathy** [comment]
We can close this. Found out I installed the x64 release directly inside the container. Doh.
