### ISSUE TITLE
🐛 useNamingConvention matcher does not accept \$

### ISSUE THREAD

**Issue by edfenergy-SteveD** [biomejs/biome#4613]
### Environment information

```block
Biome 1.9.4
```

### What happened?

I'm trying to implement a matcher in useNamingConvention to align to an object member that begins with a dollar sign, using the regex `\$(.+)`, however it's not accepting the escaped $.

Can support for this be included in a future build please? We've got a number of api calls that use this format in our project and, at the moment, they're littered with biome-ignores.

### Expected result

`\$(.+)` is an acceptable matcher

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
This doesn't seem a bug but a feature request?

**Comment by edfenergy-SteveD** [comment]
@Conaclos - oh for goodness' sake, that was it. Thank you!
