### ISSUE TITLE
📝 Chained function are forced on new line when there is an operation as parameter

### ISSUE THREAD

**Issue by oom-** [biomejs/biome#4618]
### Environment information
_See playground link_

### Configuration
_See playground link_

### Issue 
When there is an operation in the parameter of the chained function, it's forced back to the beginning of the line instead of keeping it on the same line.

I think this issue could be related: https://github.com/biomejs/biome/issues/1039

![image](https://github.com/user-attachments/assets/c78d0785-5c2c-4618-a867-c4ac1226f1af)
![image](https://github.com/user-attachments/assets/a37a81ff-b04c-4c8a-b637-b07d021c8072)

### Playground links

With a `- 60` operation: 
https://biomejs.dev/playground/?lineWidth=120&indentStyle=space&trailingCommas=none&code=YwBvAG4AcwB0ACAAZQB4AHAAaQByAGEAdABpAG8AbgBEAGEAdABlACAAPQAgAGQAYQB5AGoAcwAoACkALgBhAGQAZAAoAHIAZQBzAHAAbwBuAHMAZQAuAGUAeABwAGkAcgBlAHMAXwBpAG4AIAAtACAANgAwACwAIAAiAHMAZQBjAG8AbgBkACIAKQAuAHUAbgBpAHgAKAApADsA

Without a `- 60` operation: 
https://biomejs.dev/playground/?lineWidth=120&indentStyle=space&trailingCommas=none&code=YwBvAG4AcwB0ACAAZQB4AHAAaQByAGEAdABpAG8AbgBEAGEAdABlACAAPQAgAGQAYQB5AGoAcwAoACkALgBhAGQAZAAoAHIAZQBzAHAAbwBuAHMAZQAuAGUAeABwAGkAcgBlAHMAXwBpAG4ALAAgACIAaQB0ACcAcwAgAG4AbwB0ACAAcAByAGkAbgB0AHcAaQBkAHQAaAAiACkALgB1AG4AaQB4ACgAKQA7AA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by arendjr** [comment]
In the playground links, you can see that Prettier's behavior is the same, so it looks to me like this is by design. If I'm not mistaken, the rationale is that there shouldn't be too much information on a single line.

**Comment by ematipico** [comment]
There are different heuristics inside a "member chain". One of them checks where the chain contains complex expressions, and if so, the whole chain goes on multiple lines regardless of the line width.
