### ISSUE TITLE
🐛 Incompatibility with tsconfig.json's `noPropertyAccessFromIndexSignature`

### ISSUE THREAD

**Issue by castarco** [biomejs/biome#463]
### Environment information

```block
CLI:
  Version:                      1.2.2
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.1.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.8.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0

Discovering running Biome servers...

Running Biome Server: ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

ℹ The client isn't connected to any server but rage discovered this running Biome server.

Server:
  Version:                      1.2.2
  Name:                         biome_lsp
  CPU Architecture:             aarch64
  OS:                           macos

Workspace:
  Open Documents:               0

Other Active Server Workspaces:

Workspace:
  Open Documents:               11
  Client Name:                  Visual Studio Code
  Client Version:               1.82.2
```

### What happened?

1. Enable the property [`noPropertyAccessFromIndexSignature`](https://www.typescriptlang.org/tsconfig#noPropertyAccessFromIndexSignature) in your `tsconfig.json` file.
2. Write the following code:

   ```typescript
   export const getCssFromNodeData = (
   	data?: Readonly<Record<string, unknown>>,
   ): string[] => {
   	return typeof data?.['v'] === 'number' && data['v'] % 2 === 0 ? ['even'] : []
   }
   ```
2. Run biome: `pnpm biome check ./src/`
3. See how it complains about the indexed access being too complex:
   ```
   ✖ The computed expression can be simplified without the use of a string literal.
   ```

### Expected result

Biome should accept that code, given that the TSC type checker will fail if we use `.v` instead of `['v']` (in the particular case where `v` is not a known property of the object that we are accessing).

`tsc` would fail with the following message if we used `.v`:
```
src/stories/treeFixtures.ts:17:22 - error TS4111: Property 'v' comes from an index signature, so it must be accessed with ['v'].
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
Hi! We are aware of the issue. For now, we are no table to read `tsconfig` and type info.

**Comment by castarco** [comment]
Hi @Conaclos . Is there any known/decided osth towards higher TS compatibility? any intermediate milestone that I could help to achieve?

Best regards.

**Comment by ematipico** [comment]
There's no plan yet, at least nothing official.

I know we will definitely interact with the tsconfig.json for some info, such as path aliases, but I doubt we will reach this low level of support.

For the time being you have the option to turn off the rule.

**Comment by lgarron** [comment]
Now that Biome is doing more semantic analysis of TypeScript, is there a chance this might be supported?

**Comment by arendjr** [comment]
We should be able to infer the type of `data` in the issue's description in most cases, so I think it is possible now. That said, it seems it would introduce quite a bit of complexity for a rule that's now very simple, and which does what it says it does.

So yeah, I guess it may be feasible, but I'm not entirely convinced we _should_ yet. In any case I don't consider it a bug, so we shouldn't reopen this issue. But feel free to open a discussion about it, and we can discuss more in-depth, hear other's opinions too.

**Comment by lgarron** [comment]
> So yeah, I guess it may be feasible, but I'm not entirely convinced we _should_ yet. In any case I don't consider it a bug, so we shouldn't reopen this issue. But feel free to open a discussion about it, and we can discuss more in-depth, hear other's opinions too.

Yeah, I don't expect this to be simple to implement, it's more of a nice-to-have for now. (Although it will lead to more and more Biome ignore comments for me over time.)

I'd be glad to open a discussion, but I think reopening this issue might be more appropriate in that case?

**Comment by arendjr** [comment]
We use discussions for all feature requests/suggestions, while issues are used for bugs (which I don't think this is). As you mention, this is more of a nice-to-have, so let's go with a new discussion.
