### ISSUE TITLE
📎 Clean up `WorkspaceError`

### ISSUE THREAD

**Issue by arendjr** [biomejs/biome#4668]
### Description

The `WorkspaceError` enum contains multiple variants that are never used. Examples are `ReportNotSerializable` and `DirtyWorkspace`, but there may be more. Any variant that is unused can be safely cleaned up from the repository.

**Comment by sikehish** [comment]
I'd like to take this up :)

**Comment by ematipico** [comment]
All yours @sikehish 

Feel free to ask any questions you have here

**Comment by sikehish** [comment]
Hi @ematipico . I've raised a PR #4681. Let me know if any other changes need to be made :)
