### ISSUE TITLE
Running code actions on save breaks imports

### ISSUE THREAD

**Issue by OliverJAsh** [biomejs/biome#4680]
### VS Code version

1.89.0

### Extension version

2.2.2

### Biome version

1.7.3

### Operating system

- [ ] Windows
- [X] macOS
- [ ] Linux

### Description

When `noUnusedImports` is enabled, running code actions on save (`source.organizeImports.biome` + `quickfix.biome`) is slow and breaks the imports.

### Steps to reproduce

Full reduced test case: https://github.com/OliverJAsh/biome-vscode-quickfix-import-issue/compare/1.7.3. Contents inlined below.

Given:

`biome.json`:
```json
{
    "$schema": "./node_modules/@biomejs/biome/configuration_schema.json",
    "linter": {
      "enabled": true,
      "rules": {
        "correctness": {
          "noUnusedImports": "warn"
        }
      }
    }
  }
  
```

`.vscode/settings.json`:
```json
{
  "editor.codeActionsOnSave": {
    "source.organizeImports.biome": "explicit",
    "quickfix.biome": "explicit"
  }
}

```

`index.ts`:
```ts
// @ts-nocheck

import * as APIClientError from 'app/services/api/APIClientError';
import { TPhotoSlug, Codec } from 'app/services/api/Photo/types/PhotoSlug';

APIClientError;
export type F = TPhotoSlug;

// edit this comment and save the file

```

When I save `index.ts` and "code actions on save" runs, I notice two things. Firstly, it feels much slower than I would expect it to be. It adds about 500ms-1s to the save operation (see screen recording below). Secondly, I end up with broken imports—this is similar to https://github.com/biomejs/biome-vscode/issues/179 although note here I'm using the latest version of Biome which—I understand from https://github.com/biomejs/biome/issues/688—is supposed to include the fix.

```ts
// @ts-nocheck

import * as APIClientError from 'app/services/api/APIClientError';
import { TPhotoStype lug } from 'app/services/api/Photo/types/PhotoSlug';

APIClientError;
export type F = TPhotoSlug;

// edit this comment and save the file

```

https://github.com/biomejs/biome/assets/921609/7b68b97b-47ef-465c-b387-78e1736a4dab

### Expected behavior

Save is fast + imports are not broken.

### Does this issue occur when using the CLI directly?

Not sure / Not applicable

**Comment by ematipico** [comment]
@OliverJAsh is it possible that there are multiple processes running? Try to check the task manager, or use `biome rage --daemon-logs`.

If so, kill the processes. This happens with the old version of the VSCode extension

**Comment by OliverJAsh** [comment]
Thanks for the reply @ematipico.

It doesn't seem like that's the case. I can only see one running server. I can also reproduce this issue after restarting my entire system, with no windows/applications open except for the reduced test case I shared.

Are you able to reproduce it using my test case?

**Comment by ematipico** [comment]
Yeah, I can consistently replicate the issue. However, this issue doesn't occur with other clients such as Zed.

**Comment by OliverJAsh** [comment]
I wonder if it's related to https://github.com/biomejs/biome-vscode/issues/229, because the corruption only seems to happen after the delay.

**Comment by ematipico** [comment]
I think so. On my machine I can see that VSCode applies the changes with a delay between the two of them, in fact if I use CTRL+Z, I can see states of the code I didn't have before. I need to hit 2/3 times before reverting the code to how it was.

I am mostly certain that this is a VSCode issue, which isn't able to batch the changes in a single one, and instead it queues them and eventually emits incorrect code.

**Comment by OliverJAsh** [comment]
This doesn't seem to be an issue when using `source.fixAll.biome` instead of `quickfix.biome`.

**Comment by ematipico** [comment]
@OliverJAsh can you close the issue?

**Comment by OliverJAsh** [comment]
Sure, but I think the documentation still needs to be updated to mention the new command.
