### ISSUE TITLE
🐛 Biome check hangs on Turborepo monorepo

### ISSUE THREAD

**Issue by SamuelSmeys** [biomejs/biome#4683]
### Environment information

```block
CLI:
  Version:                      1.9.4
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.16.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "npm/10.9.0"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

1. We recently transitioned to a monorepo (using Turborepo) 
2. As a part of this transition, we started using biomeJs as our linter & formatter
3. The first few npx biome check --write /. commands worked fine, but now it hangs on every run. 

### Expected result

npx biome check doesn't hang

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by arendjr** [comment]
Can you make a reproduction? I’m afraid we don’t have enough information to know what’s going on otherwise.

**Comment by SamuelSmeys** [comment]
Hi @arendjr, thanks for looking at this. I'll see if I can make one soon

**Comment by kevin-govassist** [comment]
@SamuelSmeys I was having this issue myself with your same setup (Turborepo + Biome). It turned out to be that Biome was looking into the `dist` folder that was created upon app build. I just updated `biome.json` to exclude the dist folder from it and it solved it.

Not saying it's your case but might we worth checking.
