### ISSUE TITLE
📎 Add support for new CSS at-rules

### ISSUE THREAD

**Issue by togami2864** [biomejs/biome#4685]
### Description

To enhance our CSS parsing capabilities, we need to add support for two new CSS at-rules
- [@position-try](https://developer.mozilla.org/en-US/docs/Web/CSS/@position-try)
- [@view-transition](https://developer.mozilla.org/en-US/docs/Web/CSS/@view-transition)

You can start around here
https://github.com/biomejs/biome/blob/d80805762cd1efdeaafd2e9d542270bfced8e8f4/xtask/codegen/src/css_kinds_src.rs#L231-L243

**Comment by orimay** [comment]
We may also want to support tailwindcss [at rules](https://tailwindcss.com/docs/functions-and-directives), including the ones from [v4](https://tailwindcss.com/docs/v4-beta)

**Comment by kevinmingtarja** [comment]
Hi, I'd love to contribute to this!

**Comment by ematipico** [comment]
All yours @kevinmingtarja , than you for your interest. Feel free to ask any question here or on discord
