### ISSUE TITLE
💅 `useExhaustiveDependencies` incorrectly requires React.useRef() to be specified when passed as a prop

### ISSUE THREAD

**Issue by carlosmfreitas2409** [biomejs/biome#4768]
### Environment information

```bash
CLI:
  Version:                      1.9.4
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_PATH:               unset
  BIOME_LOG_PREFIX_NAME:        unset
  BIOME_CONFIG_PATH:            unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "bun/1.1.40"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Linter:
  JavaScript enabled:           true
  JSON enabled:                 true
  CSS enabled:                  true
  GraphQL enabled:              false
  Recommended:                  true
  All:                          false

Workspace:
  Open Documents:
```

### Rule name

useExhaustiveDependencies

### Playground link

https://biomejs.dev/playground/?lintRules=all&code=aQBtAHAAbwByAHQAIABSAGUAYQBjAHQAIABmAHIAbwBtACAAJwByAGUAYQBjAHQAJwA7AAoACgBpAG4AdABlAHIAZgBhAGMAZQAgAFMAbwBtAGUAQwBvAG0AcABvAG4AZQBuAHQAUAByAG8AcABzACAAewAKACAAIABpAG4AcAB1AHQAUgBlAGYAOgAgAFIAZQBhAGMAdAAuAFIAZQBmAE8AYgBqAGUAYwB0ADwASABUAE0ATABJAG4AcAB1AHQARQBsAGUAbQBlAG4AdAA%2BAAoAfQAKAAoAZQB4AHAAbwByAHQAIABmAHUAbgBjAHQAaQBvAG4AIABTAG8AbQBlAEMAbwBtAHAAbwBuAGUAbgB0ACgAewAgAGkAbgBwAHUAdABSAGUAZgAgAH0AOgAgAFMAbwBtAGUAQwBvAG0AcABvAG4AZQBuAHQAUAByAG8AcABzACkAOgAgAFIAZQBhAGMAdAAuAFIAZQBhAGMAdABOAG8AZABlACAAewAKACAAIABSAGUAYQBjAHQALgB1AHMAZQBFAGYAZgBlAGMAdAAoACgAKQAgAD0APgAgAHsACgAgACAAIAAgAGkAbgBwAHUAdABSAGUAZgAuAGMAdQByAHIAZQBuAHQALgBjAGwAaQBjAGsAKAApADsACgAgACAAfQAsACAAWwBdACkAOwAKACAAIAAKACAAIAByAGUAdAB1AHIAbgAgAG4AdQBsAGwAOwAKAH0A

### Expected result

If I use a `ref` (`useRef`) that is sent as a parameter to a component and use it inside some react hook, the exhaustive deps breaks.

Throw error: `This hook does not specify all of its dependencies.`

```jsx
export function SomeComponent({ inputRef }) {
  React.useEffect(() => {
    inputRef.current.click();
  }, []);
  
  return null;
}
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by arendjr** [comment]
I believe this is not an issue with Biome, but rather a more fundamental issue with how React dependencies work. There’s no type information for Biome to recognize this is a ref, so it must assume the dependency needs to be listed. I believe ESLint has the same limitation.
