### ISSUE TITLE
📎 Implement `lint/useShorthandFunctionType` - `typescript-eslint/prefer-function-type`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#48]
### Description

[prefer-function-type](https://typescript-eslint.io/rules/prefer-function-type)

**Want to contribute?** Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by emab** [comment]
Hey @Conaclos I'd be happy to take a look at this one.

**Comment by Conaclos** [comment]
Assigned :)

**Comment by emab** [comment]
<img width="1417" alt="image" src="https://github.com/biomejs/biome/assets/8884999/d641c53b-5f7b-48c2-bd28-771fd539756f">

The eslint rule seems to show a slightly different message for the third example here... should we include this? I'm not sure if it feels a bit different from the rule we're trying to implement.

**Comment by emab** [comment]
@Conaclos hope you can help me here - is there a way of converting a `TsReturnTypeAnnotation` into `AnyTsType`? I'm attempting to get the lone function definition from the interface for the fix action.

**Comment by emab** [comment]
Aha, not sure what I was doing wrong but I've got it working! 😄

**Comment by emab** [comment]
> <img alt="image" width="1417" src="https://user-images.githubusercontent.com/8884999/278140714-d641c53b-5f7b-48c2-bd28-771fd539756f.png">
> The eslint rule seems to show a slightly different message for the third example here... should we include this? I'm not sure if it feels a bit different from the rule we're trying to implement.

@Conaclos what do you think about this? The returning of `this` doesn't seem to match the rule description as far as I can tell?

**Comment by emab** [comment]
I've opened a WIP PR for this, I found it quite difficult to get to where it is now, and I feel my code is a bit messy. Would love some feedback when you have time!

**Comment by Conaclos** [comment]
> The returning of this doesn't seem to match the rule description as far as I can tell?

I agree. I think we could just ignore a call signature that returns `this` or use `this` (or use `this` in the type annotation of one of its parameters).
