### ISSUE TITLE
🐛 `bunx biome --version` is different than `bun i && bunx biome --version`

### ISSUE THREAD

**Issue by yamcodes** [biomejs/biome#486]
**Edit:** I found the solution. `biome` is a different NPM package than `@biomejs/biome`. We should reflect that in the documentation by one of:
1. Instructing to use `bunx @biomejs/biome` everywhere we now instruct to use `bunx biome`.
2. Adding a warning that running Biome using `bunx` when Biome is not installed locally should be done with `bunx @biomejs/biome`.

---

### Environment information

```block
main
```

### What happened?

For some reason, running Biome commands straight from `bunx` using `bunx biome` (when `node_modules` does not exist) uses an older version of Biome, than the one installed using `bun i biome`.

## Reproduction

1. Remove `node_modules` if exists.
3. Run `bunx biome --version`. _0.3.3_ will be printed.
4. Setup `node_modules` using `bun i`, and run `bunx biome --version` again. _1.2.2_ will be printed.

## Why is this a problem

This breaks our CI/CD configuration because most of the documented commands don't work in that older version, and we prefer not installing everything in `package.json` just for the linting job in our CI/CD.

### Expected result

Running `bunx biome --version` should print the latest version (1.2.2 at the time of this writing).

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
PR welcome. I don't know bun, so leave the solution to someone that knows it.

**Comment by nhedger** [comment]
This appears to be an issue with other package managers. I'm guessing this is just the default behaviour. Nonetheless, it is indeed a good idea to add a warning message.
