### ISSUE TITLE
☂️ Configuration `overrides` support

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#491]
From RFC https://github.com/biomejs/biome/discussions/180

## Goals

- apply a subset of configuration (formatting, lint rules, etc.) only to specific files;
- apply different subsets of configurations to different files;
- turn off tools for certain files

## Non-goals
- embedded languages, we can't provide support for something that we don't know yet how it will work.

## Configuration

Top-level override, as an array:

```json
{
	"overrides": []
}
```

The array allows the creation of multiple "rules" based on the needs of the user.

Each value of the array must be an object. An object contains the following:

### `overrides[].include`

```json
{
	"overrides": [
		{
				"include": ["tests/**.test."]
		}
	]
}
```

You can only apply the rule to a subset of files.

### `overrides[].ignore`

```json
{
	"overrides": [
		{
				"ignore": ["generated/**"]
		}
	]
}
```

You **don't** apply the rule to a subset of files.

> [!NOTE]
> People suggested patterns like 
> ```json
> {
> 	"generate/**": {}
> }
> ```
> While this could work in Biome, it has two shortcomings:
> 1. it will add a **third** way to create globs, together with `include` and `ignore`. The former two already cover the majority of cases
>
> 2. it would degrade the DX when generating the JSON schema; having **predictable** and **known** object keys helps with auto-completion and documentation.

### `overrides[].<TOOL>`

Where `<TOOL>` stands for the tool you need to:

```json
{
	"overrides": [
		{
				"ignore": ["generated/**"],
				"formatter": {},
				"linter": {},
				"organizeImports": {},
		}
	]
}
```

Each object of `<TOOL>` will be a **subset** of the relative top-level configuration:

- [`formatter`](https://biomejs.dev/reference/configuration/#formatter), it won't contain `include` and `ignore`
- [`linter`](https://biomejs.dev/reference/configuration/#linter), it won't contain `include` and `ignore`
- [`organizeImports`](https://biomejs.dev/reference/configuration/#organizeimports), it won't contain `include` and `ignore`

### `overrides[].<LANGUAGE>`

Where `<LANGUAGE>` stands for the languages supported by biome:

```json
{
	"overrides": [
		{
				"ignore": ["generated/**"],
				"javascript": {},
				"json": {},
		}
	]
}
```

Each object of `<LANGUAGE>` will contain the same set of its top-level configuration:

- [`javascript`](https://biomejs.dev/reference/configuration/#javascript)
- [`json`](https://biomejs.dev/reference/configuration/#json)

> [!NOTE]
> In the RFC, people proposed things like `[javascript][typscript]`, borrowed from other tools, that won't work in Biome because each language has **its configuration** that can't be applied to other languages. An example `javascript.parser.unsafeParameterDecoratorsEnabled`, which can't be applied to `json` files

**Comment by nstepien** [comment]
Why go with `include`+`ignore` instead of `include`+`exclude`? 🤔 

>people proposed things like `[javascript][typscript]`, borrowed from other tools, that won't work in Biome because each language has its configuration that can't be applied to other languages. An example `javascript.parser.unsafeParameterDecoratorsEnabled`, which can't be applied to json files

Is that a problem? If I'm targetting both js and json and set a js-only setting for example, it'll only be applied to js files and that's fine. The js setting won't be applied to json files. I don't see how that's not possible.

```json
{
  "overrides": [
    {
      "include": ["[javascript]", "[json]", "[jsonc]"],
      "javascript": ...,
      "linter": ...
    }
  ]
}
```

this is (roughly) equivalent to
```json
{
  "overrides": [
    {
      "include": ["**/*.js", "**/*.json"],
      "javascript": ...,
      "linter": ...
    }
  ]
}
```

**Comment by ematipico** [comment]
> Why go with include+ignore instead of include+exclude? 🤔

Currently, our field name is called `ignore` throughout the configuration. We will rename it `exclude` and deprecate `ignore`, but this can be done in another PR without touching this proposal. The semantics of the fields will stay the same.

> Is that a problem? 

It isn't; I opted for this solution mainly for two reasons:
- we leverage the exact "configuration structure" we use already;
- doing so would allow us to leverage the same code logic we already use somewhere else;
