### ISSUE TITLE
🐛 Documentation clarification for useExhaustiveDependencies

### ISSUE THREAD

**Issue by jfmengels** [biomejs/biome#498]
### Environment information

```block
NA
```

### What happened?

The documentation for https://biomejs.dev/linter/rules/use-exhaustive-dependencies/ is unclear: it doesn't explicitly mention that it is targeting React(-like?) hooks.

When I first read the rule documentation ("Enforce all dependencies are correctly specified"), I thought it was about `npm` dependencies, but it's actually about hooks.

The only mention to that is through the `use` term in the rule name, which unfortunately can be misinterpreted to be "please use exhaustive dependencies". You have to know React hooks to even know that "use" is a convention in some areas of JavaScript code.

### Expected result

I think the documentation should make it explicit that this is a rule for React hooks.

It should also explain the heuristic that it uses to determine whether something is a hook or not. For example: Is anything starting with "use" considered a hook? Do the hooks have to be imported from `react`? Can they be imported from another package or locally?

The docs should also say that if you don't use React (or something like it?) then you should not enable this rule.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by emab** [comment]
I'm sure there's been a discussion on this before, but how come there isn't a specific section for rules that are very domain specific? I.e a section for React based rules that you can enable if you're working in React?

**Comment by Conaclos** [comment]
> I'm sure there's been a discussion on this before, but how come there isn't a specific section for rules that are very domain specific? I.e a section for React based rules that you can enable if you're working in React?

Not yet. However, we plan to add this feature.
