### ISSUE TITLE
🐛 Documentation says allowUnknown, but the configuration file use ignoreUnknown

### ISSUE THREAD

**Issue by Levieber** [biomejs/biome#510]
### Environment information

```block
Not needed
```

### What happened?

![Allow Unknown Documentation](https://github.com/biomejs/biome/assets/104157600/e7c2a0d9-ebbf-4904-9a7a-1f7cb7d042a7)

![Using allow unknown on configuration file](https://github.com/biomejs/biome/assets/104157600/4566b2b5-e1d0-48c3-8894-512dbf8027a7)

![Error when use allow unknown](https://github.com/biomejs/biome/assets/104157600/12ebd899-69b2-48a4-bad0-b39bf077576d)

![Using ignore unknown on configuration file](https://github.com/biomejs/biome/assets/104157600/23c4ba4a-761f-4262-97ed-17491342125a)

### Expected result

The ignoreUnknown and its default value should be documented, which was not very explicit.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Want to send a PR?

**Comment by Levieber** [comment]
> Want to send a PR?

I am going to try. The default value is false, right?

**Comment by ematipico** [comment]
> > Want to send a PR?
> 
> I am going to try. The default value is false, right?

Yes it is! Thank you!

**Comment by Levieber** [comment]
What do you think about replacing the code block with the default value or an explanation of what happens when it is true/false?

For me, this makes it more explicit, easier to understand. And it would look the same as another configuration: vcs.useIgnoreFile.
