### ISSUE TITLE
📎 Implement `lint/noMisleadingClassInRegex` - `eslint/no-misleading-character-class`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#52]
### Description

[no-misleading-character-class](https://eslint.org/docs/latest/rules/no-misleading-character-class/)

**Want to contribute?** Lets we know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by unvalley** [comment]
I'd like to work on different rules for now😅. I'll do it someday. If anyone else wants to take it on, please go ahead.

**Comment by ushmz** [comment]
Hi, I'm interested in working on this. Could you please assign it to me?

**Comment by togami2864** [comment]
Can I work this?

**Comment by unvalley** [comment]
@togami2864 Off course, thank you!
