### ISSUE TITLE
📎 Implement `lint/useValidAriaRole` - `eslint-plugin-jsx-a11y/aria-role`

### ISSUE THREAD

**Issue by nissy-dev** [biomejs/biome#526]
### Description

Implement [aria-role](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y/blob/main/docs/rules/aria-role.md).
This rule is one of the recommended rules in eslint-plugin-jsx-a11y.

**Want to contribute?** Lets we know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by vasucp1207** [comment]
I want to give a try to this.
