### ISSUE TITLE
📎 Implement `nursery/noIrregularWhitespace` - `eslint/no-irregular-whitespace`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#53]
### Description

Implement [no-irregular-whitespace](https://eslint.org/docs/latest/rules/no-irregular-whitespace/).

Want to contribute? Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z).

**Comment by ematipico** [comment]
We should not implement this rule IMHO. We have the formatter that takes care of white spaces, and it could take care of the irregular ones too.

**Comment by Conaclos** [comment]
Does the formatter normalize the irregular whitespace?

**Comment by Conaclos** [comment]
H

> I think there's some validity to having this as a lint rule _as well as_ the formatter auto-fixing them. The formatter can take care of all of the irregular spaces in regular code, but then it's still possible to have these space characters within strings, regexes, and comments, which I think would be _incorrect_ for the formatter to change (it's more likely those characters are intentional in those places, or they at least have a significant meaning).

I am unsure about that because tehre is some legitimate use of irregular whitespaces such as non-breaking spaces?

**Comment by faultyserver** [comment]
> I am unsure about that because tehre is some legitimate use of irregular whitespaces such as non-breaking spaces?

I could see it being a non-recommended rule? There definitely are valid cases, but it would still catch a lot of accidental copy-paste issues. Like the formatter could just re-write them in normal code, but if it's a JSX text or inside of a string literal, then it's not safe to re-write because it might be intentional. But a lint rule could still warn that they are irregular characters in case that's _not_ what the user wanted, and they can add an ignore comment if they really do want it.

**Comment by michellocana** [comment]
can I get this one?

**Comment by michellocana** [comment]
I looked for how often the ESLint rule options are used, and all of the options ([skipStrings](https://github.com/search?q=path%3A.eslintrc*+%2Fno-irregular-whitespace.*skipStrings%2F&type=code), [skipComments](https://github.com/search?q=path%3A.eslintrc*+%2Fno-irregular-whitespace.*skipComments%2F&type=code), [skipRegExps](https://github.com/search?q=path%3A.eslintrc*+%2Fno-irregular-whitespace.*skipRegExps%2F&type=code), [skipTemplates](https://github.com/search?q=path%3A.eslintrc*+%2Fno-irregular-whitespace.*skipTemplates%2F&type=code), and [skipJSXText](https://github.com/search?q=path%3A.eslintrc*+%2Fno-irregular-whitespace.*skipJSXText%2F&type=code)) are used only between 100 and 200 times, so for now I'm going to implement only the default behavior of the rule.
