### ISSUE TITLE
☂️ Deprecate `rome.json`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#54]
### Description

Biome should emit a deprecation diagnostic if `rome.json` is used instead of `biome.json`.

Should we emit a deprecation if both `biome.js` and `rome.json` are found?

Tasks to do:

- [x] #108
- [x] #118
- [x] #119

**Comment by jpike88** [comment]
> Should we emit a deprecation if both biome.js and rome.json are found?

I think so
