### ISSUE TITLE
🐛 `cargo test` fails for 1.3.0 release with 232 tests failed

### ISSUE THREAD

**Issue by alerque** [biomejs/biome#562]
I'm trying to build Arch Linux packages for `biome`, and the 1.3.0 release has some problem with tests.

After setting up a clean chroot and successfully building, `cargo test` spews test failures:

```
test result: FAILED. 33 passed; 232 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.36s
```

Almost all of them are variations on this:

```
---- reporter_json::reports_formatter_write stdout ----
thread 'reporter_json::reports_formatter_write' panicked at /build/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tracing-subscriber-0.3.16/src/util.rs:91:14:
failed to set global default subscriber: SetGlobalDefaultError("a global default trace dispatcher has already been set")
```

That's the very last one thrown, obviously the test names and source locations vary bug the gist of the message is the same.

**Comment by ematipico** [comment]
Are tests that emit errors coming from the same crate?

**Comment by alerque** [comment]
They do all seem to be in the `biome_cli` crate, yes.

**Comment by alerque** [comment]
Of course that's to be expected given that the build and test commands I'm running specify that crate:

```console
$ cargo test -p biome_cli --frozen --all-features
```

**Comment by ematipico** [comment]
Great, I will look into this. Do you require a release or usually run your tests from the repository?

**Comment by alerque** [comment]
For the purposes of publishing Arch Linux packages a release tag is required, but I can rig up a test build based on any commit hash if you want to confirm something before cutting a release.

**Comment by alerque** [comment]
Thanks. I'll look forward to packaging with enabled tests for the next release.
