### ISSUE TITLE
📎 Implement `lint/useAwait` - `eslint/require-await`

### ISSUE THREAD

**Issue by unvalley** [biomejs/biome#575]
### Description

ESLint: [require-await](https://eslint.org/docs/latest/rules/require-await)

~~IMO, `noAsyncWithoutAwait` is descriptive more than `require-await`. Any better name?~~

Want to contribute? Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z).

**Comment by 2-NOW** [comment]
Can I be assigned this task? I'm interested

**Comment by Conaclos** [comment]
What about `useAwait`? Because, we already have `useYield`.

**Comment by 2-NOW** [comment]
> What about `useAwait`? Because, we already have `useYield`.

Thanks! I'll work on your suggestions.

**Comment by ematipico** [comment]
Hi @2-NOW, are you still interested?

**Comment by 2-NOW** [comment]
> Hi @2-NOW, are you still interested?

Yes, of course. I spent quite a bit of time to understand the project structure and overall content. I've already started working on it and will share what I've done this weekend on PR. Thanks for your interest!

**Comment by 2-NOW** [comment]
Working on #699 !

**Comment by 2-NOW** [comment]
I've completed the PR and are waiting for reviews 🚀 .
