### ISSUE TITLE
📎 Add a guide to explain how biome behaves with *known* files

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#587]
### Description

This is a follow-up of the discussion that happened in https://github.com/biomejs/biome/issues/237

The task is to create a new guide page called "Biome's behaviour" (or something similar). The purpose of this page is to list all those particular behaviours/assumptions that Biome does that aren't currently documented, or they are but in the wrong section.

Here's the list of things we should do:
1. Move the following paragraphs in this new page:

https://github.com/biomejs/biome/blob/e6c12c0fed2a1b1662f2f228d369917dd58b7a5c/website/src/content/docs/reference/configuration.mdx#L13-L65

2. Explain that `package.json`, `package-lock.json`, `tsconfig.json` and `jsconfig.json` are currently ignored by Biome because the tools that own these files usually apply their formatting/style, and Biome doesn't want to disrupt them. This means that **no diagnostics** will be ever emitted by Biome for those files.
3. Add a heading that explains the "known" files. These files are listed here:

https://github.com/biomejs/biome/blob/e6c12c0fed2a1b1662f2f228d369917dd58b7a5c/crates/biome_service/src/file_handlers/mod.rs#L48-L64

	And we should explain that when Biome analyses these files, they are parsed as **JSON files** with `json.parser.allowComments` and `json.parser.allowTrailingCommas` set to `true`. This is because editor tools like VSCode treat them like this.

	As a bonus, we should remove `tsconfig.json` and `jsconfig.json` from that list (in the rust file)

**Comment by TheShiveshNetwork** [comment]
Can you assign this to me? I'm interested in working on this.

**Comment by Conaclos** [comment]
Assigned :)

**Comment by TheShiveshNetwork** [comment]
@ematipico check out #624 and do let me know if it needs improvements.
