### ISSUE TITLE
📎 Implement `lint/noThisInStatic` - `mysticatea/no-this-in-static`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#59]
### Description

Implement [@mysticatea/no-this-in-static](https://github.com/mysticatea/eslint-plugin/blob/master/docs/rules/no-this-in-static.md).

**Want to contribute?** Lets we know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by ditorodev** [comment]
I'm gonna try and make a try on this! Lets see how it goes

**Comment by ditorodev** [comment]
Update: Currently getting used to it. @Conaclos has pointed me to some good example rules that I could use as reference but this weekend I don't have much time to keep trying. From Wednesday next week ill get a lot more time to try implementing this 

> conaclos — 08/30/2023 10:31 PM 
You can take a look to an existing rule: https://github.com/biomejs/biome/blob/main/crates/rome_js_analyze/src/analyzers/suspicious/no_duplicate_class_members.rs#L101

> conaclos — 08/30/2023 10:31 PM
There is no specific method is_static.
You have to traverse the modifiers of a member and look for the static modifier
Another example: https://github.com/biomejs/biome/blob/main/crates/rome_js_analyze/src/semantic_analyzers/nursery/use_naming_convention.rs#L677

> conaclos — 08/30/2023 10:38 PM
You shoudl also take a look at no_setter_return.rs. This could help you 🙂

**Comment by ditorodev** [comment]
This week im back at actively trying this 🤞

**Comment by ditorodev** [comment]
Been making amazing progress here, check the PR https://github.com/biomejs/biome/pull/366
