### ISSUE TITLE
📎 Implement `lint/noExclusiveTests` - `eslint-plugin-jest/no-focused-tests`, `eslint-plugin-mocha/no-exclusive-tests`, `eslint-plugin-no-only-tests`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#597]
### Description

Implement [no-focused-tests](https://github.com/jest-community/eslint-plugin-jest/blob/main/docs/rules/no-focused-tests.md) / [no-exclusive-tests](https://github.com/lo1tuma/eslint-plugin-mocha/blob/master/docs/rules/no-exclusive-tests.md) / [no-only-test](https://github.com/levibuzolic/eslint-plugin-no-only-tests).

I think we could restrict the rule to `test.only`, `describe.only` and `it.only`.

Want to contribute? Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md?rgh-link-date=2023-08-23T12%3A52%3A31Z).

This was [proposed](https://github.com/biomejs/biome/discussions/3#discussioncomment-7314833) by @emab.

**Comment by ematipico** [comment]
> I think we could restrict the rule to test.only, describe.only and it.only.

This choice is debatable, so we should really understand the rule's criteria. The original rule is made **for mocha only**, so should we do the same? What about other testing libraries?

For example, tape: https://www.npmjs.com/package/tape#testonlyname-opts-cb



I think this should be

**Comment by Conaclos** [comment]
We can ship a first version which supports the most common usages. `describe`, `test`, and `it` are widely used by test frameworks (AVA, Jasmine, Jest, Mocha, Tape, ...).

I am not found of tracking potential renaming of these functions because this implies maintaining a list of supported frameworks.

**Comment by Conaclos** [comment]
However, some rules could be dedicated to a test framework. Since most of test framework rely on globals, we should add a way to declare the use of a framework in the configuration or a way to detect it (e.g. via package.json dev dependencies).

**Comment by ematipico** [comment]
Sounds like a good plan!

**Comment by emab** [comment]
Maybe could be a configuration option, but having a comment above a skipped test explaining _why_ it was skipped can be extremely useful. Is this something we could consider?

**Comment by Conaclos** [comment]
> I think this rule will allow you to use .skip, and doesn't force you to explain why you are skipping?

Oh yes, sorry I misread u=your request. I think this would be better served by a dedicated rule `noSkippedTest`. What do you think?

**Comment by chansuke** [comment]
I'd like to work on this issue :pray:
