### ISSUE TITLE
📎 Disable unsafe fixes in automatic LSP quickfixes

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#61]
### Description

See [rome#4780](https://github.com/rome/tools/discussions/4780) for some contexts.

The following LSP config should not automatically apply unsafe fixes (suggestions)

```json
{
  "editor.codeActionsOnSave": {
    "quickfix.rome": true
  }
}
```

**Comment by ematipico** [comment]
I believe this was fixed by https://github.com/biomejs/biome/pull/62
