### ISSUE TITLE
🐛 Not working using `bun` or `bunx` 

### ISSUE THREAD

**Issue by FMGordillo** [biomejs/biome#636]
### Environment information

```block
$ biome rage
166 |   return child.addListener("close", exitHandler), child.addListener("error", errorHandler), child;
167 | }, exec = function(command, options, callback) {
168 |   const opts = normalizeExecArgs(command, options, callback);
169 |   return execFile(opts.file, opts.options, opts.callback);
170 | 
171 | }, spawnSync = function(file, args, options) {
                                                 ^
ESRCH: No such process
 syscall: "open"
   errno: -3

      at node:child_process:171:46
      at /.../node_modules/@biomejs/biome/bin/biome:25:7
      at globalThis (/.../chiro/my-secure-diary/node_modules/@biomejs/biome/bin/biome:53:20)
error: script "biome" exited with code 1 (SIGHUP)
```
```


### What happened?

1. Installed `biome` using `bun add --dev --exact @biomejs/biome`
2. Run `bunx @biomejs/biome init`
3. Got the error above :point_up: 

### Expected result

Biome should work as expected and throw, at least, the version

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by FMGordillo** [comment]
More context:
- OS: `NixOS 23.05.4420.679cadfdfed2 (Stoat) x86_64`
- Bun version: `1.0.6`

**Comment by ematipico** [comment]
We don't support bun out of the box.

If it does work with node, then it's a bun issue. If not, then your OS isn't part of the supported ones.

**Comment by FMGordillo** [comment]
ok

**Comment by starsep** [comment]
I am able to reproduce this issue on `biome 1.7.0` on NixOS.
When running biome via `npm`, `bun` or directly `./node_modules/@biomejs/cli-linux-x64/biome` it isn't working

Likely because file `/lib64/ld-linux-x86-64.so.2` is not available on my system

`file ./node_modules/@biomejs/cli-linux-x64/biome`
> ./node_modules/@biomejs/cli-linux-x64/biome: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=7a185d8d4f6612b5da67b6b2611cb19773fbbcd8, for GNU/Linux 3.2.0, stripped

Musl binary works fine: `./node_modules/@biomejs/cli-linux-x64-musl/biome`

I dedided to use workaround: `ln -srf node_modules/@biomejs/cli-linux-x64-musl/biome node_modules/.bin/biome`
Another option might be to use https://github.com/Mic92/nix-ld

**Comment by FMGordillo** [comment]
Forgot to update this one, but creating a nix-develop (`shell.nix` I think it is) you can add the package:

https://search.nixos.org/packages?channel=24.05&show=biome&from=0&size=50&sort=relevance&type=packages&query=biome

And the binary wil be available in the shell to use, as well as for IDE's to use

**Comment by robintown** [comment]
You can also force `pnpm exec biome` to use the static musl binary by creating your dev shell with `pkgs.mkShellNoCC` and adding `pkgs.musl` as one of the build inputs.
