### ISSUE TITLE
🐛`maxAllowedComplexity` doesn’t pass validation

### ISSUE THREAD

**Issue by arendjr** [biomejs/biome#643]
### Environment information

```block
$ /home/arendjr/Projects/monofiber/node_modules/.bin/biome rage
CLI:
  Version:                      1.3.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "yarn/1.22.19"

Biome Configuration:
  Error:                        The field maxAllowedComplexity must contain an integer between 1 and 254
  Status:                       Loaded with errors
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0

Done in 0.69s.
```

### What happened?

I have the following config:

```json
{
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true,
      "complexity": {
        "noExcessiveCognitiveComplexity": {
          "level": "error",
          "options": { "maxAllowedComplexity": 15 }
        }
      },
      "correctness": {
        "useExhaustiveDependencies": "error",
        "useHookAtTopLevel": "error"
      },
      "style": {
        "noParameterAssign": "off"
      }
    }
  }
}
```

And I get the message `The field maxAllowedComplexity must contain an integer between 1 and 254` despite the value that I specified being in the given range.

### Expected result

I should not get an error.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
I can't reproduce the bug. It seems your JSON is syntactically wrong, you miss a `}` at the end

**Comment by arendjr** [comment]
Sorry, the missing `}` was because I wanted to only copy the relevant section of my config.

But if it works for you, I wonder if something is off in my package. I’m using the one from Arch’s AUR repository. I’ll try and dig a bit deeper, thanks!

**Comment by ematipico** [comment]
Do you mind updating the rage command too? To reflect the correct configuration

**Comment by arendjr** [comment]
I just tried with the Biome version pulled from NPM, and I get the same issue. I've updated the rage output.

**Comment by arendjr** [comment]
And the same thing happens with a debug build I built locally. At least that should make it easier to debug what's going on...
