### ISSUE TITLE
📎 Small refactor for the test infrastructure of `biome_cli`

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#669]
### Description

I recently created a small utility:

https://github.com/biomejs/biome/blob/52dae46505805ecf87969544867c88a388df6b93/crates/biome_cli/tests/snap_test.rs#L357-L370

This utility is used to make assertions around file contents easier and less code repetition.

The task is to replace code like this:

https://github.com/biomejs/biome/blob/52dae46505805ecf87969544867c88a388df6b93/crates/biome_cli/tests/commands/format.rs#L135-L145

And replace it with the usage of the utility.

If/when working on it, search for `drop(` inside the tests, and that's where you want to do the substitution. 

All tests must pass, and all snapshots must stay the same. If anything changes, something went wrong.

**Comment by msdlisper** [comment]
It does reduce a lot of boilerplate code, can I try to accomplish this task?

**Comment by Conaclos** [comment]
@msdlisper You are welcome :)

**Comment by msdlisper** [comment]
@Conaclos  Could you check the code for me? :)
