### ISSUE TITLE
📎 Implement `lint/useConsistentArrayType` - `typescript-eslint/array-type`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#68]
### Description

[@typescript-eslint/array-type](https://typescript-eslint.io/rules/array-type)

This should integrate and eventually replace [useShorthandArrayType](https://biomejs.dev/lint/rules/useShorthandArrayType).

The difference is that `useConsistentArrayType` provides a setting to enforce `Array<T>` syntax instead of the shorthand `T[]`.

**Want to contribute?** Lets we know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by eryue0220** [comment]
Could I have a try for this one?

**Comment by Conaclos** [comment]
@eryue0220 Assigned :)

**Comment by hyoretsu** [comment]
This should also support the `array-simple` option from `typescript-eslint`. Imo `Array<T>` is more legible than `T[]` for complex/long types.

**Comment by ematipico** [comment]
It does? https://biomejs.dev/linter/rules/use-consistent-array-type/#syntax

**Comment by hyoretsu** [comment]
It doesn't, or at least it doesn't say so. The two options are either all Array<T> or all T[]. tseslint has a third option that uses T[] for primitives/simple types and Array<T> for more complex types.

**Comment by ematipico** [comment]
A link would have helped 😅 feel free to open and propose a new discussion.
