### ISSUE TITLE
🐛 lineWidth not working properly

### ISSUE THREAD

**Issue by eye-wave** [biomejs/biome#684]
### Environment information

```block
CLI:
  Version:                      1.3.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-kitty"
  JS_RUNTIME_VERSION:           "v19.8.1"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "bun/1.0.9"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### What happened?

no matter what LineWidth i set, chained methods in [this snippet](https://biomejs.dev/playground/?indentStyle=space&trailingComma=none&semicolons=as-needed&arrowParentheses=as-needed&enabledLinting=false&importSortingEnabled=false&unsafeParameterDecoratorsEnabled=false&allowComments=false&code=CgBjAG8AbgBzAHQAIABkAGIAIAA9ACAAewAKACAAIAB1AHMAZQByAHMAOgAgAGEAdwBhAGkAdAAgAEIAdQBuAC4AZgBpAGwAZQAoACIALgAvAGQAYgAvAHUAcwBlAHIAcwAuAGMAcwB2ACIAKQAuAHQAZQB4AHQAKAApAC4AdABoAGUAbgAoAGYAIAA9AD4AIABwAGEAcgBzAGUAQwBTAFYAKABmACkAIABhAHMAIABVAHMAZQByAFsAXQApACwACgB9AAoA&jsx=false) get wrapped onto another line
```ts
const db = {
  users: await Bun.file("./db/users.csv").text().then(f => parseCSV(f) as User[]),
}
```
```ts
const db = {
  users: await Bun.file("./db/users.csv")
    .text()
    .then(f => parseCSV(f) as User[])
}
```

### Expected result

```ts
const db = {
  users: await Bun.file("./db/users.csv").text().then(f => parseCSV(f) as User[]),
}
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
That's expected. We have a heuristic that determines when a chain call expression should go to multiple lines, regardless of the line width, and this code triggers that heuristic.

For example, the following code does what you expect:

```js
const db = {
  users: await Bun.file("./db/users.csv").text().then(paseCSV),
}
```

Prettier does the same, you can check the [playground](https://biomejs.dev/playground/?indentStyle=space&trailingComma=none&semicolons=as-needed&arrowParentheses=as-needed&code=YwBvAG4AcwB0ACAAZABiACAAPQAgAHsACgAgACAAdQBzAGUAcgBzADoAIABhAHcAYQBpAHQAIABCAHUAbgAuAGYAaQBsAGUAKAAiAC4ALwBkAGIALwB1AHMAZQByAHMALgBjAHMAdgAiACkALgB0AGUAeAB0ACgAKQAuAHQAaABlAG4AKABmACAAPQA%2BACAAcABhAHIAcwBlAEMAUwBWACgAZgApACAAYQBzACAAVQBzAGUAcgBbAF0AKQAsAAoAfQAKAAoAYwBvAG4AcwB0ACAAZABiACAAPQAgAHsACgAgACAAdQBzAGUAcgBzADoAIABhAHcAYQBpAHQAIABCAHUAbgAuAGYAaQBsAGUAKAAiAC4ALwBkAGIALwB1AHMAZQByAHMALgBjAHMAdgAiACkALgB0AGUAeAB0ACgAKQAuAHQAaABlAG4AKABwAGEAcwBlAEMAUwBWACkALAAKAH0A).

**Comment by pitoniak32** [comment]
I'm wondering if the same this is happening [here](https://biomejs.dev/playground/?indentStyle=space&trailingCommas=none&semicolons=as-needed&arrowParentheses=as-needed&code=dABlAHMAdAAuAGUAYQBjAGgAKABbAAoAIAAgAFsAJwB0AGUAcwB0ACcALAAgAFsAJwBvAHQAaABlAHIAJwBdACwAIABmAGEAbABzAGUAXQAsAAoAXQApACgACgAgACAAIgB3AGgAZQBuACAAcABhAHQAaAAgAGkAcwAgACcAJQBzACcALAAgAGEAbgBkACAAbwBwAHQAaQBvAG4AcwAgAGEAcgBlACAAJQBzACwAIABpAGcAbgBvAHIAZQAgAHMAaABvAHUAbABkACAAYgBlACAAJwAlAHMAJwAiACwACgAgACAAYQBzAHkAbgBjACAAKABfAHAAYQB0AGgAOgAgAHMAdAByAGkAbgBnACwAIABfAHAAYQB0AGgAcwA6ACAAcwB0AHIAaQBuAGcAWwBdACwAIABfAGUAeABwAGUAYwB0AGUAZAA6ACAAYgBvAG8AbABlAGEAbgApACAAPQA%2BACAAewAKACAAIAAvAC8AIABkAG8AIAB0AGgAZQAgAHQAZQBzAHQACgB9ACkA):

We have our lineWidth set to 101, but its ignoring it for similar tests to this.

when we were using biome 2.0.6:
```typescript
test.each([
  ['test', ['other'], false],
])(
  "when path is '%s', and options are %s, ignore should be '%s'",
  async (_path: string, _paths: string[], _expected: boolean) => {
  // do the test
})
```

I just upgraded to 2.4.4:
```typescript
test.each([
  ["test", ["other"], false]
])("when path is '%s', and options are %s, ignore should be '%s'", async (_path: string, _paths: string[], _expected: boolean) => {
  // do the test
})
```

I can open a new ticket if this isn't the same thing
