### ISSUE TITLE
🐛 Typescript lint is not in effect

### ISSUE THREAD

**Issue by msdlisper** [biomejs/biome#692]
### Environment information

```block
in playground
```

### What happened?

1. write code
`
interface MyType {
  a: boolean
}
const aaa: MyType = {a: 1}
`
 
the playground link: https://biomejs.dev/playground/?lintRules=all&code=aQBuAHQAZQByAGYAYQBjAGUAIABNAHkAVAB5AHAAZQAgAHsACgAgACAAYQA6ACAAYgBvAG8AbABlAGEAbgAKAH0ACgBjAG8AbgBzAHQAIABhAGEAYQA6ACAATQB5AFQAeQBwAGUAIAA9ACAAewBhADoAIAAxAH0ACgAKAHAAcgBpAG4AdAAoAGEAYQBhACkAOwA%3D

### Expected result

say: a
Type 'number' is not assignable to type 'boolean'.(2322)

the playground link: https://typescript-eslint.io/play/#ts=5.2.2&showAST=es&fileType=.tsx&code=JYOwLgpgTgZghgYwgAgLIE8Aq6AOKDeAUMsnAFzIBGA9tQDYRwiEC%2BhC1IAzmKXOWiy4UAXmT5SFAIzI2QA&eslintrc=N4KABGBEBOCuA2BTAzpAXGYBfEWg&tsconfig=N4KABGBEDGD2C2AHAlgGwKYCcDyiAuysAdgM6QBcYoEEkJemy0eAcgK6qoDCAFutAGsylBm3TgwAXxCSgA&tokens=false

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by ematipico** [comment]
Biome doesn't do type checking. I believe TypeScript ESlint forward messages coming from the TS compiler. In fact:
- the diagnostic emitted from ESLint doesn't belong to any rule
- the diagnostic is the [same of TypeScript](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgLIE8Aq6AOKDeAUMsnAFzIBGA9tQDYRwiEC+hC1IAzmKXOWiy4UAXmT5SFAIzI2QA)
