### ISSUE TITLE
☂️ Prettier code challenge hub

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#720]
### Description

>[!IMPORTANT]
> Please read the [final compatibility report](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report-challenge.md).

> [!WARNING]  
> We are preparing the submission to the challenge. If you are currently working on a fix, please submit a Pull Request as soon as possible. **We will not accept Pull Requests submitted after Wednesday 13:00 [UTC+0](https://time.is/UTC)**. 

This issue will function as hub of information and coordination for the  challenge:

https://discord.com/channels/1132231889290285117/1132607436973416458/1173725497981665401

Context:
- https://console.algora.io/challenges/prettier
- https://twitter.com/Vjeux/status/1722733472522142022

We aim for:

- 95% compatibility with prettier for JavaScript
- 95% compatibility with prettier for TypeScript
- 95% compatibility with prettier for JSX

## How to participate 

Make sure to leave a comment here saying that you're interested in contributing. When you open a PR that intends to fix an issue related to the challenge, add `challenge(formatter): <DESCRIPTION>` to the PR title. 

**_Failing to do so will nullify your contribution to the challenge_**.

Use Discord for quick feedback from other community members. Use GitHub for coordination, questions, and bike-shedding. 

## Funds allocation

The bounty is split in two. 20k for compatibility with Prettier and 2.5k for publishing the formatter to Wasmer. 

We will first focus on the compatibility part. Then, we will focus on publishing the artifact to Wasmer.

~~The funds will be transferred to our [Open Collective](https://opencollective.com/biome), and then the contributors will emit an invoice to withdraw the funds.~~ The funds will be distributed directly by the challenge owners. You will be directly contacted by them.

> [!IMPORTANT]
> UPDATE: the 1/4 fund allocation to "contributors" was a bit unclear: we were actually referring to external contributors only, not both internal and external contributors, because internal contributors are already rewarded in the 3/4 fund allocation. This ensures that external contributors are rewarded accordingly.
>
> Moreover, we clarifed how the 3/4 are allocated to team members. Half will be allocated to the ones that contributed directly to the challenge and the remaining (1/4) will be dispatched between the Biome organization and team members (to reward previous works on Biome).  

The funds [Prettier compatibility challenge] will be allocated as follows:
- 1/2 split among the internal challenge contributors (the ones that are members of the Biome team: Core Contributors and Maintainers)
- 1/4 split among the external challenge contributors (the ones that are not part of the Biome team)
- 1/4 split among members of the Biome team to reward previous effort on the project

We want to reward our Core Contributors and Maintainers, who have been with us for a long time, and they deserve to be rewarded for all the work they have been doing so far.

As for calculating the percentage of money to give to the contributors, we don't have prior experience, so we are not aware of a fair system; **for now** we will use the *number of changes*. We **don't** use the number of commits or the number of PRs. This will be subject to change if we find a better system.

## Biome infrastructure

Biome uses Prettier's test to calculate the compatibility rate roughly. You can read more here:

https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/tests/specs/prettier/README.md

The infrastructure tracks the changes between Biome and Prettier, and it creates **two snapshots**:
- a file with `.prettier-snap` extension, which is the formatting result of a Prettier test;
- a file with `.snap` extension. This file is created **only if there are differences** between Biome and Prettier. If your changes happen to increase the compatibility, and the outputs between Biome and Prettier are the same, the infrastructure **will delete** the `.snap` file, which is a **good** signal because we increased the matching.

The testing infrastructure checks against [Idempotence](https://en.wikipedia.org/wiki/Idempotence). For a formatter it means that given any snippet can't change its formatting if it is formatted twice. In particular, you get the output emitted by the first formatting pass, and you format it again. If the second result is different from the first result, it means it's a bug and the testing suite fails:

```
snippet -> format -> output1
output1 -> format -> output2
(output1 != output2) -> FAIL
(output1 == output2) -> SUCCESS
```

This check is done on our internal tests and the Prettier tests. It **might** happen that Prettier's tests will fail the Idempotence check. If so, we have two options:
- use our best judgement to fix the issue; this will likely cause a divergence, but since this is a bug in Prettier, I believe it should be accepted as intentional divergence;
- comment on the broken code, and add a `TODO` and tackle it later in a different issue;

Regardless, we should file an issue in the Prettier repository to confirm it's an issue. This will help us and Prettier. 

## How to format

You don't need to know all the internals of the formatter infrastructure. Here's some guidelines:
- use our [playground](https://biomejs.dev/playground). Use it to inspect Biome's AST and how to navigate it, and check the IR emitted by Biome and Prettier. Biome's IR is very similar to Prettier's.
- check Prettier's source code and their logic. Biome uses the same logic, although our AST might be different. Help yourselves with the playground.
- We **comment** everything worth commenting. If you have a hard time understanding Prettier's logic, but eventually you succeed, share this knowledge with us by adding good comments in the source code.
- If you need to deal with comments, [read this first](https://docs.rs/biome_formatter/latest/biome_formatter/comments/index.html), it should give you some context;

When fixing an incompatibility with Prettier, you're advised to add a test in [our internal infra](https://github.com/biomejs/biome/tree/main/crates/biome_js_formatter/tests/specs), too.

Note that you should not commit `report.md`.

## I would like to contribute, what do I do?

- Take a look to the [prettier compatibility report](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report.md). Alternatively you can take a look to the [report that highlights only the differences](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report_incompatible.md). These reports will be periodically updated.
- Choose a diff you want to tackle
- Add a comment here by claiming a diff or a file. Make sure nobody else is working on it
- Do the work
- If you have technical questions, it's advised to open a draft PR and ask the questions there. This issue is meant for coordination 

## I believe Prettier has incorrect behaviour

Prettier is not perfect, and sometimes Biome can do a better job - infra, CST, less restrictions, etc. In case this happens, [add a comment to this issue](https://github.com/biomejs/biome/issues/739). Use the template provided, so we can eventually use this issue as source to create a web page in our website to explain where Biome divergece from Prettier.

## Fixing issues

- Look for `// TODO` comments inside the Prettier tests
- Look for `// FIXME` comments inside the Prettier tests
- When finding a bug, add some context about the entity of the issue (there are also some parsing issues)

**Comment by ematipico** [comment]
Here's a gist of the difference: https://discord.com/channels/1132231889290285117/1132602615570649110/1173819749977837698

This is dated to yesterday.

**Comment by faultyserver** [comment]
I'd like to pick up a few of these that feel related. Specifically around `abstract` and `declare` in typescript code: 

- [typescript/declare/declare_function_with_body.ts](https://gist.github.com/ematipico/576b6bacb778d3b9166de0609c771115#typescriptdeclaredeclare_function_with_bodyts)
- [typescript/declare/trailing-comma/function-rest-trailing-comma.ts](https://gist.github.com/ematipico/576b6bacb778d3b9166de0609c771115#typescriptdeclaretrailing-commafunction-rest-trailing-commats)
- [typescript/interface/abstract.ts](https://gist.github.com/ematipico/576b6bacb778d3b9166de0609c771115#typescriptinterfaceabstractts) / [typescript/conformance/types/abstractKeyword/abstractKeyword.ts](https://gist.github.com/ematipico/576b6bacb778d3b9166de0609c771115#typescriptconformancetypesabstractkeywordabstractkeywordts)
- [typescript/custom/abstract/abstractProperties.ts](https://gist.github.com/ematipico/576b6bacb778d3b9166de0609c771115#typescriptcustomabstractabstractpropertiests)

**Comment by Conaclos** [comment]
I am working on:

- [js/comments/break-continue-statements.js](https://gist.github.com/ematipico/576b6bacb778d3b9166de0609c771115#jscommentsbreak-continue-statementsjs)

**Comment by TaKO8Ki** [comment]
I would like to participate in this challenge as well. I have started working on the problems listed in [this issue](419). #733

**Comment by TaKO8Ki** [comment]
I will also work on the following issues.

- [js/for/continue-and-break-comment-without-blocks.js](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report.md#jsforcontinue-and-break-comment-without-blocksjs)
- [js/for/continue-and-break-comment-1.js](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report.md#jsforcontinue-and-break-comment-1js)

**Comment by Conaclos** [comment]
> I will also work on the following issues.
> 
>     * [js/for/continue-and-break-comment-without-blocks.js](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report.md#jsforcontinue-and-break-comment-without-blocksjs)
> 
>     * [js/for/continue-and-break-comment-1.js](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report.md#jsforcontinue-and-break-comment-1js)

I think this conflicts with [js/comments/break-continue-statements.js](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report.md#jscommentsbreak-continue-statementsjs) and I am working on this.

**Comment by TaKO8Ki** [comment]
Oh I see. I will pick up other issues.

**Comment by Conaclos** [comment]
> Hello, I'd like to help out and contribute to this challenge :D

@aazam-gh you are welcome! COmment this thread by linking the diff you are working on.

**Comment by victor-teles** [comment]
I am working on 

- [js/arrays/numbers-with-holes.js](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report.md#jsarraysnumbers-with-holesjs)
- [js/arrays/holes-in-args.js](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report.md#jsarraysholes-in-argsjs)

**Comment by aazam-gh** [comment]
I will try working on this 

- [js/quotes/objects.js](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report.md#jsquotesobjectsjs)

**Comment by unvalley** [comment]
I'm working on [js/switch/comments2.js](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report_incompatible.md?rgh-link-date=2023-11-16T17%3A56%3A44Z#jsswitchcomments2js).

**Comment by ematipico** [comment]
We should be able to fix https://github.com/biomejs/biome/issues/419

The first two items are JS code, so they fall under the coding challenge

**Comment by ematipico** [comment]
The bug should fall under the challenge https://github.com/biomejs/biome/issues/725

**Comment by TaKO8Ki** [comment]
I think [typescript/tuple/dangling-comments.ts](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report_incompatible.md#typescripttupledangling-commentsts) will be fixed in #770.

**Comment by SuperchupuDev** [comment]
FYI, we just got confirmation that the challenge also aims for [all Prettier JS options](https://twitter.com/Vjeux/status/1725902140286378205). I'm gonna try working on `end-of-line`, and if #627 gets merged then the only option remaining would be `bracket-same-line`

**Comment by faultyserver** [comment]
> and if #627 gets merged then the only option remaining would be `bracket-same-line`

I'll plan on getting that PR fixed up today and implement `bracket-same-line` as well.

**Comment by Gumichocopengin8** [comment]
While looking at `js/range/*`, found some prettier test cases issue. fix: #774

**Comment by TaKO8Ki** [comment]
[js/test-declarations/test_declarations.js](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report_incompatible.md#jstest-declarationstest_declarationsjs) will be fixed in #772 and #780.

**Comment by asher-gh** [comment]
Working on [js/arrays/issue-10159.js
](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report_incompatible.md#jsarraysissue-10159js)

**Comment by SuperchupuDev** [comment]
opened a PR for the end-of-line option #786

**Comment by zcesur** [comment]
Congrats everyone!! 👏🦀
I’m preparing your submission/winner section on Algora, ready to finalize & deploy when you are 🫡

![Biome on Algora](https://github.com/biomejs/biome/assets/17045339/423d9e85-ce86-499b-a29d-14fffd301ab6)

**Comment by syrusakbary** [comment]
It's awesome to see the progress in such a small amount of time.

I'm Syrus, from Wasmer. If you guys need any help to have biome published to Wasmer and running with WASIX please let us know, we'd love to offer assistance. Keep up the good work! 💪

**Comment by aazam-gh** [comment]
Working on [js/with/indent.js](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report_incompatible.md#jswithindentjs)

**Comment by aazam-gh** [comment]
Will work on [typescript/trailing-comma/trailing.ts
](https://github.com/biomejs/biome/blob/main/crates/biome_js_formatter/report_incompatible.md#typescripttrailing-commatrailingts)

**Comment by ematipico** [comment]
The issue https://github.com/biomejs/biome/issues/810 is part of the challenge.

**Comment by Conaclos** [comment]
> [!WARNING]  
> We are preparing the submission to the challenge. If you are currently working on a fix, please submit a Pull Request as soon as possible. **We will not accept Pull Requests submitted after Wednesday 14:00 [UTC+0](https://time.is/UTC)**.

**Comment by syrusakbary** [comment]
Hey everyone!

I'm aware there will be a public announcement next Monday (Nov 27th, 2023), and it will be great if Biome is also published in [Wasmer](https://wasmer.io) by then (it will great to mention it on the public blogpost!).

For that reason, if no one wants to do the challenge and claim the $2,500 prize before the announcement it will make sense for someone from the Wasmer team to do it (words of encouragement: it should be work for a few hours max!)... in case anyone wants to complete the challenge before the public announcement please let me know so you can claim the prize!  🏆

Keep up the good work 💪

**Comment by ematipico** [comment]
Hi @syrusakbary 

I'm not sure we will be able to claim the 2.5k about wasmer before Monday, mainly because **it seems that** this requires admin permissions for registering the package and publishing it (via secrets). 

All this requires access to important information, and as per governance only the core team has access to such information, which means that only a small number of people can do the bulk of the work.

Unfortunately I can't do it, so this leaves the rest of the team.

**Comment by Conaclos** [comment]
@syrusakbary I can give a hand on that.

**Comment by syrusakbary** [comment]
Hey @ematipico @Conaclos thanks for the quick response!

Here's how I'd recommend taking approaching it so the Biome community can also take the prize from Wasmer:
1. Create an account in Wasmer and join the [Biome namespace](https://wasmer.io/biome) - Note: I just created the space manually to ease things a bit, just let me know on this thread once you have a Wasmer username so I can add you guys to it (you'll have full ownership after of the namespace)
2. Compile the project to WASIX (here's probably the most important/complex part)
3. Publish Biome manually to the Wasmer registry
4. Create a PR to Biome with the automatic compilation to WASIX and a draft CI integration (just without the token, or with a hardcoded token... tokens can be easily deleted after, so doing this can help on iteration!). Tests will probably fail (unless you use a hardcoded token), but that's easy to fix once the Governance team adds the secret :)

If that's done, and assuming the core team will be happy merging it, then we can fast-track the prize for Biome! 🚀

**Comment by Conaclos** [comment]
@syrusakbary Thanks for these details. I created a user named `biomejs`. Have you some resource for helping us in this work?

**Comment by syrusakbary** [comment]
Awesome, I just invited you to the namespace as admin @Conaclos .

I recommend this two resources:
1. Rust guides for using WASIX: https://wasix.org/docs/language-guide/rust/installation
    * Example WASIX packages: https://github.com/wasix-org/wasix-rust-examples/tree/main/wasix-grpc
2. For publishing a package in Wasmer:
    * https://docs.wasmer.io/registry/get-started
    * https://docs.wasmer.io/runtime/runners/wasix (WASIX packages)

Once you compile the program to WASIX it should be pretty easy to publish to Wasmer, but please let me know if you have more questions.

Also happy to invite more people to the [Wasmer biome namespace](https://wasmer.io/biome), just let me know here!

**Comment by syrusakbary** [comment]
Sure thing, just did @ematipico! (you can accept the invite when entering the wasmer.io page, in the notifications menu)

**Comment by syrusakbary** [comment]
Hey @ematipico , I told the Wasmer team to work on updating all the forks under WASIX, as `cargo wasix build` was failing in biome when using the forks. Now all dependencies build properly in WASIX in this fork of biome:
https://github.com/wasix-org/biome

However, there are a few things that still need to be solved in Biome's side (more info on what fails to build on biome: https://gist.github.com/john-sharratt/d085f81a3008bdd38dea5e3be181b6d6)

Thankfully now the task should be more manageable... and as such the $2,500 prize is still up! Excited for you guys to claim it!

**Comment by TaKO8Ki** [comment]
Hi @syrusakbary, can I also participate the namespace? cc: @ematipico @Conaclos

**Comment by TaKO8Ki** [comment]
@syrusakbary Thanks! I understand.

> please note that any other admin can also invite future ones from the namespace settings here: https://wasmer.io/namespace/biome/settings/collaborators)

**Comment by TaKO8Ki** [comment]
@Conaclos I knew you were working on this, but I also had an interest, so I decided to give it a try. As a result, by temporarily removing the lsp implementation for WASIX, I successfully executed `cargo wasix build` without errors. You can see the changes I made in the following link. At a glance, the compiled `biome.wasm` appears to be functioning correctly.

https://github.com/TaKO8Ki/biome/pull/1

**Comment by Conaclos** [comment]
@TaKO8Ki Feel free to open a PR. The 1.4 release takes me a lot of time, I didn't make so much progress on this.

**Comment by ematipico** [comment]
@TaKO8Ki thank you mate, awesome work! Feel free to open a PR 👌

**Comment by TaKO8Ki** [comment]
@Conaclos @ematipico Ok. I will create a PR!

**Comment by ematipico** [comment]
Thank you to all the contributors that took part in the challenge.

@Conaclos will contact all the people that took part in the challenge, and that will take part in the bounty. He will contact you **on Discord**, so make sure:
- to be on Discord
- to check your notifications, because Discord doesn't show good notifications from people you aren't friends with

**Comment by Conaclos** [comment]
Just to ensure that everyone had received a notification:

I sent an email to external contributors (using their git commit's email address) that explains how they can retrieve their reward. I contacted / will contact internal contributors via email or via Discord (some of them use a GitHub noreply alias for their git commits).
