### ISSUE TITLE
📝 Multi line template strings containing ${} after lineWidth are wrongly indented.

### ISSUE THREAD

**Issue by arthurfiorette** [biomejs/biome#725]
### Environment information

```bash
CLI:
  Version:                      1.3.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.10.2"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Configuration

```JSON
{
  "$schema": "https://biomejs.dev/schemas/1.3.3/schema.json",
  "organizeImports": {
    "enabled": true
  },
  "linter": {
    "enabled": true,
    "rules": {
      "recommended": true
    }
  },
  "formatter": {
    "indentStyle": "space",
    "ignore": ["**/coverage"],
    "lineWidth": 120
  },
  "javascript": {
    "formatter": {
      "quoteStyle": "single",
      "trailingComma": "none"
    }
  }
}
```

### Playground link

https://biomejs.dev/playground/?indentStyle=space&code=LwAvACAASQBuACAAdABoAGUAIABiAGkAbwBtAGUAIAByAGUAcwB1AGwAdAAsACAAbABpAG4AZQAgADgALAA5ACAAYQBuAGQAIAAxADAALAAxADEAIABpAG4AZABlAG4AdABhAHQAaQBvAG4AcwAgAGEAcgBlACAAbwBuAGUAIABsAGUAdgBlAGwAIAB1AHAAcABlAHIAIAB0AGgAYQBuACAAdABoAGUAeQAgAHMAaABvAHUAbABkACAAYgBlAC4AIAAKAC8ALwAgAEwAbwBvAGsAIABhAHQAIABwAHIAZQB0AHQAaQBlAHIAIABlAHgAYQBtAHAAbABlACAAYQBzACAAcgBlAGYAZQByAGUAbgBjAGUALgAKAAoAZgB1AG4AYwB0AGkAbwBuACAAdABvAFAAbAB1AGcAaQBuACgAcABsAHUAZwBpAG4AOgAgAEsAaQB0AGEAUABsAHUAZwBpAG4AKQAgAHsACgAgACAAcgBlAHQAdQByAG4AIABgAAoAIAAgACAAaQBmACAAKAAkAHsAawBLAGkAdABhAE8AcAB0AGkAbwBuAHMAfQAuACQAewBwAGwAdQBnAGkAbgAuAG4AYQBtAGUAfQAgACEAPQA9ACAAZgBhAGwAcwBlACkAIAB7AAoAIAAgACAAIAAgAGEAdwBhAGkAdAAgACQAewBrAEYAYQBzAHQAaQBmAHkAVgBhAHIAaQBhAGIAbABlAH0ALgByAGUAZwBpAHMAdABlAHIAKAByAGUAcQB1AGkAcgBlACgAIgAkAHsAcABsAHUAZwBpAG4ALgBpAG0AcABvAHIAdABVAHIAbAB9ACIAKQAsACAATwBiAGoAZQBjAHQALgBhAHMAcwBpAGcAbgAoACQAewBzAHQAcgBpAG4AZwBpAGYAeQBPAHAAdABpAG8AbgBzACgACgAgACAAIAAgACAAIAAgAHAAbAB1AGcAaQBuAC4AbwBwAHQAaQBvAG4AcwAKACAAIAAgACAAIAApAH0ALAAgACQAewBrAEsAaQB0AGEATwBwAHQAaQBvAG4AcwB9AC4AJAB7AHAAbAB1AGcAaQBuAC4AbgBhAG0AZQB9ACAAfAB8ACAAewB9ACkAKQAKACAAIAAgAH0ACgAgACAAYAA7AAoAfQAKAAoALwAvACAARQB4AHQAcgBhAGMAdABlAGQAIABmAHIAbwBtAAoALwAvACAAaAB0AHQAcABzADoALwAvAGcAaQB0AGgAdQBiAC4AYwBvAG0ALwBrAGkAdABhAGoAcwAvAGsAaQB0AGEAagBzAC8AYgBsAG8AYgAvAGUAZABhADEAYgA2AGMAZQBhADgANQA1ADYAZQBjADcANABiAGUAMgA5ADAAZgBkADUAZgA1ADMAYwA1ADUAZgAxADUANwA3ADYAMgAyAGMALwBwAGEAYwBrAGEAZwBlAHMALwBnAGUAbgBlAHIAYQB0AG8AcgAvAHMAcgBjAC8AdABlAG0AcABsAGEAdABlAHMALwBwAGwAdQBnAGkAbgAuAHQAcwAjAEwANgA1AA%3D%3D

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Conaclos** [comment]
This seems be fixed. Please let me know if I am wrong.
