### ISSUE TITLE
📝 Backslashes gets removed when formatting (regex)

### ISSUE THREAD

**Issue by bjon** [biomejs/biome#787]
### Environment information

```bash
CLI:
  Version:                      1.3.3
  Color support:                true

Platform:
  CPU Architecture:             x86_64
  OS:                           linux

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v20.9.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         "pnpm/8.10.5"

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 true

Workspace:
  Open Documents:               0
```

### Playground link

https://biomejs.dev/playground/?code=PABpAG4AcAB1AHQAIAB0AHkAcABlAD0AIgB0AGUAeAB0ACIAIABwAGEAdAB0AGUAcgBuAD0AIgBcAGQAKwBcAC4AXABkACsAXAAuAFwAZAArACIAIAAvAD4A

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by CanadaHonk** [comment]
With [this example](https://biomejs.dev/playground/?code=PABlAGwAZQBtAGUAbgB0ACAAYQB0AHQAcgBpAGIAdQB0AGUAPQAiAFwAZgBvAFwAbwBcAFwAYgBhAFwAcgAiAD4APAAvAGUAbABlAG0AZQBuAHQAPgA%3D) the AST looks good, but IR removes the `\` before the second `o` for some reason?

**Comment by ematipico** [comment]
Does https://github.com/biomejs/biome/pull/842 fix your issue?
