### ISSUE TITLE
📎 Regenerate Algoria API key to use Biome document as index

### ISSUE THREAD

**Issue by unvalley** [biomejs/biome#79]
### Description

Currently when we search something on https://biomejs.dev , the search results links are https://rome.tools .

I think here needs change: https://github.com/biomejs/biome/blob/3a3cded8f1b1e9b4abbc11db7a8a4d056c7dad4f/website/src/frontend-scripts/docsearch.ts#L16

**Comment by ematipico** [comment]
I was thinking that we could rewrite the website by using [starlight](https://starlight.astro.build/), which uses https://pagefind.app/

I don't think we need algolia

**Comment by unvalley** [comment]
OK, That's cool! I close this for now.
