### ISSUE TITLE
🐛 `IndentWidth` does not work with `IndentStyle::Tab`

### ISSUE THREAD

**Issue by magic-akari** [biomejs/biome#81]
### Environment information

```block
main branch
```

### What happened?

Check the playground.
- [playground 1](https://biomejs.dev/playground?indentWidth=4&code=ZgB1AG4AYwB0AGkAbwBuACAAZgBvAG8AKAApACAAewAKACAAIAAgACAAcgBlAHQAdQByAG4AIABbAAoAIAAgACAAIAAgACAAIAAgACIAMQAyADMANAA1ADYANwA4ADkAMAAiACwACgAgACAAIAAgACAAIAAgACAAIgAxADIAMwA0ADUANgA3ADgAOQAwACIALAAKACAAIAAgACAAIAAgACAAIAAiADEAMgAzADQANQA2ADcAOAA5ADAAIgAsAAoAIAAgACAAIAAgACAAIAAgACIAMQAyADMANAA1ADYANwA4ADkAMAAiACwACgAgACAAIAAgACAAIAAgACAAIgAxADIAMwA0ADUANgA3ADgAOQAwACIALAAKACAAIAAgACAAXQA7AAoAfQAKAA%3D%3D)
- [playground 2](https://biomejs.dev/playground?indentWidth=8&code=ZgB1AG4AYwB0AGkAbwBuACAAZgBvAG8AKAApACAAewAKAAkAZgB1AG4AYwB0AGkAbwBuACAAYgBhAHIAKAApACAAewAKAAkACQBmAHUAbgBjAHQAaQBvAG4AIABmAG8AbwAoACkAIAB7AAoACQAJAAkAZgB1AG4AYwB0AGkAbwBuACAAYgBhAHIAKAApACAAewAKAAkACQAJAAkAZgB1AG4AYwB0AGkAbwBuACAAZgBvAG8AKAApACAAewAKAAkACQAJAAkACQBmAHUAbgBjAHQAaQBvAG4AIABiAGEAcgAoACkAIAB7AAoACQAJAAkACQAJAAkAZgB1AG4AYwB0AGkAbwBuACAAZgBvAG8AKAApACAAewAKAAkACQAJAAkACQAJAAkAZgB1AG4AYwB0AGkAbwBuACAAYgBhAHIAKAApACAAewAKAAkACQAJAAkACQAJAAkACQByAGUAdAB1AHIAbgAgAFsACgAJAAkACQAJAAkACQAJAAkACQAiAGwAbwBuAGcAIgAsAAoACQAJAAkACQAJAAkACQAJAAkAIgBsAG8AbgBnACIALAAKAAkACQAJAAkACQAJAAkACQAJACIAbABvAG4AZwAiACwACgAJAAkACQAJAAkACQAJAAkACQAiAGwAbwBuAGcAIgAsAAoACQAJAAkACQAJAAkACQAJAAkAIgBsAG8AbgBnACIALAAKAAkACQAJAAkACQAJAAkACQAJACIAbABvAG4AZwAiACwACgAJAAkACQAJAAkACQAJAAkACQAiAGwAbwBuAGcAIgAsAAoACQAJAAkACQAJAAkACQAJAF0AOwAKAAkACQAJAAkACQAJAAkAfQAKAAkACQAJAAkACQAJAH0ACgAJAAkACQAJAAkAfQAKAAkACQAJAAkAfQAKAAkACQAJAH0ACgAJAAkAfQAKAAkAfQAKAH0ACgA%3D)

### Expected result

The result of prettier is the expected behavior.
Although tab is only one character, it should treat indent width as visual width, which will affect the calculation of line width.

Let's paste the biome result into editor.
<img width="1433" src="https://github.com/biomejs/biome/assets/7829098/624c2b08-d1b2-40e1-929e-0cc6798de59c">
You will find that the visual width of the code exceeds the limit of 80 characters.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by magic-akari** [comment]
I am willing to fix it  if it's confirmed to be a bug.

**Comment by Conaclos** [comment]
Confirmed and assigned :)
