### ISSUE TITLE
🐛 Ignore side-effect imports when organising imports

### ISSUE THREAD

**Issue by remojansen** [biomejs/biome#817]
### Environment information

```block
CLI:
  Version:                      1.3.3
  Color support:                true

Platform:
  CPU Architecture:             aarch64
  OS:                           macos

Environment:
  BIOME_LOG_DIR:                unset
  NO_COLOR:                     unset
  TERM:                         "xterm-256color"
  JS_RUNTIME_VERSION:           "v21.1.0"
  JS_RUNTIME_NAME:              "node"
  NODE_PACKAGE_MANAGER:         unset

Biome Configuration:
  Status:                       Loaded successfully
  Formatter disabled:           false
  Linter disabled:              false
  Organize imports disabled:    false
  VCS disabled:                 false

Workspace:
  Open Documents:               0
```

### What happened?

Using `biome format --write ./` in a project.

Input:

```ts
import '@projectx/theme/src/normalize.css';
import './index.css';
import '@projectx/theme/src/button.css';
import '@projectx/theme/src/col-3-section.css';
import '@projectx/theme/src/col-50x50-section.css';
import '@projectx/theme/src/col-full-section.css';
import '@projectx/theme/src/onetrust.css';
import '@projectx/theme/src/rich-text-accordion.css';
import '@projectx/theme/src/rich-text-table.css';
import '@projectx/theme/src/side.css';
import '@projectx/theme/src/summary.css';
import '@projectx/theme/src/utils.css';
import '@projectx/theme/src/component-ui-form.css';
import '@projectx/theme/src/main-app.css';
import { LayoutInternal } from './LayoutInternal';
import { LoginStatus } from '@projectx/constants-common';
import { ErrorHandling } from '@projectx/container-error-handler';
import { CustomError } from './CustomError';
import React from 'react';
```

Actual Output (Import sorting):
```ts
import { LoginStatus } from '@projectx/constants-common';
import { ErrorHandling } from '@projectx/container-error-handler';
import '@projectx/theme/src/button.css';
import '@projectx/theme/src/col-3-section.css';
import '@projectx/theme/src/col-50x50-section.css';
import '@projectx/theme/src/col-full-section.css';
import '@projectx/theme/src/component-ui-form.css';
import '@projectx/theme/src/main-app.css';
import '@projectx/theme/src/normalize.css';
import '@projectx/theme/src/onetrust.css';
import '@projectx/theme/src/rich-text-accordion.css';
import '@projectx/theme/src/rich-text-table.css';
import '@projectx/theme/src/side.css';
import '@projectx/theme/src/summary.css';
import '@projectx/theme/src/utils.css';
import React from 'react';
import { CustomError } from './CustomError';
import { LayoutInternal } from './LayoutInternal';
import './index.css';
```

Changing the order of CSS imports breaks the application. CSS imports should not be sorted.

[Playground demo](https://biomejs.dev/playground/?bracketSpacing=false&code=aQBtAHAAbwByAHQAIAAnAEAAcAByAG8AagBlAGMAdAB4AC8AdABoAGUAbQBlAC8AcwByAGMALwBuAG8AcgBtAGEAbABpAHoAZQAuAGMAcwBzACcAOwAKAGkAbQBwAG8AcgB0ACAAJwAuAC8AaQBuAGQAZQB4AC4AYwBzAHMAJwA7AAoAaQBtAHAAbwByAHQAIAAnAEAAcAByAG8AagBlAGMAdAB4AC8AdABoAGUAbQBlAC8AcwByAGMALwBiAHUAdAB0AG8AbgAuAGMAcwBzACcAOwAKAGkAbQBwAG8AcgB0ACAAJwBAAHAAcgBvAGoAZQBjAHQAeAAvAHQAaABlAG0AZQAvAHMAcgBjAC8AYwBvAGwALQAzAC0AcwBlAGMAdABpAG8AbgAuAGMAcwBzACcAOwAKAGkAbQBwAG8AcgB0ACAAJwBAAHAAcgBvAGoAZQBjAHQAeAAvAHQAaABlAG0AZQAvAHMAcgBjAC8AYwBvAGwALQA1ADAAeAA1ADAALQBzAGUAYwB0AGkAbwBuAC4AYwBzAHMAJwA7AAoAaQBtAHAAbwByAHQAIAAnAEAAcAByAG8AagBlAGMAdAB4AC8AdABoAGUAbQBlAC8AcwByAGMALwBjAG8AbAAtAGYAdQBsAGwALQBzAGUAYwB0AGkAbwBuAC4AYwBzAHMAJwA7AAoAaQBtAHAAbwByAHQAIAAnAEAAcAByAG8AagBlAGMAdAB4AC8AdABoAGUAbQBlAC8AcwByAGMALwBvAG4AZQB0AHIAdQBzAHQALgBjAHMAcwAnADsACgBpAG0AcABvAHIAdAAgACcAQABwAHIAbwBqAGUAYwB0AHgALwB0AGgAZQBtAGUALwBzAHIAYwAvAHIAaQBjAGgALQB0AGUAeAB0AC0AYQBjAGMAbwByAGQAaQBvAG4ALgBjAHMAcwAnADsACgBpAG0AcABvAHIAdAAgACcAQABwAHIAbwBqAGUAYwB0AHgALwB0AGgAZQBtAGUALwBzAHIAYwAvAHIAaQBjAGgALQB0AGUAeAB0AC0AdABhAGIAbABlAC4AYwBzAHMAJwA7AAoAaQBtAHAAbwByAHQAIAAnAEAAcAByAG8AagBlAGMAdAB4AC8AdABoAGUAbQBlAC8AcwByAGMALwBzAGkAZABlAC4AYwBzAHMAJwA7AAoAaQBtAHAAbwByAHQAIAAnAEAAcAByAG8AagBlAGMAdAB4AC8AdABoAGUAbQBlAC8AcwByAGMALwBzAHUAbQBtAGEAcgB5AC4AYwBzAHMAJwA7AAoAaQBtAHAAbwByAHQAIAAnAEAAcAByAG8AagBlAGMAdAB4AC8AdABoAGUAbQBlAC8AcwByAGMALwB1AHQAaQBsAHMALgBjAHMAcwAnADsACgBpAG0AcABvAHIAdAAgACcAQABwAHIAbwBqAGUAYwB0AHgALwB0AGgAZQBtAGUALwBzAHIAYwAvAGMAbwBtAHAAbwBuAGUAbgB0AC0AdQBpAC0AZgBvAHIAbQAuAGMAcwBzACcAOwAKAGkAbQBwAG8AcgB0ACAAJwBAAHAAcgBvAGoAZQBjAHQAeAAvAHQAaABlAG0AZQAvAHMAcgBjAC8AbQBhAGkAbgAtAGEAcABwAC4AYwBzAHMAJwA7AAoAaQBtAHAAbwByAHQAIAB7ACAATABhAHkAbwB1AHQASQBuAHQAZQByAG4AYQBsACAAfQAgAGYAcgBvAG0AIAAnAC4ALwBMAGEAeQBvAHUAdABJAG4AdABlAHIAbgBhAGwAJwA7AAoAaQBtAHAAbwByAHQAIAB7ACAATABvAGcAaQBuAFMAdABhAHQAdQBzACAAfQAgAGYAcgBvAG0AIAAnAEAAcAByAG8AagBlAGMAdAB4AC8AYwBvAG4AcwB0AGEAbgB0AHMALQBjAG8AbQBtAG8AbgAnADsACgBpAG0AcABvAHIAdAAgAHsAIABFAHIAcgBvAHIASABhAG4AZABsAGkAbgBnACAAfQAgAGYAcgBvAG0AIAAnAEAAcAByAG8AagBlAGMAdAB4AC8AYwBvAG4AdABhAGkAbgBlAHIALQBlAHIAcgBvAHIALQBoAGEAbgBkAGwAZQByACcAOwAKAGkAbQBwAG8AcgB0ACAAewAgAEMAdQBzAHQAbwBtAEUAcgByAG8AcgAgAH0AIABmAHIAbwBtACAAJwAuAC8AQwB1AHMAdABvAG0ARQByAHIAbwByACcAOwAKAGkAbQBwAG8AcgB0ACAAUgBlAGEAYwB0ACAAZgByAG8AbQAgACcAcgBlAGEAYwB0ACcAOwA%3D)

### Expected result

Expected Output (Import sorting):

```ts
import '@projectx/theme/src/normalize.css';
import './index.css';
import '@projectx/theme/src/button.css';
import '@projectx/theme/src/col-3-section.css';
import '@projectx/theme/src/col-50x50-section.css';
import '@projectx/theme/src/col-full-section.css';
import '@projectx/theme/src/onetrust.css';
import '@projectx/theme/src/rich-text-accordion.css';
import '@projectx/theme/src/rich-text-table.css';
import '@projectx/theme/src/side.css';
import '@projectx/theme/src/summary.css';
import '@projectx/theme/src/utils.css';
import '@projectx/theme/src/component-ui-form.css';
import '@projectx/theme/src/main-app.css';
import { LoginStatus } from '@projectx/constants-common';
import { ErrorHandling } from '@projectx/container-error-handler';
import React from 'react';
import { CustomError } from './CustomError';
import { LayoutInternal } from './LayoutInternal';
```

Confirmed as a bug in https://github.com/biomejs/biome/discussions/807

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by remojansen** [comment]
I've been looking at the source code, and here are my initial thoughts. 

1. The file extension `.css` is not relevant.
2. Side effects imports (imports without `from`) should not be organized
3. Side effects imports are identifiable in the AST as `JSImportBareClause`

If this is correct, my approach would be to treat each side effects import as an import group. The changes should be mostly contained within`/crates/biome_js_analyze/src/assists/correctness/organize_imports.rs`. 

The bug fix will change how import groups are identified: 

- From line breaks only (current implementation) 
- To line breaks or side effect imports. 

- Each side effect import will become a single-item import group. The following test cases should pass:

## Test case A (Input)

```ts
import '@projectx/theme/src/normalize.css';
import './index.css';
import '@projectx/theme/src/button.css';
import '@projectx/theme/src/col-3-section.css';
import '@projectx/theme/src/col-50x50-section.css';
import '@projectx/theme/src/col-full-section.css';
import '@projectx/theme/src/onetrust.css';
import '@projectx/theme/src/rich-text-accordion.css';
import '@projectx/theme/src/rich-text-table.css';
import '@projectx/theme/src/side.css';
import '@projectx/theme/src/summary.css';
import '@projectx/theme/src/utils.css';
import '@projectx/theme/src/component-ui-form.css';
import '@projectx/theme/src/main-app.css';
import { LayoutInternal } from './LayoutInternal';
import { LoginStatus } from '@projectx/constants-common';
import { ErrorHandling } from '@projectx/container-error-handler';
import { CustomError } from './CustomError';
import React from 'react';
```
## Test case A (Output)

```ts
import '@projectx/theme/src/normalize.css';
import './index.css';
import '@projectx/theme/src/button.css';
import '@projectx/theme/src/col-3-section.css';
import '@projectx/theme/src/col-50x50-section.css';
import '@projectx/theme/src/col-full-section.css';
import '@projectx/theme/src/onetrust.css';
import '@projectx/theme/src/rich-text-accordion.css';
import '@projectx/theme/src/rich-text-table.css';
import '@projectx/theme/src/side.css';
import '@projectx/theme/src/summary.css';
import '@projectx/theme/src/utils.css';
import '@projectx/theme/src/component-ui-form.css';
import '@projectx/theme/src/main-app.css';
import { LoginStatus } from '@projectx/constants-common';
import { ErrorHandling } from '@projectx/container-error-handler';
import React from 'react';
import { CustomError } from './CustomError';
import { LayoutInternal } from './LayoutInternal';
```

## Test case B (Input)

```ts
import '@projectx/theme/src/normalize.css';
import './index.css';
import '@projectx/theme/src/button.css';
import '@projectx/theme/src/col-3-section.css';
import '@projectx/theme/src/col-50x50-section.css';
import '@projectx/theme/src/col-full-section.css';
import '@projectx/theme/src/onetrust.css';
import '@projectx/theme/src/rich-text-accordion.css';
import '@projectx/theme/src/rich-text-table.css';
import { LoginStatus } from '@projectx/constants-common';
import { ErrorHandling } from '@projectx/container-error-handler';
import '@projectx/theme/src/side.css';
import '@projectx/theme/src/summary.css';
import '@projectx/theme/src/utils.css';
import '@projectx/theme/src/component-ui-form.css';
import '@projectx/theme/src/main-app.css';
import { LayoutInternal } from './LayoutInternal';
import { CustomError } from './CustomError';
import React from 'react';
```

## Test case B (Output)

```ts
import '@projectx/theme/src/normalize.css';
import './index.css';
import '@projectx/theme/src/button.css';
import '@projectx/theme/src/col-3-section.css';
import '@projectx/theme/src/col-50x50-section.css';
import '@projectx/theme/src/col-full-section.css';
import '@projectx/theme/src/onetrust.css';
import '@projectx/theme/src/rich-text-accordion.css';
import '@projectx/theme/src/rich-text-table.css';
import { LoginStatus } from '@projectx/constants-common';
import { ErrorHandling } from '@projectx/container-error-handler';
import '@projectx/theme/src/side.css';
import '@projectx/theme/src/summary.css';
import '@projectx/theme/src/utils.css';
import '@projectx/theme/src/component-ui-form.css';
import '@projectx/theme/src/main-app.css';
import React from 'react';
import { CustomError } from './CustomError';
import { LayoutInternal } from './LayoutInternal';
```

Please let me know if you are happy with this approach.

**Comment by remojansen** [comment]
Hi @Conaclos,

My approach has two steps:

1. Identify all side effect imports (`JSImport` with `JSImportBareClause` nodes)
2. Make each side effect import a group

Moving all side effect imports to the top will be slightly more complex it would introduce one more additional step:

4. Move the groups with side effects imports to the front of the group list (without sorting)

The final step happens in both approaches:

5. Let sorting happen (within the groups as it is right now)

However, my main concern is not the additional step. My main concern is that maybe there are weird cases in which it could cause issues. I'm not sure about it (I'm not an expert on the semantics of JS modules).

Both approaches should not be an issue in connection with #645:

- The new feature `blankLineBetweenGroups` will add a line after a group. This feature would be compatible with both my proposed and your proposed approach, so it should not be an issue. However, I think this should be implemented in a separate PR, not as part of this bug fix.

- The new feature `importGroups` allows users to customise the sorting order. As @ematipico mentioned, this would increase complexity quite a lot. It is up to you guys if you want to go in this direction I would personally not do this unless is requested by a large part of the user community.

**Comment by ematipico** [comment]
I would expect the **proposed** - hence not decided - options to adapt to the side effects logic, not the other way around. I think we should fix the bug by pretending that those proposed options aren't there yet. 

Side-effects handling is **more** important than some user-facing options.

**Comment by remojansen** [comment]
ps I think moving the side effects to the top might not be a good idea. I found this and it makes sense to me:

> Since it is hard to know which side effect imports affect which other imports, I would suggest the following solution: treat a side effect import as a boundary that splits the imports into two groups, the imports before the the side effect import and the imports after the side effect import. - [Source](https://github.com/trivago/prettier-plugin-sort-imports/issues/110)

This re-inforces the idea of treating side-effect imports as import groups.

**Comment by ematipico** [comment]
It makes sense to me!

**Comment by Conaclos** [comment]
You convinced me :)

**Comment by moogus** [comment]
Hiya, I wondered if there is any update on this?

**Comment by ematipico** [comment]
@moogus  From this [discussion](https://github.com/biomejs/biome/discussions/807#discussioncomment-7630648)

> I am happy to try to work on a bug fix over the Christmas break. It will be my first time working with Rust and contributing to Biome. I will probably need some help, but I'm feeling brave. I wanted to give Rust a go, so this could be my perfect excuse.

**Comment by moogus** [comment]
@ematipico Amazing, thank you

**Comment by ematipico** [comment]
@remojansen are there any updates?

**Comment by remojansen** [comment]
Hi, I have it done. I am just solving testing issues now. I have a question about something that has been impacted. There is a test case for comments in imports:

---
source: crates/biome_js_analyze/tests/spec_tests.rs
expression: comments.js
---
# Input
```js
// leading b
import b, {
    B, // dangling b
} from 'b'; // trailing b
// leading a
import a, {
    A, // dangling a
} from 'a'; // trailing a

// leading d
import d, {
    D, // dangling d
} from 'd'; // trailing d
// leading c
import c, {
    C, // dangling c
} from 'c'; // trailing c
// leading eof

```

# Actions
```diff
@@ -1,18 +1,18 @@
+// leading a
+import a, {
+    A, // dangling a
+} from 'a'; // trailing a
 // leading b
 import b, {
     B, // dangling b
 } from 'b'; // trailing b
-// leading a
-import a, {
-    A, // dangling a
-} from 'a'; // trailing a
 
+// leading c
+import c, {
+    C, // dangling c
+} from 'c'; // trailing c
 // leading d
 import d, {
     D, // dangling d
 } from 'd'; // trailing d
-// leading c
-import c, {
-    C, // dangling c
-} from 'c'; // trailing c
 // leading eof

```

I broke this test but as soon as I find a fix I should be good to go.

**Comment by ematipico** [comment]
@chekrd 

We document it in our [docs](https://biomejs.dev/analyzer/#grouped-imports)

**Comment by ematipico** [comment]
I take for granted that @remojansen doesn't have time to fix the bug. Help here will be appreciated
