### ISSUE TITLE
📎 Implement `lint/useNodeImportProtocol` - `eslint-plugin-unicorn/prefer-node-protocol`

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#818]
### Description

Implement [prefer-node-protocol](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prefer-node-protocol.md) that encourages the use of `import {} from "node:<builtin>"` instead of `import {} from "<builtin>"`.

We can skip the support for CommonJS (`require`).

Suggested name: `useNodeImportProtocol` or `useNodeProtocol`.

---

Want to contribute? Lets you know you are interested! We will assign you to the issue to prevent several people to work on the same issue. Don't worry, we can unassign you later if you are no longer interested in the issue! Read our [contributing guide](https://github.com/biomejs/biome/blob/main/CONTRIBUTING.md) and [analyzer contributing guide](https://github.com/biomejs/biome/blob/main/crates/biome_analyze/CONTRIBUTING.md).

**Comment by 2-NOW** [comment]
I am very interested in this work. Can I be assigned ?

**Comment by Conaclos** [comment]
Of course :) Assigned :)

**Comment by unvalley** [comment]
I think this is completed.
