### ISSUE TITLE
📎 use ignore crate for walking the file system 

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#847]
### Description

At the moment we use some in-house code for walking the file system and for matching globs to ignore the files.

While this works, we have some issues:
- we can't respect nested gitignore files during the traversal
- our glob matcher is a copy of the `glob` crate and it doesn't work very well with the gitignore paths
- we can't use globs in our cli

https://docs.rs/ignore/latest/ignore/index.html

We use this crate to enhance the feature.

**Comment by malobre** [comment]
Related:
- #805 
- #709

**Comment by ematipico** [comment]
I'm currently working on this
