### ISSUE TITLE
🐛 Break on TypeScript parameter properties

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#849]
### Environment information

```block
Playground
```

### What happened?

Biome should break lines when at least one parameter property is present.
See the related prettier PR [prettier#14402](https://github.com/prettier/prettier/pull/14402).

[Playground link](https://biomejs.dev/playground?trailingComma=es5&lintRules=all&code=YwBsAGEAcwBzACAATQB5AEMAbABhAHMAcwAgAHsACgAgACAAYwBvAG4AcwB0AHIAdQBjAHQAbwByACgACgAgACAAIAAgAGIAOgAgAHMAdAByAGkAbgBnACwACgAgACAAIAAgAHAAcgBvAHQAZQBjAHQAZQBkACAAeAA6ACAAbgB1AG0AYgBlAHIALAAKACAAIAAgACAAYQA6ACAAcwB0AHIAaQBuAGcALAAKACAAIAApACAAewB9AAoAfQAKAA%3D%3D)

### Expected result

The following code:

```ts
class MyClass {
  constructor(a: string, protected x: number, b: string) {}
}
```

should be formatted as Prettier:

```ts
class MyClass {
	constructor(
		a: string,
		protected x: number,
		b: string
	) {}
}
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by TaKO8Ki** [comment]
Can I work on this?
