### ISSUE TITLE
🐛 Line breaking after `extends` in type parameters

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#850]
### Environment information

```block
Playground
```

### What happened?

Biome doesn't break on `extends` in type parameter when line got too large.

[Playground link](https://biomejs.dev/playground?trailingComma=es5&lintRules=all&code=ZQB4AHAAbwByAHQAIAB0AHkAcABlACAATwB1AHQAZQByAFQAeQBwAGUAMgA8AAoAIAAgAEwAbwBuAGcAZQByAEwAbwBuAGcAZQByAEwAbwBuAGcAZQByAEwAbwBuAGcAZQByAEkAbgBuAGUAcgBUAHkAcABlACAAZQB4AHQAZQBuAGQAcwAgAEwAbwBuAGcAZQByAEwAbwBuAGcAZQByAEwAbwBuAGcAZQByAEwAbwBuAGcAZQByAEwAbwBuAGcAZQByAEwAbwBuAGcAZQByAEwAbwBuAGcAZQByAEwAbwBuAGcAZQByAE8AdABoAGUAcgBUAHkAcABlAAoAPgAgAD0AIAB7ACAAYQA6ACAAMQAgAH0AOwA%3D)

related Prettier PRs:
- [prettier#14672](https://github.com/prettier/prettier/pull/14672)
- [prettier#14858)](https://github.com/prettier/prettier/pull/14858)

### Expected result

The following code:

```ts
export type OuterType2<
  LongerLongerLongerLongerInnerType extends LongerLongerLongerLongerLongerLongerLongerLongerOtherType
> = { a: 1 };
```

should be formatted as Prettier:

```ts
export type OuterType2<
	LongerLongerLongerLongerInnerType extends
		LongerLongerLongerLongerLongerLongerLongerLongerOtherType,
> = { a: 1 };
```

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by Yuiki** [comment]
Can I address this issue?

**Comment by Conaclos** [comment]
You are welcome :)
