### ISSUE TITLE
📎 Add more Known files to ignore

### ISSUE THREAD

**Issue by unvalley** [biomejs/biome#869]
### Description

Biome ignores below files (you can check [here on the website](https://biomejs.dev/guides/how-biome-works/#known-files)):

- package.json
- package-lock.json
- tsconfig.json
- jsconfig.json

We can add more files to ignore, for example: 

- ~bun.lockb~
- ~package-lock.yaml~
- deno.json (should we also ignore deno.jsonc?)

ref: https://github.com/biomejs/biome/discussions/840
Thanks for bringing this up @jacobthesheep

**Comment by Gumichocopengin8** [comment]
can I work on this?

**Comment by ematipico** [comment]
All yours @Gumichocopengin8
