### ISSUE TITLE
📎 Use workspace lint to apply clippy rules

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#879]
### Description

This tasks needs https://github.com/biomejs/biome/issues/878 to be completed first.

Once it's done, we should use the new feature lints configuration https://doc.rust-lang.org/stable/cargo/reference/workspaces.html#the-lints-table to move our workspace lint rules to this new table.

The workspace rules are here: https://github.com/biomejs/biome/blob/main/.cargo/config.toml#L39

**Comment by chansuke** [comment]
I'd like to work on this issue:)
