### ISSUE TITLE
☂️  Refactor website 💻 

### ISSUE THREAD

**Issue by ematipico** [biomejs/biome#881]
Coordination issue for refactoring the website.

As explained in https://github.com/biomejs/biome/issues/865, at the moment the whole website site is powered by [starlight](https://starlight.astro.build/guides/i18n/) and [astro](https://docs.astro.build/en/getting-started/).

We have some components and part of pages that are auto-generated with Rust scripts: https://github.com/biomejs/biome/blob/main/xtask/codegen/src/generate_website.rs. If you decide to move or change the content of a page, make sure to update the script too.

As mentioned in the parent umbrella:

> Now, we have two options to tide up everything together:
> 1 keep using starlight for all the pages, and override its components where needed, especially the top bar. Blog, playground and docs should always be accessible from the top bar, although sometimes we won't have much freedom with design and styles
> 2. use Starlight only for docs/* directory (we don't have it now, we will create it), and the other pages will be built from scratch. We have more freedom in terms of design, but should make sure that we don't deviate too much from the colour palette that starlight offers. Some websites that use starlight for their docs use this approach. I believe it's possible to import starlight styles in pages that don't belong to starlight.

Here's some requirements:
- Docs, blog and playground should be reachable from every page (home page too)
- Accessibility is a must
- it would be best to keep one domain

Use the branch `website-v2` as destination branch of your PRs. Everything is ready, we should be able to merge `website-v2` to `main` without issues.

**Comment by vasucp1207** [comment]
This is my idea, turn the current search bar into a simple icon so that all the header links fit into the view nicely. 

https://github.com/biomejs/biome/assets/85363195/53daadba-ceac-4213-9041-889ee7fa11de

**Comment by ematipico** [comment]
Good progress here! Here some questions/thoughts: 

- how does the focus work? is it shown?
- I think we should still show the `/` icon on desktop
- I think the links should be placed on the left (no strong opinions)

**Comment by victor-teles** [comment]
I've made some sketches that might help with the new header component

![CleanShot 2023-11-28 at 14 34 50](https://github.com/biomejs/biome/assets/78874691/46b699d5-57bb-44a7-a049-ad7566fbdc2b)

Here's the task list we need to address:

- [ ] Customize starlight header component and add support for custom links
 -  The links need to have a `active` state for each page (e.g if user is on playground page, we need to make the link bolder for it)
- [ ] Create the new theme toggle variation
- [ ] Remove the links from sidebar (Home, Playground and Blog) 
- [ ] Refactor/migrate playground to use the starlight

c/c @ematipico @vasucp1207

**Comment by ematipico** [comment]
@victor-teles @vasucp1207 whenever you guys are ready, feel free to start sending PRs :) 

I believe we have something concrete now

**Comment by vasucp1207** [comment]
> @vasucp1207 Do you have any thoughts on the sketches of the header? do you still want to work on it?
> 
> I am going to pick the `theme toggle variation` task to work on.

I like the idea of the header go-ahead.
