### ISSUE TITLE
📝 Duplicated `@returns` JSDoc

### ISSUE THREAD

**Issue by jjonescz** [biomejs/biome#921]
### Environment information

Default playground options.

### Playground link

https://biomejs.dev/playground?code=ZgAoAAoACQAvACoAKgAgAEAAcgBlAHQAdQByAG4AcwAgAHsAUAByAG8AbQBpAHMAZQA8AHYAbwBpAGQAPgB9ACAAKgAvAAoACQAoACkAIAA9AD4AIABhAHMAeQBuAGMAIAAoACkAIAA9AD4AIAB7AH0ALAAKACkAOwAKAA%3D%3D

This input:

```js
f(
	/** @returns {Promise<void>} */
	() => async () => {},
);
```

results in:

```js
f(
	/** @returns {Promise<void>} */
	/** @returns {Promise<void>} */
		() =>
		async () => {},
);
```

Notice the duplicated JSDoc comment.

### Code of Conduct

- [X] I agree to follow Biome's Code of Conduct

**Comment by marozzocom** [comment]
Any comments are duplicated: https://biomejs.dev/playground?code=ZgAoAAoACQAvAC8ACgAgACAAIAAgAC8ALwAKAAkAKAApACAAPQA%2BACAAYQBzAHkAbgBjACAAKAApACAAPQA%2BACAAewB9ACwACgApADsACgA%3D

**Comment by faultyserver** [comment]
I've been looking at this part of the codebase recently dealing with arow chains, so i can try to fix this as well.
