### ISSUE TITLE
📎 IntelliJ Platform LSP

### ISSUE THREAD

**Issue by Conaclos** [biomejs/biome#93]
### Description

Implement lsp client for IntelliJ.

Some [preliminary works were previously done](https://github.com/rome/tools/issues/4658). In particular [an implementation](https://github.com/rome/tools/issues/4658#issuecomment-1668408736).

**Comment by victor-teles** [comment]
@Conaclos Can i help with this one? what are the basic functionalities needed?

- Formatting
- Linting
- Automatic restart LSP when `biome.json` change and settings changes
- Automatic find biome binary in node_modules
- Statusbar widget same as vscode `Biome 1.0.0`
- Toolbar action for restart server 

Anything else?

The code need to be in this repository?

**Comment by ematipico** [comment]
Thank you @victor-teles 

Here's something to start with: https://blog.jetbrains.com/platform/2023/07/lsp-for-plugin-developers/

The blog post says only four events are supported. Biome would be able to support only `textDocument/codeAction` and `textDocument/publishDiagnostics`. So **no formatting** for the time being.

The code has to live in the repository, inside the `editors/` directory. It would be great to also have, for us developers:
- instructions for local development;
- setting to change the path of the binary;


Eventually, extend the publishing workflow, to include this new plugin.

**Comment by victor-teles** [comment]
@ematipico alright, can you assign it to me ?
