### ISSUE TITLE
📎 Update import sorting doc

### ISSUE THREAD

**Issue by malobre** [biomejs/biome#961]
### Description

Import sorting is "safe to apply" since [1.3.0](https://github.com/biomejs/biome/blob/d7a5d8c101fe37db6d8cfc34bb95f5a2673e22d9/CHANGELOG.md#enhancements-2).

This change is not yet reflected:
- in the CLI `--help` message:
  ```
   --apply               Apply safe fixes, formatting
   --apply-unsafe        Apply safe fixes and unsafe fixes, formatting and import sorting
  ```
- on https://biomejs.dev/analyzer#import-sorting-via-cli the command still uses `--apply-unsafe`

**Comment by yossydev** [comment]
I want to work on this one!
