### ISSUE TITLE
📎 Fragile/broken links in blog website

### ISSUE THREAD

**Issue by YDX-2147483647** [biomejs/biome#964]
### Description

Links in both `https://biomejs.dev/blog` and `https://biomejs.dev/blog/` (note the trailing slash) are relative links. They works at `/blog`, but 404 at `/blog/`.

```html
<a href="blog/biome-wins-prettier-challenge">Biome formatter wins the Prettier challenge</a>
```

— Try click links in [`/blog/`](https://biomejs.dev/blog/)!

## Possible solutions

- Redirect `/blog/` to `/blog`.
- Alternatively, change all `href="blog/…"` to `href="/blog/…"`.

| `href`                                        | On `/blog`                              | On `/blog/`                                                  |
| --------------------------------------------- | --------------------------------------- | ------------------------------------------------------------ |
| Current: `blog/biome-wins-prettier-challenge` | ✅ `/blog/biome-wins-prettier-challenge` | ❌ `/blog/blog/biome-wins-prettier-challenge` (404 Not Found) |
| `/blog/biome-wins-prettier-challenge`         | ✅ `/blog/biome-wins-prettier-challenge` | ✅ `/blog/biome-wins-prettier-challenge`                      |

Related but not identical to: #77

**Comment by Yan-Thomas** [comment]
Nice catch! I believe it's an easier fix to just change the hrefs to `/blog/`, I'll open a PR.
