### ISSUE TITLE
📎 Implement use-function-convention

### ISSUE THREAD

**Issue by SorenHolstHansen** [biomejs/biome#975]
### Description

Implement a rule to have a consistent form of writing functions, i.e. either
```ts
function a() {}
// or
const a = () => {}
```
Sort of like https://eslint.org/docs/latest/rules/func-style

**Comment by ematipico** [comment]
Hi @SorenHolstHansen , 

Please use https://github.com/biomejs/biome/discussions/3 to propose a rule first.

Tasks issues are usually open once things are agreed.
